// Generated by root sync:blocks. Do not edit. Staged contracts; runtime activation is separate.
import type { z } from "zod";
export const INLINE_MARK_TYPES: readonly ("bold" | "italic" | "strike" | "underline" | "code")[];
export type RichTextMark = { type: "bold" | "italic" | "strike" | "underline" | "code" } | { type: "link"; attrs: { href: string; target?: "_blank" | "_self" } };
export type RichTextInline = { type: "text"; text: string; marks?: RichTextMark[] } | { type: "hardBreak" };
export type RichTextDoc = { type: "doc"; content: { type: "paragraph"; content?: RichTextInline[] }[] };
export function createRichTextSchema(zod: typeof z, max?: number, inlineOnly?: boolean): z.ZodType<RichTextDoc, RichTextDoc>;
export function safeLinkSchema(zod: typeof z, protocols?: readonly string[]): z.ZodString;
export function dateSchema(zod: typeof z): z.ZodString;
export function formattedTextSchema(zod: typeof z, format: string): z.ZodString;
export function constrainObject<T extends z.ZodType>(schema: T, constraints: readonly unknown[]): T;
