// Generated by root sync:blocks. Do not edit. Staged contracts; runtime activation is separate.
import { z } from "zod";
import { validateBlockAttrs, validateBlockTreatment } from "./schemas";
import { dependencyDescriptors, anchorDescriptors, packTreatmentSupport } from "./metadata";
import { createCanonicalNodeSchema, createCanonicalTreeSchema, validateCanonicalTree as validateTree, type CanonicalTreeContract } from "./instance-runtime.mjs";
import type { CanonicalTree } from "./types";
export { collectCanonicalAnchors, createCanonicalLayoutSchema, MENU_VISIBILITY_VALUES, CANONICAL_TREE_LIMITS } from "./instance-runtime.mjs";
export const canonicalNodeSchema = createCanonicalNodeSchema(z);
const contract: CanonicalTreeContract = { nodeSchema: canonicalNodeSchema, validateAttrs: validateBlockAttrs, validateTreatment: validateBlockTreatment, descriptors: dependencyDescriptors, anchors: anchorDescriptors };
export const canonicalTreeSchema = createCanonicalTreeSchema(z, contract) as z.ZodType<CanonicalTree>;
export function validateCanonicalTree(value: unknown): CanonicalTree { return validateTree(value, contract) as CanonicalTree; }
type TreatmentNode = { name: string; treatment?: { name: string }; children?: TreatmentNode[] };
/** Caller validates the tree against its Library or exact composed registry. */
export function assertPackTreatments(tree: TreatmentNode[], packId: string): void {
  const packs: Readonly<Record<string, Readonly<Record<string, readonly string[]>>>> = packTreatmentSupport;
  const visit = (nodes: TreatmentNode[]): void => { for (const node of nodes) {
    if (node.treatment && !packs[packId]?.[node.name]?.includes(node.treatment.name)) throw Error("PACK_TREATMENT_UNAVAILABLE: " + packId + "/" + node.name);
    if (node.children) visit(node.children);
  } };
  visit(tree);
}
