// Generated by root sync:blocks. Do not edit. Staged contracts; runtime activation is separate.
export interface RendererCoverage { id: string; title: string; blocks: readonly { name: string; title: string; renderer: "owned" | "library" | "missing"; hidden: boolean }[] }
export const rendererCoverage: readonly RendererCoverage[] = [
  {
    "blocks": [
      {
        "hidden": false,
        "name": "blocks/contact-stack",
        "renderer": "library",
        "title": "Contact Stack"
      },
      {
        "hidden": false,
        "name": "blocks/customer-showcase",
        "renderer": "library",
        "title": "Customer Showcase"
      },
      {
        "hidden": false,
        "name": "blocks/grade-gallery",
        "renderer": "library",
        "title": "Grade Gallery"
      },
      {
        "hidden": false,
        "name": "blocks/media-mentions",
        "renderer": "library",
        "title": "Media Mentions"
      },
      {
        "hidden": false,
        "name": "blocks/page-banner",
        "renderer": "library",
        "title": "Page Banner"
      },
      {
        "hidden": false,
        "name": "blocks/product-collection",
        "renderer": "library",
        "title": "Product Collection"
      },
      {
        "hidden": false,
        "name": "blocks/promo-band",
        "renderer": "library",
        "title": "Promo Band"
      },
      {
        "hidden": false,
        "name": "blocks/social-share",
        "renderer": "library",
        "title": "Social Share"
      },
      {
        "hidden": false,
        "name": "blocks/story-timeline",
        "renderer": "library",
        "title": "Story Timeline"
      },
      {
        "hidden": false,
        "name": "blocks/studio-services",
        "renderer": "library",
        "title": "Studio services"
      },
      {
        "hidden": false,
        "name": "blocks/tabbed-content",
        "renderer": "library",
        "title": "Tabbed Content"
      },
      {
        "hidden": false,
        "name": "business/locations",
        "renderer": "library",
        "title": "Business locations"
      },
      {
        "hidden": false,
        "name": "business/menu",
        "renderer": "library",
        "title": "Food and drink menu"
      },
      {
        "hidden": false,
        "name": "business/opening-hours",
        "renderer": "library",
        "title": "Opening hours"
      },
      {
        "hidden": false,
        "name": "business/service-list",
        "renderer": "library",
        "title": "Services and rates"
      },
      {
        "hidden": false,
        "name": "certificates/verify",
        "renderer": "library",
        "title": "Certificate verify"
      },
      {
        "hidden": false,
        "name": "commerce/assistant-band",
        "renderer": "library",
        "title": "Shopping Assistant Band"
      },
      {
        "hidden": false,
        "name": "commerce/brand-list",
        "renderer": "library",
        "title": "Brand list"
      },
      {
        "hidden": false,
        "name": "commerce/bundle-offer",
        "renderer": "library",
        "title": "Bundle offer"
      },
      {
        "hidden": false,
        "name": "commerce/cart-cta",
        "renderer": "library",
        "title": "Cart CTA"
      },
      {
        "hidden": false,
        "name": "commerce/category-tiles",
        "renderer": "library",
        "title": "Category Tiles"
      },
      {
        "hidden": false,
        "name": "commerce/download-library",
        "renderer": "library",
        "title": "Purchased downloads"
      },
      {
        "hidden": false,
        "name": "commerce/product-compare",
        "renderer": "library",
        "title": "Product compare"
      },
      {
        "hidden": false,
        "name": "commerce/product-hero",
        "renderer": "library",
        "title": "Product hero"
      },
      {
        "hidden": false,
        "name": "commerce/product-showcase",
        "renderer": "library",
        "title": "Product Showcase"
      },
      {
        "hidden": false,
        "name": "commerce/recently-viewed",
        "renderer": "library",
        "title": "Recently viewed"
      },
      {
        "hidden": false,
        "name": "commerce/sale-countdown",
        "renderer": "library",
        "title": "Sale countdown"
      },
      {
        "hidden": false,
        "name": "commerce/search-band",
        "renderer": "library",
        "title": "Search band"
      },
      {
        "hidden": false,
        "name": "commerce/shipping-promise",
        "renderer": "library",
        "title": "Shipping promise"
      },
      {
        "hidden": false,
        "name": "commerce/variant-picker-teaser",
        "renderer": "library",
        "title": "Variant picker teaser"
      },
      {
        "hidden": false,
        "name": "commerce/wishlist",
        "renderer": "library",
        "title": "Saved products"
      },
      {
        "hidden": false,
        "name": "core/accordion",
        "renderer": "library",
        "title": "Accordion"
      },
      {
        "hidden": false,
        "name": "core/account-teaser",
        "renderer": "library",
        "title": "Account teaser"
      },
      {
        "hidden": false,
        "name": "core/anchor-nav",
        "renderer": "library",
        "title": "Anchor nav"
      },
      {
        "hidden": false,
        "name": "core/announcement-bar",
        "renderer": "library",
        "title": "Announcement bar"
      },
      {
        "hidden": false,
        "name": "core/archive-list",
        "renderer": "library",
        "title": "Archive list"
      },
      {
        "hidden": false,
        "name": "core/audio",
        "renderer": "library",
        "title": "Audio"
      },
      {
        "hidden": false,
        "name": "core/author-bio",
        "renderer": "library",
        "title": "Author bio"
      },
      {
        "hidden": false,
        "name": "core/before-after",
        "renderer": "library",
        "title": "Before / after"
      },
      {
        "hidden": false,
        "name": "core/bento-grid",
        "renderer": "library",
        "title": "Bento grid"
      },
      {
        "hidden": false,
        "name": "core/booking-cta",
        "renderer": "library",
        "title": "Booking CTA"
      },
      {
        "hidden": false,
        "name": "core/breadcrumbs",
        "renderer": "library",
        "title": "Breadcrumbs"
      },
      {
        "hidden": false,
        "name": "core/callout",
        "renderer": "library",
        "title": "Callout"
      },
      {
        "hidden": false,
        "name": "core/carousel",
        "renderer": "library",
        "title": "Carousel"
      },
      {
        "hidden": false,
        "name": "core/child-pages",
        "renderer": "library",
        "title": "Child pages"
      },
      {
        "hidden": false,
        "name": "core/code",
        "renderer": "library",
        "title": "Code"
      },
      {
        "hidden": false,
        "name": "core/columns",
        "renderer": "library",
        "title": "Columns"
      },
      {
        "hidden": false,
        "name": "core/comparison-table",
        "renderer": "library",
        "title": "Comparison table"
      },
      {
        "hidden": false,
        "name": "core/contact-form",
        "renderer": "library",
        "title": "Contact form"
      },
      {
        "hidden": false,
        "name": "core/countdown",
        "renderer": "library",
        "title": "Countdown"
      },
      {
        "hidden": false,
        "name": "core/cta-band",
        "renderer": "library",
        "title": "CTA Band"
      },
      {
        "hidden": false,
        "name": "core/cta-with-form",
        "renderer": "library",
        "title": "CTA with inline form"
      },
      {
        "hidden": false,
        "name": "core/custom-html",
        "renderer": "library",
        "title": "Custom HTML"
      },
      {
        "hidden": false,
        "name": "core/definition-list",
        "renderer": "library",
        "title": "Definition list"
      },
      {
        "hidden": false,
        "name": "core/divider",
        "renderer": "library",
        "title": "Divider"
      },
      {
        "hidden": false,
        "name": "core/embed",
        "renderer": "library",
        "title": "Embed"
      },
      {
        "hidden": false,
        "name": "core/event-rsvp",
        "renderer": "library",
        "title": "Event RSVP"
      },
      {
        "hidden": false,
        "name": "core/faq",
        "renderer": "library",
        "title": "FAQ"
      },
      {
        "hidden": false,
        "name": "core/feature-grid",
        "renderer": "library",
        "title": "Feature Grid"
      },
      {
        "hidden": false,
        "name": "core/feature-list-alternating",
        "renderer": "library",
        "title": "Feature list (alternating)"
      },
      {
        "hidden": false,
        "name": "core/feature-tabs",
        "renderer": "library",
        "title": "Feature tabs"
      },
      {
        "hidden": false,
        "name": "core/featured-page",
        "renderer": "library",
        "title": "Featured page"
      },
      {
        "hidden": false,
        "name": "core/featured-products",
        "renderer": "library",
        "title": "Featured products"
      },
      {
        "hidden": false,
        "name": "core/file-download",
        "renderer": "library",
        "title": "File download"
      },
      {
        "hidden": false,
        "name": "core/footnotes",
        "renderer": "library",
        "title": "Footnotes"
      },
      {
        "hidden": false,
        "name": "core/form",
        "renderer": "library",
        "title": "Form embed"
      },
      {
        "hidden": false,
        "name": "core/gallery",
        "renderer": "library",
        "title": "Gallery"
      },
      {
        "hidden": false,
        "name": "core/grid",
        "renderer": "library",
        "title": "Grid"
      },
      {
        "hidden": false,
        "name": "core/group",
        "renderer": "library",
        "title": "Group"
      },
      {
        "hidden": false,
        "name": "core/heading",
        "renderer": "library",
        "title": "Heading"
      },
      {
        "hidden": false,
        "name": "core/hero",
        "renderer": "owned",
        "title": "Hero"
      },
      {
        "hidden": false,
        "name": "core/hero-split",
        "renderer": "library",
        "title": "Hero (split)"
      },
      {
        "hidden": false,
        "name": "core/hero-text-only",
        "renderer": "library",
        "title": "Hero (text only)"
      },
      {
        "hidden": false,
        "name": "core/hero-video",
        "renderer": "library",
        "title": "Hero video"
      },
      {
        "hidden": false,
        "name": "core/iframe",
        "renderer": "library",
        "title": "Iframe"
      },
      {
        "hidden": false,
        "name": "core/image",
        "renderer": "library",
        "title": "Image"
      },
      {
        "hidden": false,
        "name": "core/language-switcher",
        "renderer": "library",
        "title": "Language switcher"
      },
      {
        "hidden": false,
        "name": "core/latest-posts",
        "renderer": "library",
        "title": "Latest posts"
      },
      {
        "hidden": false,
        "name": "core/lead-magnet",
        "renderer": "library",
        "title": "Lead magnet"
      },
      {
        "hidden": false,
        "name": "core/lightbox-grid",
        "renderer": "library",
        "title": "Lightbox grid"
      },
      {
        "hidden": false,
        "name": "core/list",
        "renderer": "library",
        "title": "List"
      },
      {
        "hidden": false,
        "name": "core/logo-cloud",
        "renderer": "library",
        "title": "Logo cloud"
      },
      {
        "hidden": false,
        "name": "core/map",
        "renderer": "library",
        "title": "Map"
      },
      {
        "hidden": false,
        "name": "core/marquee",
        "renderer": "library",
        "title": "Marquee"
      },
      {
        "hidden": false,
        "name": "core/media-text",
        "renderer": "library",
        "title": "Media + Text"
      },
      {
        "hidden": false,
        "name": "core/menu",
        "renderer": "library",
        "title": "Menu"
      },
      {
        "hidden": false,
        "name": "core/newsletter-signup",
        "renderer": "library",
        "title": "Newsletter signup"
      },
      {
        "hidden": false,
        "name": "core/paragraph",
        "renderer": "library",
        "title": "Paragraph"
      },
      {
        "hidden": false,
        "name": "core/poll",
        "renderer": "library",
        "title": "Poll"
      },
      {
        "hidden": false,
        "name": "core/post-grid",
        "renderer": "library",
        "title": "Post grid"
      },
      {
        "hidden": false,
        "name": "core/pricing-cards",
        "renderer": "library",
        "title": "Pricing Cards"
      },
      {
        "hidden": false,
        "name": "core/pricing-table",
        "renderer": "library",
        "title": "Pricing table"
      },
      {
        "hidden": false,
        "name": "core/process-steps",
        "renderer": "library",
        "title": "Process steps"
      },
      {
        "hidden": false,
        "name": "core/pullquote",
        "renderer": "library",
        "title": "Pullquote"
      },
      {
        "hidden": false,
        "name": "core/quote",
        "renderer": "library",
        "title": "Quote"
      },
      {
        "hidden": false,
        "name": "core/related-content",
        "renderer": "library",
        "title": "Related content"
      },
      {
        "hidden": false,
        "name": "core/reviews",
        "renderer": "library",
        "title": "Reviews"
      },
      {
        "hidden": false,
        "name": "core/rich-text",
        "renderer": "library",
        "title": "Rich Text Section"
      },
      {
        "hidden": false,
        "name": "core/roadmap-timeline",
        "renderer": "library",
        "title": "Roadmap timeline"
      },
      {
        "hidden": false,
        "name": "core/script-embed",
        "renderer": "library",
        "title": "Script embed"
      },
      {
        "hidden": false,
        "name": "core/search-box",
        "renderer": "library",
        "title": "Search box"
      },
      {
        "hidden": false,
        "name": "core/search-results",
        "renderer": "library",
        "title": "Search results"
      },
      {
        "hidden": false,
        "name": "core/section",
        "renderer": "library",
        "title": "Section"
      },
      {
        "hidden": false,
        "name": "core/site-info",
        "renderer": "library",
        "title": "Site info"
      },
      {
        "hidden": false,
        "name": "core/social-feed",
        "renderer": "library",
        "title": "Social feed"
      },
      {
        "hidden": false,
        "name": "core/social-links",
        "renderer": "library",
        "title": "Social links"
      },
      {
        "hidden": false,
        "name": "core/spacer",
        "renderer": "library",
        "title": "Spacer"
      },
      {
        "hidden": false,
        "name": "core/split",
        "renderer": "library",
        "title": "Split"
      },
      {
        "hidden": false,
        "name": "core/stats-band",
        "renderer": "library",
        "title": "Stats band"
      },
      {
        "hidden": false,
        "name": "core/steps-with-media",
        "renderer": "library",
        "title": "Steps with media"
      },
      {
        "hidden": false,
        "name": "core/sticky-aside",
        "renderer": "library",
        "title": "Sticky aside"
      },
      {
        "hidden": false,
        "name": "core/synced",
        "renderer": "library",
        "title": "Synced content"
      },
      {
        "hidden": false,
        "name": "core/table",
        "renderer": "library",
        "title": "Table"
      },
      {
        "hidden": false,
        "name": "core/table-of-contents",
        "renderer": "library",
        "title": "Table of contents"
      },
      {
        "hidden": false,
        "name": "core/tabs",
        "renderer": "library",
        "title": "Tabs"
      },
      {
        "hidden": false,
        "name": "core/tag-cloud",
        "renderer": "library",
        "title": "Tag cloud"
      },
      {
        "hidden": false,
        "name": "core/team-grid",
        "renderer": "library",
        "title": "Team grid"
      },
      {
        "hidden": false,
        "name": "core/testimonial-wall",
        "renderer": "library",
        "title": "Testimonial wall"
      },
      {
        "hidden": false,
        "name": "core/testimonials",
        "renderer": "library",
        "title": "Testimonials"
      },
      {
        "hidden": false,
        "name": "core/trust-badges",
        "renderer": "library",
        "title": "Trust badges"
      },
      {
        "hidden": false,
        "name": "core/ugc-grid",
        "renderer": "library",
        "title": "UGC grid"
      },
      {
        "hidden": false,
        "name": "core/video",
        "renderer": "library",
        "title": "Video"
      },
      {
        "hidden": false,
        "name": "events/calendar",
        "renderer": "library",
        "title": "Event calendar"
      },
      {
        "hidden": false,
        "name": "events/next-event",
        "renderer": "library",
        "title": "Next event"
      },
      {
        "hidden": false,
        "name": "events/upcoming",
        "renderer": "library",
        "title": "Upcoming Events"
      },
      {
        "hidden": false,
        "name": "gallery/album",
        "renderer": "library",
        "title": "Gallery album"
      },
      {
        "hidden": false,
        "name": "gallery/recipe-card",
        "renderer": "library",
        "title": "Recipe card"
      },
      {
        "hidden": false,
        "name": "lms/course-grid",
        "renderer": "library",
        "title": "Course grid"
      },
      {
        "hidden": false,
        "name": "lms/curriculum",
        "renderer": "library",
        "title": "Curriculum"
      },
      {
        "hidden": false,
        "name": "lms/instructor",
        "renderer": "library",
        "title": "Instructor"
      },
      {
        "hidden": false,
        "name": "lms/progress",
        "renderer": "library",
        "title": "Learner progress"
      },
      {
        "hidden": false,
        "name": "local/sample-alert",
        "renderer": "library",
        "title": "Sample Alert"
      },
      {
        "hidden": false,
        "name": "membership/gated-teaser",
        "renderer": "library",
        "title": "Gated teaser"
      },
      {
        "hidden": false,
        "name": "membership/plans",
        "renderer": "library",
        "title": "Membership plans"
      },
      {
        "hidden": false,
        "name": "reference/field-guide",
        "renderer": "library",
        "title": "Field Guide"
      },
      {
        "hidden": false,
        "name": "support/kb-search",
        "renderer": "library",
        "title": "Knowledge base search"
      },
      {
        "hidden": false,
        "name": "support/ticket-cta",
        "renderer": "library",
        "title": "Ticket CTA"
      }
    ],
    "id": "aster-house",
    "title": "Aster House"
  },
  {
    "blocks": [
      {
        "hidden": false,
        "name": "blocks/contact-stack",
        "renderer": "library",
        "title": "Contact Stack"
      },
      {
        "hidden": false,
        "name": "blocks/customer-showcase",
        "renderer": "library",
        "title": "Customer Showcase"
      },
      {
        "hidden": false,
        "name": "blocks/grade-gallery",
        "renderer": "library",
        "title": "Grade Gallery"
      },
      {
        "hidden": false,
        "name": "blocks/media-mentions",
        "renderer": "library",
        "title": "Media Mentions"
      },
      {
        "hidden": false,
        "name": "blocks/page-banner",
        "renderer": "library",
        "title": "Page Banner"
      },
      {
        "hidden": false,
        "name": "blocks/product-collection",
        "renderer": "library",
        "title": "Product Collection"
      },
      {
        "hidden": false,
        "name": "blocks/promo-band",
        "renderer": "library",
        "title": "Promo Band"
      },
      {
        "hidden": false,
        "name": "blocks/social-share",
        "renderer": "library",
        "title": "Social Share"
      },
      {
        "hidden": false,
        "name": "blocks/story-timeline",
        "renderer": "library",
        "title": "Story Timeline"
      },
      {
        "hidden": false,
        "name": "blocks/studio-services",
        "renderer": "library",
        "title": "Studio services"
      },
      {
        "hidden": false,
        "name": "blocks/tabbed-content",
        "renderer": "library",
        "title": "Tabbed Content"
      },
      {
        "hidden": false,
        "name": "business/locations",
        "renderer": "library",
        "title": "Business locations"
      },
      {
        "hidden": false,
        "name": "business/menu",
        "renderer": "library",
        "title": "Food and drink menu"
      },
      {
        "hidden": false,
        "name": "business/opening-hours",
        "renderer": "library",
        "title": "Opening hours"
      },
      {
        "hidden": false,
        "name": "business/service-list",
        "renderer": "library",
        "title": "Services and rates"
      },
      {
        "hidden": false,
        "name": "certificates/verify",
        "renderer": "library",
        "title": "Certificate verify"
      },
      {
        "hidden": false,
        "name": "commerce/assistant-band",
        "renderer": "library",
        "title": "Shopping Assistant Band"
      },
      {
        "hidden": false,
        "name": "commerce/brand-list",
        "renderer": "library",
        "title": "Brand list"
      },
      {
        "hidden": false,
        "name": "commerce/bundle-offer",
        "renderer": "library",
        "title": "Bundle offer"
      },
      {
        "hidden": false,
        "name": "commerce/cart-cta",
        "renderer": "library",
        "title": "Cart CTA"
      },
      {
        "hidden": false,
        "name": "commerce/category-tiles",
        "renderer": "library",
        "title": "Category Tiles"
      },
      {
        "hidden": false,
        "name": "commerce/download-library",
        "renderer": "library",
        "title": "Purchased downloads"
      },
      {
        "hidden": false,
        "name": "commerce/product-compare",
        "renderer": "library",
        "title": "Product compare"
      },
      {
        "hidden": false,
        "name": "commerce/product-hero",
        "renderer": "library",
        "title": "Product hero"
      },
      {
        "hidden": false,
        "name": "commerce/product-showcase",
        "renderer": "library",
        "title": "Product Showcase"
      },
      {
        "hidden": false,
        "name": "commerce/recently-viewed",
        "renderer": "library",
        "title": "Recently viewed"
      },
      {
        "hidden": false,
        "name": "commerce/sale-countdown",
        "renderer": "library",
        "title": "Sale countdown"
      },
      {
        "hidden": false,
        "name": "commerce/search-band",
        "renderer": "library",
        "title": "Search band"
      },
      {
        "hidden": false,
        "name": "commerce/shipping-promise",
        "renderer": "library",
        "title": "Shipping promise"
      },
      {
        "hidden": false,
        "name": "commerce/variant-picker-teaser",
        "renderer": "library",
        "title": "Variant picker teaser"
      },
      {
        "hidden": false,
        "name": "commerce/wishlist",
        "renderer": "library",
        "title": "Saved products"
      },
      {
        "hidden": false,
        "name": "core/accordion",
        "renderer": "library",
        "title": "Accordion"
      },
      {
        "hidden": false,
        "name": "core/account-teaser",
        "renderer": "library",
        "title": "Account teaser"
      },
      {
        "hidden": false,
        "name": "core/anchor-nav",
        "renderer": "library",
        "title": "Anchor nav"
      },
      {
        "hidden": false,
        "name": "core/announcement-bar",
        "renderer": "library",
        "title": "Announcement bar"
      },
      {
        "hidden": false,
        "name": "core/archive-list",
        "renderer": "library",
        "title": "Archive list"
      },
      {
        "hidden": false,
        "name": "core/audio",
        "renderer": "library",
        "title": "Audio"
      },
      {
        "hidden": false,
        "name": "core/author-bio",
        "renderer": "library",
        "title": "Author bio"
      },
      {
        "hidden": false,
        "name": "core/before-after",
        "renderer": "library",
        "title": "Before / after"
      },
      {
        "hidden": false,
        "name": "core/bento-grid",
        "renderer": "library",
        "title": "Bento grid"
      },
      {
        "hidden": false,
        "name": "core/booking-cta",
        "renderer": "library",
        "title": "Booking CTA"
      },
      {
        "hidden": false,
        "name": "core/breadcrumbs",
        "renderer": "library",
        "title": "Breadcrumbs"
      },
      {
        "hidden": false,
        "name": "core/callout",
        "renderer": "library",
        "title": "Callout"
      },
      {
        "hidden": false,
        "name": "core/carousel",
        "renderer": "library",
        "title": "Carousel"
      },
      {
        "hidden": false,
        "name": "core/child-pages",
        "renderer": "library",
        "title": "Child pages"
      },
      {
        "hidden": false,
        "name": "core/code",
        "renderer": "library",
        "title": "Code"
      },
      {
        "hidden": false,
        "name": "core/columns",
        "renderer": "library",
        "title": "Columns"
      },
      {
        "hidden": false,
        "name": "core/comparison-table",
        "renderer": "library",
        "title": "Comparison table"
      },
      {
        "hidden": false,
        "name": "core/contact-form",
        "renderer": "library",
        "title": "Contact form"
      },
      {
        "hidden": false,
        "name": "core/countdown",
        "renderer": "library",
        "title": "Countdown"
      },
      {
        "hidden": false,
        "name": "core/cta-band",
        "renderer": "library",
        "title": "CTA Band"
      },
      {
        "hidden": false,
        "name": "core/cta-with-form",
        "renderer": "library",
        "title": "CTA with inline form"
      },
      {
        "hidden": false,
        "name": "core/custom-html",
        "renderer": "library",
        "title": "Custom HTML"
      },
      {
        "hidden": false,
        "name": "core/definition-list",
        "renderer": "library",
        "title": "Definition list"
      },
      {
        "hidden": false,
        "name": "core/divider",
        "renderer": "library",
        "title": "Divider"
      },
      {
        "hidden": false,
        "name": "core/embed",
        "renderer": "library",
        "title": "Embed"
      },
      {
        "hidden": false,
        "name": "core/event-rsvp",
        "renderer": "library",
        "title": "Event RSVP"
      },
      {
        "hidden": false,
        "name": "core/faq",
        "renderer": "library",
        "title": "FAQ"
      },
      {
        "hidden": false,
        "name": "core/feature-grid",
        "renderer": "library",
        "title": "Feature Grid"
      },
      {
        "hidden": false,
        "name": "core/feature-list-alternating",
        "renderer": "library",
        "title": "Feature list (alternating)"
      },
      {
        "hidden": false,
        "name": "core/feature-tabs",
        "renderer": "library",
        "title": "Feature tabs"
      },
      {
        "hidden": false,
        "name": "core/featured-page",
        "renderer": "library",
        "title": "Featured page"
      },
      {
        "hidden": false,
        "name": "core/featured-products",
        "renderer": "library",
        "title": "Featured products"
      },
      {
        "hidden": false,
        "name": "core/file-download",
        "renderer": "library",
        "title": "File download"
      },
      {
        "hidden": false,
        "name": "core/footnotes",
        "renderer": "library",
        "title": "Footnotes"
      },
      {
        "hidden": false,
        "name": "core/form",
        "renderer": "library",
        "title": "Form embed"
      },
      {
        "hidden": false,
        "name": "core/gallery",
        "renderer": "library",
        "title": "Gallery"
      },
      {
        "hidden": false,
        "name": "core/grid",
        "renderer": "library",
        "title": "Grid"
      },
      {
        "hidden": false,
        "name": "core/group",
        "renderer": "library",
        "title": "Group"
      },
      {
        "hidden": false,
        "name": "core/heading",
        "renderer": "library",
        "title": "Heading"
      },
      {
        "hidden": false,
        "name": "core/hero",
        "renderer": "owned",
        "title": "Hero"
      },
      {
        "hidden": false,
        "name": "core/hero-split",
        "renderer": "library",
        "title": "Hero (split)"
      },
      {
        "hidden": false,
        "name": "core/hero-text-only",
        "renderer": "library",
        "title": "Hero (text only)"
      },
      {
        "hidden": false,
        "name": "core/hero-video",
        "renderer": "library",
        "title": "Hero video"
      },
      {
        "hidden": false,
        "name": "core/iframe",
        "renderer": "library",
        "title": "Iframe"
      },
      {
        "hidden": false,
        "name": "core/image",
        "renderer": "library",
        "title": "Image"
      },
      {
        "hidden": false,
        "name": "core/language-switcher",
        "renderer": "library",
        "title": "Language switcher"
      },
      {
        "hidden": false,
        "name": "core/latest-posts",
        "renderer": "library",
        "title": "Latest posts"
      },
      {
        "hidden": false,
        "name": "core/lead-magnet",
        "renderer": "library",
        "title": "Lead magnet"
      },
      {
        "hidden": false,
        "name": "core/lightbox-grid",
        "renderer": "library",
        "title": "Lightbox grid"
      },
      {
        "hidden": false,
        "name": "core/list",
        "renderer": "library",
        "title": "List"
      },
      {
        "hidden": false,
        "name": "core/logo-cloud",
        "renderer": "library",
        "title": "Logo cloud"
      },
      {
        "hidden": false,
        "name": "core/map",
        "renderer": "library",
        "title": "Map"
      },
      {
        "hidden": false,
        "name": "core/marquee",
        "renderer": "library",
        "title": "Marquee"
      },
      {
        "hidden": false,
        "name": "core/media-text",
        "renderer": "library",
        "title": "Media + Text"
      },
      {
        "hidden": false,
        "name": "core/menu",
        "renderer": "library",
        "title": "Menu"
      },
      {
        "hidden": false,
        "name": "core/newsletter-signup",
        "renderer": "library",
        "title": "Newsletter signup"
      },
      {
        "hidden": false,
        "name": "core/paragraph",
        "renderer": "library",
        "title": "Paragraph"
      },
      {
        "hidden": false,
        "name": "core/poll",
        "renderer": "library",
        "title": "Poll"
      },
      {
        "hidden": false,
        "name": "core/post-grid",
        "renderer": "library",
        "title": "Post grid"
      },
      {
        "hidden": false,
        "name": "core/pricing-cards",
        "renderer": "library",
        "title": "Pricing Cards"
      },
      {
        "hidden": false,
        "name": "core/pricing-table",
        "renderer": "library",
        "title": "Pricing table"
      },
      {
        "hidden": false,
        "name": "core/process-steps",
        "renderer": "library",
        "title": "Process steps"
      },
      {
        "hidden": false,
        "name": "core/pullquote",
        "renderer": "library",
        "title": "Pullquote"
      },
      {
        "hidden": false,
        "name": "core/quote",
        "renderer": "library",
        "title": "Quote"
      },
      {
        "hidden": false,
        "name": "core/related-content",
        "renderer": "library",
        "title": "Related content"
      },
      {
        "hidden": false,
        "name": "core/reviews",
        "renderer": "library",
        "title": "Reviews"
      },
      {
        "hidden": false,
        "name": "core/rich-text",
        "renderer": "library",
        "title": "Rich Text Section"
      },
      {
        "hidden": false,
        "name": "core/roadmap-timeline",
        "renderer": "library",
        "title": "Roadmap timeline"
      },
      {
        "hidden": false,
        "name": "core/script-embed",
        "renderer": "library",
        "title": "Script embed"
      },
      {
        "hidden": false,
        "name": "core/search-box",
        "renderer": "library",
        "title": "Search box"
      },
      {
        "hidden": false,
        "name": "core/search-results",
        "renderer": "library",
        "title": "Search results"
      },
      {
        "hidden": false,
        "name": "core/section",
        "renderer": "library",
        "title": "Section"
      },
      {
        "hidden": false,
        "name": "core/site-info",
        "renderer": "library",
        "title": "Site info"
      },
      {
        "hidden": false,
        "name": "core/social-feed",
        "renderer": "library",
        "title": "Social feed"
      },
      {
        "hidden": false,
        "name": "core/social-links",
        "renderer": "library",
        "title": "Social links"
      },
      {
        "hidden": false,
        "name": "core/spacer",
        "renderer": "library",
        "title": "Spacer"
      },
      {
        "hidden": false,
        "name": "core/split",
        "renderer": "library",
        "title": "Split"
      },
      {
        "hidden": false,
        "name": "core/stats-band",
        "renderer": "library",
        "title": "Stats band"
      },
      {
        "hidden": false,
        "name": "core/steps-with-media",
        "renderer": "library",
        "title": "Steps with media"
      },
      {
        "hidden": false,
        "name": "core/sticky-aside",
        "renderer": "library",
        "title": "Sticky aside"
      },
      {
        "hidden": false,
        "name": "core/synced",
        "renderer": "library",
        "title": "Synced content"
      },
      {
        "hidden": false,
        "name": "core/table",
        "renderer": "library",
        "title": "Table"
      },
      {
        "hidden": false,
        "name": "core/table-of-contents",
        "renderer": "library",
        "title": "Table of contents"
      },
      {
        "hidden": false,
        "name": "core/tabs",
        "renderer": "library",
        "title": "Tabs"
      },
      {
        "hidden": false,
        "name": "core/tag-cloud",
        "renderer": "library",
        "title": "Tag cloud"
      },
      {
        "hidden": false,
        "name": "core/team-grid",
        "renderer": "library",
        "title": "Team grid"
      },
      {
        "hidden": false,
        "name": "core/testimonial-wall",
        "renderer": "library",
        "title": "Testimonial wall"
      },
      {
        "hidden": false,
        "name": "core/testimonials",
        "renderer": "library",
        "title": "Testimonials"
      },
      {
        "hidden": false,
        "name": "core/trust-badges",
        "renderer": "library",
        "title": "Trust badges"
      },
      {
        "hidden": false,
        "name": "core/ugc-grid",
        "renderer": "library",
        "title": "UGC grid"
      },
      {
        "hidden": false,
        "name": "core/video",
        "renderer": "library",
        "title": "Video"
      },
      {
        "hidden": false,
        "name": "events/calendar",
        "renderer": "library",
        "title": "Event calendar"
      },
      {
        "hidden": false,
        "name": "events/next-event",
        "renderer": "library",
        "title": "Next event"
      },
      {
        "hidden": false,
        "name": "events/upcoming",
        "renderer": "library",
        "title": "Upcoming Events"
      },
      {
        "hidden": false,
        "name": "gallery/album",
        "renderer": "library",
        "title": "Gallery album"
      },
      {
        "hidden": false,
        "name": "gallery/recipe-card",
        "renderer": "library",
        "title": "Recipe card"
      },
      {
        "hidden": false,
        "name": "lms/course-grid",
        "renderer": "library",
        "title": "Course grid"
      },
      {
        "hidden": false,
        "name": "lms/curriculum",
        "renderer": "library",
        "title": "Curriculum"
      },
      {
        "hidden": false,
        "name": "lms/instructor",
        "renderer": "library",
        "title": "Instructor"
      },
      {
        "hidden": false,
        "name": "lms/progress",
        "renderer": "library",
        "title": "Learner progress"
      },
      {
        "hidden": false,
        "name": "local/sample-alert",
        "renderer": "library",
        "title": "Sample Alert"
      },
      {
        "hidden": false,
        "name": "membership/gated-teaser",
        "renderer": "library",
        "title": "Gated teaser"
      },
      {
        "hidden": false,
        "name": "membership/plans",
        "renderer": "library",
        "title": "Membership plans"
      },
      {
        "hidden": false,
        "name": "reference/field-guide",
        "renderer": "library",
        "title": "Field Guide"
      },
      {
        "hidden": false,
        "name": "support/kb-search",
        "renderer": "library",
        "title": "Knowledge base search"
      },
      {
        "hidden": false,
        "name": "support/ticket-cta",
        "renderer": "library",
        "title": "Ticket CTA"
      }
    ],
    "id": "core",
    "title": "Core"
  },
  {
    "blocks": [
      {
        "hidden": false,
        "name": "blocks/contact-stack",
        "renderer": "library",
        "title": "Contact Stack"
      },
      {
        "hidden": false,
        "name": "blocks/customer-showcase",
        "renderer": "library",
        "title": "Customer Showcase"
      },
      {
        "hidden": false,
        "name": "blocks/grade-gallery",
        "renderer": "library",
        "title": "Grade Gallery"
      },
      {
        "hidden": false,
        "name": "blocks/media-mentions",
        "renderer": "library",
        "title": "Media Mentions"
      },
      {
        "hidden": false,
        "name": "blocks/page-banner",
        "renderer": "owned",
        "title": "Page Banner"
      },
      {
        "hidden": false,
        "name": "blocks/product-collection",
        "renderer": "library",
        "title": "Product Collection"
      },
      {
        "hidden": false,
        "name": "blocks/promo-band",
        "renderer": "library",
        "title": "Promo Band"
      },
      {
        "hidden": false,
        "name": "blocks/social-share",
        "renderer": "library",
        "title": "Social Share"
      },
      {
        "hidden": false,
        "name": "blocks/story-timeline",
        "renderer": "library",
        "title": "Story Timeline"
      },
      {
        "hidden": false,
        "name": "blocks/studio-services",
        "renderer": "library",
        "title": "Studio services"
      },
      {
        "hidden": false,
        "name": "blocks/tabbed-content",
        "renderer": "library",
        "title": "Tabbed Content"
      },
      {
        "hidden": false,
        "name": "business/locations",
        "renderer": "library",
        "title": "Business locations"
      },
      {
        "hidden": false,
        "name": "business/menu",
        "renderer": "library",
        "title": "Food and drink menu"
      },
      {
        "hidden": false,
        "name": "business/opening-hours",
        "renderer": "library",
        "title": "Opening hours"
      },
      {
        "hidden": false,
        "name": "business/service-list",
        "renderer": "library",
        "title": "Services and rates"
      },
      {
        "hidden": false,
        "name": "certificates/verify",
        "renderer": "library",
        "title": "Certificate verify"
      },
      {
        "hidden": false,
        "name": "commerce/assistant-band",
        "renderer": "library",
        "title": "Shopping Assistant Band"
      },
      {
        "hidden": false,
        "name": "commerce/brand-list",
        "renderer": "library",
        "title": "Brand list"
      },
      {
        "hidden": false,
        "name": "commerce/bundle-offer",
        "renderer": "library",
        "title": "Bundle offer"
      },
      {
        "hidden": false,
        "name": "commerce/cart-cta",
        "renderer": "library",
        "title": "Cart CTA"
      },
      {
        "hidden": false,
        "name": "commerce/category-tiles",
        "renderer": "owned",
        "title": "Category Tiles"
      },
      {
        "hidden": false,
        "name": "commerce/download-library",
        "renderer": "library",
        "title": "Purchased downloads"
      },
      {
        "hidden": false,
        "name": "commerce/product-compare",
        "renderer": "library",
        "title": "Product compare"
      },
      {
        "hidden": false,
        "name": "commerce/product-hero",
        "renderer": "library",
        "title": "Product hero"
      },
      {
        "hidden": false,
        "name": "commerce/product-showcase",
        "renderer": "owned",
        "title": "Product Showcase"
      },
      {
        "hidden": false,
        "name": "commerce/recently-viewed",
        "renderer": "library",
        "title": "Recently viewed"
      },
      {
        "hidden": false,
        "name": "commerce/sale-countdown",
        "renderer": "library",
        "title": "Sale countdown"
      },
      {
        "hidden": false,
        "name": "commerce/search-band",
        "renderer": "library",
        "title": "Search band"
      },
      {
        "hidden": false,
        "name": "commerce/shipping-promise",
        "renderer": "library",
        "title": "Shipping promise"
      },
      {
        "hidden": false,
        "name": "commerce/variant-picker-teaser",
        "renderer": "library",
        "title": "Variant picker teaser"
      },
      {
        "hidden": false,
        "name": "commerce/wishlist",
        "renderer": "library",
        "title": "Saved products"
      },
      {
        "hidden": false,
        "name": "core/accordion",
        "renderer": "library",
        "title": "Accordion"
      },
      {
        "hidden": false,
        "name": "core/account-teaser",
        "renderer": "library",
        "title": "Account teaser"
      },
      {
        "hidden": false,
        "name": "core/anchor-nav",
        "renderer": "library",
        "title": "Anchor nav"
      },
      {
        "hidden": false,
        "name": "core/announcement-bar",
        "renderer": "library",
        "title": "Announcement bar"
      },
      {
        "hidden": false,
        "name": "core/archive-list",
        "renderer": "library",
        "title": "Archive list"
      },
      {
        "hidden": false,
        "name": "core/audio",
        "renderer": "library",
        "title": "Audio"
      },
      {
        "hidden": false,
        "name": "core/author-bio",
        "renderer": "library",
        "title": "Author bio"
      },
      {
        "hidden": false,
        "name": "core/before-after",
        "renderer": "library",
        "title": "Before / after"
      },
      {
        "hidden": false,
        "name": "core/bento-grid",
        "renderer": "library",
        "title": "Bento grid"
      },
      {
        "hidden": false,
        "name": "core/booking-cta",
        "renderer": "library",
        "title": "Booking CTA"
      },
      {
        "hidden": false,
        "name": "core/breadcrumbs",
        "renderer": "library",
        "title": "Breadcrumbs"
      },
      {
        "hidden": false,
        "name": "core/callout",
        "renderer": "library",
        "title": "Callout"
      },
      {
        "hidden": false,
        "name": "core/carousel",
        "renderer": "library",
        "title": "Carousel"
      },
      {
        "hidden": false,
        "name": "core/child-pages",
        "renderer": "library",
        "title": "Child pages"
      },
      {
        "hidden": false,
        "name": "core/code",
        "renderer": "library",
        "title": "Code"
      },
      {
        "hidden": false,
        "name": "core/columns",
        "renderer": "owned",
        "title": "Columns"
      },
      {
        "hidden": false,
        "name": "core/comparison-table",
        "renderer": "library",
        "title": "Comparison table"
      },
      {
        "hidden": false,
        "name": "core/contact-form",
        "renderer": "library",
        "title": "Contact form"
      },
      {
        "hidden": false,
        "name": "core/countdown",
        "renderer": "library",
        "title": "Countdown"
      },
      {
        "hidden": false,
        "name": "core/cta-band",
        "renderer": "owned",
        "title": "CTA Band"
      },
      {
        "hidden": false,
        "name": "core/cta-with-form",
        "renderer": "library",
        "title": "CTA with inline form"
      },
      {
        "hidden": false,
        "name": "core/custom-html",
        "renderer": "library",
        "title": "Custom HTML"
      },
      {
        "hidden": false,
        "name": "core/definition-list",
        "renderer": "library",
        "title": "Definition list"
      },
      {
        "hidden": false,
        "name": "core/divider",
        "renderer": "library",
        "title": "Divider"
      },
      {
        "hidden": false,
        "name": "core/embed",
        "renderer": "library",
        "title": "Embed"
      },
      {
        "hidden": false,
        "name": "core/event-rsvp",
        "renderer": "library",
        "title": "Event RSVP"
      },
      {
        "hidden": false,
        "name": "core/faq",
        "renderer": "owned",
        "title": "FAQ"
      },
      {
        "hidden": false,
        "name": "core/feature-grid",
        "renderer": "owned",
        "title": "Feature Grid"
      },
      {
        "hidden": false,
        "name": "core/feature-list-alternating",
        "renderer": "library",
        "title": "Feature list (alternating)"
      },
      {
        "hidden": false,
        "name": "core/feature-tabs",
        "renderer": "library",
        "title": "Feature tabs"
      },
      {
        "hidden": false,
        "name": "core/featured-page",
        "renderer": "library",
        "title": "Featured page"
      },
      {
        "hidden": false,
        "name": "core/featured-products",
        "renderer": "library",
        "title": "Featured products"
      },
      {
        "hidden": false,
        "name": "core/file-download",
        "renderer": "library",
        "title": "File download"
      },
      {
        "hidden": false,
        "name": "core/footnotes",
        "renderer": "library",
        "title": "Footnotes"
      },
      {
        "hidden": false,
        "name": "core/form",
        "renderer": "owned",
        "title": "Form embed"
      },
      {
        "hidden": false,
        "name": "core/gallery",
        "renderer": "library",
        "title": "Gallery"
      },
      {
        "hidden": false,
        "name": "core/grid",
        "renderer": "library",
        "title": "Grid"
      },
      {
        "hidden": false,
        "name": "core/group",
        "renderer": "library",
        "title": "Group"
      },
      {
        "hidden": false,
        "name": "core/heading",
        "renderer": "library",
        "title": "Heading"
      },
      {
        "hidden": false,
        "name": "core/hero",
        "renderer": "owned",
        "title": "Hero"
      },
      {
        "hidden": false,
        "name": "core/hero-split",
        "renderer": "owned",
        "title": "Hero (split)"
      },
      {
        "hidden": false,
        "name": "core/hero-text-only",
        "renderer": "library",
        "title": "Hero (text only)"
      },
      {
        "hidden": false,
        "name": "core/hero-video",
        "renderer": "library",
        "title": "Hero video"
      },
      {
        "hidden": false,
        "name": "core/iframe",
        "renderer": "library",
        "title": "Iframe"
      },
      {
        "hidden": false,
        "name": "core/image",
        "renderer": "library",
        "title": "Image"
      },
      {
        "hidden": false,
        "name": "core/language-switcher",
        "renderer": "library",
        "title": "Language switcher"
      },
      {
        "hidden": false,
        "name": "core/latest-posts",
        "renderer": "owned",
        "title": "Latest posts"
      },
      {
        "hidden": false,
        "name": "core/lead-magnet",
        "renderer": "library",
        "title": "Lead magnet"
      },
      {
        "hidden": false,
        "name": "core/lightbox-grid",
        "renderer": "library",
        "title": "Lightbox grid"
      },
      {
        "hidden": false,
        "name": "core/list",
        "renderer": "library",
        "title": "List"
      },
      {
        "hidden": false,
        "name": "core/logo-cloud",
        "renderer": "library",
        "title": "Logo cloud"
      },
      {
        "hidden": false,
        "name": "core/map",
        "renderer": "library",
        "title": "Map"
      },
      {
        "hidden": false,
        "name": "core/marquee",
        "renderer": "library",
        "title": "Marquee"
      },
      {
        "hidden": false,
        "name": "core/media-text",
        "renderer": "owned",
        "title": "Media + Text"
      },
      {
        "hidden": false,
        "name": "core/menu",
        "renderer": "library",
        "title": "Menu"
      },
      {
        "hidden": false,
        "name": "core/newsletter-signup",
        "renderer": "library",
        "title": "Newsletter signup"
      },
      {
        "hidden": false,
        "name": "core/paragraph",
        "renderer": "library",
        "title": "Paragraph"
      },
      {
        "hidden": false,
        "name": "core/poll",
        "renderer": "library",
        "title": "Poll"
      },
      {
        "hidden": false,
        "name": "core/post-grid",
        "renderer": "library",
        "title": "Post grid"
      },
      {
        "hidden": false,
        "name": "core/pricing-cards",
        "renderer": "owned",
        "title": "Pricing Cards"
      },
      {
        "hidden": false,
        "name": "core/pricing-table",
        "renderer": "library",
        "title": "Pricing table"
      },
      {
        "hidden": false,
        "name": "core/process-steps",
        "renderer": "library",
        "title": "Process steps"
      },
      {
        "hidden": false,
        "name": "core/pullquote",
        "renderer": "library",
        "title": "Pullquote"
      },
      {
        "hidden": false,
        "name": "core/quote",
        "renderer": "library",
        "title": "Quote"
      },
      {
        "hidden": false,
        "name": "core/related-content",
        "renderer": "library",
        "title": "Related content"
      },
      {
        "hidden": false,
        "name": "core/reviews",
        "renderer": "library",
        "title": "Reviews"
      },
      {
        "hidden": false,
        "name": "core/rich-text",
        "renderer": "library",
        "title": "Rich Text Section"
      },
      {
        "hidden": false,
        "name": "core/roadmap-timeline",
        "renderer": "library",
        "title": "Roadmap timeline"
      },
      {
        "hidden": false,
        "name": "core/script-embed",
        "renderer": "library",
        "title": "Script embed"
      },
      {
        "hidden": false,
        "name": "core/search-box",
        "renderer": "library",
        "title": "Search box"
      },
      {
        "hidden": false,
        "name": "core/search-results",
        "renderer": "library",
        "title": "Search results"
      },
      {
        "hidden": false,
        "name": "core/section",
        "renderer": "owned",
        "title": "Section"
      },
      {
        "hidden": false,
        "name": "core/site-info",
        "renderer": "library",
        "title": "Site info"
      },
      {
        "hidden": false,
        "name": "core/social-feed",
        "renderer": "library",
        "title": "Social feed"
      },
      {
        "hidden": false,
        "name": "core/social-links",
        "renderer": "library",
        "title": "Social links"
      },
      {
        "hidden": false,
        "name": "core/spacer",
        "renderer": "library",
        "title": "Spacer"
      },
      {
        "hidden": false,
        "name": "core/split",
        "renderer": "library",
        "title": "Split"
      },
      {
        "hidden": false,
        "name": "core/stats-band",
        "renderer": "library",
        "title": "Stats band"
      },
      {
        "hidden": false,
        "name": "core/steps-with-media",
        "renderer": "library",
        "title": "Steps with media"
      },
      {
        "hidden": false,
        "name": "core/sticky-aside",
        "renderer": "library",
        "title": "Sticky aside"
      },
      {
        "hidden": false,
        "name": "core/synced",
        "renderer": "library",
        "title": "Synced content"
      },
      {
        "hidden": false,
        "name": "core/table",
        "renderer": "library",
        "title": "Table"
      },
      {
        "hidden": false,
        "name": "core/table-of-contents",
        "renderer": "library",
        "title": "Table of contents"
      },
      {
        "hidden": false,
        "name": "core/tabs",
        "renderer": "library",
        "title": "Tabs"
      },
      {
        "hidden": false,
        "name": "core/tag-cloud",
        "renderer": "library",
        "title": "Tag cloud"
      },
      {
        "hidden": false,
        "name": "core/team-grid",
        "renderer": "library",
        "title": "Team grid"
      },
      {
        "hidden": false,
        "name": "core/testimonial-wall",
        "renderer": "library",
        "title": "Testimonial wall"
      },
      {
        "hidden": false,
        "name": "core/testimonials",
        "renderer": "owned",
        "title": "Testimonials"
      },
      {
        "hidden": false,
        "name": "core/trust-badges",
        "renderer": "library",
        "title": "Trust badges"
      },
      {
        "hidden": false,
        "name": "core/ugc-grid",
        "renderer": "library",
        "title": "UGC grid"
      },
      {
        "hidden": false,
        "name": "core/video",
        "renderer": "library",
        "title": "Video"
      },
      {
        "hidden": false,
        "name": "events/calendar",
        "renderer": "library",
        "title": "Event calendar"
      },
      {
        "hidden": false,
        "name": "events/next-event",
        "renderer": "library",
        "title": "Next event"
      },
      {
        "hidden": false,
        "name": "events/upcoming",
        "renderer": "library",
        "title": "Upcoming Events"
      },
      {
        "hidden": false,
        "name": "gallery/album",
        "renderer": "library",
        "title": "Gallery album"
      },
      {
        "hidden": false,
        "name": "gallery/recipe-card",
        "renderer": "library",
        "title": "Recipe card"
      },
      {
        "hidden": false,
        "name": "lms/course-grid",
        "renderer": "library",
        "title": "Course grid"
      },
      {
        "hidden": false,
        "name": "lms/curriculum",
        "renderer": "library",
        "title": "Curriculum"
      },
      {
        "hidden": false,
        "name": "lms/instructor",
        "renderer": "library",
        "title": "Instructor"
      },
      {
        "hidden": false,
        "name": "lms/progress",
        "renderer": "library",
        "title": "Learner progress"
      },
      {
        "hidden": false,
        "name": "local/sample-alert",
        "renderer": "library",
        "title": "Sample Alert"
      },
      {
        "hidden": false,
        "name": "membership/gated-teaser",
        "renderer": "library",
        "title": "Gated teaser"
      },
      {
        "hidden": false,
        "name": "membership/plans",
        "renderer": "library",
        "title": "Membership plans"
      },
      {
        "hidden": false,
        "name": "reference/field-guide",
        "renderer": "library",
        "title": "Field Guide"
      },
      {
        "hidden": false,
        "name": "support/kb-search",
        "renderer": "library",
        "title": "Knowledge base search"
      },
      {
        "hidden": false,
        "name": "support/ticket-cta",
        "renderer": "library",
        "title": "Ticket CTA"
      }
    ],
    "id": "depot",
    "title": "Depot"
  },
  {
    "blocks": [
      {
        "hidden": false,
        "name": "blocks/contact-stack",
        "renderer": "library",
        "title": "Contact Stack"
      },
      {
        "hidden": false,
        "name": "blocks/customer-showcase",
        "renderer": "library",
        "title": "Customer Showcase"
      },
      {
        "hidden": false,
        "name": "blocks/grade-gallery",
        "renderer": "library",
        "title": "Grade Gallery"
      },
      {
        "hidden": false,
        "name": "blocks/media-mentions",
        "renderer": "library",
        "title": "Media Mentions"
      },
      {
        "hidden": false,
        "name": "blocks/page-banner",
        "renderer": "owned",
        "title": "Page Banner"
      },
      {
        "hidden": false,
        "name": "blocks/product-collection",
        "renderer": "library",
        "title": "Product Collection"
      },
      {
        "hidden": false,
        "name": "blocks/promo-band",
        "renderer": "library",
        "title": "Promo Band"
      },
      {
        "hidden": false,
        "name": "blocks/social-share",
        "renderer": "library",
        "title": "Social Share"
      },
      {
        "hidden": false,
        "name": "blocks/story-timeline",
        "renderer": "library",
        "title": "Story Timeline"
      },
      {
        "hidden": false,
        "name": "blocks/studio-services",
        "renderer": "library",
        "title": "Studio services"
      },
      {
        "hidden": false,
        "name": "blocks/tabbed-content",
        "renderer": "library",
        "title": "Tabbed Content"
      },
      {
        "hidden": false,
        "name": "business/locations",
        "renderer": "library",
        "title": "Business locations"
      },
      {
        "hidden": false,
        "name": "business/menu",
        "renderer": "library",
        "title": "Food and drink menu"
      },
      {
        "hidden": false,
        "name": "business/opening-hours",
        "renderer": "library",
        "title": "Opening hours"
      },
      {
        "hidden": false,
        "name": "business/service-list",
        "renderer": "library",
        "title": "Services and rates"
      },
      {
        "hidden": false,
        "name": "certificates/verify",
        "renderer": "library",
        "title": "Certificate verify"
      },
      {
        "hidden": false,
        "name": "commerce/assistant-band",
        "renderer": "library",
        "title": "Shopping Assistant Band"
      },
      {
        "hidden": false,
        "name": "commerce/brand-list",
        "renderer": "library",
        "title": "Brand list"
      },
      {
        "hidden": false,
        "name": "commerce/bundle-offer",
        "renderer": "library",
        "title": "Bundle offer"
      },
      {
        "hidden": false,
        "name": "commerce/cart-cta",
        "renderer": "library",
        "title": "Cart CTA"
      },
      {
        "hidden": false,
        "name": "commerce/category-tiles",
        "renderer": "owned",
        "title": "Category Tiles"
      },
      {
        "hidden": false,
        "name": "commerce/download-library",
        "renderer": "library",
        "title": "Purchased downloads"
      },
      {
        "hidden": false,
        "name": "commerce/product-compare",
        "renderer": "library",
        "title": "Product compare"
      },
      {
        "hidden": false,
        "name": "commerce/product-hero",
        "renderer": "library",
        "title": "Product hero"
      },
      {
        "hidden": false,
        "name": "commerce/product-showcase",
        "renderer": "owned",
        "title": "Product Showcase"
      },
      {
        "hidden": false,
        "name": "commerce/recently-viewed",
        "renderer": "library",
        "title": "Recently viewed"
      },
      {
        "hidden": false,
        "name": "commerce/sale-countdown",
        "renderer": "library",
        "title": "Sale countdown"
      },
      {
        "hidden": false,
        "name": "commerce/search-band",
        "renderer": "library",
        "title": "Search band"
      },
      {
        "hidden": false,
        "name": "commerce/shipping-promise",
        "renderer": "library",
        "title": "Shipping promise"
      },
      {
        "hidden": false,
        "name": "commerce/variant-picker-teaser",
        "renderer": "library",
        "title": "Variant picker teaser"
      },
      {
        "hidden": false,
        "name": "commerce/wishlist",
        "renderer": "library",
        "title": "Saved products"
      },
      {
        "hidden": false,
        "name": "core/accordion",
        "renderer": "library",
        "title": "Accordion"
      },
      {
        "hidden": false,
        "name": "core/account-teaser",
        "renderer": "library",
        "title": "Account teaser"
      },
      {
        "hidden": false,
        "name": "core/anchor-nav",
        "renderer": "library",
        "title": "Anchor nav"
      },
      {
        "hidden": false,
        "name": "core/announcement-bar",
        "renderer": "library",
        "title": "Announcement bar"
      },
      {
        "hidden": false,
        "name": "core/archive-list",
        "renderer": "library",
        "title": "Archive list"
      },
      {
        "hidden": false,
        "name": "core/audio",
        "renderer": "library",
        "title": "Audio"
      },
      {
        "hidden": false,
        "name": "core/author-bio",
        "renderer": "library",
        "title": "Author bio"
      },
      {
        "hidden": false,
        "name": "core/before-after",
        "renderer": "library",
        "title": "Before / after"
      },
      {
        "hidden": false,
        "name": "core/bento-grid",
        "renderer": "library",
        "title": "Bento grid"
      },
      {
        "hidden": false,
        "name": "core/booking-cta",
        "renderer": "library",
        "title": "Booking CTA"
      },
      {
        "hidden": false,
        "name": "core/breadcrumbs",
        "renderer": "library",
        "title": "Breadcrumbs"
      },
      {
        "hidden": false,
        "name": "core/callout",
        "renderer": "library",
        "title": "Callout"
      },
      {
        "hidden": false,
        "name": "core/carousel",
        "renderer": "library",
        "title": "Carousel"
      },
      {
        "hidden": false,
        "name": "core/child-pages",
        "renderer": "library",
        "title": "Child pages"
      },
      {
        "hidden": false,
        "name": "core/code",
        "renderer": "library",
        "title": "Code"
      },
      {
        "hidden": false,
        "name": "core/columns",
        "renderer": "owned",
        "title": "Columns"
      },
      {
        "hidden": false,
        "name": "core/comparison-table",
        "renderer": "library",
        "title": "Comparison table"
      },
      {
        "hidden": false,
        "name": "core/contact-form",
        "renderer": "library",
        "title": "Contact form"
      },
      {
        "hidden": false,
        "name": "core/countdown",
        "renderer": "library",
        "title": "Countdown"
      },
      {
        "hidden": false,
        "name": "core/cta-band",
        "renderer": "owned",
        "title": "CTA Band"
      },
      {
        "hidden": false,
        "name": "core/cta-with-form",
        "renderer": "library",
        "title": "CTA with inline form"
      },
      {
        "hidden": false,
        "name": "core/custom-html",
        "renderer": "library",
        "title": "Custom HTML"
      },
      {
        "hidden": false,
        "name": "core/definition-list",
        "renderer": "library",
        "title": "Definition list"
      },
      {
        "hidden": false,
        "name": "core/divider",
        "renderer": "library",
        "title": "Divider"
      },
      {
        "hidden": false,
        "name": "core/embed",
        "renderer": "library",
        "title": "Embed"
      },
      {
        "hidden": false,
        "name": "core/event-rsvp",
        "renderer": "library",
        "title": "Event RSVP"
      },
      {
        "hidden": false,
        "name": "core/faq",
        "renderer": "owned",
        "title": "FAQ"
      },
      {
        "hidden": false,
        "name": "core/feature-grid",
        "renderer": "owned",
        "title": "Feature Grid"
      },
      {
        "hidden": false,
        "name": "core/feature-list-alternating",
        "renderer": "library",
        "title": "Feature list (alternating)"
      },
      {
        "hidden": false,
        "name": "core/feature-tabs",
        "renderer": "library",
        "title": "Feature tabs"
      },
      {
        "hidden": false,
        "name": "core/featured-page",
        "renderer": "library",
        "title": "Featured page"
      },
      {
        "hidden": false,
        "name": "core/featured-products",
        "renderer": "library",
        "title": "Featured products"
      },
      {
        "hidden": false,
        "name": "core/file-download",
        "renderer": "library",
        "title": "File download"
      },
      {
        "hidden": false,
        "name": "core/footnotes",
        "renderer": "library",
        "title": "Footnotes"
      },
      {
        "hidden": false,
        "name": "core/form",
        "renderer": "owned",
        "title": "Form embed"
      },
      {
        "hidden": false,
        "name": "core/gallery",
        "renderer": "library",
        "title": "Gallery"
      },
      {
        "hidden": false,
        "name": "core/grid",
        "renderer": "library",
        "title": "Grid"
      },
      {
        "hidden": false,
        "name": "core/group",
        "renderer": "library",
        "title": "Group"
      },
      {
        "hidden": false,
        "name": "core/heading",
        "renderer": "library",
        "title": "Heading"
      },
      {
        "hidden": false,
        "name": "core/hero",
        "renderer": "owned",
        "title": "Hero"
      },
      {
        "hidden": false,
        "name": "core/hero-split",
        "renderer": "owned",
        "title": "Hero (split)"
      },
      {
        "hidden": false,
        "name": "core/hero-text-only",
        "renderer": "library",
        "title": "Hero (text only)"
      },
      {
        "hidden": false,
        "name": "core/hero-video",
        "renderer": "library",
        "title": "Hero video"
      },
      {
        "hidden": false,
        "name": "core/iframe",
        "renderer": "library",
        "title": "Iframe"
      },
      {
        "hidden": false,
        "name": "core/image",
        "renderer": "library",
        "title": "Image"
      },
      {
        "hidden": false,
        "name": "core/language-switcher",
        "renderer": "library",
        "title": "Language switcher"
      },
      {
        "hidden": false,
        "name": "core/latest-posts",
        "renderer": "owned",
        "title": "Latest posts"
      },
      {
        "hidden": false,
        "name": "core/lead-magnet",
        "renderer": "library",
        "title": "Lead magnet"
      },
      {
        "hidden": false,
        "name": "core/lightbox-grid",
        "renderer": "library",
        "title": "Lightbox grid"
      },
      {
        "hidden": false,
        "name": "core/list",
        "renderer": "library",
        "title": "List"
      },
      {
        "hidden": false,
        "name": "core/logo-cloud",
        "renderer": "library",
        "title": "Logo cloud"
      },
      {
        "hidden": false,
        "name": "core/map",
        "renderer": "library",
        "title": "Map"
      },
      {
        "hidden": false,
        "name": "core/marquee",
        "renderer": "library",
        "title": "Marquee"
      },
      {
        "hidden": false,
        "name": "core/media-text",
        "renderer": "owned",
        "title": "Media + Text"
      },
      {
        "hidden": false,
        "name": "core/menu",
        "renderer": "library",
        "title": "Menu"
      },
      {
        "hidden": false,
        "name": "core/newsletter-signup",
        "renderer": "library",
        "title": "Newsletter signup"
      },
      {
        "hidden": false,
        "name": "core/paragraph",
        "renderer": "library",
        "title": "Paragraph"
      },
      {
        "hidden": false,
        "name": "core/poll",
        "renderer": "library",
        "title": "Poll"
      },
      {
        "hidden": false,
        "name": "core/post-grid",
        "renderer": "library",
        "title": "Post grid"
      },
      {
        "hidden": false,
        "name": "core/pricing-cards",
        "renderer": "owned",
        "title": "Pricing Cards"
      },
      {
        "hidden": false,
        "name": "core/pricing-table",
        "renderer": "library",
        "title": "Pricing table"
      },
      {
        "hidden": false,
        "name": "core/process-steps",
        "renderer": "library",
        "title": "Process steps"
      },
      {
        "hidden": false,
        "name": "core/pullquote",
        "renderer": "library",
        "title": "Pullquote"
      },
      {
        "hidden": false,
        "name": "core/quote",
        "renderer": "library",
        "title": "Quote"
      },
      {
        "hidden": false,
        "name": "core/related-content",
        "renderer": "library",
        "title": "Related content"
      },
      {
        "hidden": false,
        "name": "core/reviews",
        "renderer": "library",
        "title": "Reviews"
      },
      {
        "hidden": false,
        "name": "core/rich-text",
        "renderer": "library",
        "title": "Rich Text Section"
      },
      {
        "hidden": false,
        "name": "core/roadmap-timeline",
        "renderer": "library",
        "title": "Roadmap timeline"
      },
      {
        "hidden": false,
        "name": "core/script-embed",
        "renderer": "library",
        "title": "Script embed"
      },
      {
        "hidden": false,
        "name": "core/search-box",
        "renderer": "library",
        "title": "Search box"
      },
      {
        "hidden": false,
        "name": "core/search-results",
        "renderer": "library",
        "title": "Search results"
      },
      {
        "hidden": false,
        "name": "core/section",
        "renderer": "owned",
        "title": "Section"
      },
      {
        "hidden": false,
        "name": "core/site-info",
        "renderer": "library",
        "title": "Site info"
      },
      {
        "hidden": false,
        "name": "core/social-feed",
        "renderer": "library",
        "title": "Social feed"
      },
      {
        "hidden": false,
        "name": "core/social-links",
        "renderer": "library",
        "title": "Social links"
      },
      {
        "hidden": false,
        "name": "core/spacer",
        "renderer": "library",
        "title": "Spacer"
      },
      {
        "hidden": false,
        "name": "core/split",
        "renderer": "library",
        "title": "Split"
      },
      {
        "hidden": false,
        "name": "core/stats-band",
        "renderer": "library",
        "title": "Stats band"
      },
      {
        "hidden": false,
        "name": "core/steps-with-media",
        "renderer": "library",
        "title": "Steps with media"
      },
      {
        "hidden": false,
        "name": "core/sticky-aside",
        "renderer": "library",
        "title": "Sticky aside"
      },
      {
        "hidden": false,
        "name": "core/synced",
        "renderer": "library",
        "title": "Synced content"
      },
      {
        "hidden": false,
        "name": "core/table",
        "renderer": "library",
        "title": "Table"
      },
      {
        "hidden": false,
        "name": "core/table-of-contents",
        "renderer": "library",
        "title": "Table of contents"
      },
      {
        "hidden": false,
        "name": "core/tabs",
        "renderer": "library",
        "title": "Tabs"
      },
      {
        "hidden": false,
        "name": "core/tag-cloud",
        "renderer": "library",
        "title": "Tag cloud"
      },
      {
        "hidden": false,
        "name": "core/team-grid",
        "renderer": "library",
        "title": "Team grid"
      },
      {
        "hidden": false,
        "name": "core/testimonial-wall",
        "renderer": "library",
        "title": "Testimonial wall"
      },
      {
        "hidden": false,
        "name": "core/testimonials",
        "renderer": "owned",
        "title": "Testimonials"
      },
      {
        "hidden": false,
        "name": "core/trust-badges",
        "renderer": "library",
        "title": "Trust badges"
      },
      {
        "hidden": false,
        "name": "core/ugc-grid",
        "renderer": "library",
        "title": "UGC grid"
      },
      {
        "hidden": false,
        "name": "core/video",
        "renderer": "library",
        "title": "Video"
      },
      {
        "hidden": false,
        "name": "events/calendar",
        "renderer": "library",
        "title": "Event calendar"
      },
      {
        "hidden": false,
        "name": "events/next-event",
        "renderer": "library",
        "title": "Next event"
      },
      {
        "hidden": false,
        "name": "events/upcoming",
        "renderer": "library",
        "title": "Upcoming Events"
      },
      {
        "hidden": false,
        "name": "gallery/album",
        "renderer": "library",
        "title": "Gallery album"
      },
      {
        "hidden": false,
        "name": "gallery/recipe-card",
        "renderer": "library",
        "title": "Recipe card"
      },
      {
        "hidden": false,
        "name": "lms/course-grid",
        "renderer": "library",
        "title": "Course grid"
      },
      {
        "hidden": false,
        "name": "lms/curriculum",
        "renderer": "library",
        "title": "Curriculum"
      },
      {
        "hidden": false,
        "name": "lms/instructor",
        "renderer": "library",
        "title": "Instructor"
      },
      {
        "hidden": false,
        "name": "lms/progress",
        "renderer": "library",
        "title": "Learner progress"
      },
      {
        "hidden": false,
        "name": "local/sample-alert",
        "renderer": "library",
        "title": "Sample Alert"
      },
      {
        "hidden": false,
        "name": "membership/gated-teaser",
        "renderer": "library",
        "title": "Gated teaser"
      },
      {
        "hidden": false,
        "name": "membership/plans",
        "renderer": "library",
        "title": "Membership plans"
      },
      {
        "hidden": false,
        "name": "reference/field-guide",
        "renderer": "library",
        "title": "Field Guide"
      },
      {
        "hidden": false,
        "name": "support/kb-search",
        "renderer": "library",
        "title": "Knowledge base search"
      },
      {
        "hidden": false,
        "name": "support/ticket-cta",
        "renderer": "library",
        "title": "Ticket CTA"
      }
    ],
    "id": "journal",
    "title": "Journal"
  }
]
;
