// Generated by root sync:blocks. Do not edit. Staged contracts; runtime activation is separate.
import type { z } from "zod";
import type { blockSchemas, blockTreatmentSchemas } from "./schemas";
import type { CanonicalEnvelope } from "./instance-runtime.mjs";
export type { CanonicalLayout, CanonicalVisibility, CanonicalLock } from "./instance-runtime.mjs";
export type BlockName = keyof typeof blockSchemas;
export type AttrsByName = { [Name in BlockName]: z.output<(typeof blockSchemas)[Name]> };
export type InputAttrsByName = { [Name in BlockName]: z.input<(typeof blockSchemas)[Name]> };
export type TreatmentByName = { [Name in BlockName]: z.output<(typeof blockTreatmentSchemas)[Name]> };
export type CanonicalBlockInstance = { [Name in BlockName]: Omit<CanonicalEnvelope, "name" | "attrs" | "children" | "treatment"> & { name: Name; attrs: AttrsByName[Name]; treatment?: TreatmentByName[Name]; children?: CanonicalBlockInstance[] } }[BlockName];
export type CanonicalTree = CanonicalBlockInstance[];
