// AUTO-GENERATED by generate-extension-index.mjs.
import { plugin as plugin0 } from "../extensions/dashboard/plugin";
import { plugin as plugin1 } from "../extensions/events/plugin";
export const extensionPlugins: Array<{id:string;settingsKey:string;defaultEnabled:boolean;parentId?:string}> = [plugin0, plugin1];
