import { defineTable } from "convex/server";
import { v } from "convex/values";
export const contentPromotionTables = {
	contentPromotion_mediaRecoveryGrants: defineTable({
		recoveryKey: v.string(),
		reviewFingerprint: v.string(),
		transferKey: v.string(),
		intentId: v.id("contentPromotion_mediaUploads"),
		storageId: v.id("_storage"),
		creatorId: v.id("users"),
		beneficiaryId: v.id("users"),
		reason: v.string(),
		fingerprint: v.string(),
		createdAt: v.number(),
	}).index("by_recovery_key", ["recoveryKey"]),
	contentPromotion_mediaRecoveryAudit: defineTable({
		grantId: v.id("contentPromotion_mediaRecoveryGrants"),
		actorId: v.id("users"),
		event: v.union(v.literal("granted"), v.literal("reconciled")),
		createdAt: v.number(),
	}).index("by_grant", ["grantId"]),
	contentPromotion_mediaUploads: defineTable({
		transferKey: v.string(),
		operatorId: v.id("users"),
		sourceIdentityJson: v.string(),
		targetIdentityJson: v.string(),
		sha256: v.string(),
		fileSize: v.number(),
		mimeType: v.string(),
		status: v.union(v.literal("issued"), v.literal("verified")),
		storageId: v.optional(v.id("_storage")),
		createdAt: v.number(),
		updatedAt: v.number(),
	}).index("by_transfer_key", ["transferKey"]),
	contentPromotion_receipts: defineTable({
		digest: v.string(),
		manifestJson: v.string(),
		planJson: v.string(),
		operatorId: v.id("users"),
		targetInstanceKey: v.string(),
		status: v.union(
			v.literal("ready"),
			v.literal("applied"),
			v.literal("rolled-back"),
			v.literal("retired"),
		),
		createdAt: v.number(),
		expiresAt: v.number(),
		appliedAt: v.optional(v.number()),
		resultJson: v.optional(v.string()),
	}).index("by_target_digest", ["targetInstanceKey", "digest"]),
	contentPromotion_mappings: defineTable({
		sourceInstanceKey: v.string(),
		sourceKey: v.string(),
		kind: v.string(),
		targetId: v.string(),
		updatedAt: v.number(),
	}).index("by_source_key", ["sourceInstanceKey", "sourceKey"]),
	contentPromotion_backups: defineTable({
		receiptId: v.id("contentPromotion_receipts"),
		key: v.string(),
		kind: v.string(),
		targetId: v.string(),
		beforeJson: v.union(v.string(), v.null()),
		afterRevision: v.string(),
	}).index("by_receipt", ["receiptId"]),
};
