import {test,expect,mock} from "bun:test";
import {act,createElement} from "react";
import * as convexReact from "convex/react";
import {getFunctionName} from "convex/server";
import {createRequire} from "node:module";
const require=createRequire(import.meta.url),{JSDOM}=createRequire(require.resolve("isomorphic-dompurify"))("jsdom");
let auth={isLoaded:true,isSignedIn:true,userId:"customer-a",sessionId:"session-a"};
mock.module("convex/react",()=>({...convexReact,useConvexAuth:()=>({isLoading:false,isAuthenticated:true})}));
mock.module("@/lib/auth/clerk",()=>({useAuth:()=>auth}));
mock.module("@/lib/site-runtime",()=>({getSiteRuntime:()=>({instanceKey:"test-instance"})}));
mock.module("@/contexts/SettingsContext",()=>({useSettings:()=>({plugins:{commerceEnabled:true,commerceWishlistsEnabled:true}})}));
mock.module("../../shell/DashboardShellContext",()=>({useDashboardShell:()=>({to:path=>path})}));
mock.module("@tanstack/react-router",()=>({Link:({to,children,...props})=>createElement("a",{href:to,...props},children)}));
mock.module("../../grid/WidgetCard",()=>({WidgetEmpty:({title,description,action})=><div>{title}{description}{action}</div>,WidgetSkeleton:()=> <div>Loading saved products</div>}));
const {default:widget}=await import("./manifest");
async function inDom(run){const dom=new JSDOM('<div id="root"></div>',{url:"https://example.test/dashboard",pretendToBeVisual:true});const keys=["window","document","HTMLElement","IS_REACT_ACT_ENVIRONMENT"],before=Object.fromEntries(keys.map(key=>[key,globalThis[key]]));Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});const {createRoot}=await import("react-dom/client"),root=createRoot(document.getElementById("root"));try{await run(root);}finally{await act(async()=>root.unmount());dom.window.close();Object.assign(globalThis,before);}}
function fixture(initial){let data=initial,connection={isWebSocketConnected:true},onConnection=()=>{};const queries=[],writes=[];const client={connectionState:()=>connection,subscribeToConnectionState(fn){onConnection=fn;return()=>{};},watchQuery(fn,args){const q={name:getFunctionName(fn),args,stopped:false,notify:()=>{}};queries.push(q);return {localQueryResult:()=>data,onUpdate(fn){q.notify=fn;return()=>{q.stopped=true;};}};},mutation(fn,args){writes.push({name:getFunctionName(fn),args});return Promise.resolve(null);}};return{queries,writes,view:()=> <convexReact.ConvexProvider client={client}><widget.Widget size="md"/></convexReact.ConvexProvider>,set(next){data=next;for(const q of queries)if(!q.stopped)q.notify();},offline(){connection={isWebSocketConnected:false};onConnection();}};}
const snapshot=(state="ready")=>({page:[{_id:"list-a",name:"First saved list",isPublic:false,itemCount:1},{_id:"list-b",name:"Second saved list",isPublic:false,itemCount:1}],isDone:false,continueCursor:"next",expiresAt:Date.now()+15000,summary:state==="ready"?{state,totalLists:31,totalItems:31}:{state,totalLists:null,totalItems:null}});
test("widget shows the whole-owner total while querying only its small preview page",async()=>{const f=fixture(snapshot());await inDom(async root=>{await act(async()=>root.render(f.view()));expect(document.querySelector('[role="status"]').textContent).toBe("31 saved items");expect(document.querySelectorAll('li')).toHaveLength(2);expect(f.queries[0].args.paginationOpts).toEqual({numItems:4,cursor:null});expect(f.writes).toHaveLength(0);});});
test("preparing totals request owner repair once and never display a partial count",async()=>{const f=fixture(snapshot("preparing"));await inDom(async root=>{await act(async()=>root.render(f.view()));expect(document.querySelector('[role="status"]').textContent).toBe("Counting saved products…");expect(f.writes).toEqual([{name:"commerceWishlists/ownerMaintenance:ensure",args:{instanceKey:"test-instance"}}]);await act(async()=>f.set(snapshot()));expect(document.querySelector('[role="status"]').textContent).toBe("31 saved items");expect(f.writes).toHaveLength(1);});});
test("offline and account remounts remove retained list content",async()=>{const f=fixture(snapshot());await inDom(async root=>{await act(async()=>root.render(f.view()));await act(async()=>f.offline());expect(document.body.textContent).toContain("Reconnecting");expect(document.body.textContent).not.toContain("First saved list");});const second=fixture(snapshot());await inDom(async root=>{await act(async()=>root.render(second.view()));await act(async()=>{second.set(undefined);auth={...auth,userId:"customer-b",sessionId:"session-b"};root.render(second.view());});expect(document.body.textContent).not.toContain("First saved list");expect(document.body.textContent).toContain("Loading saved products");});auth={...auth,userId:"customer-a",sessionId:"session-a"};});
