/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard/security'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardPostsRouteImport } from './routes/dashboard/posts'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardCommentsRouteImport } from './routes/dashboard/comments'
import { Route as ApiRobotsRouteImport } from './routes/api/robots'
import { Route as MarketingSearchRouteImport } from './routes/_marketing/search'
import { Route as MarketingArchiveRouteImport } from './routes/_marketing/archive'
import { Route as ApiFeedIndexRouteImport } from './routes/api/feed/index'
import { Route as MarketingBlogIndexRouteImport } from './routes/_marketing/blog/index'
import { Route as ApiSitemapXmlRouteImport } from './routes/api/sitemap.xml'
import { Route as ApiSitemapStyleXslRouteImport } from './routes/api/sitemap-style.xsl'
import { Route as ApiSitemapTypePageXmlRouteImport } from './routes/api/sitemap-$type-$page.xml'
import { Route as ApiFeedRss2RouteImport } from './routes/api/feed/rss2'
import { Route as ApiFeedAtomRouteImport } from './routes/api/feed/atom'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as MarketingTagSlugRouteImport } from './routes/_marketing/tag/$slug'
import { Route as MarketingPageSplatRouteImport } from './routes/_marketing/page/$'
import { Route as MarketingCategorySlugRouteImport } from './routes/_marketing/category/$slug'
import { Route as MarketingBlogSlugRouteImport } from './routes/_marketing/blog/$slug'
import { Route as MarketingAuthorSlugRouteImport } from './routes/_marketing/author/$slug'
import { Route as MarketingArchivesIdRouteImport } from './routes/_marketing/archives/$id'
import { Route as ApiCommentsFeedIndexRouteImport } from './routes/api/comments/feed/index'
import { Route as ApiCommentsFeedAtomRouteImport } from './routes/api/comments/feed/atom'
import { Route as ApiTagSlugFeedIndexRouteImport } from './routes/api/tag/$slug/feed/index'
import { Route as ApiCategorySlugFeedIndexRouteImport } from './routes/api/category/$slug/feed/index'
import { Route as ApiBlogSlugFeedIndexRouteImport } from './routes/api/blog/$slug/feed/index'
import { Route as ApiAuthorSlugFeedIndexRouteImport } from './routes/api/author/$slug/feed/index'
import { Route as ApiTagSlugFeedAtomRouteImport } from './routes/api/tag/$slug/feed/atom'
import { Route as ApiCategorySlugFeedAtomRouteImport } from './routes/api/category/$slug/feed/atom'
import { Route as ApiBlogSlugFeedAtomRouteImport } from './routes/api/blog/$slug/feed/atom'
import { Route as ApiAuthorSlugFeedAtomRouteImport } from './routes/api/author/$slug/feed/atom'
import { Route as MarketingBlogYearMonthSlugRouteImport } from './routes/_marketing/blog/$year/$month/$slug'
import { Route as MarketingBlogYearMonthDaySlugRouteImport } from './routes/_marketing/blog/$year/$month/$day/$slug'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostsRoute = DashboardPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommentsRoute = DashboardCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiRobotsRoute = ApiRobotsRouteImport.update({
  id: '/api/robots',
  path: '/api/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSearchRoute = MarketingSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingArchiveRoute = MarketingArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => MarketingRoute,
} as any)
const ApiFeedIndexRoute = ApiFeedIndexRouteImport.update({
  id: '/api/feed/',
  path: '/api/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingBlogIndexRoute = MarketingBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => MarketingRoute,
} as any)
const ApiSitemapXmlRoute = ApiSitemapXmlRouteImport.update({
  id: '/api/sitemap/xml',
  path: '/api/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapStyleXslRoute = ApiSitemapStyleXslRouteImport.update({
  id: '/api/sitemap-style/xsl',
  path: '/api/sitemap-style/xsl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapTypePageXmlRoute = ApiSitemapTypePageXmlRouteImport.update({
  id: '/api/sitemap-$type-$page/xml',
  path: '/api/sitemap-$type-$page/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRss2Route = ApiFeedRss2RouteImport.update({
  id: '/api/feed/rss2',
  path: '/api/feed/rss2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedAtomRoute = ApiFeedAtomRouteImport.update({
  id: '/api/feed/atom',
  path: '/api/feed/atom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingTagSlugRoute = MarketingTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPageSplatRoute = MarketingPageSplatRouteImport.update({
  id: '/page/$',
  path: '/page/$',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCategorySlugRoute = MarketingCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingBlogSlugRoute = MarketingBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAuthorSlugRoute = MarketingAuthorSlugRouteImport.update({
  id: '/author/$slug',
  path: '/author/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingArchivesIdRoute = MarketingArchivesIdRouteImport.update({
  id: '/archives/$id',
  path: '/archives/$id',
  getParentRoute: () => MarketingRoute,
} as any)
const ApiCommentsFeedIndexRoute = ApiCommentsFeedIndexRouteImport.update({
  id: '/api/comments/feed/',
  path: '/api/comments/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsFeedAtomRoute = ApiCommentsFeedAtomRouteImport.update({
  id: '/api/comments/feed/atom',
  path: '/api/comments/feed/atom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagSlugFeedIndexRoute = ApiTagSlugFeedIndexRouteImport.update({
  id: '/api/tag/$slug/feed/',
  path: '/api/tag/$slug/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategorySlugFeedIndexRoute =
  ApiCategorySlugFeedIndexRouteImport.update({
    id: '/api/category/$slug/feed/',
    path: '/api/category/$slug/feed/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBlogSlugFeedIndexRoute = ApiBlogSlugFeedIndexRouteImport.update({
  id: '/api/blog/$slug/feed/',
  path: '/api/blog/$slug/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthorSlugFeedIndexRoute = ApiAuthorSlugFeedIndexRouteImport.update({
  id: '/api/author/$slug/feed/',
  path: '/api/author/$slug/feed/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagSlugFeedAtomRoute = ApiTagSlugFeedAtomRouteImport.update({
  id: '/api/tag/$slug/feed/atom',
  path: '/api/tag/$slug/feed/atom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategorySlugFeedAtomRoute = ApiCategorySlugFeedAtomRouteImport.update({
  id: '/api/category/$slug/feed/atom',
  path: '/api/category/$slug/feed/atom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogSlugFeedAtomRoute = ApiBlogSlugFeedAtomRouteImport.update({
  id: '/api/blog/$slug/feed/atom',
  path: '/api/blog/$slug/feed/atom',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthorSlugFeedAtomRoute = ApiAuthorSlugFeedAtomRouteImport.update({
  id: '/api/author/$slug/feed/atom',
  path: '/api/author/$slug/feed/atom',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingBlogYearMonthSlugRoute =
  MarketingBlogYearMonthSlugRouteImport.update({
    id: '/blog/$year/$month/$slug',
    path: '/blog/$year/$month/$slug',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingBlogYearMonthDaySlugRoute =
  MarketingBlogYearMonthDaySlugRouteImport.update({
    id: '/blog/$year/$month/$day/$slug',
    path: '/blog/$year/$month/$day/$slug',
    getParentRoute: () => MarketingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/archive': typeof MarketingArchiveRoute
  '/search': typeof MarketingSearchRoute
  '/api/robots': typeof ApiRobotsRoute
  '/dashboard/comments': typeof DashboardCommentsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/archives/$id': typeof MarketingArchivesIdRoute
  '/author/$slug': typeof MarketingAuthorSlugRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/category/$slug': typeof MarketingCategorySlugRoute
  '/page/$': typeof MarketingPageSplatRoute
  '/tag/$slug': typeof MarketingTagSlugRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/feed/atom': typeof ApiFeedAtomRoute
  '/api/feed/rss2': typeof ApiFeedRss2Route
  '/api/sitemap-$type-$page/xml': typeof ApiSitemapTypePageXmlRoute
  '/api/sitemap-style/xsl': typeof ApiSitemapStyleXslRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
  '/blog/': typeof MarketingBlogIndexRoute
  '/api/feed/': typeof ApiFeedIndexRoute
  '/api/comments/feed/atom': typeof ApiCommentsFeedAtomRoute
  '/api/comments/feed/': typeof ApiCommentsFeedIndexRoute
  '/blog/$year/$month/$slug': typeof MarketingBlogYearMonthSlugRoute
  '/api/author/$slug/feed/atom': typeof ApiAuthorSlugFeedAtomRoute
  '/api/blog/$slug/feed/atom': typeof ApiBlogSlugFeedAtomRoute
  '/api/category/$slug/feed/atom': typeof ApiCategorySlugFeedAtomRoute
  '/api/tag/$slug/feed/atom': typeof ApiTagSlugFeedAtomRoute
  '/api/author/$slug/feed/': typeof ApiAuthorSlugFeedIndexRoute
  '/api/blog/$slug/feed/': typeof ApiBlogSlugFeedIndexRoute
  '/api/category/$slug/feed/': typeof ApiCategorySlugFeedIndexRoute
  '/api/tag/$slug/feed/': typeof ApiTagSlugFeedIndexRoute
  '/blog/$year/$month/$day/$slug': typeof MarketingBlogYearMonthDaySlugRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/archive': typeof MarketingArchiveRoute
  '/search': typeof MarketingSearchRoute
  '/api/robots': typeof ApiRobotsRoute
  '/dashboard/comments': typeof DashboardCommentsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/': typeof MarketingIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/archives/$id': typeof MarketingArchivesIdRoute
  '/author/$slug': typeof MarketingAuthorSlugRoute
  '/blog/$slug': typeof MarketingBlogSlugRoute
  '/category/$slug': typeof MarketingCategorySlugRoute
  '/page/$': typeof MarketingPageSplatRoute
  '/tag/$slug': typeof MarketingTagSlugRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/feed/atom': typeof ApiFeedAtomRoute
  '/api/feed/rss2': typeof ApiFeedRss2Route
  '/api/sitemap-$type-$page/xml': typeof ApiSitemapTypePageXmlRoute
  '/api/sitemap-style/xsl': typeof ApiSitemapStyleXslRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
  '/blog': typeof MarketingBlogIndexRoute
  '/api/feed': typeof ApiFeedIndexRoute
  '/api/comments/feed/atom': typeof ApiCommentsFeedAtomRoute
  '/api/comments/feed': typeof ApiCommentsFeedIndexRoute
  '/blog/$year/$month/$slug': typeof MarketingBlogYearMonthSlugRoute
  '/api/author/$slug/feed/atom': typeof ApiAuthorSlugFeedAtomRoute
  '/api/blog/$slug/feed/atom': typeof ApiBlogSlugFeedAtomRoute
  '/api/category/$slug/feed/atom': typeof ApiCategorySlugFeedAtomRoute
  '/api/tag/$slug/feed/atom': typeof ApiTagSlugFeedAtomRoute
  '/api/author/$slug/feed': typeof ApiAuthorSlugFeedIndexRoute
  '/api/blog/$slug/feed': typeof ApiBlogSlugFeedIndexRoute
  '/api/category/$slug/feed': typeof ApiCategorySlugFeedIndexRoute
  '/api/tag/$slug/feed': typeof ApiTagSlugFeedIndexRoute
  '/blog/$year/$month/$day/$slug': typeof MarketingBlogYearMonthDaySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_marketing/archive': typeof MarketingArchiveRoute
  '/_marketing/search': typeof MarketingSearchRoute
  '/api/robots': typeof ApiRobotsRoute
  '/dashboard/comments': typeof DashboardCommentsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/posts': typeof DashboardPostsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_marketing/archives/$id': typeof MarketingArchivesIdRoute
  '/_marketing/author/$slug': typeof MarketingAuthorSlugRoute
  '/_marketing/blog/$slug': typeof MarketingBlogSlugRoute
  '/_marketing/category/$slug': typeof MarketingCategorySlugRoute
  '/_marketing/page/$': typeof MarketingPageSplatRoute
  '/_marketing/tag/$slug': typeof MarketingTagSlugRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/feed/atom': typeof ApiFeedAtomRoute
  '/api/feed/rss2': typeof ApiFeedRss2Route
  '/api/sitemap-$type-$page/xml': typeof ApiSitemapTypePageXmlRoute
  '/api/sitemap-style/xsl': typeof ApiSitemapStyleXslRoute
  '/api/sitemap/xml': typeof ApiSitemapXmlRoute
  '/_marketing/blog/': typeof MarketingBlogIndexRoute
  '/api/feed/': typeof ApiFeedIndexRoute
  '/api/comments/feed/atom': typeof ApiCommentsFeedAtomRoute
  '/api/comments/feed/': typeof ApiCommentsFeedIndexRoute
  '/_marketing/blog/$year/$month/$slug': typeof MarketingBlogYearMonthSlugRoute
  '/api/author/$slug/feed/atom': typeof ApiAuthorSlugFeedAtomRoute
  '/api/blog/$slug/feed/atom': typeof ApiBlogSlugFeedAtomRoute
  '/api/category/$slug/feed/atom': typeof ApiCategorySlugFeedAtomRoute
  '/api/tag/$slug/feed/atom': typeof ApiTagSlugFeedAtomRoute
  '/api/author/$slug/feed/': typeof ApiAuthorSlugFeedIndexRoute
  '/api/blog/$slug/feed/': typeof ApiBlogSlugFeedIndexRoute
  '/api/category/$slug/feed/': typeof ApiCategorySlugFeedIndexRoute
  '/api/tag/$slug/feed/': typeof ApiTagSlugFeedIndexRoute
  '/_marketing/blog/$year/$month/$day/$slug': typeof MarketingBlogYearMonthDaySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/archive'
    | '/search'
    | '/api/robots'
    | '/dashboard/comments'
    | '/dashboard/notifications'
    | '/dashboard/posts'
    | '/dashboard/profile'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/archives/$id'
    | '/author/$slug'
    | '/blog/$slug'
    | '/category/$slug'
    | '/page/$'
    | '/tag/$slug'
    | '/api/auth/callback'
    | '/api/feed/atom'
    | '/api/feed/rss2'
    | '/api/sitemap-$type-$page/xml'
    | '/api/sitemap-style/xsl'
    | '/api/sitemap/xml'
    | '/blog/'
    | '/api/feed/'
    | '/api/comments/feed/atom'
    | '/api/comments/feed/'
    | '/blog/$year/$month/$slug'
    | '/api/author/$slug/feed/atom'
    | '/api/blog/$slug/feed/atom'
    | '/api/category/$slug/feed/atom'
    | '/api/tag/$slug/feed/atom'
    | '/api/author/$slug/feed/'
    | '/api/blog/$slug/feed/'
    | '/api/category/$slug/feed/'
    | '/api/tag/$slug/feed/'
    | '/blog/$year/$month/$day/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/archive'
    | '/search'
    | '/api/robots'
    | '/dashboard/comments'
    | '/dashboard/notifications'
    | '/dashboard/posts'
    | '/dashboard/profile'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/'
    | '/dashboard'
    | '/archives/$id'
    | '/author/$slug'
    | '/blog/$slug'
    | '/category/$slug'
    | '/page/$'
    | '/tag/$slug'
    | '/api/auth/callback'
    | '/api/feed/atom'
    | '/api/feed/rss2'
    | '/api/sitemap-$type-$page/xml'
    | '/api/sitemap-style/xsl'
    | '/api/sitemap/xml'
    | '/blog'
    | '/api/feed'
    | '/api/comments/feed/atom'
    | '/api/comments/feed'
    | '/blog/$year/$month/$slug'
    | '/api/author/$slug/feed/atom'
    | '/api/blog/$slug/feed/atom'
    | '/api/category/$slug/feed/atom'
    | '/api/tag/$slug/feed/atom'
    | '/api/author/$slug/feed'
    | '/api/blog/$slug/feed'
    | '/api/category/$slug/feed'
    | '/api/tag/$slug/feed'
    | '/blog/$year/$month/$day/$slug'
  id:
    | '__root__'
    | '/_marketing'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_marketing/archive'
    | '/_marketing/search'
    | '/api/robots'
    | '/dashboard/comments'
    | '/dashboard/notifications'
    | '/dashboard/posts'
    | '/dashboard/profile'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/_marketing/'
    | '/dashboard/'
    | '/_marketing/archives/$id'
    | '/_marketing/author/$slug'
    | '/_marketing/blog/$slug'
    | '/_marketing/category/$slug'
    | '/_marketing/page/$'
    | '/_marketing/tag/$slug'
    | '/api/auth/callback'
    | '/api/feed/atom'
    | '/api/feed/rss2'
    | '/api/sitemap-$type-$page/xml'
    | '/api/sitemap-style/xsl'
    | '/api/sitemap/xml'
    | '/_marketing/blog/'
    | '/api/feed/'
    | '/api/comments/feed/atom'
    | '/api/comments/feed/'
    | '/_marketing/blog/$year/$month/$slug'
    | '/api/author/$slug/feed/atom'
    | '/api/blog/$slug/feed/atom'
    | '/api/category/$slug/feed/atom'
    | '/api/tag/$slug/feed/atom'
    | '/api/author/$slug/feed/'
    | '/api/blog/$slug/feed/'
    | '/api/category/$slug/feed/'
    | '/api/tag/$slug/feed/'
    | '/_marketing/blog/$year/$month/$day/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiRobotsRoute: typeof ApiRobotsRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiFeedAtomRoute: typeof ApiFeedAtomRoute
  ApiFeedRss2Route: typeof ApiFeedRss2Route
  ApiSitemapTypePageXmlRoute: typeof ApiSitemapTypePageXmlRoute
  ApiSitemapStyleXslRoute: typeof ApiSitemapStyleXslRoute
  ApiSitemapXmlRoute: typeof ApiSitemapXmlRoute
  ApiFeedIndexRoute: typeof ApiFeedIndexRoute
  ApiCommentsFeedAtomRoute: typeof ApiCommentsFeedAtomRoute
  ApiCommentsFeedIndexRoute: typeof ApiCommentsFeedIndexRoute
  ApiAuthorSlugFeedAtomRoute: typeof ApiAuthorSlugFeedAtomRoute
  ApiBlogSlugFeedAtomRoute: typeof ApiBlogSlugFeedAtomRoute
  ApiCategorySlugFeedAtomRoute: typeof ApiCategorySlugFeedAtomRoute
  ApiTagSlugFeedAtomRoute: typeof ApiTagSlugFeedAtomRoute
  ApiAuthorSlugFeedIndexRoute: typeof ApiAuthorSlugFeedIndexRoute
  ApiBlogSlugFeedIndexRoute: typeof ApiBlogSlugFeedIndexRoute
  ApiCategorySlugFeedIndexRoute: typeof ApiCategorySlugFeedIndexRoute
  ApiTagSlugFeedIndexRoute: typeof ApiTagSlugFeedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/posts': {
      id: '/dashboard/posts'
      path: '/posts'
      fullPath: '/dashboard/posts'
      preLoaderRoute: typeof DashboardPostsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/comments': {
      id: '/dashboard/comments'
      path: '/comments'
      fullPath: '/dashboard/comments'
      preLoaderRoute: typeof DashboardCommentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/robots': {
      id: '/api/robots'
      path: '/api/robots'
      fullPath: '/api/robots'
      preLoaderRoute: typeof ApiRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/search': {
      id: '/_marketing/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MarketingSearchRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/archive': {
      id: '/_marketing/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof MarketingArchiveRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/api/feed/': {
      id: '/api/feed/'
      path: '/api/feed'
      fullPath: '/api/feed/'
      preLoaderRoute: typeof ApiFeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/blog/': {
      id: '/_marketing/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof MarketingBlogIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/api/sitemap/xml': {
      id: '/api/sitemap/xml'
      path: '/api/sitemap/xml'
      fullPath: '/api/sitemap/xml'
      preLoaderRoute: typeof ApiSitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap-style/xsl': {
      id: '/api/sitemap-style/xsl'
      path: '/api/sitemap-style/xsl'
      fullPath: '/api/sitemap-style/xsl'
      preLoaderRoute: typeof ApiSitemapStyleXslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap-$type-$page/xml': {
      id: '/api/sitemap-$type-$page/xml'
      path: '/api/sitemap-$type-$page/xml'
      fullPath: '/api/sitemap-$type-$page/xml'
      preLoaderRoute: typeof ApiSitemapTypePageXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/rss2': {
      id: '/api/feed/rss2'
      path: '/api/feed/rss2'
      fullPath: '/api/feed/rss2'
      preLoaderRoute: typeof ApiFeedRss2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed/atom': {
      id: '/api/feed/atom'
      path: '/api/feed/atom'
      fullPath: '/api/feed/atom'
      preLoaderRoute: typeof ApiFeedAtomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/tag/$slug': {
      id: '/_marketing/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof MarketingTagSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/page/$': {
      id: '/_marketing/page/$'
      path: '/page/$'
      fullPath: '/page/$'
      preLoaderRoute: typeof MarketingPageSplatRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/category/$slug': {
      id: '/_marketing/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof MarketingCategorySlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog/$slug': {
      id: '/_marketing/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof MarketingBlogSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/author/$slug': {
      id: '/_marketing/author/$slug'
      path: '/author/$slug'
      fullPath: '/author/$slug'
      preLoaderRoute: typeof MarketingAuthorSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/archives/$id': {
      id: '/_marketing/archives/$id'
      path: '/archives/$id'
      fullPath: '/archives/$id'
      preLoaderRoute: typeof MarketingArchivesIdRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/api/comments/feed/': {
      id: '/api/comments/feed/'
      path: '/api/comments/feed'
      fullPath: '/api/comments/feed/'
      preLoaderRoute: typeof ApiCommentsFeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments/feed/atom': {
      id: '/api/comments/feed/atom'
      path: '/api/comments/feed/atom'
      fullPath: '/api/comments/feed/atom'
      preLoaderRoute: typeof ApiCommentsFeedAtomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tag/$slug/feed/': {
      id: '/api/tag/$slug/feed/'
      path: '/api/tag/$slug/feed'
      fullPath: '/api/tag/$slug/feed/'
      preLoaderRoute: typeof ApiTagSlugFeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/category/$slug/feed/': {
      id: '/api/category/$slug/feed/'
      path: '/api/category/$slug/feed'
      fullPath: '/api/category/$slug/feed/'
      preLoaderRoute: typeof ApiCategorySlugFeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/$slug/feed/': {
      id: '/api/blog/$slug/feed/'
      path: '/api/blog/$slug/feed'
      fullPath: '/api/blog/$slug/feed/'
      preLoaderRoute: typeof ApiBlogSlugFeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/author/$slug/feed/': {
      id: '/api/author/$slug/feed/'
      path: '/api/author/$slug/feed'
      fullPath: '/api/author/$slug/feed/'
      preLoaderRoute: typeof ApiAuthorSlugFeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tag/$slug/feed/atom': {
      id: '/api/tag/$slug/feed/atom'
      path: '/api/tag/$slug/feed/atom'
      fullPath: '/api/tag/$slug/feed/atom'
      preLoaderRoute: typeof ApiTagSlugFeedAtomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/category/$slug/feed/atom': {
      id: '/api/category/$slug/feed/atom'
      path: '/api/category/$slug/feed/atom'
      fullPath: '/api/category/$slug/feed/atom'
      preLoaderRoute: typeof ApiCategorySlugFeedAtomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/$slug/feed/atom': {
      id: '/api/blog/$slug/feed/atom'
      path: '/api/blog/$slug/feed/atom'
      fullPath: '/api/blog/$slug/feed/atom'
      preLoaderRoute: typeof ApiBlogSlugFeedAtomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/author/$slug/feed/atom': {
      id: '/api/author/$slug/feed/atom'
      path: '/api/author/$slug/feed/atom'
      fullPath: '/api/author/$slug/feed/atom'
      preLoaderRoute: typeof ApiAuthorSlugFeedAtomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/blog/$year/$month/$slug': {
      id: '/_marketing/blog/$year/$month/$slug'
      path: '/blog/$year/$month/$slug'
      fullPath: '/blog/$year/$month/$slug'
      preLoaderRoute: typeof MarketingBlogYearMonthSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/blog/$year/$month/$day/$slug': {
      id: '/_marketing/blog/$year/$month/$day/$slug'
      path: '/blog/$year/$month/$day/$slug'
      fullPath: '/blog/$year/$month/$day/$slug'
      preLoaderRoute: typeof MarketingBlogYearMonthDaySlugRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingArchiveRoute: typeof MarketingArchiveRoute
  MarketingSearchRoute: typeof MarketingSearchRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingArchivesIdRoute: typeof MarketingArchivesIdRoute
  MarketingAuthorSlugRoute: typeof MarketingAuthorSlugRoute
  MarketingBlogSlugRoute: typeof MarketingBlogSlugRoute
  MarketingCategorySlugRoute: typeof MarketingCategorySlugRoute
  MarketingPageSplatRoute: typeof MarketingPageSplatRoute
  MarketingTagSlugRoute: typeof MarketingTagSlugRoute
  MarketingBlogIndexRoute: typeof MarketingBlogIndexRoute
  MarketingBlogYearMonthSlugRoute: typeof MarketingBlogYearMonthSlugRoute
  MarketingBlogYearMonthDaySlugRoute: typeof MarketingBlogYearMonthDaySlugRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingArchiveRoute: MarketingArchiveRoute,
  MarketingSearchRoute: MarketingSearchRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingArchivesIdRoute: MarketingArchivesIdRoute,
  MarketingAuthorSlugRoute: MarketingAuthorSlugRoute,
  MarketingBlogSlugRoute: MarketingBlogSlugRoute,
  MarketingCategorySlugRoute: MarketingCategorySlugRoute,
  MarketingPageSplatRoute: MarketingPageSplatRoute,
  MarketingTagSlugRoute: MarketingTagSlugRoute,
  MarketingBlogIndexRoute: MarketingBlogIndexRoute,
  MarketingBlogYearMonthSlugRoute: MarketingBlogYearMonthSlugRoute,
  MarketingBlogYearMonthDaySlugRoute: MarketingBlogYearMonthDaySlugRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCommentsRoute: typeof DashboardCommentsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPostsRoute: typeof DashboardPostsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCommentsRoute: DashboardCommentsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPostsRoute: DashboardPostsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiRobotsRoute: ApiRobotsRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiFeedAtomRoute: ApiFeedAtomRoute,
  ApiFeedRss2Route: ApiFeedRss2Route,
  ApiSitemapTypePageXmlRoute: ApiSitemapTypePageXmlRoute,
  ApiSitemapStyleXslRoute: ApiSitemapStyleXslRoute,
  ApiSitemapXmlRoute: ApiSitemapXmlRoute,
  ApiFeedIndexRoute: ApiFeedIndexRoute,
  ApiCommentsFeedAtomRoute: ApiCommentsFeedAtomRoute,
  ApiCommentsFeedIndexRoute: ApiCommentsFeedIndexRoute,
  ApiAuthorSlugFeedAtomRoute: ApiAuthorSlugFeedAtomRoute,
  ApiBlogSlugFeedAtomRoute: ApiBlogSlugFeedAtomRoute,
  ApiCategorySlugFeedAtomRoute: ApiCategorySlugFeedAtomRoute,
  ApiTagSlugFeedAtomRoute: ApiTagSlugFeedAtomRoute,
  ApiAuthorSlugFeedIndexRoute: ApiAuthorSlugFeedIndexRoute,
  ApiBlogSlugFeedIndexRoute: ApiBlogSlugFeedIndexRoute,
  ApiCategorySlugFeedIndexRoute: ApiCategorySlugFeedIndexRoute,
  ApiTagSlugFeedIndexRoute: ApiTagSlugFeedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
