/**
 * Lucide icon resolver for kebab-case names coming from the registry and from
 * admin-authored menu items ("shopping-bag" → ShoppingBag).
 *
 * A curated static map keeps the bundle small (lucide's dynamic import map
 * would emit a chunk per icon). Add to ICONS when a menu needs a name that is
 * not here; unknown names fall back to `Circle` so nothing ever renders blank.
 */

import {
  Activity,
  Archive,
  ArrowRight,
  Award,
  BadgeCheck,
  BadgeDollarSign,
  Banknote,
  Bell,
  BellRing,
  Bolt,
  BookMarked,
  BookOpen,
  Bookmark,
  Box,
  Boxes,
  Briefcase,
  Building,
  Calendar,
  Camera,
  Circle,
  CircleCheck,
  CircleHelp,
  CircleUser,
  ClipboardList,
  Clock,
  Coins,
  Compass,
  Contact,
  CreditCard,
  Crown,
  DollarSign,
  Download,
  ExternalLink,
  FileText,
  Flag,
  Folder,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Grid2x2,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  House,
  IdCard,
  Image,
  Inbox,
  Info,
  Key,
  KeyRound,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Layers,
  Library,
  LifeBuoy,
  Link,
  List,
  Lock,
  LockKeyhole,
  LogOut,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Newspaper,
  Package,
  PackageCheck,
  PackageOpen,
  Palette,
  Pencil,
  Percent,
  Phone,
  Pin,
  Play,
  Podcast,
  Puzzle,
  Receipt,
  RefreshCcw,
  Repeat,
  Rocket,
  RotateCcw,
  Rss,
  ScrollText,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  SquarePen,
  SquareUser,
  Star,
  Store,
  Tag,
  Target,
  Ticket,
  TrendingUp,
  Trophy,
  Truck,
  User,
  UserCog,
  UserRound,
  Users,
  Video,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  archive: Archive,
  "arrow-right": ArrowRight,
  award: Award,
  "badge-check": BadgeCheck,
  "badge-dollar-sign": BadgeDollarSign,
  banknote: Banknote,
  "bar-chart-3": TrendingUp,
  "bar-chart": TrendingUp,
  "chart-bar": TrendingUp,
  bell: Bell,
  "bell-ring": BellRing,
  bolt: Bolt,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  bookmark: Bookmark,
  box: Box,
  boxes: Boxes,
  briefcase: Briefcase,
  building: Building,
  calendar: Calendar,
  camera: Camera,
  circle: Circle,
  "circle-check": CircleCheck,
  "check-circle": CircleCheck,
  "circle-help": CircleHelp,
  "help-circle": CircleHelp,
  "circle-user": CircleUser,
  "user-circle": CircleUser,
  "clipboard-list": ClipboardList,
  clock: Clock,
  coins: Coins,
  compass: Compass,
  contact: Contact,
  "credit-card": CreditCard,
  crown: Crown,
  "dollar-sign": DollarSign,
  download: Download,
  "external-link": ExternalLink,
  "file-text": FileText,
  flag: Flag,
  folder: Folder,
  gem: Gem,
  gift: Gift,
  globe: Globe,
  "graduation-cap": GraduationCap,
  "grid-2x2": Grid2x2,
  handshake: Handshake,
  headphones: Headphones,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  house: House,
  home: House,
  "id-card": IdCard,
  image: Image,
  inbox: Inbox,
  info: Info,
  key: Key,
  "key-round": KeyRound,
  languages: Languages,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "layout-template": LayoutTemplate,
  layers: Layers,
  library: Library,
  "life-buoy": LifeBuoy,
  link: Link,
  list: List,
  lock: Lock,
  "lock-keyhole": LockKeyhole,
  "log-out": LogOut,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  medal: Medal,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  newspaper: Newspaper,
  package: Package,
  "package-check": PackageCheck,
  "package-open": PackageOpen,
  palette: Palette,
  pencil: Pencil,
  percent: Percent,
  phone: Phone,
  pin: Pin,
  play: Play,
  podcast: Podcast,
  puzzle: Puzzle,
  receipt: Receipt,
  "refresh-ccw": RefreshCcw,
  "refresh-cw": RefreshCcw,
  repeat: Repeat,
  rocket: Rocket,
  "rotate-ccw": RotateCcw,
  rss: Rss,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "sliders-horizontal": SlidersHorizontal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  "square-pen": SquarePen,
  "pen-square": SquarePen,
  "square-user": SquareUser,
  star: Star,
  store: Store,
  tag: Tag,
  target: Target,
  ticket: Ticket,
  "trending-up": TrendingUp,
  trophy: Trophy,
  truck: Truck,
  user: User,
  "user-cog": UserCog,
  "user-round": UserRound,
  users: Users,
  video: Video,
  wallet: Wallet,
  wrench: Wrench,
  zap: Zap,
};

export const FALLBACK_ICON: LucideIcon = Circle;

/** Normalizes "ShoppingBag", "shopping_bag", " shopping-bag " to "shopping-bag". */
export function normalizeIconName(name: string | null | undefined): string {
  if (!name) return "";
  return name
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();
}

export function resolveIcon(name: string | null | undefined): LucideIcon {
  return ICONS[normalizeIconName(name)] ?? FALLBACK_ICON;
}

export function hasIcon(name: string | null | undefined): boolean {
  return Boolean(ICONS[normalizeIconName(name)]);
}
