// Generated by generate-legacy-compatibility.ts; do not edit.
import * as legacyZod from 'zod';
let loadSchemas0Cache;
function loadSchemas0(){if(loadSchemas0Cache)return loadSchemas0Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var contactStackAttrsSchema = z.object({
  heading: z.string().max(140).default("Contact the site"),
  intro: z.string().max(800).default(""),
  phone: z.string().max(80).default(""),
  email: z.string().max(160).default(""),
  address: z.string().max(500).default(""),
  hours: z.string().max(500).default(""),
  mapEmbedUrl: z.string().max(1000).default(""),
  items: z.array(z.object({
    label: z.string().max(80).default(""),
    value: z.string().max(300).default(""),
    href: z.string().max(500).default("")
  })).max(8).default([])
});
var contactStackAttrsSchema2 = z2.object({
  heading: z2.string().max(140).default("Contact the site"),
  intro: z2.string().max(800).default(""),
  phone: z2.string().max(80).default(""),
  email: z2.string().max(160).default(""),
  address: z2.string().max(500).default(""),
  hours: z2.string().max(500).default(""),
  mapEmbedUrl: z2.string().max(1000).default(""),
  items: z2.array(z2.object({
    label: z2.string().max(80).default(""),
    value: z2.string().max(300).default(""),
    href: z2.string().max(500).default("")
  })).max(8).default([])
});
return loadSchemas0Cache={savedSchema:contactStackAttrsSchema,renderedSchema:contactStackAttrsSchema2};}
let loadSchemas1Cache;
function loadSchemas1(){if(loadSchemas1Cache)return loadSchemas1Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var customerShowcaseAttrsSchema = z.object({
  heading: z.string().max(140).default("Built with site product"),
  intro: z.string().max(800).default(""),
  items: z.array(z.object({
    quote: z.string().max(900).default(""),
    name: z.string().max(120).default(""),
    role: z.string().max(120).default(""),
    company: z.string().max(140).default(""),
    mediaId: z.string().default(""),
    mediaAlt: z.string().max(200).default(""),
    instrumentType: z.string().max(120).default(""),
    url: z.string().max(500).default("")
  })).max(24).default([])
});
var customerShowcaseAttrsSchema2 = z2.object({
  heading: z2.string().max(140).default("Built with site product"),
  intro: z2.string().max(800).default(""),
  items: z2.array(z2.object({
    quote: z2.string().max(900).default(""),
    name: z2.string().max(120).default(""),
    role: z2.string().max(120).default(""),
    company: z2.string().max(140).default(""),
    mediaId: z2.string().default(""),
    mediaAlt: z2.string().max(200).default(""),
    instrumentType: z2.string().max(120).default(""),
    url: z2.string().max(500).default("")
  })).max(24).default([])
});
return loadSchemas1Cache={savedSchema:customerShowcaseAttrsSchema,renderedSchema:customerShowcaseAttrsSchema2};}
let loadSchemas2Cache;
function loadSchemas2(){if(loadSchemas2Cache)return loadSchemas2Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var gradeImageSchema = z.object({
  mediaId: z.string().default(""),
  alt: z.string().max(200).default(""),
  caption: z.string().max(220).default("")
});
var gradeGalleryAttrsSchema = z.object({
  heading: z.string().max(140).default("Product grades"),
  intro: z.string().max(800).default(""),
  sections: z.array(z.object({
    grade: z.string().max(80).default("Grade"),
    description: z.string().max(1600).default(""),
    notes: z.string().max(800).default(""),
    images: z.array(gradeImageSchema).max(16).default([])
  })).max(12).default([])
});
var gradeImageSchema2 = z2.object({
  mediaId: z2.string().default(""),
  alt: z2.string().max(200).default(""),
  caption: z2.string().max(220).default("")
});
var gradeGalleryAttrsSchema2 = z2.object({
  heading: z2.string().max(140).default("Product grades"),
  intro: z2.string().max(800).default(""),
  sections: z2.array(z2.object({
    grade: z2.string().max(80).default("Grade"),
    description: z2.string().max(1600).default(""),
    notes: z2.string().max(800).default(""),
    images: z2.array(gradeImageSchema2).max(16).default([])
  })).max(12).default([])
});
return loadSchemas2Cache={savedSchema:gradeGalleryAttrsSchema,renderedSchema:gradeGalleryAttrsSchema2};}
let loadSchemas3Cache;
function loadSchemas3(){if(loadSchemas3Cache)return loadSchemas3Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var mediaMentionsAttrsSchema = z.object({
  heading: z.string().max(140).default("In the media"),
  intro: z.string().max(800).default(""),
  items: z.array(z.object({
    title: z.string().max(180).default(""),
    source: z.string().max(120).default(""),
    byline: z.string().max(160).default(""),
    summary: z.string().max(700).default(""),
    mediaId: z.string().default(""),
    mediaAlt: z.string().max(200).default(""),
    ctaLabel: z.string().max(60).default("Read more"),
    ctaUrl: z.string().max(500).default(""),
    kind: z.enum(["article", "pdf", "video", "audio"]).default("article")
  })).max(24).default([])
});
var mediaMentionsAttrsSchema2 = z2.object({
  heading: z2.string().max(140).default("In the media"),
  intro: z2.string().max(800).default(""),
  items: z2.array(z2.object({
    title: z2.string().max(180).default(""),
    source: z2.string().max(120).default(""),
    byline: z2.string().max(160).default(""),
    summary: z2.string().max(700).default(""),
    mediaId: z2.string().default(""),
    mediaAlt: z2.string().max(200).default(""),
    ctaLabel: z2.string().max(60).default("Read more"),
    ctaUrl: z2.string().max(500).default(""),
    kind: z2.enum(["article", "pdf", "video", "audio"]).default("article")
  })).max(24).default([])
});
return loadSchemas3Cache={savedSchema:mediaMentionsAttrsSchema,renderedSchema:mediaMentionsAttrsSchema2};}
let loadSchemas4Cache;
function loadSchemas4(){if(loadSchemas4Cache)return loadSchemas4Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var pageBannerAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  title: z.string().max(140).default("Page title"),
  subtitle: z.string().max(500).default(""),
  mediaId: z.string().default(""),
  mediaAlt: z.string().max(200).default(""),
  breadcrumbLabel: z.string().max(80).default(""),
  ctaLabel: z.string().max(60).default(""),
  ctaUrl: z.string().max(500).default("")
});
var pageBannerAttrsSchema2 = z2.object({
  eyebrow: z2.string().max(80).default(""),
  title: z2.string().max(140).default("Page title"),
  subtitle: z2.string().max(500).default(""),
  mediaId: z2.string().default(""),
  mediaAlt: z2.string().max(200).default(""),
  breadcrumbLabel: z2.string().max(80).default(""),
  ctaLabel: z2.string().max(60).default(""),
  ctaUrl: z2.string().max(500).default("")
});
return loadSchemas4Cache={savedSchema:pageBannerAttrsSchema,renderedSchema:pageBannerAttrsSchema2};}
let loadSchemas5Cache;
function loadSchemas5(){if(loadSchemas5Cache)return loadSchemas5Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var productCardSchema = z.object({
  title: z.string().max(160).default(""),
  summary: z.string().max(400).default(""),
  href: z.string().max(500).default(""),
  price: z.string().max(60).default(""),
  badge: z.string().max(60).default(""),
  mediaId: z.string().default(""),
  imageAlt: z.string().max(200).default("")
});
var productCollectionAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(140).default("Featured products"),
  intro: z.string().max(700).default(""),
  mode: z.enum(["manual", "category", "tag", "sale", "featured", "recent", "recentlyViewed"]).default("manual"),
  display: z.enum(["grid", "carousel", "tabs"]).default("grid"),
  productIds: z.array(z.string().max(120)).max(48).default([]),
  categorySlug: z.string().max(160).default(""),
  tagSlug: z.string().max(160).default(""),
  count: z.number().min(1).max(24).default(4),
  columns: z.number().min(2).max(4).default(4),
  showPrice: z.boolean().default(true),
  showRating: z.boolean().default(false),
  showSaleBadge: z.boolean().default(true),
  showAddToCart: z.boolean().default(false),
  ctaLabel: z.string().max(60).default(""),
  ctaUrl: z.string().max(500).default(""),
  products: z.array(productCardSchema).max(24).default([]),
  groups: z.array(z.object({
    label: z.string().max(80).default("Group"),
    productIds: z.array(z.string().max(120)).max(24).default([]),
    products: z.array(productCardSchema).max(24).default([])
  })).max(8).default([])
});
var productCardSchema2 = z2.object({
  title: z2.string().max(160).default(""),
  summary: z2.string().max(400).default(""),
  href: z2.string().max(500).default(""),
  price: z2.string().max(60).default(""),
  badge: z2.string().max(60).default(""),
  mediaId: z2.string().default(""),
  imageAlt: z2.string().max(200).default("")
});
var productCollectionAttrsSchema2 = z2.object({
  eyebrow: z2.string().max(80).default(""),
  heading: z2.string().max(140).default("Featured products"),
  intro: z2.string().max(700).default(""),
  mode: z2.enum(["manual", "category", "tag", "sale", "featured", "recent", "recentlyViewed"]).default("manual"),
  display: z2.enum(["grid", "carousel", "tabs"]).default("grid"),
  productIds: z2.array(z2.string().max(120)).max(48).default([]),
  categorySlug: z2.string().max(160).default(""),
  tagSlug: z2.string().max(160).default(""),
  count: z2.number().min(1).max(24).default(4),
  columns: z2.number().min(2).max(4).default(4),
  showPrice: z2.boolean().default(true),
  showRating: z2.boolean().default(false),
  showSaleBadge: z2.boolean().default(true),
  showAddToCart: z2.boolean().default(false),
  ctaLabel: z2.string().max(60).default(""),
  ctaUrl: z2.string().max(500).default(""),
  products: z2.array(productCardSchema2).max(24).default([]),
  groups: z2.array(z2.object({
    label: z2.string().max(80).default("Group"),
    productIds: z2.array(z2.string().max(120)).max(24).default([]),
    products: z2.array(productCardSchema2).max(24).default([])
  })).max(8).default([])
});
return loadSchemas5Cache={savedSchema:productCollectionAttrsSchema,renderedSchema:productCollectionAttrsSchema2};}
let loadSchemas6Cache;
function loadSchemas6(){if(loadSchemas6Cache)return loadSchemas6Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var promoBandAttrsSchema = z.object({
  eyebrow: z.string().max(80).default("Promotion"),
  heading: z.string().max(140).default("Promotion"),
  body: z.string().max(1000).default(""),
  mediaId: z.string().default(""),
  mediaAlt: z.string().max(200).default(""),
  primaryCtaLabel: z.string().max(60).default(""),
  primaryCtaUrl: z.string().max(500).default(""),
  secondaryCtaLabel: z.string().max(60).default(""),
  secondaryCtaUrl: z.string().max(500).default(""),
  details: z.array(z.object({
    label: z.string().max(80).default(""),
    value: z.string().max(180).default("")
  })).max(6).default([])
});
var promoBandAttrsSchema2 = z2.object({
  eyebrow: z2.string().max(80).default("Promotion"),
  heading: z2.string().max(140).default("Promotion"),
  body: z2.string().max(1000).default(""),
  mediaId: z2.string().default(""),
  mediaAlt: z2.string().max(200).default(""),
  primaryCtaLabel: z2.string().max(60).default(""),
  primaryCtaUrl: z2.string().max(500).default(""),
  secondaryCtaLabel: z2.string().max(60).default(""),
  secondaryCtaUrl: z2.string().max(500).default(""),
  details: z2.array(z2.object({
    label: z2.string().max(80).default(""),
    value: z2.string().max(180).default("")
  })).max(6).default([])
});
return loadSchemas6Cache={savedSchema:promoBandAttrsSchema,renderedSchema:promoBandAttrsSchema2};}
let loadSchemas7Cache;
function loadSchemas7(){if(loadSchemas7Cache)return loadSchemas7Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var socialShareAttrsSchema = z.object({
  heading: z.string().max(120).default("Share this page"),
  body: z.string().max(500).default(""),
  networks: z.array(z.enum(["facebook", "x", "pinterest", "linkedin", "email", "copy"])).max(8).default([
    "facebook",
    "x",
    "pinterest",
    "email"
  ]),
  shareUrlMode: z.enum(["currentPage", "custom"]).default("currentPage"),
  customUrl: z.string().max(500).default("")
});
var socialShareAttrsSchema2 = z2.object({
  heading: z2.string().max(120).default("Share this page"),
  body: z2.string().max(500).default(""),
  networks: z2.array(z2.enum(["facebook", "x", "pinterest", "linkedin", "email", "copy"])).max(8).default([
    "facebook",
    "x",
    "pinterest",
    "email"
  ]),
  shareUrlMode: z2.enum(["currentPage", "custom"]).default("currentPage"),
  customUrl: z2.string().max(500).default("")
});
return loadSchemas7Cache={savedSchema:socialShareAttrsSchema,renderedSchema:socialShareAttrsSchema2};}
let loadSchemas8Cache;
function loadSchemas8(){if(loadSchemas8Cache)return loadSchemas8Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var storyTimelineAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(140).default(""),
  intro: z.string().max(800).default(""),
  items: z.array(z.object({
    label: z.string().max(80).default(""),
    title: z.string().max(160).default(""),
    body: z.string().max(1600).default(""),
    mediaId: z.string().default(""),
    mediaAlt: z.string().max(200).default(""),
    side: z.enum(["auto", "left", "right"]).default("auto"),
    linkLabel: z.string().max(60).default(""),
    linkUrl: z.string().max(500).default("")
  })).max(40).default([])
});
var storyTimelineAttrsSchema2 = z2.object({
  eyebrow: z2.string().max(80).default(""),
  heading: z2.string().max(140).default(""),
  intro: z2.string().max(800).default(""),
  items: z2.array(z2.object({
    label: z2.string().max(80).default(""),
    title: z2.string().max(160).default(""),
    body: z2.string().max(1600).default(""),
    mediaId: z2.string().default(""),
    mediaAlt: z2.string().max(200).default(""),
    side: z2.enum(["auto", "left", "right"]).default("auto"),
    linkLabel: z2.string().max(60).default(""),
    linkUrl: z2.string().max(500).default("")
  })).max(40).default([])
});
return loadSchemas8Cache={savedSchema:storyTimelineAttrsSchema,renderedSchema:storyTimelineAttrsSchema2};}
let loadSchemas9Cache;
function loadSchemas9(){if(loadSchemas9Cache)return loadSchemas9Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var tabbedContentAttrsSchema = z.object({
  heading: z.string().max(140).default(""),
  intro: z.string().max(700).default(""),
  orientation: z.enum(["top", "left"]).default("top"),
  tabs: z.array(z.object({
    label: z.string().max(60).default("Tab"),
    title: z.string().max(140).default(""),
    body: z.string().max(3000).default(""),
    mediaId: z.string().default(""),
    mediaAlt: z.string().max(200).default(""),
    ctaLabel: z.string().max(60).default(""),
    ctaUrl: z.string().max(500).default("")
  })).max(12).default([
    {
      label: "Overview",
      title: "Overview",
      body: "",
      mediaId: "",
      mediaAlt: "",
      ctaLabel: "",
      ctaUrl: ""
    },
    {
      label: "Details",
      title: "Details",
      body: "",
      mediaId: "",
      mediaAlt: "",
      ctaLabel: "",
      ctaUrl: ""
    }
  ])
});
var tabbedContentAttrsSchema2 = z2.object({
  heading: z2.string().max(140).default(""),
  intro: z2.string().max(700).default(""),
  orientation: z2.enum(["top", "left"]).default("top"),
  tabs: z2.array(z2.object({
    label: z2.string().max(60).default("Tab"),
    title: z2.string().max(140).default(""),
    body: z2.string().max(3000).default(""),
    mediaId: z2.string().default(""),
    mediaAlt: z2.string().max(200).default(""),
    ctaLabel: z2.string().max(60).default(""),
    ctaUrl: z2.string().max(500).default("")
  })).max(12).default([
    {
      label: "Overview",
      title: "Overview",
      body: "",
      mediaId: "",
      mediaAlt: "",
      ctaLabel: "",
      ctaUrl: ""
    },
    {
      label: "Details",
      title: "Details",
      body: "",
      mediaId: "",
      mediaAlt: "",
      ctaLabel: "",
      ctaUrl: ""
    }
  ])
});
return loadSchemas9Cache={savedSchema:tabbedContentAttrsSchema,renderedSchema:tabbedContentAttrsSchema2};}
let loadSchemas10Cache;
function loadSchemas10(){if(loadSchemas10Cache)return loadSchemas10Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var assistantBandAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(140).default("Not sure what fits? Ask."),
  body: z.string().max(600).default(""),
  prompts: z.array(z.string().max(160)).max(8).default([]),
  ctaLabel: z.string().max(60).default("Browse the shop"),
  ctaUrl: z.string().max(500).default("/products")
});
var assistantBandAttrsSchema2 = z2.object({
  eyebrow: z2.string().max(80).default(""),
  heading: z2.string().max(140).default("Not sure what fits? Ask."),
  body: z2.string().max(600).default(""),
  prompts: z2.array(z2.string().max(160)).max(8).default([]),
  ctaLabel: z2.string().max(60).default("Browse the shop"),
  ctaUrl: z2.string().max(500).default("/products")
});
return loadSchemas10Cache={savedSchema:assistantBandAttrsSchema,renderedSchema:assistantBandAttrsSchema2};}
let loadSchemas11Cache;
function loadSchemas11(){if(loadSchemas11Cache)return loadSchemas11Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var categoryTilesAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(140).default("Shop by category"),
  intro: z.string().max(700).default(""),
  categorySlugs: z.array(z.string().max(160)).max(24).default([]),
  limit: z.number().min(1).max(24).default(6),
  columns: z.number().min(2).max(4).default(3),
  showCounts: z.boolean().default(true),
  showDescriptions: z.boolean().default(false),
  ctaLabel: z.string().max(60).default(""),
  ctaUrl: z.string().max(500).default("")
});
var categoryTilesAttrsSchema2 = z2.object({
  eyebrow: z2.string().max(80).default(""),
  heading: z2.string().max(140).default("Shop by category"),
  intro: z2.string().max(700).default(""),
  categorySlugs: z2.array(z2.string().max(160)).max(24).default([]),
  limit: z2.number().min(1).max(24).default(6),
  columns: z2.number().min(2).max(4).default(3),
  showCounts: z2.boolean().default(true),
  showDescriptions: z2.boolean().default(false),
  ctaLabel: z2.string().max(60).default(""),
  ctaUrl: z2.string().max(500).default("")
});
return loadSchemas11Cache={savedSchema:categoryTilesAttrsSchema,renderedSchema:categoryTilesAttrsSchema2};}
let loadSchemas12Cache;
function loadSchemas12(){if(loadSchemas12Cache)return loadSchemas12Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var productShowcaseAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(140).default("Featured products"),
  intro: z.string().max(700).default(""),
  source: z.enum(["newest", "category", "sale", "slugs"]).default("newest"),
  categorySlug: z.string().max(160).default(""),
  productSlugs: z.array(z.string().max(160)).max(24).default([]),
  count: z.number().min(1).max(24).default(4),
  columns: z.number().min(2).max(4).default(4),
  showAddToCart: z.boolean().default(true),
  ctaLabel: z.string().max(60).default(""),
  ctaUrl: z.string().max(500).default("")
});
var productShowcaseAttrsSchema2 = z2.object({
  eyebrow: z2.string().max(80).default(""),
  heading: z2.string().max(140).default("Featured products"),
  intro: z2.string().max(700).default(""),
  source: z2.enum(["newest", "category", "sale", "slugs"]).default("newest"),
  categorySlug: z2.string().max(160).default(""),
  productSlugs: z2.array(z2.string().max(160)).max(24).default([]),
  count: z2.number().min(1).max(24).default(4),
  columns: z2.number().min(2).max(4).default(4),
  showAddToCart: z2.boolean().default(true),
  ctaLabel: z2.string().max(60).default(""),
  ctaUrl: z2.string().max(500).default("")
});
return loadSchemas12Cache={savedSchema:productShowcaseAttrsSchema,renderedSchema:productShowcaseAttrsSchema2};}
let loadSchemas13Cache;
function loadSchemas13(){if(loadSchemas13Cache)return loadSchemas13Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var accordionAttrsSchema = z.object({
  heading: z.string().max(120).default(""),
  body: paragraphText(300),
  items: z.array(z.object({
    title: z.string().max(120).default(""),
    body: paragraphText(2000)
  })).max(40).default([]),
  defaultOpen: z.number().min(0).default(0)
});
var accordionAttrsSchema2 = z2.object({
  heading: z2.string().default(""),
  body: z2.string().default(""),
  items: z2.array(z2.object({
    title: z2.string().default(""),
    body: z2.string().default("")
  })).default([]),
  defaultOpen: z2.number().default(0)
});
return loadSchemas13Cache={savedSchema:accordionAttrsSchema,renderedSchema:accordionAttrsSchema2};}
let loadSchemas14Cache;
function loadSchemas14(){if(loadSchemas14Cache)return loadSchemas14Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var paragraphText = (max = 1000) => z.string().max(max).default("");
var authorBioAttrsSchema = z.object({
  userId: z.string().default(""),
  name: z.string().max(80).default(""),
  role: z.string().max(80).default(""),
  bio: paragraphText(500),
  mediaId: z.string().default(""),
  links: z.array(z.object({
    label: z.string().max(40).default(""),
    href: urlOrEmpty.default("")
  })).max(6).default([])
});
var authorBioAttrsSchema2 = z2.object({
  userId: z2.string().default(""),
  name: z2.string().default(""),
  role: z2.string().default(""),
  bio: z2.string().default(""),
  mediaId: z2.string().default(""),
  links: z2.array(z2.object({
    label: z2.string().default(""),
    href: z2.string().default("")
  })).default([])
});
return loadSchemas14Cache={savedSchema:authorBioAttrsSchema,renderedSchema:authorBioAttrsSchema2};}
let loadSchemas15Cache;
function loadSchemas15(){if(loadSchemas15Cache)return loadSchemas15Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var paragraphText = (max = 1000) => z.string().max(max).default("");
var bentoGridAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(300),
  items: z.array(z.object({
    title: z.string().max(80).default(""),
    body: paragraphText(400),
    mediaId: z.string().default(""),
    size: z.union([z.literal("small"), z.literal("medium"), z.literal("large")]).default("medium"),
    ctaLabel: z.string().max(40).default(""),
    ctaUrl: urlOrEmpty.default("")
  })).max(12).default([])
});
var bentoGridAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  items: z2.array(z2.object({
    title: z2.string().default(""),
    body: z2.string().default(""),
    mediaId: z2.string().default(""),
    size: z2.union([z2.literal("small"), z2.literal("medium"), z2.literal("large")]).default("medium"),
    ctaLabel: z2.string().default(""),
    ctaUrl: z2.string().default("")
  })).default([])
});
return loadSchemas15Cache={savedSchema:bentoGridAttrsSchema,renderedSchema:bentoGridAttrsSchema2};}
let loadSchemas16Cache;
function loadSchemas16(){if(loadSchemas16Cache)return loadSchemas16Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var paragraphText = (max = 1000) => z.string().max(max).default("");
var bookingCtaAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().min(1).max(120).default(""),
  body: paragraphText(400),
  ctaLabel: z.string().max(40).default("Book a time"),
  ctaUrl: urlOrEmpty.default(""),
  embedUrl: urlOrEmpty.default("")
});
var bookingCtaAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  ctaLabel: z2.string().default(""),
  ctaUrl: z2.string().default(""),
  embedUrl: z2.string().default("")
});
return loadSchemas16Cache={savedSchema:bookingCtaAttrsSchema,renderedSchema:bookingCtaAttrsSchema2};}
let loadSchemas17Cache;
function loadSchemas17(){if(loadSchemas17Cache)return loadSchemas17Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var codeAttrsSchema = z.object({
  language: z.string().max(40).default(""),
  code: z.string().default(""),
  filename: z.string().max(120).default("")
});
var codeAttrsSchema2 = z2.object({
  language: z2.string().default(""),
  code: z2.string().default(""),
  filename: z2.string().default("")
});
return loadSchemas17Cache={savedSchema:codeAttrsSchema,renderedSchema:codeAttrsSchema2};}
let loadSchemas18Cache;
function loadSchemas18(){if(loadSchemas18Cache)return loadSchemas18Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var comparisonTableAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(300),
  columns: z.array(z.string().max(40)).min(2).max(6).default(["Feature", "Us", "Them"]),
  rows: z.array(z.object({
    label: z.string().max(80).default(""),
    cells: z.array(z.string().max(80)).default([])
  })).max(40).default([])
});
var comparisonTableAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  columns: z2.array(z2.string()).default([]),
  rows: z2.array(z2.object({
    label: z2.string().default(""),
    cells: z2.array(z2.string()).default([])
  })).default([])
});
return loadSchemas18Cache={savedSchema:comparisonTableAttrsSchema,renderedSchema:comparisonTableAttrsSchema2};}
let loadSchemas19Cache;
function loadSchemas19(){if(loadSchemas19Cache)return loadSchemas19Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var contactFormAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(400),
  fields: z.array(z.object({
    name: z.string().max(40).default("name"),
    label: z.string().max(80).default("Name"),
    type: z.union([
      z.literal("text"),
      z.literal("email"),
      z.literal("tel"),
      z.literal("textarea"),
      z.literal("select")
    ]).default("text"),
    required: z.boolean().default(false),
    placeholder: z.string().max(120).default(""),
    options: z.array(z.string().max(80)).default([])
  })).max(12).default([]),
  submitLabel: z.string().max(40).default("Send message"),
  recipientEmail: z.string().max(200).default(""),
  successMessage: z.string().max(200).default("Thanks — we'll be in touch.")
});
var contactFormAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  fields: z2.array(z2.object({
    name: z2.string().default("field"),
    label: z2.string().default("Field"),
    type: z2.union([z2.literal("text"), z2.literal("email"), z2.literal("tel"), z2.literal("textarea"), z2.literal("select")]).default("text"),
    required: z2.boolean().default(false),
    placeholder: z2.string().default(""),
    options: z2.array(z2.string()).default([])
  })).default([]),
  submitLabel: z2.string().default("Send"),
  recipientEmail: z2.string().default(""),
  successMessage: z2.string().default("")
});
return loadSchemas19Cache={savedSchema:contactFormAttrsSchema,renderedSchema:contactFormAttrsSchema2};}
let loadSchemas20Cache;
function loadSchemas20(){if(loadSchemas20Cache)return loadSchemas20Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var paragraphText = (max = 1000) => z.string().max(max).default("");
var ctaBandAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().min(1, "Heading required").max(120).default(""),
  body: paragraphText(400),
  primaryCtaLabel: z.string().max(40).default(""),
  primaryCtaUrl: urlOrEmpty.default(""),
  secondaryCtaLabel: z.string().max(40).default(""),
  secondaryCtaUrl: urlOrEmpty.default("")
});
var ctaBandAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  primaryCtaLabel: z2.string().default(""),
  primaryCtaUrl: z2.string().default(""),
  secondaryCtaLabel: z2.string().default(""),
  secondaryCtaUrl: z2.string().default("")
});
return loadSchemas20Cache={savedSchema:ctaBandAttrsSchema,renderedSchema:ctaBandAttrsSchema2};}
let loadSchemas21Cache;
function loadSchemas21(){if(loadSchemas21Cache)return loadSchemas21Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var ctaWithFormAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().min(1).max(120).default(""),
  body: paragraphText(400),
  placeholder: z.string().max(80).default("you@company.com"),
  submitLabel: z.string().max(40).default("Get started"),
  fineprint: z.string().max(200).default("")
});
var ctaWithFormAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  placeholder: z2.string().default(""),
  submitLabel: z2.string().default("Get started"),
  fineprint: z2.string().default("")
});
return loadSchemas21Cache={savedSchema:ctaWithFormAttrsSchema,renderedSchema:ctaWithFormAttrsSchema2};}
let loadSchemas22Cache;
function loadSchemas22(){if(loadSchemas22Cache)return loadSchemas22Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var dividerAttrsSchema = z.object({
  variant: z.union([
    z.literal("default"),
    z.literal("section"),
    z.literal("subtle")
  ]).default("default")
});
var dividerAttrsSchema2 = z2.object({
  variant: z2.union([z2.literal("default"), z2.literal("section"), z2.literal("subtle")]).default("default")
});
return loadSchemas22Cache={savedSchema:dividerAttrsSchema,renderedSchema:dividerAttrsSchema2};}
let loadSchemas23Cache;
function loadSchemas23(){if(loadSchemas23Cache)return loadSchemas23Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var embedAttrsSchema = z.object({
  url: urlOrEmpty.default(""),
  caption: z.string().max(300).default("")
});
var embedAttrsSchema2 = z2.object({
  url: z2.string().default(""),
  caption: z2.string().default("")
});
return loadSchemas23Cache={savedSchema:embedAttrsSchema,renderedSchema:embedAttrsSchema2};}
let loadSchemas24Cache;
function loadSchemas24(){if(loadSchemas24Cache)return loadSchemas24Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var faqAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(400),
  items: z.array(z.object({
    question: z.string().max(200).default(""),
    answer: z.string().max(1000).default("")
  })).max(40).default([])
});
var faqAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  items: z2.array(z2.object({
    question: z2.string().default(""),
    answer: z2.string().default("")
  })).default([])
});
return loadSchemas24Cache={savedSchema:faqAttrsSchema,renderedSchema:faqAttrsSchema2};}
let loadSchemas25Cache;
function loadSchemas25(){if(loadSchemas25Cache)return loadSchemas25Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var featureGridAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(400),
  items: z.array(z.object({
    title: z.string().max(80).default(""),
    description: z.string().max(300).default("")
  })).max(12).default([])
});
var featureGridAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  items: z2.array(z2.object({
    title: z2.string().default(""),
    description: z2.string().default("")
  })).default([])
});
return loadSchemas25Cache={savedSchema:featureGridAttrsSchema,renderedSchema:featureGridAttrsSchema2};}
let loadSchemas26Cache;
function loadSchemas26(){if(loadSchemas26Cache)return loadSchemas26Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var paragraphText = (max = 1000) => z.string().max(max).default("");
var featureListAlternatingAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(400),
  items: z.array(z.object({
    title: z.string().max(80).default(""),
    body: paragraphText(400),
    mediaId: z.string().default(""),
    mediaAlt: z.string().max(200).default(""),
    ctaLabel: z.string().max(40).default(""),
    ctaUrl: urlOrEmpty.default("")
  })).max(10).default([])
});
var featureListAlternatingAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  items: z2.array(z2.object({
    title: z2.string().default(""),
    body: z2.string().default(""),
    mediaId: z2.string().default(""),
    mediaAlt: z2.string().default(""),
    ctaLabel: z2.string().default(""),
    ctaUrl: z2.string().default("")
  })).default([])
});
return loadSchemas26Cache={savedSchema:featureListAlternatingAttrsSchema,renderedSchema:featureListAlternatingAttrsSchema2};}
let loadSchemas27Cache;
function loadSchemas27(){if(loadSchemas27Cache)return loadSchemas27Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var featuredProductsAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(300),
  productIds: z.array(z.string()).max(12).default([]),
  count: z.number().min(1).max(12).default(4),
  showPrice: z.boolean().default(true)
});
var featuredProductsAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  productIds: z2.array(z2.string()).default([]),
  count: z2.number().default(4),
  showPrice: z2.boolean().default(true)
});
return loadSchemas27Cache={savedSchema:featuredProductsAttrsSchema,renderedSchema:featuredProductsAttrsSchema2};}
let loadSchemas28Cache;
function loadSchemas28(){if(loadSchemas28Cache)return loadSchemas28Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var headingAttrsSchema = z.object({
  level: z.union([
    z.literal(1),
    z.literal(2),
    z.literal(3),
    z.literal(4),
    z.literal(5),
    z.literal(6)
  ]).default(2),
  text: z.string().min(1, "Heading text required").max(200).default("Heading"),
  anchor: z.string().max(80).default("")
});
var headingAttrsSchema2 = z2.object({
  level: z2.union([z2.literal(1), z2.literal(2), z2.literal(3), z2.literal(4), z2.literal(5), z2.literal(6)]).default(2),
  text: z2.string().default(""),
  anchor: z2.string().default("")
});
return loadSchemas28Cache={savedSchema:headingAttrsSchema,renderedSchema:headingAttrsSchema2};}
let loadSchemas29Cache;
function loadSchemas29(){if(loadSchemas29Cache)return loadSchemas29Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var paragraphText = (max = 1000) => z.string().max(max).default("");
var heroAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  title: z.string().min(1, "Title required").max(120).default(""),
  body: paragraphText(600),
  primaryCtaLabel: z.string().max(40).default(""),
  primaryCtaUrl: urlOrEmpty.default(""),
  secondaryCtaLabel: z.string().max(40).default(""),
  secondaryCtaUrl: urlOrEmpty.default(""),
  mediaId: z.string().default("")
});
var heroAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  title: z2.string().default(""),
  body: z2.string().default(""),
  primaryCtaLabel: z2.string().default(""),
  primaryCtaUrl: z2.string().default(""),
  secondaryCtaLabel: z2.string().default(""),
  secondaryCtaUrl: z2.string().default(""),
  mediaId: z2.string().default("")
});
return loadSchemas29Cache={savedSchema:heroAttrsSchema,renderedSchema:heroAttrsSchema2};}
let loadSchemas30Cache;
function loadSchemas30(){if(loadSchemas30Cache)return loadSchemas30Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var paragraphText = (max = 1000) => z.string().max(max).default("");
var heroSplitAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  title: z.string().min(1).max(120).default(""),
  body: paragraphText(600),
  primaryCtaLabel: z.string().max(40).default(""),
  primaryCtaUrl: urlOrEmpty.default(""),
  secondaryCtaLabel: z.string().max(40).default(""),
  secondaryCtaUrl: urlOrEmpty.default(""),
  mediaId: z.string().default(""),
  mediaAlt: z.string().max(200).default(""),
  mediaSide: z.union([z.literal("left"), z.literal("right")]).default("right")
});
var heroSplitAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  title: z2.string().default(""),
  body: z2.string().default(""),
  primaryCtaLabel: z2.string().default(""),
  primaryCtaUrl: z2.string().default(""),
  secondaryCtaLabel: z2.string().default(""),
  secondaryCtaUrl: z2.string().default(""),
  mediaId: z2.string().default(""),
  mediaAlt: z2.string().default(""),
  mediaSide: z2.union([z2.literal("left"), z2.literal("right")]).default("right")
});
return loadSchemas30Cache={savedSchema:heroSplitAttrsSchema,renderedSchema:heroSplitAttrsSchema2};}
let loadSchemas31Cache;
function loadSchemas31(){if(loadSchemas31Cache)return loadSchemas31Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var paragraphText = (max = 1000) => z.string().max(max).default("");
var heroTextOnlyAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  title: z.string().min(1).max(120).default(""),
  body: paragraphText(600),
  primaryCtaLabel: z.string().max(40).default(""),
  primaryCtaUrl: urlOrEmpty.default(""),
  secondaryCtaLabel: z.string().max(40).default(""),
  secondaryCtaUrl: urlOrEmpty.default(""),
  alignment: z.union([z.literal("center"), z.literal("left")]).default("center")
});
var heroTextOnlyAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  title: z2.string().default(""),
  body: z2.string().default(""),
  primaryCtaLabel: z2.string().default(""),
  primaryCtaUrl: z2.string().default(""),
  secondaryCtaLabel: z2.string().default(""),
  secondaryCtaUrl: z2.string().default(""),
  alignment: z2.union([z2.literal("center"), z2.literal("left")]).default("center")
});
return loadSchemas31Cache={savedSchema:heroTextOnlyAttrsSchema,renderedSchema:heroTextOnlyAttrsSchema2};}
let loadSchemas32Cache;
function loadSchemas32(){if(loadSchemas32Cache)return loadSchemas32Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var imageAttrsSchema = z.object({
  mediaId: z.string().default(""),
  alt: z.string().max(200).default(""),
  caption: z.string().max(300).default(""),
  href: urlOrEmpty.default("")
});
var imageAttrsSchema2 = z2.object({
  mediaId: z2.string().default(""),
  alt: z2.string().default(""),
  caption: z2.string().default(""),
  href: z2.string().default("")
});
return loadSchemas32Cache={savedSchema:imageAttrsSchema,renderedSchema:imageAttrsSchema2};}
let loadSchemas33Cache;
function loadSchemas33(){if(loadSchemas33Cache)return loadSchemas33Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var latestPostsAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(300),
  count: z.number().min(1).max(24).default(3),
  categorySlug: z.string().max(120).default(""),
  tagSlug: z.string().max(120).default(""),
  showExcerpts: z.boolean().default(true),
  showAuthors: z.boolean().default(true)
});
var latestPostsAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  count: z2.number().default(3),
  categorySlug: z2.string().default(""),
  tagSlug: z2.string().default(""),
  showExcerpts: z2.boolean().default(true),
  showAuthors: z2.boolean().default(true)
});
return loadSchemas33Cache={savedSchema:latestPostsAttrsSchema,renderedSchema:latestPostsAttrsSchema2};}
let loadSchemas34Cache;
function loadSchemas34(){if(loadSchemas34Cache)return loadSchemas34Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var listAttrsSchema = z.object({
  style: z.union([
    z.literal("bullet"),
    z.literal("ordered"),
    z.literal("task")
  ]).default("bullet"),
  items: z.array(z.object({
    text: z.string().max(500).default(""),
    done: z.boolean().optional()
  })).default([{ text: "" }])
});
var listAttrsSchema2 = z2.object({
  style: z2.union([z2.literal("bullet"), z2.literal("ordered"), z2.literal("task")]).default("bullet"),
  items: z2.array(z2.object({
    text: z2.string().default(""),
    done: z2.boolean().optional()
  })).default([])
});
return loadSchemas34Cache={savedSchema:listAttrsSchema,renderedSchema:listAttrsSchema2};}
let loadSchemas35Cache;
function loadSchemas35(){if(loadSchemas35Cache)return loadSchemas35Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var logoCloudAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  logos: z.array(z.object({
    name: z.string().max(80).default(""),
    mediaId: z.string().default(""),
    href: urlOrEmpty.default("")
  })).max(24).default([])
});
var logoCloudAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  logos: z2.array(z2.object({
    name: z2.string().default(""),
    mediaId: z2.string().default(""),
    href: z2.string().default("")
  })).default([])
});
return loadSchemas35Cache={savedSchema:logoCloudAttrsSchema,renderedSchema:logoCloudAttrsSchema2};}
let loadSchemas36Cache;
function loadSchemas36(){if(loadSchemas36Cache)return loadSchemas36Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var paragraphText = (max = 1000) => z.string().max(max).default("");
var mediaTextAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(600),
  mediaId: z.string().default(""),
  mediaAlt: z.string().max(200).default(""),
  mediaPosition: z.union([z.literal("left"), z.literal("right")]).default("right"),
  ctaLabel: z.string().max(40).default(""),
  ctaUrl: urlOrEmpty.default("")
});
var mediaTextAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  mediaId: z2.string().default(""),
  mediaAlt: z2.string().default(""),
  mediaPosition: z2.union([z2.literal("left"), z2.literal("right")]).default("right"),
  ctaLabel: z2.string().default(""),
  ctaUrl: z2.string().default("")
});
return loadSchemas36Cache={savedSchema:mediaTextAttrsSchema,renderedSchema:mediaTextAttrsSchema2};}
let loadSchemas37Cache;
function loadSchemas37(){if(loadSchemas37Cache)return loadSchemas37Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var newsletterSignupAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(300),
  placeholder: z.string().max(80).default("Your email"),
  submitLabel: z.string().max(40).default("Subscribe"),
  successMessage: z.string().max(200).default("Check your inbox to confirm."),
  variant: z.union([z.literal("inline"), z.literal("large")]).default("inline")
});
var newsletterSignupAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  placeholder: z2.string().default("Your email"),
  submitLabel: z2.string().default("Subscribe"),
  successMessage: z2.string().default(""),
  variant: z2.union([z2.literal("inline"), z2.literal("large")]).default("inline")
});
return loadSchemas37Cache={savedSchema:newsletterSignupAttrsSchema,renderedSchema:newsletterSignupAttrsSchema2};}
let loadSchemas38Cache;
function loadSchemas38(){if(loadSchemas38Cache)return loadSchemas38Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var paragraphAttrsSchema = z.object({
  body: paragraphText(2000)
});
var paragraphAttrsSchema2 = z2.object({
  body: z2.string().default("")
});
return loadSchemas38Cache={savedSchema:paragraphAttrsSchema,renderedSchema:paragraphAttrsSchema2};}
let loadSchemas39Cache;
function loadSchemas39(){if(loadSchemas39Cache)return loadSchemas39Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var paragraphText = (max = 1000) => z.string().max(max).default("");
var pricingCardsAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(400),
  plans: z.array(z.object({
    name: z.string().max(40).default(""),
    price: z.string().max(40).default(""),
    description: z.string().max(200).default(""),
    features: z.array(z.string().max(120)).max(20).default([]),
    ctaLabel: z.string().max(40).default(""),
    ctaUrl: urlOrEmpty.default(""),
    featured: z.boolean().default(false)
  })).max(6).default([])
});
var pricingCardsAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  plans: z2.array(z2.object({
    name: z2.string().default(""),
    price: z2.string().default(""),
    description: z2.string().default(""),
    features: z2.array(z2.string()).default([]),
    ctaLabel: z2.string().default(""),
    ctaUrl: z2.string().default(""),
    featured: z2.boolean().default(false)
  })).default([])
});
return loadSchemas39Cache={savedSchema:pricingCardsAttrsSchema,renderedSchema:pricingCardsAttrsSchema2};}
let loadSchemas40Cache;
function loadSchemas40(){if(loadSchemas40Cache)return loadSchemas40Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var processStepsAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(300),
  steps: z.array(z.object({
    title: z.string().max(80).default(""),
    body: paragraphText(400)
  })).max(12).default([])
});
var processStepsAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  steps: z2.array(z2.object({
    title: z2.string().default(""),
    body: z2.string().default("")
  })).default([])
});
return loadSchemas40Cache={savedSchema:processStepsAttrsSchema,renderedSchema:processStepsAttrsSchema2};}
let loadSchemas41Cache;
function loadSchemas41(){if(loadSchemas41Cache)return loadSchemas41Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var quoteAttrsSchema = z.object({
  text: z.string().min(1, "Quote text required").max(800).default(""),
  cite: z.string().max(120).default(""),
  source: urlOrEmpty.default("")
});
var quoteAttrsSchema2 = z2.object({
  text: z2.string().default(""),
  cite: z2.string().default(""),
  source: z2.string().default("")
});
return loadSchemas41Cache={savedSchema:quoteAttrsSchema,renderedSchema:quoteAttrsSchema2};}
let loadSchemas42Cache;
function loadSchemas42(){if(loadSchemas42Cache)return loadSchemas42Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var richTextAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(2000)
});
var richTextAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default("")
});
return loadSchemas42Cache={savedSchema:richTextAttrsSchema,renderedSchema:richTextAttrsSchema2};}
let loadSchemas43Cache;
function loadSchemas43(){if(loadSchemas43Cache)return loadSchemas43Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var roadmapTimelineAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(300),
  items: z.array(z.object({
    label: z.string().max(40).default(""),
    title: z.string().max(120).default(""),
    body: paragraphText(400),
    status: z.union([z.literal("done"), z.literal("in_progress"), z.literal("planned")]).default("planned")
  })).max(30).default([])
});
var roadmapTimelineAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  items: z2.array(z2.object({
    label: z2.string().default(""),
    title: z2.string().default(""),
    body: z2.string().default(""),
    status: z2.union([z2.literal("done"), z2.literal("in_progress"), z2.literal("planned")]).default("planned")
  })).default([])
});
return loadSchemas43Cache={savedSchema:roadmapTimelineAttrsSchema,renderedSchema:roadmapTimelineAttrsSchema2};}
let loadSchemas44Cache;
function loadSchemas44(){if(loadSchemas44Cache)return loadSchemas44Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var socialLinksAttrsSchema = z.object({
  heading: z.string().max(80).default(""),
  links: z.array(z.object({
    platform: z.string().max(40).default(""),
    label: z.string().max(40).default(""),
    href: urlOrEmpty.default("")
  })).max(12).default([])
});
var socialLinksAttrsSchema2 = z2.object({
  heading: z2.string().default(""),
  links: z2.array(z2.object({
    platform: z2.string().default(""),
    label: z2.string().default(""),
    href: z2.string().default("")
  })).default([])
});
return loadSchemas44Cache={savedSchema:socialLinksAttrsSchema,renderedSchema:socialLinksAttrsSchema2};}
let loadSchemas45Cache;
function loadSchemas45(){if(loadSchemas45Cache)return loadSchemas45Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var spacerAttrsSchema = z.object({
  size: z.union([
    z.literal("small"),
    z.literal("medium"),
    z.literal("large"),
    z.literal("xlarge")
  ]).default("medium")
});
var spacerAttrsSchema2 = z2.object({
  size: z2.union([z2.literal("small"), z2.literal("medium"), z2.literal("large"), z2.literal("xlarge")]).default("medium")
});
return loadSchemas45Cache={savedSchema:spacerAttrsSchema,renderedSchema:spacerAttrsSchema2};}
let loadSchemas46Cache;
function loadSchemas46(){if(loadSchemas46Cache)return loadSchemas46Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var statsBandAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(300),
  stats: z.array(z.object({
    value: z.string().max(40).default(""),
    label: z.string().max(80).default("")
  })).max(6).default([])
});
var statsBandAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  stats: z2.array(z2.object({
    value: z2.string().default(""),
    label: z2.string().default("")
  })).default([])
});
return loadSchemas46Cache={savedSchema:statsBandAttrsSchema,renderedSchema:statsBandAttrsSchema2};}
let loadSchemas47Cache;
function loadSchemas47(){if(loadSchemas47Cache)return loadSchemas47Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var tabsAttrsSchema = z.object({
  heading: z.string().max(120).default(""),
  tabs: z.array(z.object({
    label: z.string().max(40).default(""),
    body: paragraphText(2000)
  })).max(8).default([])
});
var tabsAttrsSchema2 = z2.object({
  heading: z2.string().default(""),
  tabs: z2.array(z2.object({
    label: z2.string().default(""),
    body: z2.string().default("")
  })).default([])
});
return loadSchemas47Cache={savedSchema:tabsAttrsSchema,renderedSchema:tabsAttrsSchema2};}
let loadSchemas48Cache;
function loadSchemas48(){if(loadSchemas48Cache)return loadSchemas48Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var tagCloudAttrsSchema = z.object({
  heading: z.string().max(80).default(""),
  max: z.number().min(1).max(100).default(30)
});
var tagCloudAttrsSchema2 = z2.object({
  heading: z2.string().default(""),
  max: z2.number().default(30)
});
return loadSchemas48Cache={savedSchema:tagCloudAttrsSchema,renderedSchema:tagCloudAttrsSchema2};}
let loadSchemas49Cache;
function loadSchemas49(){if(loadSchemas49Cache)return loadSchemas49Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var urlOrEmpty = z.string().refine((v) => {
  if (v === "")
    return true;
  if (v.startsWith("/") || v.startsWith("#"))
    return true;
  if (v.startsWith("mailto:") || v.startsWith("tel:"))
    return true;
  try {
    new URL(v);
    return true;
  } catch {
    return false;
  }
}, { message: "Must be a valid URL or empty" });
var paragraphText = (max = 1000) => z.string().max(max).default("");
var teamGridAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(400),
  members: z.array(z.object({
    name: z.string().max(80).default(""),
    role: z.string().max(80).default(""),
    bio: z.string().max(400).default(""),
    mediaId: z.string().default(""),
    href: urlOrEmpty.default("")
  })).max(20).default([])
});
var teamGridAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  members: z2.array(z2.object({
    name: z2.string().default(""),
    role: z2.string().default(""),
    bio: z2.string().default(""),
    mediaId: z2.string().default(""),
    href: z2.string().default("")
  })).default([])
});
return loadSchemas49Cache={savedSchema:teamGridAttrsSchema,renderedSchema:teamGridAttrsSchema2};}
let loadSchemas50Cache;
function loadSchemas50(){if(loadSchemas50Cache)return loadSchemas50Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var paragraphText = (max = 1000) => z.string().max(max).default("");
var testimonialAttrsSchema = z.object({
  eyebrow: z.string().max(80).default(""),
  heading: z.string().max(120).default(""),
  body: paragraphText(400),
  items: z.array(z.object({
    quote: z.string().max(500).default(""),
    name: z.string().max(80).default(""),
    role: z.string().max(80).default("")
  })).max(20).default([])
});
var testimonialAttrsSchema2 = z2.object({
  eyebrow: z2.string().default(""),
  heading: z2.string().default(""),
  body: z2.string().default(""),
  items: z2.array(z2.object({
    quote: z2.string().default(""),
    name: z2.string().default(""),
    role: z2.string().default("")
  })).default([])
});
return loadSchemas50Cache={savedSchema:testimonialAttrsSchema,renderedSchema:testimonialAttrsSchema2};}
let loadSchemas51Cache;
function loadSchemas51(){if(loadSchemas51Cache)return loadSchemas51Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var upcomingEventsAttrsSchema = z.object({
  heading: z.string().max(160).default("Upcoming events"),
  intro: z.string().max(1000).default(""),
  count: z.number().int().min(1).max(12).default(3),
  showDescription: z.boolean().default(true),
  emptyText: z.string().max(240).default("New dates are on the way.")
});
var upcomingEventsAttrsSchema2 = z2.object({
  heading: z2.string().max(160).default("Upcoming events"),
  intro: z2.string().max(1000).default(""),
  count: z2.number().int().min(1).max(12).default(3),
  showDescription: z2.boolean().default(true),
  emptyText: z2.string().max(240).default("New dates are on the way.")
});
return loadSchemas51Cache={savedSchema:upcomingEventsAttrsSchema,renderedSchema:upcomingEventsAttrsSchema2};}
let loadSchemas52Cache;
function loadSchemas52(){if(loadSchemas52Cache)return loadSchemas52Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var sampleAlertAttrsSchema = z.object({
  heading: z.string().max(120).default("Important update"),
  body: z.string().max(800).default("Add the alert copy here."),
  variant: z.union([
    z.literal("info"),
    z.literal("success"),
    z.literal("warning")
  ]).default("info"),
  ctaLabel: z.string().max(40).default(""),
  ctaUrl: z.string().max(300).default("")
});
var sampleAlertAttrsSchema2 = z2.object({
  heading: z2.string().max(120).default("Important update"),
  body: z2.string().max(800).default("Add the alert copy here."),
  variant: z2.union([
    z2.literal("info"),
    z2.literal("success"),
    z2.literal("warning")
  ]).default("info"),
  ctaLabel: z2.string().max(40).default(""),
  ctaUrl: z2.string().max(300).default("")
});
return loadSchemas52Cache={savedSchema:sampleAlertAttrsSchema,renderedSchema:sampleAlertAttrsSchema2};}
let loadSchemas53Cache;
function loadSchemas53(){if(loadSchemas53Cache)return loadSchemas53Cache;
const {z:z}=legacyZod;
const {z:z2}=legacyZod;
var safeLink = z.string().max(2000).refine((value) => !value || /^(https?:\/\/|\/(?!\/)|#|mailto:|tel:)/i.test(value), "Use an HTTP(S), site-relative, email or telephone link");
var fieldGuideAttrsSchema = z.object({
  heading: z.string().max(160).default(""),
  body: z.string().max(4000).default(""),
  count: z.number().int().min(1).max(12).default(3),
  spacing: z.number().int().min(0).max(8).default(4),
  showDetails: z.boolean().default(true),
  alignment: z.enum(["left", "center", "right"]).default("left"),
  ink: z.enum(["foreground", "primary", "muted"]).default("foreground"),
  font: z.enum(["body", "display"]).default("display"),
  mediaId: z.string().max(256).default(""),
  mediaAlt: z.string().max(250).default(""),
  note: z.string().max(160).nullable().default(null),
  link: z.object({ label: z.string().max(80).default(""), href: safeLink.default(""), newTab: z.boolean().default(false) }).default({ label: "", href: "", newTab: false }),
  items: z.array(z.object({ label: z.string().max(100), value: z.string().max(300) })).max(12).default([])
});
var safeLink2 = z2.string().max(2000).refine((value) => !value || /^(https?:\/\/|\/(?!\/)|#|mailto:|tel:)/i.test(value), "Use an HTTP(S), site-relative, email or telephone link");
var fieldGuideAttrsSchema2 = z2.object({
  heading: z2.string().max(160).default(""),
  body: z2.string().max(4000).default(""),
  count: z2.number().int().min(1).max(12).default(3),
  spacing: z2.number().int().min(0).max(8).default(4),
  showDetails: z2.boolean().default(true),
  alignment: z2.enum(["left", "center", "right"]).default("left"),
  ink: z2.enum(["foreground", "primary", "muted"]).default("foreground"),
  font: z2.enum(["body", "display"]).default("display"),
  mediaId: z2.string().max(256).default(""),
  mediaAlt: z2.string().max(250).default(""),
  note: z2.string().max(160).nullable().default(null),
  link: z2.object({ label: z2.string().max(80).default(""), href: safeLink2.default(""), newTab: z2.boolean().default(false) }).default({ label: "", href: "", newTab: false }),
  items: z2.array(z2.object({ label: z2.string().max(100), value: z2.string().max(300) })).max(12).default([])
});
return loadSchemas53Cache={savedSchema:fieldGuideAttrsSchema,renderedSchema:fieldGuideAttrsSchema2};}
let loadHelpersCache;
function loadHelpers(){if(loadHelpersCache)return loadHelpersCache;

var DEFAULT_HREF_OPTIONS = {
  allowRelative: true,
  allowHash: true,
  allowMailto: true,
  allowTel: true,
  allowProtocolRelative: false
};
function sanitizeUrlValue(value, options) {
  const trimmed = value?.trim();
  if (!trimmed)
    return;
  if (/[\u0000-\u001f\u007f\\]/.test(trimmed))
    return;
  const resolved = { ...DEFAULT_HREF_OPTIONS, ...options };
  if (/^(javascript|data|vbscript|blob|file):/i.test(trimmed)) {
    return;
  }
  if (trimmed.startsWith("//")) {
    return resolved.allowProtocolRelative ? trimmed : undefined;
  }
  if (trimmed.startsWith("#")) {
    return resolved.allowHash ? trimmed : undefined;
  }
  if (/^(\/|\.\.\/|\.\/|\?)/.test(trimmed)) {
    return resolved.allowRelative ? trimmed : undefined;
  }
  try {
    const parsed = new URL(trimmed);
    if (parsed.protocol === "http:" || parsed.protocol === "https:") {
      return trimmed;
    }
    if (parsed.protocol === "mailto:" && resolved.allowMailto) {
      return trimmed;
    }
    if (parsed.protocol === "tel:" && resolved.allowTel) {
      return trimmed;
    }
    return;
  } catch {
    if (resolved.allowRelative && !trimmed.includes(":")) {
      return trimmed;
    }
    return;
  }
}
function sanitizeHref(value, options) {
  return sanitizeUrlValue(value, options);
}
function isExternalUrl(href) {
  return /^https?:\/\//i.test(href);
}
function stringValue(value) {
  return typeof value === "string" ? value : "";
}
function arrayValue(value) {
  return Array.isArray(value) ? value : [];
}
function pageSectionsToBlocks(sections) {
  return (sections ?? []).map((section) => {
    const data = section.data ?? {};
    const base = {
      id: section.id || `blk_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`,
      version: 1
    };
    switch (section.type) {
      case "hero":
        return {
          ...base,
          name: "core/hero",
          attrs: {
            eyebrow: stringValue(data.eyebrow),
            title: stringValue(data.title),
            body: stringValue(data.body),
            primaryCtaLabel: stringValue(data.primaryCtaLabel),
            primaryCtaUrl: stringValue(data.primaryCtaUrl),
            secondaryCtaLabel: stringValue(data.secondaryCtaLabel),
            secondaryCtaUrl: stringValue(data.secondaryCtaUrl),
            mediaId: stringValue(data.mediaId)
          }
        };
      case "feature-grid":
        return {
          ...base,
          name: "core/feature-grid",
          attrs: {
            eyebrow: stringValue(data.eyebrow),
            heading: stringValue(data.heading),
            body: stringValue(data.body),
            items: arrayValue(data.items).map((item) => ({
              title: stringValue(item.title),
              description: stringValue(item.description)
            }))
          }
        };
      case "cta-band":
        return {
          ...base,
          name: "core/cta-band",
          attrs: {
            eyebrow: stringValue(data.eyebrow),
            heading: stringValue(data.heading),
            body: stringValue(data.body),
            primaryCtaLabel: stringValue(data.primaryCtaLabel),
            primaryCtaUrl: stringValue(data.primaryCtaUrl),
            secondaryCtaLabel: stringValue(data.secondaryCtaLabel),
            secondaryCtaUrl: stringValue(data.secondaryCtaUrl)
          }
        };
      case "story-split":
        return {
          ...base,
          name: "core/media-text",
          attrs: {
            eyebrow: stringValue(data.eyebrow),
            heading: stringValue(data.heading) || stringValue(data.title),
            body: stringValue(data.body) || stringValue(data.content),
            mediaId: stringValue(data.mediaId),
            mediaAlt: stringValue(data.mediaAlt),
            mediaPosition: stringValue(data.mediaPosition) === "left" ? "left" : "right",
            ctaLabel: stringValue(data.ctaLabel),
            ctaUrl: stringValue(data.ctaUrl)
          }
        };
      case "pricing-cards":
        return {
          ...base,
          name: "core/pricing-cards",
          attrs: {
            eyebrow: stringValue(data.eyebrow),
            heading: stringValue(data.heading) || stringValue(data.title),
            body: stringValue(data.body) || stringValue(data.content),
            plans: arrayValue(data.plans || data.items).map((plan) => ({
              name: stringValue(plan.name) || stringValue(plan.title),
              price: stringValue(plan.price),
              description: stringValue(plan.description) || stringValue(plan.body),
              features: arrayValue(plan.features).map(stringValue).filter(Boolean),
              ctaLabel: stringValue(plan.ctaLabel),
              ctaUrl: stringValue(plan.ctaUrl),
              featured: plan.featured === true
            }))
          }
        };
      case "testimonial-band":
        return {
          ...base,
          name: "core/testimonials",
          attrs: {
            eyebrow: stringValue(data.eyebrow),
            heading: stringValue(data.heading) || stringValue(data.title),
            body: stringValue(data.body) || stringValue(data.content),
            items: arrayValue(data.items || data.testimonials).map((item) => ({
              quote: stringValue(item.quote) || stringValue(item.body),
              name: stringValue(item.name) || stringValue(item.author),
              role: stringValue(item.role) || stringValue(item.title)
            }))
          }
        };
      case "rich-text":
      default:
        return {
          ...base,
          name: "core/rich-text",
          attrs: {
            eyebrow: stringValue(data.eyebrow),
            heading: stringValue(data.heading) || stringValue(data.title),
            body: stringValue(data.body) || stringValue(data.content)
          }
        };
    }
  });
}
return loadHelpersCache={pageSectionsToBlocks:pageSectionsToBlocks,legacySanitizeHref:sanitizeHref,legacyIsExternalUrl:isExternalUrl};}
export const legacyCompatibility={"blocks/contact-stack":{...{"name":"blocks/contact-stack","fromVersion":1,"toVersion":1,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas0().savedSchema;},get renderedSchema(){return loadSchemas0().renderedSchema;}},
"blocks/customer-showcase":{...{"name":"blocks/customer-showcase","fromVersion":1,"toVersion":1,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas1().savedSchema;},get renderedSchema(){return loadSchemas1().renderedSchema;}},
"blocks/grade-gallery":{...{"name":"blocks/grade-gallery","fromVersion":1,"toVersion":1,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas2().savedSchema;},get renderedSchema(){return loadSchemas2().renderedSchema;}},
"blocks/media-mentions":{...{"name":"blocks/media-mentions","fromVersion":1,"toVersion":1,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas3().savedSchema;},get renderedSchema(){return loadSchemas3().renderedSchema;}},
"blocks/page-banner":{...{"name":"blocks/page-banner","fromVersion":1,"toVersion":1,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas4().savedSchema;},get renderedSchema(){return loadSchemas4().renderedSchema;}},
"blocks/product-collection":{...{"name":"blocks/product-collection","fromVersion":1,"toVersion":2,"transforms":[{"kind":"pack-treatment","path":["display"]},{"kind":"pack-treatment","path":["columns"]}],"treatments":[{"name":"gallery","axes":["display","columns","aspect"]}]},get savedSchema(){return loadSchemas5().savedSchema;},get renderedSchema(){return loadSchemas5().renderedSchema;}},
"blocks/promo-band":{...{"name":"blocks/promo-band","fromVersion":1,"toVersion":1,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas6().savedSchema;},get renderedSchema(){return loadSchemas6().renderedSchema;}},
"blocks/social-share":{...{"name":"blocks/social-share","fromVersion":1,"toVersion":1,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas7().savedSchema;},get renderedSchema(){return loadSchemas7().renderedSchema;}},
"blocks/story-timeline":{...{"name":"blocks/story-timeline","fromVersion":1,"toVersion":2,"transforms":[{"kind":"pack-treatment","path":["items","*","side"]}],"treatments":[]},get savedSchema(){return loadSchemas8().savedSchema;},get renderedSchema(){return loadSchemas8().renderedSchema;}},
"blocks/tabbed-content":{...{"name":"blocks/tabbed-content","fromVersion":1,"toVersion":2,"transforms":[{"kind":"pack-treatment","path":["orientation"]}],"treatments":[]},get savedSchema(){return loadSchemas9().savedSchema;},get renderedSchema(){return loadSchemas9().renderedSchema;}},
"commerce/assistant-band":{...{"name":"commerce/assistant-band","fromVersion":1,"toVersion":1,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas10().savedSchema;},get renderedSchema(){return loadSchemas10().renderedSchema;}},
"commerce/category-tiles":{...{"name":"commerce/category-tiles","fromVersion":1,"toVersion":2,"transforms":[{"kind":"pack-treatment","path":["columns"]}],"treatments":[]},get savedSchema(){return loadSchemas11().savedSchema;},get renderedSchema(){return loadSchemas11().renderedSchema;}},
"commerce/product-showcase":{...{"name":"commerce/product-showcase","fromVersion":1,"toVersion":2,"transforms":[{"kind":"pack-treatment","path":["columns"]}],"treatments":[]},get savedSchema(){return loadSchemas12().savedSchema;},get renderedSchema(){return loadSchemas12().renderedSchema;}},
"core/accordion":{...{"name":"core/accordion","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas13().savedSchema;},get renderedSchema(){return loadSchemas13().renderedSchema;}},
"core/author-bio":{...{"name":"core/author-bio","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas14().savedSchema;},get renderedSchema(){return loadSchemas14().renderedSchema;}},
"core/bento-grid":{...{"name":"core/bento-grid","fromVersion":1,"toVersion":2,"transforms":[{"kind":"pack-treatment","path":["items","*","size"]}],"treatments":[]},get savedSchema(){return loadSchemas15().savedSchema;},get renderedSchema(){return loadSchemas15().renderedSchema;}},
"core/booking-cta":{...{"name":"core/booking-cta","fromVersion":1,"toVersion":2,"transforms":[{"kind":"empty-to-null","path":["heading"]}],"treatments":[]},get savedSchema(){return loadSchemas16().savedSchema;},get renderedSchema(){return loadSchemas16().renderedSchema;}},
"core/code":{...{"name":"core/code","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas17().savedSchema;},get renderedSchema(){return loadSchemas17().renderedSchema;}},
"core/comparison-table":{...{"name":"core/comparison-table","fromVersion":1,"toVersion":2,"transforms":[{"kind":"empty-to-null","path":["columns"]}],"treatments":[]},get savedSchema(){return loadSchemas18().savedSchema;},get renderedSchema(){return loadSchemas18().renderedSchema;}},
"core/contact-form":{...{"name":"core/contact-form","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas19().savedSchema;},get renderedSchema(){return loadSchemas19().renderedSchema;}},
"core/cta-band":{...{"name":"core/cta-band","fromVersion":1,"toVersion":2,"transforms":[{"kind":"empty-to-null","path":["heading"]}],"treatments":[]},get savedSchema(){return loadSchemas20().savedSchema;},get renderedSchema(){return loadSchemas20().renderedSchema;}},
"core/cta-with-form":{...{"name":"core/cta-with-form","fromVersion":1,"toVersion":2,"transforms":[{"kind":"empty-to-null","path":["heading"]}],"treatments":[]},get savedSchema(){return loadSchemas21().savedSchema;},get renderedSchema(){return loadSchemas21().renderedSchema;}},
"core/divider":{...{"name":"core/divider","fromVersion":1,"toVersion":2,"transforms":[{"kind":"pack-treatment","path":["variant"]}],"treatments":[{"name":"original","axes":["variant"]}]},get savedSchema(){return loadSchemas22().savedSchema;},get renderedSchema(){return loadSchemas22().renderedSchema;}},
"core/embed":{...{"name":"core/embed","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas23().savedSchema;},get renderedSchema(){return loadSchemas23().renderedSchema;}},
"core/faq":{...{"name":"core/faq","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas24().savedSchema;},get renderedSchema(){return loadSchemas24().renderedSchema;}},
"core/feature-grid":{...{"name":"core/feature-grid","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas25().savedSchema;},get renderedSchema(){return loadSchemas25().renderedSchema;}},
"core/feature-list-alternating":{...{"name":"core/feature-list-alternating","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas26().savedSchema;},get renderedSchema(){return loadSchemas26().renderedSchema;}},
"core/featured-products":{...{"name":"core/featured-products","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas27().savedSchema;},get renderedSchema(){return loadSchemas27().renderedSchema;}},
"core/heading":{...{"name":"core/heading","fromVersion":1,"toVersion":2,"transforms":[{"kind":"empty-to-null","path":["text"]},{"kind":"text-to-richtext","path":["text"],"mode":"plain-inline"}],"treatments":[]},get savedSchema(){return loadSchemas28().savedSchema;},get renderedSchema(){return loadSchemas28().renderedSchema;}},
"core/hero":{...{"name":"core/hero","fromVersion":1,"toVersion":2,"transforms":[{"kind":"empty-to-null","path":["title"]}],"treatments":[]},get savedSchema(){return loadSchemas29().savedSchema;},get renderedSchema(){return loadSchemas29().renderedSchema;}},
"core/hero-split":{...{"name":"core/hero-split","fromVersion":1,"toVersion":2,"transforms":[{"kind":"empty-to-null","path":["title"]},{"kind":"pack-treatment","path":["mediaSide"]}],"treatments":[]},get savedSchema(){return loadSchemas30().savedSchema;},get renderedSchema(){return loadSchemas30().renderedSchema;}},
"core/hero-text-only":{...{"name":"core/hero-text-only","fromVersion":1,"toVersion":2,"transforms":[{"kind":"empty-to-null","path":["title"]},{"kind":"pack-treatment","path":["alignment"]}],"treatments":[]},get savedSchema(){return loadSchemas31().savedSchema;},get renderedSchema(){return loadSchemas31().renderedSchema;}},
"core/image":{...{"name":"core/image","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas32().savedSchema;},get renderedSchema(){return loadSchemas32().renderedSchema;}},
"core/latest-posts":{...{"name":"core/latest-posts","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas33().savedSchema;},get renderedSchema(){return loadSchemas33().renderedSchema;}},
"core/list":{...{"name":"core/list","fromVersion":1,"toVersion":2,"transforms":[{"kind":"text-to-richtext","path":["items","*","text"],"mode":"markdown-inline"}],"treatments":[]},get savedSchema(){return loadSchemas34().savedSchema;},get renderedSchema(){return loadSchemas34().renderedSchema;}},
"core/logo-cloud":{...{"name":"core/logo-cloud","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas35().savedSchema;},get renderedSchema(){return loadSchemas35().renderedSchema;}},
"core/media-text":{...{"name":"core/media-text","fromVersion":1,"toVersion":2,"transforms":[{"kind":"pack-treatment","path":["mediaPosition"]}],"treatments":[]},get savedSchema(){return loadSchemas36().savedSchema;},get renderedSchema(){return loadSchemas36().renderedSchema;}},
"core/newsletter-signup":{...{"name":"core/newsletter-signup","fromVersion":1,"toVersion":2,"transforms":[{"kind":"pack-treatment","path":["variant"]}],"treatments":[]},get savedSchema(){return loadSchemas37().savedSchema;},get renderedSchema(){return loadSchemas37().renderedSchema;}},
"core/paragraph":{...{"name":"core/paragraph","fromVersion":1,"toVersion":2,"transforms":[{"kind":"text-to-richtext","path":["body"],"mode":"markdown-prose"}],"treatments":[]},get savedSchema(){return loadSchemas38().savedSchema;},get renderedSchema(){return loadSchemas38().renderedSchema;}},
"core/pricing-cards":{...{"name":"core/pricing-cards","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas39().savedSchema;},get renderedSchema(){return loadSchemas39().renderedSchema;}},
"core/process-steps":{...{"name":"core/process-steps","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas40().savedSchema;},get renderedSchema(){return loadSchemas40().renderedSchema;}},
"core/quote":{...{"name":"core/quote","fromVersion":1,"toVersion":2,"transforms":[{"kind":"empty-to-null","path":["text"]}],"treatments":[]},get savedSchema(){return loadSchemas41().savedSchema;},get renderedSchema(){return loadSchemas41().renderedSchema;}},
"core/rich-text":{...{"name":"core/rich-text","fromVersion":1,"toVersion":2,"transforms":[{"kind":"text-to-richtext","path":["body"],"mode":"plain-prose"}],"treatments":[]},get savedSchema(){return loadSchemas42().savedSchema;},get renderedSchema(){return loadSchemas42().renderedSchema;}},
"core/roadmap-timeline":{...{"name":"core/roadmap-timeline","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas43().savedSchema;},get renderedSchema(){return loadSchemas43().renderedSchema;}},
"core/social-links":{...{"name":"core/social-links","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas44().savedSchema;},get renderedSchema(){return loadSchemas44().renderedSchema;}},
"core/spacer":{...{"name":"core/spacer","fromVersion":1,"toVersion":2,"transforms":[{"kind":"pack-treatment","path":["size"]}],"treatments":[{"name":"original","axes":["size"]}]},get savedSchema(){return loadSchemas45().savedSchema;},get renderedSchema(){return loadSchemas45().renderedSchema;}},
"core/stats-band":{...{"name":"core/stats-band","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas46().savedSchema;},get renderedSchema(){return loadSchemas46().renderedSchema;}},
"core/tabs":{...{"name":"core/tabs","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas47().savedSchema;},get renderedSchema(){return loadSchemas47().renderedSchema;}},
"core/tag-cloud":{...{"name":"core/tag-cloud","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas48().savedSchema;},get renderedSchema(){return loadSchemas48().renderedSchema;}},
"core/team-grid":{...{"name":"core/team-grid","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas49().savedSchema;},get renderedSchema(){return loadSchemas49().renderedSchema;}},
"core/testimonials":{...{"name":"core/testimonials","fromVersion":1,"toVersion":2,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas50().savedSchema;},get renderedSchema(){return loadSchemas50().renderedSchema;}},
"events/upcoming":{...{"name":"events/upcoming","fromVersion":1,"toVersion":1,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas51().savedSchema;},get renderedSchema(){return loadSchemas51().renderedSchema;}},
"local/sample-alert":{...{"name":"local/sample-alert","fromVersion":1,"toVersion":1,"transforms":[],"treatments":[]},get savedSchema(){return loadSchemas52().savedSchema;},get renderedSchema(){return loadSchemas52().renderedSchema;}},
"reference/field-guide":{...{"name":"reference/field-guide","fromVersion":1,"toVersion":2,"transforms":[{"kind":"pack-treatment","path":["spacing"]},{"kind":"pack-treatment","path":["alignment"]},{"kind":"pack-treatment","path":["ink"]},{"kind":"pack-treatment","path":["font"]}],"treatments":[{"name":"editorial","axes":["spacing","alignment","ink","font"]}]},get savedSchema(){return loadSchemas53().savedSchema;},get renderedSchema(){return loadSchemas53().renderedSchema;}}};
export function legacySanitizeHref(...args){return loadHelpers().legacySanitizeHref(...args); }
export function legacyIsExternalUrl(...args){return loadHelpers().legacyIsExternalUrl(...args); }
export function pageSectionsToBlocks(...args){return loadHelpers().pageSectionsToBlocks(...args); }
