import {useEffect,useState} from "react";
import {useAction,useConvex,useMutation,useQuery} from "convex/react";
import {api} from "@backend/convex/_generated/api";
import type {Id} from "@backend/convex/_generated/dataModel";
import {useAuth} from "@/lib/auth-context";
import {useUnsavedChangesWarning} from "@/hooks/useUnsavedChangesWarning";
import {Button} from "@/components/ui/button";
import {Link} from "@tanstack/react-router";
type Source={id:Id<"socialFeedSources">;provider:"instagram"|"mastodon";handle:string;enabled:boolean;revision:number;status:"pending"|"ready"|"failed"|"disabled";refreshedAt:number|null;expiresAt:number|null};
const input="w-full rounded-md border border-border bg-background px-3 py-2 text-sm text-foreground";
export function SocialFeedManager(){const {can,isLoading,user}=useAuth(),client=useConvex();if(isLoading)return <p role="status">Loading social feeds…</p>;if(!can("manage_options"))return <p role="alert">You do not have permission to manage this website’s social feeds.</p>;return <Manager key={`${client.url}:${user?._id}`}/>;}
function Manager(){
 const inventory=useQuery(api.socialFeeds.sources.list,{}),create=useMutation(api.socialFeeds.sources.create),enable=useMutation(api.socialFeeds.sources.setEnabled),remove=useMutation(api.socialFeeds.sources.remove),refresh=useAction(api.socialFeeds.actions.refreshSource);
 const [handle,setHandle]=useState(""),[active,setActive]=useState(false),[editing,setEditing]=useState<string|null>(null),[editDirty,setEditDirty]=useState(false),[pending,setPending]=useState<string|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[now,setNow]=useState(Date.now);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);
 useUnsavedChangesWarning({isDirty:!!handle||active||editDirty||pending!==null,enabled:true});
 const act=async(key:string,fn:()=>Promise<string>)=>{if(pending)return;setPending(key);setError("");setMessage("");try{setMessage(await fn());}catch(error){setError(error instanceof Error?error.message:"The source could not be updated. Your draft is still here.");}finally{setPending(null);}};
 const selected=inventory?.sources.find(source=>source.id===editing);
 return <div className="space-y-6 p-6" aria-label="Social feed connections">
  <header className="space-y-2"><Link to="/settings/integrations" className="text-sm underline underline-offset-4">← Integrations</Link><h1 className="text-2xl font-semibold">Social feeds</h1><p className="max-w-3xl text-sm text-muted-foreground">Connect a public account for this website’s Social Feed blocks. Active sources refresh automatically; disabling a source withdraws its posts from your pages.</p></header>
  {error&&<p role="alert" className="rounded-md border border-destructive p-3 text-sm text-destructive">{error}</p>}{message&&<p role="status" className="text-sm">{message}</p>}
  <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(20rem,1fr)]">
   <section className="min-w-0 space-y-4" aria-label="Connected social accounts"><h2 className="font-semibold">Connected accounts {inventory&&<span className="font-normal text-muted-foreground">({inventory.sources.length}/20)</span>}</h2>
    {!inventory?<p role="status">Loading connected accounts…</p>:!inventory.sources.length?<p className="rounded-lg border border-dashed border-border p-6 text-sm text-muted-foreground">No connected accounts yet. Add a public Mastodon account to get started.</p>:<ul className="space-y-3">{inventory.sources.map(source=>{
     const status=source.status==="ready"&&source.expiresAt!==null&&source.expiresAt<=now?"pending":source.status;
     return <li key={source.id} className="space-y-3 rounded-lg border border-border p-4" aria-label={`Social account ${source.handle}`}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h3 className="break-all text-sm font-semibold">@{source.handle}</h3><p className="mt-1 text-xs capitalize text-muted-foreground">{source.provider}</p></div><span className="rounded-full bg-muted px-2 py-1 text-xs capitalize">{status==="pending"?"Awaiting refresh":status}</span></div>
      <p className="text-xs text-muted-foreground">{source.refreshedAt?`Last updated ${new Date(source.refreshedAt).toLocaleString()}.`:"No posts fetched yet."}{source.enabled&&" Refreshes are checked every five minutes; cached posts expire after fifteen minutes."}</p>
      {status==="failed"&&<p className="text-sm text-destructive">The account could not be refreshed. Check the handle and approved server, then try again.</p>}
      <div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" disabled={pending!==null||editDirty||!source.enabled} onClick={()=>void act(`refresh:${source.id}`,async()=>{const result=await refresh({sourceId:source.id});return result.status==="refreshed"?"Feed refreshed.":result.status==="skipped"?"Refresh was not started. It may already be running or have been requested in the last minute.":result.status==="superseded"?"The source changed during refresh. Its current settings have been preserved.":"The provider refresh failed. Check the account details and try again.";})}>{pending===`refresh:${source.id}`?"Refreshing…":"Refresh posts"}</Button>
       <Button variant="outline" size="sm" disabled={pending!==null||editDirty} onClick={()=>void act(`enable:${source.id}`,async()=>{await enable({sourceId:source.id,expectedRevision:source.revision,enabled:!source.enabled});return source.enabled?"Source disabled. Its cached posts have been withdrawn.":"Source enabled. Use Refresh posts to load its public posts now.";})}>{source.enabled?"Disable":"Enable"}</Button>
       <Button variant="outline" size="sm" disabled={pending!==null||editDirty} onClick={()=>{setEditing(source.id);setError("");setMessage("");}}>Edit account</Button>
       {!source.enabled&&<Button variant="outline" size="sm" disabled={pending!==null||editDirty} onClick={()=>{if(!window.confirm(`Remove @${source.handle} from this website? Existing Social Feed blocks will remain unavailable until you connect this account again.`))return;void act(`remove:${source.id}`,async()=>{await remove({sourceId:source.id,expectedRevision:source.revision});if(editing===source.id)setEditing(null);return "Source removed from this website.";});}}>Remove connection</Button>}
      </div></li>;
    })}</ul>}
   </section>
   <div className="space-y-5">
    {editing?selected?<AccountEditor key={selected.id} source={selected} changed={setEditDirty} close={()=>{setEditing(null);setEditDirty(false);}}/>:<section className="space-y-3 rounded-lg border border-border p-5"><p role="status">This source is no longer available.</p><Button variant="outline" onClick={()=>{setEditing(null);setEditDirty(false);}}>Close editor</Button></section>:<section className="space-y-4 rounded-lg border border-border p-5" aria-label="Connect a social account"><h2 className="font-semibold">Connect an account</h2>
     <form className="space-y-4" onSubmit={event=>{event.preventDefault();void act("create",async()=>{await create({provider:"mastodon",handle:handle.trim(),enabled:active});setHandle("");setActive(false);return active?"Account connected. Use Refresh posts to load its public posts now.":"Account connected and disabled. Enable it when you’re ready to display its posts.";});}}>
      <fieldset disabled={pending!==null||!inventory||inventory.sources.length>=20} className="space-y-4"><label className="block space-y-1 text-sm">Mastodon handle<input className={input} name="handle" placeholder="name@mastodon.social" value={handle} maxLength={160} required autoCapitalize="none" autoCorrect="off" spellCheck={false} onChange={event=>setHandle(event.target.value)}/></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" className="mt-1" checked={active} onChange={event=>setActive(event.target.checked)}/>Enable automatic refresh and public display</label><Button type="submit" disabled={!handle.trim()}>{pending==="create"?"Connecting…":"Connect account"}</Button></fieldset>
     </form>
    </section>}
    <aside className="space-y-3 rounded-lg border border-border p-5 text-sm"><h2 className="font-semibold">Use this account in a block</h2><p className="text-muted-foreground">Add a Social Feed block, select Mastodon, and enter the connected handle exactly as shown. Each environment needs its own connection.</p><p className="text-muted-foreground">Approved Mastodon servers: {inventory?.approvedMastodonOrigins.join(", ")||"Loading…"}</p><p className="text-muted-foreground">Instagram connections are not available yet.</p></aside>
   </div>
  </div>
 </div>;
}
function AccountEditor({source,changed,close}:{source:Source;changed:(dirty:boolean)=>void;close:()=>void}){
 const update=useMutation(api.socialFeeds.sources.updateAccount),[draft,setDraft]=useState(source.handle),[baseline,setBaseline]=useState(source.handle),[revision,setRevision]=useState(source.revision),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const dirty=draft!==baseline,stale=revision!==source.revision;
 useEffect(()=>changed(dirty||busy),[dirty,busy,changed]);
 return <section className="space-y-4 rounded-lg border border-border p-5" aria-label="Edit social account"><h2 className="font-semibold">Edit account</h2><p className="text-sm text-muted-foreground">Changing the account clears its cached posts. Blocks using the previous handle will need to be updated.</p>{stale&&<div role="status" className="space-y-2 text-sm"><p>This source changed while you were editing. Your draft is still here.</p><Button variant="outline" disabled={busy} onClick={()=>{setDraft(source.handle);setBaseline(source.handle);setRevision(source.revision);setError("");}}>Reload current account</Button></div>}
 <form className="space-y-4" onSubmit={async event=>{event.preventDefault();if(busy||stale||!dirty)return;setBusy(true);setError("");try{await update({sourceId:source.id,expectedRevision:revision,handle:draft.trim()});close();}catch(error){setError(error instanceof Error?error.message:"The account could not be saved. Your draft is still here.");}finally{setBusy(false);}}}><label className="block space-y-1 text-sm">Account handle<input className={input} value={draft} maxLength={160} required disabled={busy} autoCapitalize="none" autoCorrect="off" spellCheck={false} onChange={event=>setDraft(event.target.value)}/></label>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex gap-2"><Button type="submit" disabled={busy||stale||!dirty}>{busy?"Saving…":"Save account"}</Button><Button type="button" variant="outline" disabled={busy} onClick={close}>Cancel editing</Button></div></form></section>;
}
