import { useId, useState } from "react";
import { Button } from "@/components/ui/button";
import type { PrimitiveName } from "@backend/canonical-blocks-foundation/primitiveContracts";
import type { CompositionNode } from "@backend/canonical-blocks-foundation/composition";
import { compositionOutline, containerPrimitives, editComposition, newPrimitive, nodeAt, primitiveNames, primitiveProperties, textPrimitives, visualDefinition, type NodePath, type PropertySchema } from "./composition-editor";
const inputClass = "min-h-11 w-full rounded-md border border-input bg-background px-3 py-2 text-sm";
const label = (name: string) => name.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/^./, c => c.toUpperCase());
function PropertyInput({ schema, value, onChange }: { schema: PropertySchema; value: unknown; onChange: (value: unknown) => void }) {
  const choices = schema.enum ?? (schema.anyOf?.every(item => item.const !== undefined) ? schema.anyOf.map(item => item.const!) : undefined);
  if (choices) return <select aria-label="Property value" className={inputClass} value={value === undefined ? "" : String(value)} onChange={event => onChange(event.target.value === "" ? undefined : choices.find(item => String(item) === event.target.value))}><option value="">Use default</option>{choices.map(item => <option key={String(item)} value={String(item)}>{label(String(item))}</option>)}</select>;
  if (schema.type === "boolean") return <select aria-label="Property value" className={inputClass} value={value === undefined ? "" : String(value)} onChange={event => onChange(event.target.value === "" ? undefined : event.target.value === "true")}><option value="">Use default</option><option value="true">Yes</option><option value="false">No</option></select>;
  if (schema.type === "object" && schema.properties) return <div className="space-y-2 rounded-md border border-border p-3">{Object.entries(schema.properties).map(([key, field]) => <div key={key} role="group" aria-label={label(key)}><span className="text-xs font-medium">{label(key)}</span><PropertyInput schema={field} value={(value as Record<string, unknown> | undefined)?.[key]} onChange={next => { const updated = { ...(value as Record<string, unknown>) };if (next === undefined) delete updated[key];else updated[key] = next;onChange(Object.keys(updated).length ? updated : undefined); }} /></div>)}</div>;
  if (schema.type === "string" || schema.type === "number" || schema.type === "integer") return <input aria-label="Property value" className={inputClass} type={schema.type === "string" ? "text" : "number"} min={schema.minimum} max={schema.maximum} step={schema.type === "integer" ? 1 : undefined} maxLength={schema.maxLength ?? 20000} value={typeof value === "string" || typeof value === "number" ? value : ""} placeholder="Use default" onChange={event => onChange(event.target.value === "" ? undefined : schema.type === "string" ? event.target.value : Number(event.target.value))} />;
  return <p className="text-xs text-muted-foreground">Bind this property to a content field, or edit its structured value in advanced source.</p>;
}
export function CompositionDesigner({ source, onChange, disabled, initialTreatment = "default" }: { source: string; onChange: (value: string) => void; disabled: boolean; initialTreatment?: string }) {
  const [path, setPath] = useState<NodePath>([]), [treatment, setTreatment] = useState(initialTreatment), [adding, setAdding] = useState<PrimitiveName>("Text"), [error, setError] = useState("");
  const id = useId();
  let value;try { value = visualDefinition(source); } catch { return <p role="status" className="text-sm text-muted-foreground">The composition outline will return once the advanced source contains a valid primitive tree.</p>; }
  const activeTreatment = treatment !== "default" && !value.packTreatments?.[treatment] ? "default" : treatment;
  const tree = activeTreatment === "default" ? value.composition.root : value.packTreatments![activeTreatment].root;
  let selected: CompositionNode;let selectedPath = path;try { selected = nodeAt(tree, path); } catch { selected = tree;selectedPath = []; }
  const change = (operation: (node: CompositionNode, root: CompositionNode) => CompositionNode | void) => {
    if (disabled) return;
    try { const next = editComposition(source, activeTreatment, root => operation(nodeAt(root, selectedPath), root) ?? root);onChange(next);setError(""); }
    catch (issue) { setError(issue instanceof Error ? issue.message : "Could not update the composition."); }
  };
  const bindings = selected.bind && typeof selected.bind === "object" ? selected.bind : {};
  const properties = primitiveProperties(selected.el).properties ?? {};
  const setProp = (key: string, next: unknown) => change(node => { const props = { ...node.props };if (next === undefined) delete props[key];else props[key] = next;node.props = props; });
  return <fieldset disabled={disabled} className="space-y-4 rounded-lg border border-border bg-card p-4" aria-label="Composition designer"><legend className="px-2 font-semibold">Composition</legend>
    <p className="text-sm text-muted-foreground">Arrange elements and adjust their appearance. Your template supplies the fonts, colors and spacing.</p>
    {Object.keys(value.packTreatments ?? {}).length > 0 && <label className="block text-sm" htmlFor={id + "-treatment"}>Composition to edit<select id={id + "-treatment"} className={inputClass} value={activeTreatment} onChange={event => { setTreatment(event.target.value);setPath([]); }}><option value="default">Default composition</option>{Object.keys(value.packTreatments!).map(key => <option key={key}>{key}</option>)}</select></label>}
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
    <div className="grid gap-4 md:grid-cols-[minmax(10rem,0.65fr)_minmax(0,1fr)]"><nav aria-label="Composition outline" className="space-y-1">{compositionOutline(tree).map(row => <button type="button" key={row.path.join(".")} aria-current={row.path.join(".") === selectedPath.join(".") ? "true" : undefined} onClick={() => setPath(row.path)} className="flex min-h-11 w-full items-center rounded-md px-3 text-left text-sm hover:bg-muted aria-[current=true]:bg-muted" style={{ paddingInlineStart: 12 + row.path.length * 14 }}>{row.node.el}{row.node.each && <span className="ml-2 text-xs text-muted-foreground">Repeating</span>}</button>)}</nav>
    <div className="min-w-0 space-y-4" key={activeTreatment + "/" + selectedPath.join(".")}><h3 className="font-medium">{selected.el} settings</h3>
    {textPrimitives.has(selected.el) && <TextBinding value={typeof selected.bind === "string" ? selected.bind : ""} fields={value.spec.fields.filter(field => ["text", "number"].includes(field.type)).map(field => field.id)} onChange={bind => change(node => { node.bind = bind; })} />}
    <div className="space-y-3">{Object.entries(properties).filter(([key]) => key !== "blockId").map(([key, schema]) => <div key={key} role="group" aria-label={label(key)} className="space-y-2"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-sm font-medium">{label(key)}</span>{!textPrimitives.has(selected.el) && <label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={Object.hasOwn(bindings, key)} onChange={event => { const bound = event.target.checked;change(node => { const next = { ...(typeof node.bind === "object" ? node.bind : {}) };if (bound) { next[key] = "attrs." + key;const props = { ...node.props };delete props[key];node.props = props; }else delete next[key];node.bind = next; }); }} />Bind {label(key)}</label>}</div>{Object.hasOwn(bindings, key) ? <input aria-label={`${label(key)} binding`} className={inputClass} maxLength={1000} value={bindings[key]} onChange={event => { const text = event.target.value;change(node => { node.bind = { ...(typeof node.bind === "object" ? node.bind : {}), [key]: text }; }); }} /> : <PropertyInput schema={schema} value={selected.props?.[key]} onChange={next => setProp(key, next)} />}</div>)}</div>
    <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" size="sm" onClick={() => { change((node, root) => { const wrapper: CompositionNode = { el: "Stack", props: { gap: "md" }, children: [node] };if (!selectedPath.length) return wrapper;nodeAt(root, selectedPath.slice(0,-1)).children![selectedPath.at(-1)!] = wrapper; }); }}>Wrap in stack</Button>{selectedPath.length > 0 && <><Button type="button" variant="outline" size="sm" disabled={selectedPath.at(-1) === 0} onClick={() => { const index = selectedPath.at(-1)!;change((_node, root) => { const children = nodeAt(root, selectedPath.slice(0,-1)).children!;[children[index-1], children[index]] = [children[index], children[index-1]]; });setPath([...selectedPath.slice(0,-1), index-1]); }}>Move up</Button><Button type="button" variant="outline" size="sm" disabled={selectedPath.at(-1) === nodeAt(tree,selectedPath.slice(0,-1)).children!.length-1} onClick={() => { const index = selectedPath.at(-1)!;change((_node, root) => { const children = nodeAt(root, selectedPath.slice(0,-1)).children!;[children[index+1], children[index]] = [children[index], children[index+1]]; });setPath([...selectedPath.slice(0,-1), index+1]); }}>Move down</Button><Button type="button" variant="outline" size="sm" onClick={() => { change((_node, root) => { nodeAt(root,selectedPath.slice(0,-1)).children!.splice(selectedPath.at(-1)!,1); });setPath(selectedPath.slice(0,-1)); }}>Remove element</Button></>}</div>
    {containerPrimitives.has(selected.el) && <div className="space-y-2 rounded-md bg-muted/40 p-3"><label htmlFor={id + "-primitive"} className="text-sm font-medium">Add an element</label><select id={id + "-primitive"} value={adding} onChange={event => setAdding(event.target.value as PrimitiveName)} className={inputClass}>{primitiveNames.filter(name => name !== "Slot" || value.spec.supports.children).map(name => <option key={name}>{name}</option>)}</select><Button type="button" variant="outline" onClick={() => change(node => { node.children = [...node.children ?? [], newPrimitive(adding)]; })}>Add child element</Button></div>}
    <details><summary className="cursor-pointer text-sm font-medium">Conditions and repeated content</summary><div className="mt-3 space-y-3">{["if", ...(containerPrimitives.has(selected.el) ? ["each", "as"] : [])].map(key => <label key={key} className="block text-sm">{key === "if" ? "Show when" : key === "each" ? "Repeat for each" : "Item name"}<input className={inputClass} maxLength={1000} value={selected[key as "if" | "each" | "as"] ?? ""} onChange={event => { const text = event.target.value;change(node => { if (text) node[key as "if" | "each" | "as"] = text;else delete node[key as "if" | "each" | "as"]; }); }} /></label>)}</div></details>
    </div></div>
  </fieldset>;
}
function TextBinding({ value, fields, onChange }: { value: string; fields: string[]; onChange: (value: string) => void }) {
  const id = useId();let literal: string | null = null;try { const parsed = JSON.parse(value);if (typeof parsed === "string") literal = parsed; } catch { /* Existing expressions remain exact. */ }
  const mode = literal !== null ? "text" : fields.some(field => value === "attrs." + field) ? value : "expression";
  return <div className="space-y-2"><label htmlFor={id + "-mode"} className="text-sm font-medium">Text source</label><select id={id + "-mode"} value={mode} className={inputClass} onChange={event => onChange(event.target.value === "text" ? JSON.stringify("Your text") : event.target.value === "expression" ? "''" : event.target.value)}><option value="text">Custom text</option>{fields.map(field => <option key={field} value={"attrs." + field}>{label(field)} field</option>)}<option value="expression">Expression</option></select>{mode === "text" ? <label className="block text-sm">Element text<input className={inputClass} maxLength={20000} value={literal!} onChange={event => onChange(JSON.stringify(event.target.value))} /></label> : mode === "expression" ? <label className="block text-sm">Text expression<input className={inputClass} maxLength={1000} value={value} onChange={event => onChange(event.target.value)} /></label> : <p className="text-xs text-muted-foreground">This text stays editable in each page that uses the block.</p>}</div>;
}
