import assert from'node:assert/strict';import{mock}from'bun:test';import{JSDOM}from'jsdom';
const dom=new JSDOM('<!doctype html><div id="root"></div>',{url:'https://example.org/',pretendToBeVisual:true});for(const name of ['window','document','HTMLElement','Element','Node','navigator','HTMLInputElement','ShadowRoot','MutationObserver'])Object.defineProperty(globalThis,name,{value:dom.window[name],configurable:true});Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true,getComputedStyle:dom.window.getComputedStyle.bind(dom.window),requestAnimationFrame:dom.window.requestAnimationFrame.bind(dom.window),cancelAnimationFrame:dom.window.cancelAnimationFrame.bind(dom.window),ResizeObserver:class{observe(){}unobserve(){}disconnect(){}}});
const{createElement,act}=await import('react');const{createRoot}=await import('react-dom/client');let config={userMenu:{loggedInDisplay:'avatar-dropdown',dropdownPreset:'dashboard-profile-logout'}},menu=null,signouts=0;const user={firstName:'Casey',lastName:'Reader',displayName:'Casey Reader',email:'casey@example.invalid',primaryEmailAddress:{emailAddress:'casey@example.invalid'},imageUrl:''};
mock.module('@/lib/auth/clerk',()=>({useUser:()=>({user}),useClerk:()=>({signOut:()=>{signouts++}})}));mock.module('@/hooks/useCurrentUser',()=>({useCurrentUser:()=>({user})}));mock.module('@/hooks/layout/useHeaderConfig',()=>({useHeaderConfig:()=>config}));mock.module('@/hooks/useDashboardConfig',()=>({useDashboardConfig:()=>({config:{profileLocation:'dashboard-profile'}}),useDashboardPath:()=>({basePath:'/members',to:(p='')=>'/members'+p})}));mock.module('@/dashboard/shell/useDashboardMenu',()=>({useDashboardMenu:()=>({nav:menu})}));mock.module('@tanstack/react-router',()=>({Link:({to,children,...rest})=>createElement('a',{href:to,...rest},children)}));
const{UserMenu}=await import('./UserMenu.tsx');const{ProfileMenu}=await import('../../dashboard/shell/ProfileMenu.tsx');const root=createRoot(document.querySelector('#root'));let checks=0;
for(const display of ['avatar-dropdown','name-dropdown','avatar-only'])for(const preset of ['dashboard-profile-logout','profile-settings-logout','custom']){
 config={userMenu:{loggedInDisplay:display,dropdownPreset:preset}};await act(async()=>root.render(createElement(UserMenu)));const trigger=document.querySelector('[aria-label="Account menu"]');assert.equal(trigger.textContent.includes('Casey Reader'),display!=='avatar-only');assert.equal(trigger.textContent.includes('CR'),display!=='name-dropdown');await act(async()=>trigger.click());const links=[...document.querySelectorAll('[role="menuitem"][href]')].map(e=>e.getAttribute('href'));assert.deepEqual(links,preset==='profile-settings-logout'?['/members/profile','/members/settings']:['/members','/members/profile','/members/settings']);await act(async()=>[...document.querySelectorAll('[role="menuitem"]')].find(e=>e.textContent.includes('Log Out')).click());checks++;
}
const link=(id,label,href,children=[])=>({id,kind:'link',label,href,children,exact:false,external:false});menu=[{id:'h',kind:'heading',label:'Member tools',href:'',exact:false,external:false,children:[link('p','Member profile','/members/profile',[link('s','Member settings','/members/settings')])]}];
for(const Component of [UserMenu,ProfileMenu]){await act(async()=>root.render(createElement(Component,{items:menu,badges:{}})));await act(async()=>document.querySelector('[aria-label="Account menu"]').click());const labels=[...document.querySelectorAll('[role="menuitem"][href]')].map(e=>e.textContent);assert.deepEqual(labels,['Member profile','Member settings'],'assigned descendants remain reachable in each account menu');await act(async()=>[...document.querySelectorAll('[role="menuitem"]')].find(e=>/Log Out|Sign out/.test(e.textContent)).click());checks++;}
assert.equal(signouts,11);await act(async()=>root.unmount());dom.window.close();console.log(JSON.stringify({checks}));
