import {mock} from 'bun:test';import assert from 'node:assert/strict';import {createElement,act} from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {createRoot} from 'react-dom/client';import {JSDOM} from 'jsdom';import {getFunctionName} from 'convex/server';
let offer={name:'Journal letters',consentText:'Send me monthly letters.',privacyUrl:'/privacy',digest:'a'.repeat(64)},submitted=[],undos=[];
const convex=await import('convex/react');mock.module('convex/react',()=>({...convex,useQuery:(ref)=>getFunctionName(ref)==='audiences/footer:offer'?offer:undefined,useMutation:ref=>async args=>{const name=getFunctionName(ref);if(name==='audiences/footer:subscribe'){submitted.push(args);return {ok:true};}if(name==='audiences/footer:unsubscribe'){undos.push(args);return null;}throw Error('Wrong mutation '+name);}}));
mock.module('@/hooks/layout/useSiteIdentity',()=>({useSiteIdentity:()=>({title:'Newsletter study'})}));mock.module('@/hooks/layout/useFooterConfig',()=>({useFooterConfig:()=>undefined}));mock.module('@/hooks/layout/useMenuForLocation',()=>({useMenuForLocation:()=>undefined}));mock.module('@/components/layout/SocialLinks',()=>({SocialLinks:()=>null}));
const router=await import('@tanstack/react-router');mock.module('@tanstack/react-router',()=>({...router,Link:({to,children})=>createElement('a',{href:to},children)}));
const {FOOTER_DEFAULTS}=await import('@/templates/sdk/chromeDefinitions');const cell={type:'newsletter',audienceId:'selected-list',heading:'Join our letters',subtext:'Once a month.',buttonText:'Join'};
for(const pack of ['core','journal','depot','aster-house']){const {default:Surface}=await import(`../../templates/packs/${pack}/surfaces/chrome.footer.tsx`);const config=structuredClone(FOOTER_DEFAULTS);config.rows=[{id:'r',columns:[{id:'c',cell}],padding:'normal',background:'default',container:'default'}];const html=renderToStaticMarkup(createElement(Surface,{data:{variant:'full',siteIdentity:{title:'Newsletter study'},footerConfig:config}}));assert(html.includes('Send me monthly letters.'));assert(html.includes('href="/privacy"'));assert(html.includes('type="checkbox"'));}
const dom=new JSDOM('<html><body><div id="app"></div></body></html>',{url:'https://example.test',pretendToBeVisual:true});for(const name of ['window','document','HTMLElement','Element','Node','navigator','getComputedStyle','requestAnimationFrame','cancelAnimationFrame'])Object.defineProperty(globalThis,name,{configurable:true,value:name==='getComputedStyle'?dom.window.getComputedStyle.bind(dom.window):dom.window[name]});globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const {FooterAudienceNewsletter}=await import('./FooterAudienceNewsletter');const root=createRoot(document.getElementById('app'));await act(async()=>root.render(createElement(FooterAudienceNewsletter,{cell})));
assert(document.querySelector('button[type=submit]').disabled);await act(async()=>document.querySelector('input[type=checkbox]').click());assert(!document.querySelector('button[type=submit]').disabled);
// JSDOM transport check; actual email entry and validation are tested in browser acceptance.
const form=document.querySelector('form');form.reportValidity=()=>true;await act(async()=>form.dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));assert.equal(submitted.length,1);assert.equal(submitted[0].audienceId,cell.audienceId);assert.equal(submitted[0].offerDigest,offer.digest);assert.equal(submitted[0].consent,true);assert.match(submitted[0].secret,/^[a-f0-9]{64}$/);assert(document.body.textContent.includes('Request received.'));
await act(async()=>[...document.querySelectorAll('button')].find(b=>b.textContent==='Undo this signup').click());assert.equal(undos[0].secret,submitted[0].secret);assert(document.body.textContent.includes('Opt-out request recorded.'));
offer=null;await act(async()=>root.render(createElement(FooterAudienceNewsletter,{cell})));assert.equal(document.querySelector('form'),null);assert(document.body.textContent.includes('not available'));
offer=undefined;await act(async()=>root.render(createElement(FooterAudienceNewsletter,{cell})));assert(document.body.textContent.includes('Preparing signup'));await act(async()=>root.unmount());dom.window.close();console.log(JSON.stringify({packs:4,consentRequired:true,selectedAudienceSent:true,optOut:true,unavailableAndLoading:true}));
