/** Precompute finite Convex validators without rebuilding Zod JSON Schema in each isolate. */
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import * as authoritative from '../../ConvexPress-Admin/packages/backend/canonical-blocks-foundation/transport-validator-source';
const source=fileURLToPath(new URL('../../ConvexPress-Admin/packages/backend/canonical-blocks-foundation/transport-validator-source.ts',import.meta.url));
const output=fileURLToPath(new URL('../../ConvexPress-Admin/packages/backend/convex/canonicalDocuments/validators.ts',import.meta.url));
type Shape={type:string;value?:unknown;keys?:Shape;values?:{fieldType:Shape;optional:boolean};tableName?:string};
function emit(shape:Shape):string{
 switch(shape.type){
  case 'string':case 'number':case 'boolean':case 'null':case 'any':case 'bytes':case 'int64':return `v.${shape.type==='int64'?'int64':shape.type}()`;
  case 'literal':return `v.literal(${JSON.stringify(shape.value)})`;
  case 'id':return `v.id(${JSON.stringify(shape.tableName)})`;
  case 'array':return `v.array(${emit(shape.value as Shape)})`;
  case 'union':return `v.union(${(shape.value as Shape[]).map(emit).join(',')})`;
  case 'record':if(shape.values!.optional)throw Error('Optional record values are unsupported');return `v.record(${emit(shape.keys!)},${emit(shape.values!.fieldType)})`;
  case 'object':return `v.object({${Object.entries(shape.value as Record<string,{fieldType:Shape;optional:boolean}>).map(([key,field])=>`${JSON.stringify(key)}:${field.optional?`v.optional(${emit(field.fieldType)})`:emit(field.fieldType)}`).join(',')}})`;
  default:throw Error(`Unsupported transport validator: ${shape.type}`);
 }
}
const types=new Map([...readFileSync(source,'utf8').matchAll(/export const (\w+):\s*Validator<\s*(\w+)/g)].map(match=>[match[1],match[2]]));
const entries=Object.entries(authoritative).sort(([a],[b])=>a.localeCompare(b));
if(entries.length!==types.size)throw Error('Every transport validator needs an explicit DTO type');
const storageOutput=fileURLToPath(new URL('../../ConvexPress-Admin/packages/backend/convex/canonicalDocuments/definitionStorage.ts',import.meta.url));
const storageGenerated=[
 '// Generated by sync:blocks:transport-validators. Do not edit.',
 '// Schema leaf: no document DTO imports, which can depend on the generated data model.',
 'import {v} from "convex/values";',
 `export const composedRegistrySnapshotValidator=${emit(authoritative.composedRegistrySnapshotValidator.json as Shape)};`,
 '',
].join('\n');
const documentTypes=[...new Set(types.values())].filter(type=>!['CanonicalMigrationDto','PublicCanonicalDocument','ComposedRegistrySnapshot'].includes(type)).sort();
const generated=[
 '// Generated by sync:blocks:transport-validators. Do not edit. Full Zod refinements remain enforced by the canonical service.',
 'import {v,type Validator} from "convex/values";',
 `import type {${documentTypes.join(',')}} from "./foundation/documentContracts";`,
 'import type {CanonicalMigrationDto} from "./foundation/migrationContracts";',
 'import type {PublicCanonicalDocument} from "./foundation/publicDocumentContracts";',
 'export {composedRegistrySnapshotValidator} from "./definitionStorage";',
 ...entries.filter(([name])=>name!=='composedRegistrySnapshotValidator').map(([name,validator])=>
   `export const ${name}:Validator<${types.get(name)},"required",string>=${emit(validator.json as Shape)};`),
 '',
].join('\n');
if(process.argv.includes('--check')){if(readFileSync(output,'utf8')!==generated)throw Error('Stale canonical transport validators. Run bun run sync:blocks:transport-validators.');}
else writeFileSync(output,generated);
if(process.argv.includes('--check')){if(readFileSync(storageOutput,'utf8')!==storageGenerated)throw Error('Stale canonical definition storage validator.');}
else writeFileSync(storageOutput,storageGenerated);
// Compare actual Convex JSON shapes, not just source text or TypeScript casts.
const runtime=await import(output);
for(const [name,validator] of entries)if(JSON.stringify(runtime[name].json)!==JSON.stringify(validator.json))throw Error(`Transport shape drift: ${name}`);
console.log(`Canonical transport validators ${process.argv.includes('--check')?'verified':'generated'}: ${entries.length} exact shapes; ${generated.length} source bytes; no runtime Zod-to-JSON conversion.`);
