import { dependencyFields, anchorFields, searchableFields, authoringFieldRules } from "./spec-runtime.mjs";
export { dependencyFields, anchorFields } from "./spec-runtime.mjs";
import { canonicalStorageValidatorSource } from "./storage.mjs";
import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, rename, lstat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { discoverBlocks } from "./discovery.mjs";
import { attrsSchema, blockSpecJsonSchema, zodObject, fieldTypeNames } from "./schema.mjs";

const q = JSON.stringify;
const header = "// Generated by root sync:blocks. Do not edit. Staged contracts; runtime activation is separate.\n";
export function canonicalJson(value) {
  if (Array.isArray(value)) return value.map(canonicalJson);
  if (value && typeof value === "object") return Object.fromEntries(Object.keys(value).sort().map(key => [key, canonicalJson(value[key])]));
  return value;
}
const json = value => JSON.stringify(canonicalJson(value), null, 2) + "\n";
const hash = value => createHash("sha256").update(value).digest("hex");
const convexObject = fields => `v.object({${fields.map(field => `${q(field.id)}:${convexField(field)}`).join(",")}})`;
export function convexField(field) {
  let code;
  switch (field.type) {
    case "number": code = "v.number()"; break;
    case "boolean": code = "v.boolean()"; break;
    case "select": code = field.options.length === 1 ? `v.literal(${q(field.options[0])})` : `v.union(${field.options.map(value => `v.literal(${q(value)})`).join(",")})`; break;
    case "color-role": code = 'v.union(v.literal("primary"),v.literal("accent"),v.literal("muted"))'; break;
    case "object": code = convexObject(field.fields); break;
    case "repeater": code = `v.array(${field.item ? convexField(field.item) : convexObject(field.fields)})`; break;
    case "link": code = field.storage === "href" ? "v.string()" : 'v.object({label:v.string(),href:v.string(),newTab:v.optional(v.boolean())})'; break;
    case "media": code = field.storage === "id" ? "v.string()" : 'v.object({id:v.string(),alt:v.optional(v.string()),focalPoint:v.optional(v.object({x:v.number(),y:v.number()}))})'; break;
    case "richtext": {
      const marks = ["bold", "italic", "strike", "underline", "code"].map(type => `v.object({type:v.literal(${q(type)})})`);
      marks.push('v.object({type:v.literal("link"),attrs:v.object({href:v.string(),target:v.optional(v.union(v.literal("_blank"),v.literal("_self")))})})');
      code = `v.object({type:v.literal("doc"),content:v.array(v.object({type:v.literal("paragraph"),content:v.optional(v.array(v.union(v.object({type:v.literal("text"),text:v.string(),marks:v.optional(v.array(v.union(${marks.join(",")})))}),v.object({type:v.literal("hardBreak")}))))}))})`;
      break;
    }
    case "text": case "date": case "icon": case "reference": case "menu": case "form": code = "v.string()"; break;
    default: throw new Error(`Unknown field type ${field.type}`);
  }
  if (field.nullable) code = `v.union(${code},v.null())`;
  if (!field.required || Object.prototype.hasOwnProperty.call(field, "default")) code = `v.optional(${code})`;
  return code;
}
export async function generateArtifacts(discovered) {
  const { blocks, packs } = discovered;
  const entries = blocks.map(({ spec }) => `${q(spec.name)}:once(()=>${zodObject(spec.fields, spec.constraints)})`);
  const treatmentEntries = blocks.map(({ spec }) => {
    const variants = (spec.treatments ?? []).map(treatment => `z.object({name:z.literal(${q(treatment.name)}),values:z.object({${treatment.axes.map(axis => `${q(axis.id)}:${axis.type === "select" ? `z.enum(${q(axis.options)})` : `z.number().int().min(${axis.min}).max(${axis.max})`}`).join(",")}}).strict()}).strict()`);
    return `${q(spec.name)}:once(()=>${variants.length === 0 ? "z.never()" : variants.length === 1 ? variants[0] : `z.union([${variants.join(",")}])`})`;
  });
  const getters = (factory) => blocks.map(({spec})=>`get ${q(spec.name)}(){return ${factory}[${q(spec.name)}]();}`).join(",\n");
  const treatmentSchemas = `const treatmentFactories = {${treatmentEntries.join(",\n")}} as const;\nexport const blockTreatmentSchemas = {${getters("treatmentFactories")}} as const;\nexport function validateBlockTreatment(name: string, treatment: unknown) { if (!Object.prototype.hasOwnProperty.call(blockTreatmentSchemas,name)) throw Error("Unknown block treatment"); return blockTreatmentSchemas[name as keyof typeof blockTreatmentSchemas].parse(treatment); }\n`;
  const schemas = header + 'import { z } from "zod";\nimport { createRichTextSchema, safeLinkSchema, dateSchema, formattedTextSchema, constrainObject } from "./field-runtime.mjs";\n' +
    '// Construct only schemas used by this document; preserve object-shaped validators and stable identity.\nfunction once<T>(create:()=>T):()=>T { let ready=false; let value!:T; return ()=>{ if(!ready){value=create();ready=true;} return value; }; }\n' +
    `const schemaFactories = {\n${entries.join(",\n")}\n} as const;\nexport const blockSchemas = {${getters("schemaFactories")}} as const;\n` +
    'export type BlockName = keyof typeof blockSchemas;\n' +
    'export function validateBlockAttrs(name: string, attrs: unknown) {\n  if (!Object.prototype.hasOwnProperty.call(blockSchemas, name)) throw new Error(`Unknown block name ${name}`);\n  return blockSchemas[name as BlockName].parse(attrs);\n}\n';
  const authoringSchemas = '\nimport { validateAuthoringActions, validateAuthoringFields, type AuthoringAction, type AuthoringFieldRule } from "./spec-runtime.mjs";\n' +
    `const authoringActions: Readonly<Record<string, readonly AuthoringAction[]>> = ${json(Object.fromEntries(blocks.filter(({spec}) => spec.authoringActions?.length).map(({spec}) => [spec.name, spec.authoringActions])))};\n` +
    `const fieldRules: Readonly<Record<string, readonly AuthoringFieldRule[]>> = ${json(Object.fromEntries(blocks.map(({spec}) => [spec.name, authoringFieldRules(spec.fields)]).filter(([, choices]) => choices.length)))};\n` +
    'export function validateBlockAuthoringAttrs(name: string, attrs: unknown) { return validateAuthoringFields(z, validateAuthoringActions(z, validateBlockAttrs(name, attrs), authoringActions[name]), fieldRules[name]); }\n';
  const fieldAccess = `
type FieldValidator = { unwrap?: () => FieldValidator; shape?: Record<string, FieldValidator>; element?: FieldValidator; parse: (value: unknown) => unknown };
export function validateBlockField(name: string, path: readonly (string | number)[], value: unknown) {
  if (!Object.prototype.hasOwnProperty.call(blockSchemas, name) || !path.length) throw new Error("Unknown block field");
  let schema = blockSchemas[name as BlockName] as unknown as FieldValidator;
  for (const part of path) {
    let depth = 0;
    while (!schema.shape && !schema.element && schema.unwrap && depth++ < 10) schema = schema.unwrap();
    if (typeof part === "number" && Number.isSafeInteger(part) && part >= 0 && schema.element) schema = schema.element;
    else if (typeof part === "string" && schema.shape && Object.prototype.hasOwnProperty.call(schema.shape, part)) schema = schema.shape[part];
    else throw new Error("Unknown block field path");
  }
  return schema.parse(value);
}
`;
  const types = header + 'import type { z } from "zod";\nimport type { blockSchemas, blockTreatmentSchemas } from "./schemas";\nimport type { CanonicalEnvelope } from "./instance-runtime.mjs";\nexport type { CanonicalLayout, CanonicalVisibility, CanonicalLock } from "./instance-runtime.mjs";\nexport type BlockName = keyof typeof blockSchemas;\nexport type AttrsByName = { [Name in BlockName]: z.output<(typeof blockSchemas)[Name]> };\nexport type InputAttrsByName = { [Name in BlockName]: z.input<(typeof blockSchemas)[Name]> };\nexport type TreatmentByName = { [Name in BlockName]: z.output<(typeof blockTreatmentSchemas)[Name]> };\nexport type CanonicalBlockInstance = { [Name in BlockName]: Omit<CanonicalEnvelope, "name" | "attrs" | "children" | "treatment"> & { name: Name; attrs: AttrsByName[Name]; treatment?: TreatmentByName[Name]; children?: CanonicalBlockInstance[] } }[BlockName];\nexport type CanonicalTree = CanonicalBlockInstance[];\n';
  const convex = header + 'import { v } from "convex/values";\nexport { validateBlockAttrs } from "./schemas";\n// Convex checks shape; always call validateBlockAttrs for bounds, URLs and defaults before saving.\n' +
    `export const blockAttrsValidators = {\n${blocks.map(({ spec }) => `${q(spec.name)}:${convexObject(spec.fields)}`).join(",\n")}\n} as const;\n`;
  const catalog = blocks.map(({ spec, source, provenance }) => ({ name: spec.name, version: spec.version, title: spec.title, description: spec.description, category: spec.category, role: spec.role, keywords: spec.keywords, ai: spec.ai, fields: spec.fields, constraints: spec.constraints ?? [], ...(spec.authoringActions ? { authoringActions: spec.authoringActions } : {}), supports: spec.supports, treatments: spec.treatments ?? [], examples: spec.examples.map(example => attrsSchema(spec.fields, spec.constraints).parse(example)), data: spec.data, requires: spec.requires ?? { plugins: [], capabilities: [] }, source, provenance }));
  const metadata = Object.fromEntries(blocks.map(({ spec, source, provenance, hasRenderer }) => [spec.name, { libraryRenderer: hasRenderer ? source.replace(/block.json$/, "render.tsx") : null, version: spec.version, fields: dependencyFields(spec.fields), data: spec.data, requires: spec.requires ?? { plugins: [], capabilities: [] }, supportsChildren: spec.supports.children, supports: spec.supports, treatments: spec.treatments ?? [], source, provenance }]));
  const anchors = Object.fromEntries(blocks.map(({ spec }) => [spec.name, anchorFields(spec.fields)]));
  const searchText = Object.fromEntries(blocks.map(({ spec }) => [spec.name, searchableFields(spec.fields, spec.searchText ?? [])]));
  const editors = Object.fromEntries(blocks.map(({ spec }) => [spec.name, { version: spec.version, requires: spec.requires ?? { plugins: [], capabilities: [] }, fields: spec.fields, constraints: spec.constraints ?? [], preview: spec.preview, category: spec.category, title: spec.title, role: spec.role, supports: spec.supports }]));
  const coverage = { phase: "schema-foundation", packs, blocks: blocks.map(({ spec, source, provenance, hasRenderer }) => ({ name: spec.name, title: spec.title, category: spec.category, role: spec.role, version: spec.version, examples: spec.examples.map(example => attrsSchema(spec.fields, spec.constraints).parse(example)), source, provenance, requires: spec.requires ?? { plugins: [], capabilities: [] }, libraryRenderer: hasRenderer ? source.replace(/block.json$/, "render.tsx") : null, treatments: packs.map(pack => ({ packId: pack.id, status: "not-verified", screenshot: null })) })) };
  const runtime = await readFile(new URL("./field-runtime.mjs", import.meta.url), "utf8");
  const files = {
    "renderer-coverage.ts": header + 'export interface RendererCoverage { id: string; title: string; blocks: readonly { name: string; title: string; renderer: "owned" | "library" | "missing"; hidden: boolean }[] }\n' + `export const rendererCoverage: readonly RendererCoverage[] = ${json(packs.map(pack => ({ id: pack.id, title: pack.design?.name ?? pack.id, blocks: blocks.map(({spec,hasRenderer}) => ({ name: spec.name, title: spec.title, renderer: Object.hasOwn(pack.renderers ?? {}, spec.name) ? "owned" : hasRenderer ? "library" : "missing", hidden: (pack.hidden ?? []).includes(spec.name) })) })))};\n`,
    "promotions.ts": header + 'export interface InstalledPromotion { sourceName: string; sourceVersion: number; sourceDigest: string; packageDigest: string; specDigest: string; rendererDigest: string }\n' + `export const installedPromotions: Readonly<Record<string, InstalledPromotion>> = ${json(Object.fromEntries(blocks.filter(block => block.promotion).map(block => [block.spec.name, block.promotion])))};\n`,
    "pack-designs.ts": header + 'export interface PackDesign { id: string; name: string; version: string; description: string; design: string; revision: string }\n' + `export const packDesigns: Readonly<Record<string, PackDesign>> = ${json(Object.fromEntries(packs.filter(pack => pack.design).map(pack => [pack.id, pack.design])))};\n`,
    "patterns.ts": header + 'import type { CanonicalTree } from "./types";\nexport interface TemplatePattern { id: string; packId: string; title: string; description: string; category: "intro" | "story" | "features" | "collection" | "contact"; blocks: CanonicalTree }\n' + `export const templatePatterns: readonly TemplatePattern[] = ${json(packs.flatMap(pack => pack.patterns ?? []))};\n`,
    "storage.ts": header + 'import { v } from "convex/values";\n// Shape only. Every authoring write must also call validateCanonicalTree.\nexport const canonicalStoredNodeValidator = ' + canonicalStorageValidatorSource() + ';\nexport const canonicalStoredTreeValidator = v.array(canonicalStoredNodeValidator);\n',
    "ai-catalog.ts": header + 'export interface AiCatalogEntry { name: string; version: number; title: string; description: string; ai: { useFor: string; avoid: string }; supports: { children: boolean; styles: boolean; layout: string[]; anchor: boolean; visibility: boolean }; requires: { plugins: string[]; capabilities: string[] }; example: Record<string, unknown> }\n' + `export const aiCatalogRevision = ${q(hash(schemas + runtime + json(blocks.map(({spec}) => spec)) + json(packs)))};\nexport const aiCatalog: readonly AiCatalogEntry[] = ${json(catalog.map(({name, version, title, description, ai, supports, requires, examples}) => ({name, version, title, description, ai, supports, requires, example:examples[0]})))};\n`,
    "schemas.ts": schemas + authoringSchemas + treatmentSchemas + fieldAccess, "types.ts": types, "convex.ts": convex, "catalog.json": json(catalog),
    "search-text.ts": header + `export const searchTextDescriptors = ${json(searchText).trim()} as const;\n`,
    "metadata.ts": header + `export const dependencyDescriptors = ${json(metadata).trim()} as const;\nexport const anchorDescriptors = ${json(anchors).trim()} as const;\nexport const packTreatmentSupport = ${json(Object.fromEntries(packs.map(pack => [pack.id, pack.treatments ?? {}]))).trim()} as const;\n` + `
export const packBlockPresentation = ${json(Object.fromEntries(packs.map(pack => [pack.id, { styles: pack.styles, hidden: pack.hidden }]))).trim()} as const;
export interface PackBlockPresentation { styles: Readonly<Record<string, readonly string[]>>; hidden: readonly string[] }
export function blockPresentationForPack(packId: string | undefined): PackBlockPresentation {
  const packs: Readonly<Record<string, PackBlockPresentation>> = packBlockPresentation;
  return packId && Object.prototype.hasOwnProperty.call(packs, packId) ? packs[packId] : { styles: {}, hidden: [] };
}
export function stylesForBlock(packId: string | undefined, name: string): readonly string[] {
  const descriptors: Readonly<Record<string, { supports: { styles: boolean } }>> = dependencyDescriptors;
  if (!Object.prototype.hasOwnProperty.call(descriptors, name) || !descriptors[name].supports.styles) return [];
  const styles = blockPresentationForPack(packId).styles;
  return ["default", ...(Object.prototype.hasOwnProperty.call(styles, name) ? styles[name].filter(style => style !== "default") : [])];
}
/** Unsupported saved choices survive template switches but render as default. */
export function resolveBlockStyle(packId: string | undefined, name: string, saved: string | undefined): string {
  return saved && stylesForBlock(packId, name).includes(saved) ? saved : "default";
}
`,
    "instances.ts": header + `import { z } from "zod";
import { validateBlockAttrs, validateBlockTreatment } from "./schemas";
import { dependencyDescriptors, anchorDescriptors, packTreatmentSupport } from "./metadata";
import { createCanonicalNodeSchema, createCanonicalTreeSchema, validateCanonicalTree as validateTree, type CanonicalTreeContract } from "./instance-runtime.mjs";
import type { CanonicalTree } from "./types";
export { collectCanonicalAnchors, createCanonicalLayoutSchema, MENU_VISIBILITY_VALUES, CANONICAL_TREE_LIMITS } from "./instance-runtime.mjs";
export const canonicalNodeSchema = createCanonicalNodeSchema(z);
const contract: CanonicalTreeContract = { nodeSchema: canonicalNodeSchema, validateAttrs: validateBlockAttrs, validateTreatment: validateBlockTreatment, descriptors: dependencyDescriptors, anchors: anchorDescriptors };
export const canonicalTreeSchema = createCanonicalTreeSchema(z, contract) as z.ZodType<CanonicalTree>;
export function validateCanonicalTree(value: unknown): CanonicalTree { return validateTree(value, contract) as CanonicalTree; }
type TreatmentNode = { name: string; treatment?: { name: string }; children?: TreatmentNode[] };
/** Caller validates the tree against its Library or exact composed registry. */
export function assertPackTreatments(tree: TreatmentNode[], packId: string): void {
  const packs: Readonly<Record<string, Readonly<Record<string, readonly string[]>>>> = packTreatmentSupport;
  const visit = (nodes: TreatmentNode[]): void => { for (const node of nodes) {
    if (node.treatment && !packs[packId]?.[node.name]?.includes(node.treatment.name)) throw Error("PACK_TREATMENT_UNAVAILABLE: " + packId + "/" + node.name);
    if (node.children) visit(node.children);
  } };
  visit(tree);
}
`,
    "instance-runtime.mjs": header + await readFile(new URL("./instance-runtime.mjs", import.meta.url), "utf8"),
    "instance-runtime.d.mts": header + await readFile(new URL("./instance-runtime.d.mts", import.meta.url), "utf8"),
    "spec-runtime.mjs": header + await readFile(new URL("./spec-runtime.mjs", import.meta.url), "utf8"),
    "spec-runtime.d.mts": header + await readFile(new URL("./spec-runtime.d.mts", import.meta.url), "utf8"),
    "dependencies.json": json(metadata), "editors.json": json(editors),
    "editor-metadata.ts": header + `import type { BlockName } from "./types";
export const fieldTypes = ${q(fieldTypeNames)} as const;
export type FieldType = (typeof fieldTypes)[number];
export interface EditorField {
  id: string; type: FieldType; title?: string; description?: string; required?: boolean; nullable?: boolean; default?: unknown;
  min?: number; max?: number; integer?: boolean; inline?: boolean; multiline?: true; authoringNonblank?: true; format?: string; domId?: true;
  options?: readonly (string | number)[]; optionsMode?: "authoring"; of?: string; storage?: string; allowEmpty?: boolean; protocols?: readonly string[];
  fields?: readonly EditorField[]; item?: EditorField; constraints?: readonly unknown[];
}
export interface EditorDefinition { version: number; requires: { plugins: readonly string[]; capabilities: readonly string[] }; fields: readonly EditorField[]; constraints: readonly unknown[]; preview: string; category: string; title: string; role: string; supports: { children: boolean; styles: boolean; layout: readonly string[]; anchor: boolean; visibility: boolean } }
export const editorDefinitions: Record<BlockName, EditorDefinition> = ${json(editors)};
`, "coverage.json": json(coverage),
    "migrations.json": json(Object.fromEntries(blocks.filter(({ spec }) => spec.migration).map(({ spec }) => [spec.name, { toVersion: spec.version, ...spec.migration }]))),
    "block-spec.schema.json": json(blockSpecJsonSchema), "field-runtime.mjs": header + runtime,
    "field-runtime.d.mts": header + 'import type { z } from "zod";\nexport const INLINE_MARK_TYPES: readonly ("bold" | "italic" | "strike" | "underline" | "code")[];\nexport type RichTextMark = { type: "bold" | "italic" | "strike" | "underline" | "code" } | { type: "link"; attrs: { href: string; target?: "_blank" | "_self" } };\nexport type RichTextInline = { type: "text"; text: string; marks?: RichTextMark[] } | { type: "hardBreak" };\nexport type RichTextDoc = { type: "doc"; content: { type: "paragraph"; content?: RichTextInline[] }[] };\nexport function createRichTextSchema(zod: typeof z, max?: number, inlineOnly?: boolean): z.ZodType<RichTextDoc, RichTextDoc>;\nexport function safeLinkSchema(zod: typeof z, protocols?: readonly string[]): z.ZodString;\nexport function dateSchema(zod: typeof z): z.ZodString;\nexport function formattedTextSchema(zod: typeof z, format: string): z.ZodString;\nexport function constrainObject<T extends z.ZodType>(schema: T, constraints: readonly unknown[]): T;\n',
  };
  files["manifest.json"] = json({ format: 1, sources: blocks.map(({ source, spec }) => ({ source, sha256: hash(json(spec)) })), files: Object.fromEntries(Object.entries(files).map(([name, content]) => [name, hash(content)])) });
  return files;
}
export async function syncBlocks({ root = fileURLToPath(new URL("../../", import.meta.url)), check = false, output = "blocks/.generated" } = {}) {
  const discovered = await discoverBlocks(root);
  const files = await generateArtifacts(discovered);
  const destination = path.resolve(root, output);
  if (!destination.startsWith(path.resolve(root) + path.sep)) throw new Error("Generated output must be inside the project root");
  // Do not follow output symlinks into another checkout or app.
  let cursor = path.resolve(root);
  for (const segment of path.relative(root, destination).split(path.sep)) {
    cursor = path.join(cursor, segment);
    try { if ((await lstat(cursor)).isSymbolicLink()) throw new Error(`Output symlink refused: ${cursor}`); } catch (error) { if (error.code !== "ENOENT") throw error; }
  }
  let existing = [];
  try { existing = await readdir(destination); } catch (error) { if (error.code !== "ENOENT") throw error; }
  const unexpected = existing.filter(name => !Object.prototype.hasOwnProperty.call(files, name));
  if (unexpected.length) throw new Error(`Unexpected generated files: ${unexpected.join(", ")}. Inspect and remove obsolete outputs explicitly.`);
  const changed = [];
  for (const [name, expected] of Object.entries(files)) {
    let actual;
    try {
      if ((await lstat(path.join(destination, name))).isSymbolicLink()) throw new Error(`Generated file symlink refused: ${name}`);
      actual = await readFile(path.join(destination, name), "utf8");
    } catch (error) { if (error.code !== "ENOENT") throw error; }
    if (actual !== expected) changed.push(name);
  }
  if (check && changed.length) throw new Error(`Generated block drift: ${changed.join(", ")}. Run bun run sync:blocks.`);
  if (!check && changed.length) {
    await mkdir(destination, { recursive: true });
    for (const name of changed) {
      const temporary = path.join(destination, `.${name}.${process.pid}.tmp`);
      await (await import("node:fs/promises")).writeFile(temporary, files[name], { flag: "wx" });
      await rename(temporary, path.join(destination, name));
    }
  }
  return { blocks: discovered.blocks.length, packs: discovered.packs.length, changed };
}
