/** Pure draft operations. Admin's copy is generated by sync:templates. */
export type Values = Record<string, Record<string, unknown>>;
export interface DraftSnapshot { values: Values; variants: Record<string, string> }
export interface DraftHistory { past: DraftSnapshot[]; present: DraftSnapshot; future: DraftSnapshot[] }
const LIMIT = 50;
const clone = <T>(value: T): T => structuredClone(value);
export function createDraftHistory(snapshot: DraftSnapshot): DraftHistory { return { past: [], present: clone(snapshot), future: [] }; }
export function applyDraftChange(history: DraftHistory, snapshot: DraftSnapshot): DraftHistory {
  if (JSON.stringify(history.present) === JSON.stringify(snapshot)) return history;
  return { past: [...history.past, history.present].slice(-LIMIT), present: clone(snapshot), future: [] };
}
export function undoDraft(history: DraftHistory): DraftHistory {
  if (!history.past.length) return history;
  return { past: history.past.slice(0, -1), present: history.past[history.past.length - 1], future: [history.present, ...history.future] };
}
export function redoDraft(history: DraftHistory): DraftHistory {
  if (!history.future.length) return history;
  return { past: [...history.past, history.present].slice(-LIMIT), present: history.future[0], future: history.future.slice(1) };
}
const safePath = (path: string) => path.split(".").filter((part) => part && !["__proto__", "prototype", "constructor"].includes(part));
export function readDraftField(fields: Record<string, unknown> | undefined, path: string): unknown {
  let value: unknown = fields;
  for (const key of safePath(path)) value = value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>)[key] : undefined;
  return value;
}
function writeField(fields: Record<string, unknown>, path: string, value: unknown, remove = false) {
  const keys = safePath(path);
  if (!keys.length || keys.length !== path.split(".").length) return;
  let target = fields;
  for (const key of keys.slice(0, -1)) {
    const current = target[key];
    target[key] = current && typeof current === "object" && !Array.isArray(current) ? { ...current } : {};
    target = target[key] as Record<string, unknown>;
  }
  if (remove) delete target[keys[keys.length - 1]];
  else target[keys[keys.length - 1]] = value;
}
export function setDraftField(snapshot: DraftSnapshot, moduleId: string, fieldId: string, value: unknown): DraftSnapshot {
  const next = clone(snapshot);
  next.values[moduleId] = { ...next.values[moduleId] };
  // A cleared control means inherit the pack/brand default. Persisting null
  // would shadow that default and remove its rendered CSS value instead.
  writeField(next.values[moduleId], fieldId, value, value == null);
  const surface = moduleId === "shop" ? ({ catalogVariant: "shop.catalog", productVariant: "shop.product" } as Record<string, string>)[fieldId] : undefined;
  if (surface) {
    if (typeof value === "string" && value) next.variants[surface] = value;
    else delete next.variants[surface];
  }
  return next;
}
export function resetDraftModule(snapshot: DraftSnapshot, moduleId: string): DraftSnapshot {
  const next = clone(snapshot);
  delete next.values[moduleId];
  if (moduleId === "shop") { delete next.variants["shop.catalog"]; delete next.variants["shop.product"]; }
  return next;
}
export function resetDraftBrand(snapshot: DraftSnapshot, modules: Array<{ id: string; fields: Array<{ id: string; brandBound?: boolean }> }>): DraftSnapshot {
  const next = clone(snapshot);
  // Palette extensions (dark/sidebar/chart tokens) also belong to the color override group.
  delete next.values.colors;
  for (const module of modules) {
    if (!next.values[module.id]) continue;
    for (const field of module.fields) if (field.brandBound) writeField(next.values[module.id], field.id, undefined, true);
    if (!Object.keys(next.values[module.id]).length) delete next.values[module.id];
  }
  return next;
}
export function applyColorPreset(snapshot: DraftSnapshot, colors: Record<string, string>): DraftSnapshot {
  return { ...clone(snapshot), values: { ...clone(snapshot.values), colors: clone(colors) } };
}
export function draftChanges(before: DraftSnapshot, after: DraftSnapshot): string[] {
  const changes: string[] = [];
  for (const moduleId of new Set([...Object.keys(before.values), ...Object.keys(after.values)])) {
    for (const field of new Set([...Object.keys(before.values[moduleId] ?? {}), ...Object.keys(after.values[moduleId] ?? {})])) {
      if (JSON.stringify(before.values[moduleId]?.[field]) !== JSON.stringify(after.values[moduleId]?.[field])) changes.push(`${moduleId}.${field}`);
    }
  }
  for (const surface of new Set([...Object.keys(before.variants), ...Object.keys(after.variants)])) if (before.variants[surface] !== after.variants[surface]) changes.push(`variant.${surface}`);
  return changes;
}
