/** Authoritative portable Customizer schema. Admin receives a generated byte-for-byte mirror. */
import { HEADER_DEFAULTS, FOOTER_DEFAULTS, HEADER_SECTIONS, FOOTER_SECTIONS } from "./chromeDefinitions";
import { readDraftField } from "./draftModel";

export interface TemplateSettingsField {
  id: string;
  label: string;
  type: "color" | "font" | "select" | "toggle" | "text" | "number" | "image" | "menuLocation" | "range";
  default: unknown;
  options?: Array<{ value: string; label: string }>;
  /** Default comes from the brand doc / site identity until overridden. */
  brandBound?: boolean;
  /** Surfaces this field affects; used by the Customizer's context filter. */
  surfaces?: string[];
  min?: number;
  max?: number;
}

export interface TemplateSettingsGroup {
  id: string;
  title: string;
  fields: TemplateSettingsField[];
}

export const COLOR_TOKENS = [
  ["background", "Background"],
  ["foreground", "Text"],
  ["card", "Card"],
  ["card-foreground", "Card text"],
  ["muted", "Muted surface"],
  ["muted-foreground", "Muted text"],
  ["primary", "Primary"],
  ["primary-foreground", "On primary"],
  ["secondary", "Secondary"],
  ["secondary-foreground", "On secondary"],
  ["accent", "Accent"],
  ["accent-foreground", "On accent"],
  ["border", "Border"],
  ["input", "Input border"],
  ["ring", "Focus ring"],
  ["destructive", "Destructive"],
] as const;

export interface ColorPreset {
  id: string;
  name: string;
  colors: Record<string, string>;
}

export interface SettingsModule extends TemplateSettingsGroup {
  /** Optional named palettes a pack ships for the colors module. */
  presets?: ColorPreset[];
}

const field = (id: string, label: string, type: TemplateSettingsField["type"], def: unknown, extra: Partial<TemplateSettingsField> = {}): TemplateSettingsField => ({
  id,
  label,
  type,
  default: def,
  ...extra,
});

function chromeFields(sections: Array<{ id: string; label: string; hasToggle: boolean; fields: Array<{ id: string; label: string; type: string; options?: Array<{ value: string; label: string }> }> }>, defaults: Record<string, unknown>, surface: string): TemplateSettingsField[] {
  return sections.flatMap(section => {
    const values = defaults[section.id] as Record<string, unknown>;
    const fields = section.fields.map(item => field(`${section.id}.${item.id}`, `${section.label}: ${item.label}`, item.type === "variant-grid" ? "select" : item.type as TemplateSettingsField["type"], values?.[item.id], { options: item.options, surfaces: [surface] }));
    if (section.hasToggle) fields.unshift(field(`${section.id}.enabled`, `Show ${section.label.toLowerCase()}`, "toggle", values?.enabled ?? true, { surfaces: [surface] }));
    return fields;
  });
}

/** Standard modules. `default: null` for colours means "use the site palette / brand value". */
export const STANDARD_MODULES: Record<string, SettingsModule> = {
  colors: {
    id: "colors",
    title: "Colors",
    fields: COLOR_TOKENS.map(([token, label]) => field(token, label, "color", null, { brandBound: true })),
  },
  typography: {
    id: "typography",
    title: "Typography",
    fields: [
      field("display", "Display font", "font", null, { brandBound: true }),
      field("body", "Body font", "font", null, { brandBound: true }),
      field("scale", "Type scale", "select", "comfortable", {
        options: [
          { value: "compact", label: "Compact" },
          { value: "comfortable", label: "Comfortable" },
          { value: "spacious", label: "Spacious" },
        ],
      }),
    ],
  },
  layout: {
    id: "layout",
    title: "Layout",
    fields: [
      field("radius", "Corner radius", "select", null, {
        brandBound: true,
        options: [
          { value: "sharp", label: "Sharp" },
          { value: "subtle", label: "Subtle" },
          { value: "rounded", label: "Rounded" },
          { value: "pill", label: "Pill" },
        ],
      }),
      field("contentWidth", "Content width", "select", "wide", {
        options: [
          { value: "narrow", label: "Narrow" },
          { value: "wide", label: "Wide" },
          { value: "full", label: "Full" },
        ],
      }),
      field("sectionSpacing", "Section spacing", "select", "comfortable", {
        options: [{ value: "compact", label: "Compact" }, { value: "comfortable", label: "Comfortable" }, { value: "spacious", label: "Spacious" }],
      }),
      field("elementSpacing", "Content spacing", "select", "comfortable", {
        options: [{ value: "compact", label: "Compact" }, { value: "comfortable", label: "Comfortable" }, { value: "spacious", label: "Spacious" }],
      }),
      field("blockGap", "Space between blocks", "select", "none", {
        options: [{ value: "none", label: "None" }, { value: "small", label: "Small" }, { value: "medium", label: "Medium" }, { value: "large", label: "Large" }],
      }),
    ],
  },
  shop: {
    id: "shop",
    title: "Shop",
    fields: [
      field("catalogVariant", "Catalog layout", "select", null, { surfaces: ["shop.catalog"] }),
      field("productVariant", "Product page layout", "select", null, { surfaces: ["shop.product"] }),
      field("gridDensity", "Product grid density", "select", "comfortable", {
        surfaces: ["shop.catalog"],
        options: [{ value: "comfortable", label: "Comfortable" }, { value: "dense", label: "Dense" }],
      }),
      field("cartPanel", "Cart", "select", "persistent", {
        surfaces: ["shop.catalog", "shop.product"],
        options: [
          { value: "persistent", label: "Persistent column" },
          { value: "drawer", label: "Drawer only" },
        ],
      }),
    ],
  },
  header: {
    id: "header", title: "Header",
    fields: chromeFields(HEADER_SECTIONS, HEADER_DEFAULTS, "chrome.header"),
  },
  footer: {
    id: "footer", title: "Footer",
    fields: chromeFields(FOOTER_SECTIONS, FOOTER_DEFAULTS, "chrome.footer"),
  },
  menuLayout: {
    id: "menuLayout", title: "Menu locations",
    fields: [
      field("primary", "Primary menu location", "menuLocation", "header", { surfaces: ["chrome.header", "chrome.mobileNav"] }),
      field("secondary", "Secondary menu location", "menuLocation", "secondary", { surfaces: ["chrome.header"] }),
      field("footer", "Footer menu location", "menuLocation", "footer", { surfaces: ["chrome.footer"] }),
      ...[1, 2, 3, 4].map(index => field(`footer-${index}`, `Footer column ${index} location`, "menuLocation", `footer-${index}`, { surfaces: ["chrome.footer"] })),
    ],
  },
};

export const RADIUS_VALUES: Record<string, string> = {
  sharp: "0rem",
  subtle: "0.375rem",
  rounded: "0.625rem",
  pill: "1.25rem",
};

export const CONTENT_WIDTH_VALUES: Record<string, string> = {
  narrow: "64rem",
  wide: "80rem",
  full: "100%",
};

/** Modules a pack includes, in order, with the pack's own groups appended. */
export function modulesFor(manifest: { modules?: string[]; settings?: TemplateSettingsGroup[]; presets?: Record<string, ColorPreset[]>; menuLocations?: Record<string, string>; defaults?: Record<string, Record<string, unknown>> } | undefined): SettingsModule[] {
  const included = (manifest?.modules ?? []).map((id) => STANDARD_MODULES[id]).filter((m): m is SettingsModule => Boolean(m)).map((module) => ({ ...module, presets: manifest?.presets?.[module.id] ?? module.presets, ...(module.id === "menuLayout" ? { fields: module.fields.map((field) => ({ ...field, default: manifest?.menuLocations?.[field.id] ?? field.default })) } : {}) }));
  return [...included, ...((manifest?.settings ?? []) as SettingsModule[])].map(module => ({
    ...module,
    fields: module.fields.map(field => {
      const packDefault = readDraftField(manifest?.defaults?.[module.id], field.id);
      return packDefault === undefined ? field : { ...field, default: packDefault };
    }),
  }));
}

/** Default values per module from the schema. */
export function defaultsFor(modules: SettingsModule[]): Record<string, Record<string, unknown>> {
  const out: Record<string, Record<string, unknown>> = {};
  for (const module of modules) {
    out[module.id] = module.id === "header" ? structuredClone(HEADER_DEFAULTS) : module.id === "footer" ? structuredClone(FOOTER_DEFAULTS) : {};
    for (const f of module.fields) {
      const path = f.id.split(".");
      let cursor = out[module.id];
      for (const key of path.slice(0, -1)) cursor = (cursor[key] ??= {}) as Record<string, unknown>;
      cursor[path[path.length - 1]] = f.default;
    }
  }
  return out;
}

