// Generated by sync-extension-manifests.mjs.
import manifest0 from "../../extensions/commerce/manifest";
import manifest1 from "../../extensions/commerceBundles/manifest";
import manifest2 from "../../extensions/commerceDigital/manifest";
import manifest3 from "../../extensions/commerceReturns/manifest";
import manifest4 from "../../extensions/commerceReviews/manifest";
import manifest5 from "../../extensions/commerceSubscriptions/manifest";
import manifest6 from "../../extensions/commerceWishlists/manifest";
import manifest7 from "../../extensions/dashboard/manifest";
import manifest8 from "../../extensions/events/manifest";
import manifest9 from "../../extensions/forms/manifest";
import manifest10 from "../../extensions/gallery/manifest";
import manifest11 from "../../extensions/knowledgeBase/manifest";
import manifest12 from "../../extensions/lms/manifest";
import manifest13 from "../../extensions/membership/manifest";
import manifest14 from "../../extensions/recipes/manifest";
import manifest15 from "../../extensions/tickets/manifest";
export const INSTALLED_MANIFESTS = [manifest0, manifest1, manifest2, manifest3, manifest4, manifest5, manifest6, manifest7, manifest8, manifest9, manifest10, manifest11, manifest12, manifest13, manifest14, manifest15];
