import {expect,test} from 'bun:test';import {createRequire} from 'node:module';import {mkdtemp,rm} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import {act} from 'react';
const require=createRequire(import.meta.url),{JSDOM}=createRequire(require.resolve('isomorphic-dompurify'))('jsdom');
test('backend mismatch preserves control navigation without opening protected content',async()=>{
 const output=await mkdtemp(fileURLToPath(new URL('../../.error-recovery-',import.meta.url))),dom=new JSDOM('<div id="app"></div>',{url:'http://localhost',pretendToBeVisual:true});const names=['window','document','navigator','HTMLElement','Node','IS_REACT_ACT_ENVIRONMENT'],prior=names.map(n=>[n,Object.getOwnPropertyDescriptor(globalThis,n)]);for(const name of names)Object.defineProperty(globalThis,name,{configurable:true,writable:true,value:name==='IS_REACT_ACT_ENVIRONMENT'?true:dom.window[name]});let root;
 try{const fixture=fileURLToPath(new URL('./ErrorTemplate.recovery.fixture.tsx',import.meta.url));const built=await Bun.build({entrypoints:[fixture],outdir:output,target:'bun',format:'esm',define:{'import.meta.env.DEV':'false'},plugins:[{name:'recovery-fixture',setup(build){build.onResolve({filter:/^(@tanstack\/react-router|@\/control\/ControlShellContext|@\/control\/components\/StandaloneFrame)$/},()=>({path:fixture}));build.onResolve({filter:/^react(?:-dom)?(?:\/.*)?$/},args=>({path:require.resolve(args.path),external:true}));}}]});if(!built.success)throw Error(built.logs.map(String).join('\n'));const m=await import(built.outputs[0].path);const {createRoot}=await import('react-dom/client');root=createRoot(document.getElementById('app'));
 const render=async message=>act(async()=>root.render(<m.ErrorTemplate error={new Error(message)}/>));const click=async text=>act(async()=>[...document.querySelectorAll('button')].find(b=>b.textContent.includes(text)).click());
 await render("[CONVEX Q(users:getCurrentRoleAccess)] Server Error\nCould not find public function for 'users:getCurrentRoleAccess'.");expect(document.querySelector('[aria-label="Control frame"]')).not.toBeNull();expect(document.body.textContent).toContain('This environment needs an update');expect(document.body.textContent).not.toContain('users:getCurrentRoleAccess');await click('Open Sites');expect(m.calls.sites).toBe(1);await click('Try Again');expect(m.calls.retry).toBe(1);
 await render('[CONVEX Q(users:getCurrentRoleAccess)] [Request ID: opaque] Server Error\n  Called by client');expect(document.querySelector('[aria-label="Control frame"]')).not.toBeNull();expect(document.body.textContent).toContain('Unable to verify access to this environment');expect(document.body.textContent).toContain('connection and backend version');expect(document.body.textContent).not.toContain('users:getCurrentRoleAccess');expect(document.body.textContent).not.toContain('needs an update');await click('Open Sites');expect(m.calls.sites).toBe(2);
 await render('Access denied');expect(document.querySelector('[aria-label="Control frame"]')).not.toBeNull();expect(document.body.textContent).toContain('Something went wrong');expect(document.body.textContent).not.toContain('needs an update');
 m.setStandalone(false);await render('Offline');expect(document.querySelector('[aria-label="Control frame"]')).toBeNull();expect(document.querySelector('a').textContent).toContain('Dashboard');
 }finally{if(root)await act(async()=>root.unmount());dom.window.close();await rm(output,{recursive:true,force:true});for(const [name,descriptor]of prior)if(descriptor)Object.defineProperty(globalThis,name,descriptor);else delete globalThis[name];}
});
