/** Offline, deterministic schema-derived typed media reference inventory. Run with Bun. */
import schema from "../convex/schema";
import { opaqueAuthoringOwners } from "../convex/media/referenceOwners";
import { ensureMediaReferenceIndex } from "../convex/media/referenceIndexes";
import { readFileSync, writeFileSync } from "node:fs";
const inventory: Record<string, { path: string[]; optional: boolean }[]> = {};
function walk(node: any, path: string[], optional: boolean, refs: { path: string[]; optional: boolean }[]) {
  if (node.type === "id" && node.tableName === "media") refs.push({ path, optional });
  if (node.type === "object") for (const [key, field] of Object.entries<any>(node.value)) walk(field.fieldType, [...path, key], field.optional, refs);
  if (node.type === "array") walk(node.value, [...path, "*"], true, refs);
  if (node.type === "union") for (const member of node.value) walk(member, path, optional, refs);
}
for (const [table, definition] of Object.entries(schema.tables).sort(([a], [b]) => a.localeCompare(b))) {
  const refs: { path: string[]; optional: boolean }[] = [];
  walk(definition.validator.json, [], false, refs);
  if (refs.length) inventory[table] = refs;
}
const opaque: Record<string, string[]> = {};
for (const table of [...opaqueAuthoringOwners].sort()) {
  const definition = schema.tables[table].validator.json as any;
  opaque[table] = Object.entries<any>(definition.value).filter(([, field]) => /"type":"(?:string|any)"/.test(JSON.stringify(field.fieldType))).map(([field]) => field).sort();
}
const indexes: Record<string, Record<string, string>> = {};
for (const [table, descriptors] of Object.entries(inventory)) {
  for (const descriptor of descriptors) {
    if (descriptor.path.includes("*")) continue;
    const field = descriptor.path.join(".");
    // Newly discovered scalar fields may not yet occur in the previous generated
    // inventory used to compose schema.ts. Apply the same plan here so one codegen
    // pass can emit their mapping; the next schema load installs that exact index.
    const name = ensureMediaReferenceIndex((schema.tables as any)[table], field, table);
    (indexes[table] ??= {})[field] = name;
  }
}
const output = `// Generated by scripts/generate-media-reference-inventory.ts. Do not edit.\nexport const typedMediaReferences = ${JSON.stringify(inventory, null, 2)} as const;\nexport const opaqueMediaReferences = ${JSON.stringify(opaque, null, 2)} as const;\nexport const mediaReferenceIndexes = ${JSON.stringify(indexes, null, 2)} as const;\n`;
const target = new URL("../convex/media/referenceInventory.generated.ts", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(target, "utf8") !== output) throw new Error("Media reference inventory drift; regenerate from current schema.");
} else writeFileSync(target, output);
console.log(`Verified ${Object.keys(inventory).length} typed media-reference tables.`);
