/**
 * Demo shop: Northstar Coffee — home espresso and brewing gear.
 *
 * Built to show compatibility reasoning: two portafilter sizes (51 mm vs
 * 58 mm), thermoblock vs dual-boiler maintenance, pour-over consumables.
 */

import type { DemoShop } from "./types";

const USD = (dollars: number) => Math.round(dollars * 100);

export const northstarCoffee: DemoShop = {
  key: "northstar-coffee",
  siteTitle: "Northstar Coffee",
  tagline: "Home espresso, done properly.",
  storeName: "Northstar Coffee",
  storeEmail: "hello@northstar.coffee",
  currencyCode: "USD",
  currencySymbol: "$",
  brand: {
    moodPrompt:
      "Warm, artisanal, confident. A small roastery that also sells the gear it trusts. Cream paper, roasted-bean browns, a burnt-orange accent, generous whitespace, editorial serif headlines.",
    voice: "warm and direct, like a barista who wants you to succeed at home",
    industry: "coffee equipment and roastery",
    hardRules: [
      "Never recommend a tamper that does not match the machine's portafilter size.",
      "Always mention descaling for thermoblock machines.",
    ],
    typography: { display: "Fraunces", body: "Inter", scale: "comfortable" },
    density: "comfortable",
    radius: "rounded",
  },
  palette: [
    { slug: "background", name: "Cream", color: "#f7f2ea" },
    { slug: "foreground", name: "Roast", color: "#2b211b" },
    { slug: "card", name: "Paper", color: "#fffaf3" },
    { slug: "card-foreground", name: "Roast", color: "#2b211b" },
    { slug: "popover", name: "Paper", color: "#fffaf3" },
    { slug: "popover-foreground", name: "Roast", color: "#2b211b" },
    { slug: "primary", name: "Burnt orange", color: "#b5542a" },
    { slug: "primary-foreground", name: "Cream", color: "#fff7ef" },
    { slug: "secondary", name: "Latte", color: "#ead9c6" },
    { slug: "secondary-foreground", name: "Roast", color: "#2b211b" },
    { slug: "muted", name: "Oat", color: "#efe6da" },
    { slug: "muted-foreground", name: "Cocoa", color: "#7a6656" },
    { slug: "accent", name: "Latte", color: "#ead9c6" },
    { slug: "accent-foreground", name: "Roast", color: "#2b211b" },
    { slug: "border", name: "Crema", color: "#dccbb8" },
    { slug: "input", name: "Crema", color: "#dccbb8" },
    { slug: "ring", name: "Burnt orange", color: "#b5542a" },
    { slug: "radius", name: "Radius", color: "var(--radius)" },
  ],
  imageStyle:
    "clean studio product photograph on a warm cream seamless backdrop, soft window light from the left, subtle shadow, no text, no people, centered, e-commerce catalog style, photorealistic",
  assistant: {
    displayName: "Northstar barista",
    tagline: "Knows your setup. Suggests what fits.",
    tone: "warm, expert, concise; explains why each pick fits the shopper's machine",
    starterPrompts: [
      "Which machine fits under a 15-inch cabinet?",
      "What do I need to start pulling shots?",
      "Best grinder for pour-over under $100?",
    ],
    disclosureText:
      "Suggestions are generated from your cart and search. Prices and stock are live.",
  },
  categories: [
    { slug: "espresso-machines", name: "Espresso machines", description: "Pump, dual-boiler and capsule machines for the kitchen counter.", sortOrder: 1 },
    { slug: "grinders", name: "Grinders", description: "Conical and flat burr grinders, electric and hand.", sortOrder: 2 },
    { slug: "brewers", name: "Brewers & kettles", description: "Pour-over, stovetop and the kettles that feed them.", sortOrder: 3 },
    { slug: "accessories", name: "Accessories", description: "Tampers, portafilters, pitchers, scales and filters.", sortOrder: 4 },
    { slug: "coffee-beans", name: "Coffee beans", description: "Roasted weekly in small batches.", sortOrder: 5 },
    { slug: "maintenance", name: "Cleaning & maintenance", description: "Keep every machine tasting like day one.", sortOrder: 6 },
  ],
  products: [
    {
      slug: "northstar-compact-15-espresso-machine",
      title: "Northstar Compact 15 Espresso Machine",
      category: "espresso-machines",
      excerpt: "A 15-bar thermoblock machine with a real steam wand that fits under a standard cabinet.",
      description:
        "<p>The Compact 15 is the machine we hand to friends who want proper espresso without a countertop takeover. A 15-bar Italian pump, a fast-heating thermoblock and a 51 mm pressurised portafilter make it forgiving with supermarket beans and rewarding with ours.</p><p>At 11.8 inches tall it clears a 15-inch cabinet with room to fill the 1.2 L tank. The articulating steam wand textures milk for flat whites and lattes.</p>",
      priceMinor: USD(299),
      compareAtMinor: USD(349),
      sku: "NS-CM15",
      stock: 24,
      weightOz: 150,
      attributes: {
        portafilter_mm: 51,
        pump_bar: 15,
        heating: "thermoblock",
        height_in: 11.8,
        width_in: 6,
        depth_in: 12.5,
        water_tank_l: 1.2,
        steam_wand: true,
        fits_under_15in_cabinet: true,
        three_way_valve: false,
        power_w: 1350,
        good_for: ["espresso", "lattes", "small kitchens"],
      },
      summary: "51 mm portafilter, thermoblock, 11.8 in tall — fits under a 15-inch cabinet.",
      imagePrompt: "a compact brushed stainless steel home espresso machine with a black portafilter and a steam wand, single small cup of espresso beside it",
    },
    {
      slug: "northstar-pro-58-dual-boiler",
      title: "Northstar Pro 58 Dual Boiler",
      category: "espresso-machines",
      excerpt: "Commercial 58 mm group, PID dual boiler, café-grade steam. The machine you stop upgrading from.",
      description:
        "<p>Two boilers mean you can pull and steam at the same time. The 58 mm commercial group takes any standard basket and tamper, the PID holds brew temperature within a degree, and the three-way solenoid valve lets you backflush like a café.</p><p>15.6 inches tall with a 2.5 L tank. Ships with a bottomless portafilter and a 58 mm tamper.</p>",
      priceMinor: USD(1299),
      sku: "NS-PRO58",
      stock: 6,
      weightOz: 480,
      attributes: {
        portafilter_mm: 58,
        pump_bar: 9,
        heating: "dual boiler",
        pid: true,
        height_in: 15.6,
        width_in: 11.5,
        depth_in: 16,
        water_tank_l: 2.5,
        steam_wand: true,
        fits_under_15in_cabinet: false,
        three_way_valve: true,
        power_w: 1700,
        good_for: ["espresso", "milk drinks", "enthusiasts"],
      },
      summary: "58 mm commercial group, PID dual boiler, backflushable — 15.6 in tall.",
      imagePrompt: "a premium stainless steel dual boiler espresso machine with two pressure gauges, wooden accents on the portafilter handle and steam knob",
    },
    {
      slug: "northstar-pod-mini",
      title: "Northstar Pod Mini",
      category: "espresso-machines",
      excerpt: "One-touch capsule espresso in a 10-inch footprint. Zero fuss, zero grinder.",
      description:
        "<p>For the household that wants a good shot at 6 a.m. with one button. The Pod Mini takes standard capsules, heats in 25 seconds and sits 10.2 inches tall. There is no grinder to buy and no tamper to learn.</p><p>Descale every two to three months with our solution and it keeps going for years.</p>",
      priceMinor: USD(129),
      sku: "NS-POD",
      stock: 40,
      weightOz: 70,
      attributes: {
        capsule_based: true,
        heating: "thermoblock",
        height_in: 10.2,
        width_in: 4.5,
        depth_in: 13,
        water_tank_l: 0.8,
        steam_wand: false,
        fits_under_15in_cabinet: true,
        needs_grinder: false,
        good_for: ["speed", "small kitchens", "no fuss"],
      },
      summary: "Capsule machine, 10.2 in tall, no grinder or tamper needed.",
      imagePrompt: "a small modern matte black capsule espresso machine with a single espresso cup on its drip tray",
    },
    {
      slug: "meridian-conical-burr-grinder",
      title: "Meridian Conical Burr Grinder",
      category: "grinders",
      excerpt: "40 mm conical burrs, 30 settings from espresso to French press. Our everyday grinder.",
      description:
        "<p>Meridian grinds fine enough for a 15-bar pump machine and coarse enough for a press, with a stepped dial you can actually repeat. Low retention, quiet motor, 250 g hopper.</p>",
      priceMinor: USD(189),
      sku: "NS-GR-MER",
      stock: 18,
      weightOz: 88,
      attributes: {
        burr_type: "40 mm conical",
        settings: 30,
        espresso_capable: true,
        pour_over_capable: true,
        electric: true,
        height_in: 13.4,
        hopper_g: 250,
        good_for: ["espresso", "pour-over", "daily use"],
      },
      summary: "Electric conical burr, espresso to French press, 13.4 in tall.",
      imagePrompt: "a sleek electric conical burr coffee grinder in graphite with a clear bean hopper",
    },
    {
      slug: "trailhead-hand-grinder",
      title: "Trailhead Hand Grinder",
      category: "grinders",
      excerpt: "Steel conical burrs in a pocket-sized body. Pour-over and moka in under a minute.",
      description:
        "<p>Trailhead is the grinder that lives in the camping box and the office drawer. External adjustment ring, 25 g capacity, folding handle. Excellent for pour-over and moka; it will do espresso for the Compact 15 if you are patient.</p>",
      priceMinor: USD(89),
      sku: "NS-GR-TRL",
      stock: 33,
      weightOz: 18,
      attributes: {
        burr_type: "38 mm steel conical",
        settings: "stepless external",
        espresso_capable: "slow but yes",
        pour_over_capable: true,
        electric: false,
        capacity_g: 25,
        good_for: ["pour-over", "moka", "travel"],
      },
      summary: "Manual burr grinder, ideal for pour-over and moka, travel-sized.",
      imagePrompt: "a compact stainless steel manual hand coffee grinder with a folding handle standing upright",
    },
    {
      slug: "summit-flat-burr-grinder",
      title: "Summit 64 Flat Burr Grinder",
      category: "grinders",
      excerpt: "64 mm flat burrs, single-dose workflow, near-zero retention. Built for the Pro 58.",
      description:
        "<p>Flat burrs give the clarity and evenness espresso obsessives chase. Summit is a single-dose grinder: weigh in, grind out, nothing left behind. Stepless adjustment, anti-static chute, 16.5 inches tall.</p>",
      priceMinor: USD(449),
      sku: "NS-GR-SUM",
      stock: 9,
      weightOz: 170,
      attributes: {
        burr_type: "64 mm flat",
        settings: "stepless",
        espresso_capable: true,
        pour_over_capable: true,
        electric: true,
        single_dose: true,
        height_in: 16.5,
        good_for: ["espresso", "enthusiasts"],
      },
      summary: "Single-dose 64 mm flat burr grinder for serious espresso.",
      imagePrompt: "a tall premium single-dose flat burr espresso grinder in matte white with a small bellows on top",
    },
    {
      slug: "aurora-pour-over-dripper",
      title: "Aurora Pour-Over Dripper",
      category: "brewers",
      excerpt: "Ceramic cone dripper, size 02, brews one to four cups.",
      description:
        "<p>A thick glazed ceramic cone that holds heat through the whole pour. Takes size 02 paper filters. Sits on a mug or a carafe.</p>",
      priceMinor: USD(34),
      sku: "NS-BR-AUR",
      stock: 50,
      weightOz: 14,
      attributes: {
        method: "pour-over",
        filter_size: "02",
        material: "ceramic",
        cups: "1–4",
        needs_kettle: true,
        grind: "medium",
      },
      summary: "Ceramic size-02 cone; pairs with a gooseneck kettle and medium grind.",
      imagePrompt: "a glossy white ceramic pour-over coffee dripper cone on a glass carafe",
    },
    {
      slug: "northstar-moka-6",
      title: "Northstar Moka 6-Cup",
      category: "brewers",
      excerpt: "Aluminium stovetop moka pot, six espresso cups, induction plate included.",
      description:
        "<p>The stovetop classic with a heavy base that works on gas, electric and induction. Six-cup size makes about 300 ml. Use a fine-medium grind — the Trailhead does it beautifully.</p>",
      priceMinor: USD(59),
      sku: "NS-BR-MOKA",
      stock: 27,
      weightOz: 24,
      attributes: {
        method: "stovetop",
        cups: 6,
        material: "aluminium",
        induction: true,
        grind: "fine-medium",
      },
      summary: "Six-cup stovetop moka pot, induction-ready.",
      imagePrompt: "a classic octagonal aluminium stovetop moka pot with a black handle",
    },
    {
      slug: "northstar-gooseneck-kettle",
      title: "Northstar Gooseneck Kettle",
      category: "brewers",
      excerpt: "Variable-temperature electric gooseneck, 0.9 L, holds temperature for an hour.",
      description:
        "<p>Precise pouring and precise heat. Set 92 °C for pour-over or 80 °C for tea, and the base holds it. 0.9 L capacity, 1200 W, counterbalanced handle.</p>",
      priceMinor: USD(79),
      sku: "NS-BR-KET",
      stock: 21,
      weightOz: 40,
      attributes: {
        electric: true,
        variable_temperature: true,
        capacity_l: 0.9,
        hold_temperature_min: 60,
        spout: "gooseneck",
        good_for: ["pour-over", "tea"],
      },
      summary: "Variable-temp gooseneck kettle for pour-over.",
      imagePrompt: "a matte black electric gooseneck kettle on its base with a small temperature display",
    },
    {
      slug: "precision-tamper-51mm",
      title: "51 mm Precision Tamper",
      category: "accessories",
      excerpt: "Machined stainless base, walnut handle. Fits 51 mm portafilters like the Compact 15.",
      description:
        "<p>A flat, precisely sized base gives a level bed and a repeatable puck. This one is 51 mm: it fits the Compact 15 and most compact home machines. It will not fit a 58 mm commercial group.</p>",
      priceMinor: USD(29),
      sku: "NS-AC-T51",
      stock: 60,
      weightOz: 12,
      attributes: {
        fits_portafilter_mm: 51,
        base: "flat stainless",
        handle: "walnut",
        not_compatible_with: "58 mm portafilters",
      },
      summary: "Flat 51 mm tamper — matches the Compact 15's portafilter.",
      imagePrompt: "a 51 mm espresso tamper with a polished stainless steel base and a walnut wood handle",
    },
    {
      slug: "precision-tamper-58mm",
      title: "58 mm Precision Tamper",
      category: "accessories",
      excerpt: "Machined 58.4 mm base for commercial groups like the Pro 58.",
      description:
        "<p>58.4 mm fills a commercial basket edge to edge. Fits the Pro 58 and any standard 58 mm group. Not for 51 mm machines.</p>",
      priceMinor: USD(39),
      sku: "NS-AC-T58",
      stock: 35,
      weightOz: 16,
      attributes: {
        fits_portafilter_mm: 58,
        base: "flat stainless 58.4",
        handle: "black walnut",
        not_compatible_with: "51 mm portafilters",
      },
      summary: "58.4 mm tamper for the Pro 58 and other commercial groups.",
      imagePrompt: "a heavy 58 mm espresso tamper with a dark walnut handle and a mirror-polished steel base",
    },
    {
      slug: "bottomless-portafilter-51mm",
      title: "51 mm Bottomless Portafilter",
      category: "accessories",
      excerpt: "Naked portafilter with a non-pressurised basket for the Compact 15.",
      description:
        "<p>See your extraction and step up from the pressurised basket. Includes an 18 g non-pressurised basket. Fits the Compact 15's 51 mm group; requires a grinder that can go fine, like the Meridian.</p>",
      priceMinor: USD(49),
      sku: "NS-AC-BP51",
      stock: 22,
      weightOz: 20,
      attributes: {
        fits_portafilter_mm: 51,
        basket_g: 18,
        pressurised: false,
        requires_espresso_grinder: true,
      },
      summary: "Naked 51 mm portafilter with an 18 g basket for the Compact 15.",
      imagePrompt: "a bottomless espresso portafilter with a black handle and an exposed metal basket",
    },
    {
      slug: "steaming-pitcher-12oz",
      title: "12 oz Steaming Pitcher",
      category: "accessories",
      excerpt: "Stainless pitcher with a sharp spout for latte art. Sized for one or two drinks.",
      description:
        "<p>12 oz is the right size for a home steam wand: enough milk for a latte, small enough to texture properly. Rolled spout, etched fill lines.</p>",
      priceMinor: USD(19),
      sku: "NS-AC-PIT",
      stock: 70,
      weightOz: 9,
      attributes: {
        capacity_oz: 12,
        material: "stainless steel",
        for: "steam wand milk texturing",
        fill_lines: true,
      },
      summary: "12 oz stainless pitcher for a home steam wand.",
      imagePrompt: "a stainless steel milk frothing pitcher with a sharp pointed spout",
    },
    {
      slug: "coffee-scale-0-1g",
      title: "Northstar Coffee Scale 0.1 g",
      category: "accessories",
      excerpt: "0.1 g resolution, built-in timer, fits under a portafilter or a dripper.",
      description:
        "<p>Weigh doses, time shots, watch pour-over ratios. Rechargeable, water-resistant top, auto-tare. Small enough for a drip tray.</p>",
      priceMinor: USD(45),
      sku: "NS-AC-SCL",
      stock: 44,
      weightOz: 10,
      attributes: {
        resolution_g: 0.1,
        timer: true,
        rechargeable: true,
        fits_drip_tray: true,
        good_for: ["espresso", "pour-over"],
      },
      summary: "0.1 g scale with a timer for dosing and pour-over.",
      imagePrompt: "a slim black digital coffee scale with a small LED display and a cup on it",
    },
    {
      slug: "paper-filters-02-100",
      title: "Size 02 Paper Filters (100)",
      category: "accessories",
      excerpt: "Oxygen-bleached cone filters for size 02 drippers like the Aurora.",
      description:
        "<p>Clean, quick-draining cone filters. One box is about three months of daily brewing. Size 02 fits the Aurora dripper.</p>",
      priceMinor: USD(9),
      sku: "NS-AC-F02",
      stock: 200,
      weightOz: 6,
      attributes: {
        filter_size: "02",
        count: 100,
        bleached: "oxygen",
        fits: "Aurora dripper and other size-02 cones",
      },
      summary: "100 size-02 cone filters for the Aurora dripper.",
      imagePrompt: "a stack of white cone-shaped paper coffee filters in a simple kraft box",
    },
    {
      slug: "aurora-espresso-blend-12oz",
      title: "Aurora Espresso Blend, 12 oz",
      category: "coffee-beans",
      excerpt: "Chocolate, dried cherry, a heavy body that stands up to milk.",
      description:
        "<p>Our house espresso: Brazil and Colombia roasted medium-dark for syrupy shots and sweet lattes. Roasted to order; rest four days before pulling.</p>",
      priceMinor: USD(18),
      sku: "NS-BN-AUR",
      stock: 120,
      weightOz: 13,
      attributes: {
        roast: "medium-dark",
        weight_oz: 12,
        whole_bean: true,
        best_for: ["espresso", "milk drinks", "moka"],
        notes: ["chocolate", "dried cherry", "brown sugar"],
      },
      summary: "House espresso blend, medium-dark, made for milk drinks.",
      imagePrompt: "a 12 oz kraft coffee bag with a simple burnt orange label reading Aurora, whole beans spilling beside it",
    },
    {
      slug: "ethiopia-natural-12oz",
      title: "Ethiopia Natural, 12 oz",
      category: "coffee-beans",
      excerpt: "Blueberry and jasmine. A light roast that sings on pour-over.",
      description:
        "<p>Sun-dried Guji lot roasted light. Bright and floral as a pour-over; as espresso it is fruit-forward and needs a slightly finer grind and a longer ratio.</p>",
      priceMinor: USD(19),
      sku: "NS-BN-ETH",
      stock: 80,
      weightOz: 13,
      attributes: {
        roast: "light",
        weight_oz: 12,
        whole_bean: true,
        best_for: ["pour-over", "filter"],
        notes: ["blueberry", "jasmine", "honey"],
      },
      summary: "Light-roast single origin, best on pour-over.",
      imagePrompt: "a 12 oz kraft coffee bag with a pale blue label reading Ethiopia Natural, a few light roasted beans beside it",
    },
    {
      slug: "decaf-nightfall-12oz",
      title: "Decaf Nightfall, 12 oz",
      category: "coffee-beans",
      excerpt: "Swiss Water decaf, medium roast, cocoa and toffee. Nobody notices.",
      description:
        "<p>A Colombian decaf that behaves like real coffee in every brewer. Medium roast, chemical-free process, works for espresso and drip.</p>",
      priceMinor: USD(17),
      sku: "NS-BN-DEC",
      stock: 60,
      weightOz: 13,
      attributes: {
        roast: "medium",
        weight_oz: 12,
        whole_bean: true,
        decaf: "Swiss Water",
        best_for: ["espresso", "drip", "evening"],
        notes: ["cocoa", "toffee"],
      },
      summary: "Swiss Water decaf that works for espresso and drip.",
      imagePrompt: "a 12 oz kraft coffee bag with a deep navy label reading Nightfall Decaf",
    },
    {
      slug: "descaling-solution-2-pack",
      title: "Descaling Solution, 2-Pack",
      category: "maintenance",
      excerpt: "Citric-based descaler safe for thermoblocks, boilers and capsule machines.",
      description:
        "<p>Scale is what kills home machines. Run one bottle through every two to three months — more often with hard water. Safe for aluminium thermoblocks, stainless boilers and capsule machines. Two bottles, two cycles.</p>",
      priceMinor: USD(14),
      sku: "NS-MT-DSC",
      stock: 150,
      weightOz: 20,
      attributes: {
        type: "descaler",
        cycles: 2,
        safe_for: ["thermoblock", "boiler", "capsule machines", "kettles"],
        interval: "every 2–3 months",
      },
      summary: "Two descaling cycles; safe for every machine we sell.",
      imagePrompt: "two small white bottles of coffee machine descaling solution with a minimal orange label",
    },
    {
      slug: "backflush-tablets-30",
      title: "Backflush Cleaning Tablets (30)",
      category: "maintenance",
      excerpt: "Espresso machine detergent tablets for machines with a three-way valve.",
      description:
        "<p>Weekly backflushing keeps the group head and valve free of rancid oils. Only for machines with a three-way solenoid valve like the Pro 58 — the Compact 15 and Pod Mini cannot be backflushed.</p>",
      priceMinor: USD(12),
      sku: "NS-MT-BF",
      stock: 90,
      weightOz: 4,
      attributes: {
        type: "backflush detergent",
        count: 30,
        requires: "three-way valve",
        not_for: ["Compact 15", "Pod Mini"],
        interval: "weekly",
      },
      summary: "For three-way-valve machines like the Pro 58 only.",
      imagePrompt: "a small clear jar of white espresso machine cleaning tablets with a simple label",
    },
  ],
  relations: [
    // Compact 15
    { from: "northstar-compact-15-espresso-machine", to: "precision-tamper-51mm", type: "accessory_of", weight: 0.95, evidence: "Sized for the Compact 15's 51 mm portafilter." },
    { from: "northstar-compact-15-espresso-machine", to: "bottomless-portafilter-51mm", type: "accessory_of", weight: 0.8, evidence: "Drops into the Compact 15's 51 mm group for non-pressurised shots." },
    { from: "northstar-compact-15-espresso-machine", to: "steaming-pitcher-12oz", type: "accessory_of", weight: 0.9, evidence: "The Compact 15 has a steam wand; 12 oz is the right pitcher size for it." },
    { from: "northstar-compact-15-espresso-machine", to: "coffee-scale-0-1g", type: "accessory_of", weight: 0.7, evidence: "Fits on the Compact 15's drip tray for dosing and timing shots." },
    { from: "northstar-compact-15-espresso-machine", to: "meridian-conical-burr-grinder", type: "accessory_of", weight: 0.9, evidence: "Grinds fine enough for a 15-bar machine; the Compact 15 has no built-in grinder." },
    { from: "northstar-compact-15-espresso-machine", to: "aurora-espresso-blend-12oz", type: "consumable_for", weight: 0.85, evidence: "Our house espresso blend, roasted for milk drinks." },
    { from: "northstar-compact-15-espresso-machine", to: "decaf-nightfall-12oz", type: "consumable_for", weight: 0.6, evidence: "Evening shots without the caffeine." },
    { from: "northstar-compact-15-espresso-machine", to: "descaling-solution-2-pack", type: "maintenance_for", weight: 0.95, evidence: "Thermoblock machines need descaling every 2–3 months." },
    { from: "northstar-compact-15-espresso-machine", to: "northstar-pro-58-dual-boiler", type: "upgrade_of", weight: 0.7, evidence: "Dual boiler and a 58 mm commercial group when you outgrow a thermoblock." },
    { from: "northstar-compact-15-espresso-machine", to: "northstar-pod-mini", type: "similar_to", weight: 0.4, evidence: "Also fits under a 15-inch cabinet, without a grinder." },
    // Pro 58
    { from: "northstar-pro-58-dual-boiler", to: "precision-tamper-58mm", type: "accessory_of", weight: 0.9, evidence: "58.4 mm base for the Pro 58's commercial basket." },
    { from: "northstar-pro-58-dual-boiler", to: "summit-flat-burr-grinder", type: "accessory_of", weight: 0.9, evidence: "Single-dose flat burrs match the Pro 58's precision." },
    { from: "northstar-pro-58-dual-boiler", to: "steaming-pitcher-12oz", type: "accessory_of", weight: 0.8, evidence: "Café-grade steam wand; one pitcher per drink." },
    { from: "northstar-pro-58-dual-boiler", to: "coffee-scale-0-1g", type: "accessory_of", weight: 0.7, evidence: "Time and weigh every shot." },
    { from: "northstar-pro-58-dual-boiler", to: "aurora-espresso-blend-12oz", type: "consumable_for", weight: 0.85, evidence: "House espresso blend." },
    { from: "northstar-pro-58-dual-boiler", to: "ethiopia-natural-12oz", type: "consumable_for", weight: 0.6, evidence: "Fruit-forward light roast for a change of pace." },
    { from: "northstar-pro-58-dual-boiler", to: "backflush-tablets-30", type: "maintenance_for", weight: 0.95, evidence: "The Pro 58 has a three-way valve; backflush weekly." },
    { from: "northstar-pro-58-dual-boiler", to: "descaling-solution-2-pack", type: "maintenance_for", weight: 0.8, evidence: "Descale the boilers every few months." },
    // Pod Mini
    { from: "northstar-pod-mini", to: "descaling-solution-2-pack", type: "maintenance_for", weight: 0.9, evidence: "Capsule machines scale up fast; descale every 2–3 months." },
    { from: "northstar-pod-mini", to: "northstar-compact-15-espresso-machine", type: "upgrade_of", weight: 0.6, evidence: "Real portafilter espresso in the same cabinet height." },
    // Grinders
    { from: "meridian-conical-burr-grinder", to: "aurora-espresso-blend-12oz", type: "consumable_for", weight: 0.7, evidence: "Whole beans for the grinder." },
    { from: "meridian-conical-burr-grinder", to: "ethiopia-natural-12oz", type: "consumable_for", weight: 0.6, evidence: "Grinds medium for pour-over too." },
    { from: "meridian-conical-burr-grinder", to: "summit-flat-burr-grinder", type: "upgrade_of", weight: 0.6, evidence: "Flat burrs and single dosing for espresso clarity." },
    { from: "meridian-conical-burr-grinder", to: "trailhead-hand-grinder", type: "similar_to", weight: 0.4, evidence: "Same burr geometry, hand-powered and half the price." },
    { from: "trailhead-hand-grinder", to: "ethiopia-natural-12oz", type: "consumable_for", weight: 0.7, evidence: "Light roasts shine on pour-over." },
    { from: "trailhead-hand-grinder", to: "meridian-conical-burr-grinder", type: "upgrade_of", weight: 0.6, evidence: "Electric, with 30 repeatable settings." },
    { from: "summit-flat-burr-grinder", to: "aurora-espresso-blend-12oz", type: "consumable_for", weight: 0.7, evidence: "Beans for the grinder." },
    // Brewers
    { from: "aurora-pour-over-dripper", to: "paper-filters-02-100", type: "consumable_for", weight: 0.98, evidence: "Size 02 filters fit the Aurora exactly." },
    { from: "aurora-pour-over-dripper", to: "northstar-gooseneck-kettle", type: "accessory_of", weight: 0.9, evidence: "A gooseneck gives the slow, even pour the Aurora wants." },
    { from: "aurora-pour-over-dripper", to: "trailhead-hand-grinder", type: "accessory_of", weight: 0.8, evidence: "Medium grind for pour-over, no electricity needed." },
    { from: "aurora-pour-over-dripper", to: "coffee-scale-0-1g", type: "accessory_of", weight: 0.7, evidence: "Hit a 1:16 ratio every time." },
    { from: "aurora-pour-over-dripper", to: "ethiopia-natural-12oz", type: "consumable_for", weight: 0.85, evidence: "Our best pour-over coffee." },
    { from: "northstar-moka-6", to: "trailhead-hand-grinder", type: "accessory_of", weight: 0.8, evidence: "Fine-medium grind for moka." },
    { from: "northstar-moka-6", to: "aurora-espresso-blend-12oz", type: "consumable_for", weight: 0.8, evidence: "Medium-dark blends suit stovetop brewing." },
    { from: "northstar-gooseneck-kettle", to: "aurora-pour-over-dripper", type: "accessory_of", weight: 0.8, evidence: "The dripper this kettle was made for." },
    { from: "northstar-gooseneck-kettle", to: "descaling-solution-2-pack", type: "maintenance_for", weight: 0.6, evidence: "Kettles scale too; the descaler is safe for them." },
    // Accessories
    { from: "precision-tamper-51mm", to: "bottomless-portafilter-51mm", type: "bundle_with", weight: 0.7, evidence: "Tamper and naked portafilter are the classic 51 mm upgrade pair." },
    { from: "bottomless-portafilter-51mm", to: "meridian-conical-burr-grinder", type: "accessory_of", weight: 0.8, evidence: "A non-pressurised basket needs a real espresso grinder." },
    { from: "steaming-pitcher-12oz", to: "aurora-espresso-blend-12oz", type: "consumable_for", weight: 0.5, evidence: "A blend built for milk." },
    { from: "coffee-scale-0-1g", to: "paper-filters-02-100", type: "bundle_with", weight: 0.4, evidence: "Weighed pour-over needs filters." },
    // Beans
    { from: "aurora-espresso-blend-12oz", to: "ethiopia-natural-12oz", type: "similar_to", weight: 0.4, evidence: "Try the light roast next." },
    { from: "ethiopia-natural-12oz", to: "paper-filters-02-100", type: "bundle_with", weight: 0.5, evidence: "Pour-over coffee needs filters." },
  ],
};
