/**
 * Demo shop: Ridgeline Cycles — bikes, drivetrain, tires and the parts that
 * only fit some of them. Built to show standards-based compatibility:
 * 29" vs 700c, 12-speed vs 9-speed, hydraulic vs mechanical brake pads.
 */

import type { DemoShop } from "./types";

const USD = (dollars: number) => Math.round(dollars * 100);

export const ridgelineCycles: DemoShop = {
  key: "ridgeline-cycles",
  siteTitle: "Ridgeline Cycles",
  tagline: "Parts that fit. Rides that don't stop.",
  storeName: "Ridgeline Cycles",
  storeEmail: "shop@ridgeline.bike",
  currencyCode: "USD",
  currencySymbol: "$",
  brand: {
    moodPrompt:
      "Technical, bold, high-contrast. A trail shop that is precise about standards. Deep slate and charcoal, an electric chartreuse accent, tight geometric sans, dense product grids, mono type for specs.",
    voice: "direct, knowledgeable, a little dry; never oversells",
    industry: "bicycle shop",
    hardRules: [
      "Always state the wheel size, speed count and brake type a part fits.",
      "Never suggest a chain or cassette that does not match the bike's speed count.",
    ],
    typography: { display: "Space Grotesk", body: "Inter", scale: "compact" },
    density: "compact",
    radius: "subtle",
  },
  palette: [
    { slug: "background", name: "Slate", color: "#14181d" },
    { slug: "foreground", name: "Chalk", color: "#e8ecef" },
    { slug: "card", name: "Charcoal", color: "#1d2329" },
    { slug: "card-foreground", name: "Chalk", color: "#e8ecef" },
    { slug: "popover", name: "Charcoal", color: "#1d2329" },
    { slug: "popover-foreground", name: "Chalk", color: "#e8ecef" },
    { slug: "primary", name: "Chartreuse", color: "#c6f135" },
    { slug: "primary-foreground", name: "Slate", color: "#101317" },
    { slug: "secondary", name: "Graphite", color: "#2a323a" },
    { slug: "secondary-foreground", name: "Chalk", color: "#e8ecef" },
    { slug: "muted", name: "Graphite", color: "#242b32" },
    { slug: "muted-foreground", name: "Fog", color: "#9aa5af" },
    { slug: "accent", name: "Graphite", color: "#2a323a" },
    { slug: "accent-foreground", name: "Chalk", color: "#e8ecef" },
    { slug: "border", name: "Steel", color: "#313a43" },
    { slug: "input", name: "Steel", color: "#313a43" },
    { slug: "ring", name: "Chartreuse", color: "#c6f135" },
  ],
  imageStyle:
    "clean studio product photograph on a dark slate seamless backdrop, crisp rim lighting, subtle reflection, no text, no people, centered, technical catalog style, photorealistic",
  assistant: {
    displayName: "Ridgeline mechanic",
    tagline: "Checks fit before it suggests.",
    tone: "direct, knowledgeable, a little dry; names the standard every part must match",
    starterPrompts: [
      "What chain fits the Traverse 29?",
      "Set me up tubeless",
      "Which pads fit my brakes?",
    ],
    disclosureText:
      "Fit suggestions come from your cart and search. Double-check standards before you buy.",
  },
  categories: [
    { slug: "bikes", name: "Bikes", description: "Trail, gravel and commute, built in-house.", sortOrder: 1 },
    { slug: "drivetrain", name: "Drivetrain", description: "Chains, cassettes and lube by speed count.", sortOrder: 2 },
    { slug: "tires-tubes", name: "Tires & tubes", description: "By wheel size: 29 inch and 700c.", sortOrder: 3 },
    { slug: "brakes", name: "Brakes", description: "Pads and rotors for hydraulic and mechanical discs.", sortOrder: 4 },
    { slug: "accessories", name: "Accessories", description: "Pumps, lights and tools for every ride.", sortOrder: 5 },
  ],
  products: [
    {
      slug: "ridgeline-traverse-29-hardtail",
      title: "Ridgeline Traverse 29 Hardtail",
      category: "bikes",
      excerpt: "Trail hardtail on 29-inch wheels, 12-speed 1x, hydraulic discs, tubeless-ready.",
      description:
        "<p>The Traverse is our do-everything trail hardtail. 29 × 2.4 tubeless-ready wheels, a 12-speed 1x drivetrain with an 11–50T cassette, four-piston hydraulic disc brakes on 180 mm rotors, Boost 148 rear spacing.</p><p>Ships tubeless-ready with tubes installed; add sealant and valves to convert.</p>",
      priceMinor: USD(1499),
      sku: "RL-TRV29",
      stock: 5,
      weightOz: 470,
      attributes: {
        wheel_size: "29 in",
        tire_clearance: "29 x 2.6",
        speeds: 12,
        drivetrain: "1x12",
        cassette: "11-50T",
        brakes: "hydraulic disc",
        rotor_mm: 180,
        rear_spacing: "Boost 148",
        tubeless_ready: true,
        valve: "presta",
        use: ["trail", "singletrack"],
      },
      summary: "29 in wheels, 12-speed, hydraulic discs with 180 mm rotors.",
      imagePrompt: "a modern trail hardtail mountain bike with 29 inch knobby tires, matte olive frame, black components, side profile",
    },
    {
      slug: "ridgeline-commute-700c",
      title: "Ridgeline Commute 700c Flat Bar",
      category: "bikes",
      excerpt: "A no-drama city bike: 700c wheels, 9-speed, mechanical disc brakes, rack mounts.",
      description:
        "<p>Built for daily miles. 700 × 32c tires, a 9-speed drivetrain that is cheap to maintain, mechanical disc brakes on 160 mm rotors, fender and rack mounts. Runs tubes; it is not a tubeless bike.</p>",
      priceMinor: USD(899),
      sku: "RL-CMT",
      stock: 8,
      weightOz: 440,
      attributes: {
        wheel_size: "700c",
        tire_clearance: "700 x 38c",
        speeds: 9,
        drivetrain: "1x9",
        brakes: "mechanical disc",
        rotor_mm: 160,
        tubeless_ready: false,
        valve: "presta",
        mounts: ["rack", "fenders"],
        use: ["commute", "city"],
      },
      summary: "700c, 9-speed, mechanical discs — tubes only.",
      imagePrompt: "a clean flat-bar commuter bicycle with 700c wheels, slim tires, dark teal frame, rear rack, side profile",
    },
    {
      slug: "ridgeline-gravel-ascent",
      title: "Ridgeline Gravel Ascent",
      category: "bikes",
      excerpt: "Drop-bar gravel bike, 700c tubeless, 12-speed 1x, hydraulic discs on 160 mm rotors.",
      description:
        "<p>Long days on dirt roads. 700 × 40c tubeless-ready tires, 12-speed 1x with an 11–50T cassette, hydraulic disc brakes on 160 mm rotors, three bottle mounts. Shares its chain and cassette standard with the Traverse; wheel size with the Commute.</p>",
      priceMinor: USD(1899),
      sku: "RL-GRV",
      stock: 4,
      weightOz: 400,
      attributes: {
        wheel_size: "700c",
        tire_clearance: "700 x 45c",
        speeds: 12,
        drivetrain: "1x12",
        cassette: "11-50T",
        brakes: "hydraulic disc",
        rotor_mm: 160,
        tubeless_ready: true,
        valve: "presta",
        use: ["gravel", "endurance"],
      },
      summary: "700c tubeless, 12-speed, hydraulic discs with 160 mm rotors.",
      imagePrompt: "a drop-bar gravel bicycle with 700c wheels and knobby tires, sand colored frame, side profile",
    },
    {
      slug: "chain-12-speed-126",
      title: "12-Speed Chain, 126 Links",
      category: "drivetrain",
      excerpt: "Narrow 12-speed chain with a quick link. Fits the Traverse and the Ascent.",
      description:
        "<p>12-speed chains are narrower than 9- or 11-speed and only run on 12-speed cassettes. 126 links covers a 50T cassette with room to trim. Quick link included.</p>",
      priceMinor: USD(34),
      sku: "RL-CH12",
      stock: 30,
      weightOz: 10,
      attributes: {
        speeds: 12,
        links: 126,
        quick_link: true,
        fits: ["12-speed drivetrains"],
        not_for: ["9-speed", "11-speed"],
      },
      summary: "12-speed only — fits the Traverse 29 and Gravel Ascent.",
      imagePrompt: "a coiled silver 12-speed bicycle chain with a gold quick link",
    },
    {
      slug: "chain-9-speed",
      title: "9-Speed Chain",
      category: "drivetrain",
      excerpt: "Wide, durable 9-speed chain for commuters. Fits the Commute 700c.",
      description:
        "<p>Nine-speed chains are wider and last longer. This one fits 9-speed cassettes only; it will jam on 12-speed cogs. Quick link included.</p>",
      priceMinor: USD(19),
      sku: "RL-CH9",
      stock: 40,
      weightOz: 11,
      attributes: {
        speeds: 9,
        links: 116,
        quick_link: true,
        fits: ["9-speed drivetrains"],
        not_for: ["12-speed"],
      },
      summary: "9-speed only — fits the Commute 700c.",
      imagePrompt: "a coiled dark grey 9-speed bicycle chain with a quick link",
    },
    {
      slug: "cassette-11-50t-12-speed",
      title: "11–50T 12-Speed Cassette",
      category: "drivetrain",
      excerpt: "Replacement wide-range cassette for 12-speed 1x bikes.",
      description:
        "<p>The same 11–50T cassette the Traverse and Ascent ship with. HG-style freehub body. Replace with the chain when the teeth shark-fin.</p>",
      priceMinor: USD(129),
      sku: "RL-CS1250",
      stock: 12,
      weightOz: 18,
      attributes: {
        speeds: 12,
        range: "11-50T",
        freehub: "HG",
        fits: ["Traverse 29", "Gravel Ascent"],
        not_for: ["9-speed"],
      },
      summary: "12-speed 11–50T; replace together with the chain.",
      imagePrompt: "a large black 12-speed wide-range bicycle cassette standing on edge",
    },
    {
      slug: "chain-lube-wet-4oz",
      title: "Wet Chain Lube, 4 oz",
      category: "drivetrain",
      excerpt: "Long-lasting wet lube for mud, rain and trail.",
      description:
        "<p>Wet lube clings through water crossings and rain. Reapply every 100 miles or after a wet ride. Best for trail and winter; picks up more dust than dry lube.</p>",
      priceMinor: USD(12),
      sku: "RL-LB-WET",
      stock: 90,
      weightOz: 5,
      attributes: {
        type: "wet",
        size_oz: 4,
        conditions: ["wet", "mud", "trail"],
        interval: "every 100 miles",
      },
      summary: "For wet and muddy riding; reapply every 100 miles.",
      imagePrompt: "a small bottle of bicycle chain lubricant with a drip tip and a dark green label",
    },
    {
      slug: "chain-lube-dry-4oz",
      title: "Dry Chain Lube, 4 oz",
      category: "drivetrain",
      excerpt: "Clean-running dry lube for pavement and dust.",
      description:
        "<p>Dry lube keeps a commuter chain clean and quiet. Reapply every 50 miles. Not for rain.</p>",
      priceMinor: USD(12),
      sku: "RL-LB-DRY",
      stock: 80,
      weightOz: 5,
      attributes: {
        type: "dry",
        size_oz: 4,
        conditions: ["dry", "pavement", "dust"],
        interval: "every 50 miles",
      },
      summary: "For dry, paved riding; keeps commuter chains clean.",
      imagePrompt: "a small bottle of dry bicycle chain lubricant with a white label",
    },
    {
      slug: "tire-29x2-4-trail-tubeless",
      title: "29 × 2.4 Trail Tire, Tubeless-Ready",
      category: "tires-tubes",
      excerpt: "Aggressive trail tread for 29-inch wheels. Runs tubeless or with a 29 tube.",
      description:
        "<p>Fits 29-inch rims with 2.6 inch clearance or more. Tubeless-ready bead; pair with sealant, or run a 29 inch tube. Will not fit 700c road rims of narrow width.</p>",
      priceMinor: USD(69),
      sku: "RL-TR29",
      stock: 20,
      weightOz: 32,
      attributes: {
        wheel_size: "29 in",
        width: "2.4 in",
        tubeless_ready: true,
        fits: ["Traverse 29"],
        not_for: ["700c commuter rims"],
      },
      summary: "29 × 2.4 tubeless-ready — fits the Traverse 29.",
      imagePrompt: "a single 29 inch knobby mountain bike tire standing upright",
    },
    {
      slug: "tire-700x40c-gravel",
      title: "700 × 40c Gravel Tire",
      category: "tires-tubes",
      excerpt: "Fast-rolling file tread for gravel. Tubeless-ready, fits the Ascent.",
      description:
        "<p>40 mm wide, tubeless-ready, fits 700c frames with 45c clearance like the Gravel Ascent. Too wide for the Commute's 38c clearance.</p>",
      priceMinor: USD(59),
      sku: "RL-TG40",
      stock: 24,
      weightOz: 18,
      attributes: {
        wheel_size: "700c",
        width: "40c",
        tubeless_ready: true,
        fits: ["Gravel Ascent"],
        not_for: ["Commute 700c (max 38c)", "29 in rims"],
      },
      summary: "700 × 40c tubeless — fits the Gravel Ascent, too wide for the Commute.",
      imagePrompt: "a single 700c gravel bicycle tire with a fine file tread standing upright",
    },
    {
      slug: "tire-700x32c-commuter",
      title: "700 × 32c Commuter Tire",
      category: "tires-tubes",
      excerpt: "Puncture-belted slick for city miles. Fits the Commute and the Ascent.",
      description:
        "<p>32 mm slick with a puncture belt and reflective sidewall. Tube-type only. Fits the Commute 700c and, for road days, the Gravel Ascent.</p>",
      priceMinor: USD(39),
      sku: "RL-TC32",
      stock: 30,
      weightOz: 14,
      attributes: {
        wheel_size: "700c",
        width: "32c",
        tubeless_ready: false,
        reflective_sidewall: true,
        fits: ["Commute 700c", "Gravel Ascent"],
        not_for: ["29 in rims"],
      },
      summary: "700 × 32c tube-type — fits the Commute and the Ascent.",
      imagePrompt: "a single 700c slick commuter bicycle tire with a reflective sidewall stripe",
    },
    {
      slug: "tubeless-sealant-8oz",
      title: "Tubeless Sealant, 8 oz",
      category: "tires-tubes",
      excerpt: "Latex sealant for tubeless setups. Two tires per bottle.",
      description:
        "<p>Seals punctures up to 6 mm. Use 2–3 oz per tire; refresh every three months. Only for tubeless-ready tires and rims — it does nothing inside a tube.</p>",
      priceMinor: USD(14),
      sku: "RL-SEAL",
      stock: 60,
      weightOz: 9,
      attributes: {
        size_oz: 8,
        tires_per_bottle: 2,
        requires: "tubeless-ready tire and rim",
        not_for: ["tube setups"],
        interval: "refresh every 3 months",
      },
      summary: "For tubeless setups only; refresh every three months.",
      imagePrompt: "a squeeze bottle of white tubeless tire sealant with a black cap",
    },
    {
      slug: "tube-29-presta-48",
      title: "29-Inch Tube, Presta 48 mm",
      category: "tires-tubes",
      excerpt: "Spare or everyday tube for 29 × 2.1–2.6 tires.",
      description:
        "<p>Butyl tube for 29 inch tires from 2.1 to 2.6 inches wide with a 48 mm presta valve. Carry one even if you ride tubeless.</p>",
      priceMinor: USD(9),
      sku: "RL-TB29",
      stock: 100,
      weightOz: 7,
      attributes: {
        wheel_size: "29 in",
        width_range: "2.1-2.6 in",
        valve: "presta 48 mm",
        fits: ["Traverse 29"],
        not_for: ["700c"],
      },
      summary: "29 in tube — spare for the Traverse even when tubeless.",
      imagePrompt: "a folded black bicycle inner tube with a presta valve on a dark backdrop",
    },
    {
      slug: "tube-700c-presta-48",
      title: "700c Tube, Presta 48 mm",
      category: "tires-tubes",
      excerpt: "Tube for 700 × 28–45c tires. Fits the Commute and the Ascent.",
      description:
        "<p>Butyl tube for 700c tires from 28 to 45 mm wide, 48 mm presta valve. Everyday tube for the Commute; emergency spare for the tubeless Ascent.</p>",
      priceMinor: USD(8),
      sku: "RL-TB700",
      stock: 120,
      weightOz: 5,
      attributes: {
        wheel_size: "700c",
        width_range: "28-45c",
        valve: "presta 48 mm",
        fits: ["Commute 700c", "Gravel Ascent"],
        not_for: ["29 in"],
      },
      summary: "700c tube — fits the Commute and the Ascent.",
      imagePrompt: "a folded black 700c bicycle inner tube with a long presta valve",
    },
    {
      slug: "brake-pads-hydraulic-resin",
      title: "Hydraulic Disc Brake Pads, Resin",
      category: "brakes",
      excerpt: "Quiet resin pads for Ridgeline hydraulic calipers on the Traverse and Ascent.",
      description:
        "<p>Resin compound, quiet and strong in the dry. Fits the four-piston hydraulic calipers on the Traverse 29 and Gravel Ascent. Not compatible with the Commute's mechanical calipers.</p>",
      priceMinor: USD(18),
      sku: "RL-PD-HYD",
      stock: 45,
      weightOz: 2,
      attributes: {
        brake_type: "hydraulic disc",
        compound: "resin",
        fits: ["Traverse 29", "Gravel Ascent"],
        not_for: ["Commute 700c mechanical calipers"],
        pairs: 1,
      },
      summary: "Fits the hydraulic calipers on the Traverse and the Ascent.",
      imagePrompt: "a pair of bicycle hydraulic disc brake pads with springs on a dark backdrop",
    },
    {
      slug: "brake-pads-mechanical",
      title: "Mechanical Disc Brake Pads",
      category: "brakes",
      excerpt: "Semi-metallic pads for cable-actuated disc calipers like the Commute's.",
      description:
        "<p>Semi-metallic compound for mechanical disc calipers. Fits the Commute 700c. Different shape from the hydraulic pads; they do not interchange.</p>",
      priceMinor: USD(14),
      sku: "RL-PD-MEC",
      stock: 40,
      weightOz: 2,
      attributes: {
        brake_type: "mechanical disc",
        compound: "semi-metallic",
        fits: ["Commute 700c"],
        not_for: ["hydraulic calipers"],
        pairs: 1,
      },
      summary: "Fits the Commute's mechanical calipers only.",
      imagePrompt: "a pair of semi-metallic bicycle disc brake pads with a retaining pin",
    },
    {
      slug: "rotor-180mm-6-bolt",
      title: "180 mm Rotor, 6-Bolt",
      category: "brakes",
      excerpt: "Replacement 180 mm rotor for the Traverse. Needs an adapter on 160 mm bikes.",
      description:
        "<p>Stainless 180 mm rotor, 6-bolt mount. Drop-in replacement for the Traverse 29. The Ascent and Commute run 160 mm; fitting 180 mm there requires a caliper adapter.</p>",
      priceMinor: USD(32),
      sku: "RL-RT180",
      stock: 16,
      weightOz: 6,
      attributes: {
        diameter_mm: 180,
        mount: "6-bolt",
        fits: ["Traverse 29"],
        needs_adapter_on: ["Gravel Ascent", "Commute 700c"],
      },
      summary: "Direct fit for the Traverse; adapter needed on 160 mm bikes.",
      imagePrompt: "a stainless steel 180 mm bicycle disc brake rotor with cutouts",
    },
    {
      slug: "frame-pump-presta-schrader",
      title: "Frame Pump, Presta/Schrader",
      category: "accessories",
      excerpt: "High-volume mini pump with a hose. Seats tubeless tires in a pinch.",
      description:
        "<p>Mounts under a bottle cage. Auto-select head for presta and schrader, flexible hose, 100 psi max. High volume mode gets a 29 tire up fast.</p>",
      priceMinor: USD(29),
      sku: "RL-PMP",
      stock: 35,
      weightOz: 6,
      attributes: {
        valves: ["presta", "schrader"],
        max_psi: 100,
        mount: "bottle cage",
        hose: true,
      },
      summary: "Fits presta and schrader; mounts under a bottle cage.",
      imagePrompt: "a compact aluminium bicycle mini pump with a flexible hose and frame mount",
    },
    {
      slug: "light-set-usb-c",
      title: "Front & Rear Light Set, USB-C",
      category: "accessories",
      excerpt: "600-lumen front, 50-lumen rear, both USB-C. Fits any handlebar and seatpost.",
      description:
        "<p>Be seen and see the road. 600 lumens up front with a cut-off beam, a 50-lumen rear with a brake-sensing flash. Silicone straps fit round and aero posts.</p>",
      priceMinor: USD(49),
      sku: "RL-LGT",
      stock: 28,
      weightOz: 8,
      attributes: {
        front_lumens: 600,
        rear_lumens: 50,
        charging: "USB-C",
        runtime_h: "3-20",
        fits: ["any bike"],
      },
      summary: "USB-C front and rear lights; fit any bike.",
      imagePrompt: "a compact bicycle front headlight and a small red rear light side by side",
    },
    {
      slug: "multi-tool-19",
      title: "19-Function Multi-Tool",
      category: "accessories",
      excerpt: "Hex keys, Torx, chain breaker and a quick-link tool in 150 g.",
      description:
        "<p>Everything a trailside fix needs: 2–8 mm hex, T25, spoke keys, a chain breaker that handles 9- to 12-speed chains and a quick-link pliers.</p>",
      priceMinor: USD(27),
      sku: "RL-TOOL",
      stock: 50,
      weightOz: 5,
      attributes: {
        functions: 19,
        chain_breaker: "9-12 speed",
        quick_link_tool: true,
        weight_g: 150,
        fits: ["any bike"],
      },
      summary: "Trailside tool with a 9–12 speed chain breaker.",
      imagePrompt: "a folding bicycle multi-tool with hex keys fanned out, matte black",
    },
  ],
  relations: [
    // Traverse 29 (29 in, 12-speed, hydraulic, 180 mm)
    { from: "ridgeline-traverse-29-hardtail", to: "chain-12-speed-126", type: "consumable_for", weight: 0.95, evidence: "The Traverse runs a 12-speed drivetrain; this is the matching chain." },
    { from: "ridgeline-traverse-29-hardtail", to: "cassette-11-50t-12-speed", type: "consumable_for", weight: 0.8, evidence: "Same 11–50T 12-speed cassette the Traverse ships with." },
    { from: "ridgeline-traverse-29-hardtail", to: "tire-29x2-4-trail-tubeless", type: "consumable_for", weight: 0.9, evidence: "29 × 2.4 fits the Traverse's 29 in wheels and 2.6 in clearance." },
    { from: "ridgeline-traverse-29-hardtail", to: "tubeless-sealant-8oz", type: "accessory_of", weight: 0.9, evidence: "The Traverse is tubeless-ready; sealant converts it." },
    { from: "ridgeline-traverse-29-hardtail", to: "tube-29-presta-48", type: "accessory_of", weight: 0.8, evidence: "29 in spare tube for the Traverse, even when tubeless." },
    { from: "ridgeline-traverse-29-hardtail", to: "brake-pads-hydraulic-resin", type: "maintenance_for", weight: 0.9, evidence: "Fits the Traverse's hydraulic four-piston calipers." },
    { from: "ridgeline-traverse-29-hardtail", to: "rotor-180mm-6-bolt", type: "maintenance_for", weight: 0.8, evidence: "Direct replacement for the Traverse's 180 mm rotors." },
    { from: "ridgeline-traverse-29-hardtail", to: "chain-lube-wet-4oz", type: "consumable_for", weight: 0.85, evidence: "Wet lube for trail and mud." },
    { from: "ridgeline-traverse-29-hardtail", to: "frame-pump-presta-schrader", type: "accessory_of", weight: 0.7, evidence: "High-volume mode suits 29 in tires." },
    { from: "ridgeline-traverse-29-hardtail", to: "light-set-usb-c", type: "accessory_of", weight: 0.6, evidence: "Fits any handlebar and seatpost." },
    { from: "ridgeline-traverse-29-hardtail", to: "multi-tool-19", type: "accessory_of", weight: 0.7, evidence: "Chain breaker handles 12-speed chains." },
    { from: "ridgeline-traverse-29-hardtail", to: "ridgeline-gravel-ascent", type: "similar_to", weight: 0.4, evidence: "Same 12-speed drivetrain, drop bars and 700c wheels instead." },
    // Commute 700c (9-speed, mechanical, tubes)
    { from: "ridgeline-commute-700c", to: "chain-9-speed", type: "consumable_for", weight: 0.95, evidence: "The Commute is 9-speed; a 12-speed chain will not fit." },
    { from: "ridgeline-commute-700c", to: "tire-700x32c-commuter", type: "consumable_for", weight: 0.9, evidence: "700 × 32c fits the Commute's 38c clearance." },
    { from: "ridgeline-commute-700c", to: "tube-700c-presta-48", type: "consumable_for", weight: 0.9, evidence: "The Commute runs tubes; 700c 28–45c." },
    { from: "ridgeline-commute-700c", to: "brake-pads-mechanical", type: "maintenance_for", weight: 0.9, evidence: "Fits the Commute's cable-actuated calipers." },
    { from: "ridgeline-commute-700c", to: "chain-lube-dry-4oz", type: "consumable_for", weight: 0.85, evidence: "Dry lube keeps a pavement chain clean." },
    { from: "ridgeline-commute-700c", to: "light-set-usb-c", type: "accessory_of", weight: 0.9, evidence: "Lights for commuting; fit any bike." },
    { from: "ridgeline-commute-700c", to: "frame-pump-presta-schrader", type: "accessory_of", weight: 0.7, evidence: "Fits the Commute's presta valves." },
    { from: "ridgeline-commute-700c", to: "multi-tool-19", type: "accessory_of", weight: 0.6, evidence: "Chain breaker handles 9-speed chains." },
    { from: "ridgeline-commute-700c", to: "ridgeline-gravel-ascent", type: "upgrade_of", weight: 0.6, evidence: "Same 700c wheel size with tubeless tires, 12-speed and hydraulic brakes." },
    // Gravel Ascent (700c tubeless, 12-speed, hydraulic, 160 mm)
    { from: "ridgeline-gravel-ascent", to: "chain-12-speed-126", type: "consumable_for", weight: 0.95, evidence: "The Ascent runs the same 12-speed drivetrain as the Traverse." },
    { from: "ridgeline-gravel-ascent", to: "cassette-11-50t-12-speed", type: "consumable_for", weight: 0.8, evidence: "Matching 11–50T 12-speed cassette." },
    { from: "ridgeline-gravel-ascent", to: "tire-700x40c-gravel", type: "consumable_for", weight: 0.9, evidence: "700 × 40c fits the Ascent's 45c clearance." },
    { from: "ridgeline-gravel-ascent", to: "tire-700x32c-commuter", type: "compatible_with", weight: 0.6, evidence: "Narrow road slick for pavement days on the Ascent." },
    { from: "ridgeline-gravel-ascent", to: "tubeless-sealant-8oz", type: "accessory_of", weight: 0.9, evidence: "The Ascent is tubeless-ready." },
    { from: "ridgeline-gravel-ascent", to: "tube-700c-presta-48", type: "accessory_of", weight: 0.7, evidence: "700c emergency tube for the tubeless Ascent." },
    { from: "ridgeline-gravel-ascent", to: "brake-pads-hydraulic-resin", type: "maintenance_for", weight: 0.9, evidence: "Fits the Ascent's hydraulic calipers." },
    { from: "ridgeline-gravel-ascent", to: "rotor-180mm-6-bolt", type: "compatible_with", weight: 0.4, evidence: "The Ascent ships with 160 mm rotors; 180 mm needs a caliper adapter." },
    { from: "ridgeline-gravel-ascent", to: "chain-lube-wet-4oz", type: "consumable_for", weight: 0.7, evidence: "Wet lube for gravel and rain." },
    { from: "ridgeline-gravel-ascent", to: "chain-lube-dry-4oz", type: "consumable_for", weight: 0.6, evidence: "Dry lube for dusty summer gravel." },
    { from: "ridgeline-gravel-ascent", to: "frame-pump-presta-schrader", type: "accessory_of", weight: 0.7, evidence: "Fits under a bottle cage." },
    { from: "ridgeline-gravel-ascent", to: "light-set-usb-c", type: "accessory_of", weight: 0.6, evidence: "Fits drop bars and round posts." },
    { from: "ridgeline-gravel-ascent", to: "multi-tool-19", type: "accessory_of", weight: 0.7, evidence: "12-speed chain breaker on board." },
    // Parts → parts
    { from: "chain-12-speed-126", to: "cassette-11-50t-12-speed", type: "bundle_with", weight: 0.8, evidence: "Replace chain and cassette together on 12-speed bikes." },
    { from: "chain-12-speed-126", to: "chain-lube-wet-4oz", type: "consumable_for", weight: 0.6, evidence: "Lube a new chain after the factory grease wears off." },
    { from: "chain-12-speed-126", to: "multi-tool-19", type: "accessory_of", weight: 0.5, evidence: "Quick-link pliers and a 12-speed chain breaker." },
    { from: "chain-9-speed", to: "chain-lube-dry-4oz", type: "consumable_for", weight: 0.6, evidence: "Dry lube for commuter chains." },
    { from: "cassette-11-50t-12-speed", to: "chain-12-speed-126", type: "bundle_with", weight: 0.8, evidence: "A new cassette wants a new chain." },
    { from: "tire-29x2-4-trail-tubeless", to: "tubeless-sealant-8oz", type: "accessory_of", weight: 0.9, evidence: "Tubeless-ready tire; sealant seals it." },
    { from: "tire-29x2-4-trail-tubeless", to: "tube-29-presta-48", type: "compatible_with", weight: 0.7, evidence: "Run it with a 29 in tube instead of sealant." },
    { from: "tire-700x40c-gravel", to: "tubeless-sealant-8oz", type: "accessory_of", weight: 0.9, evidence: "Tubeless-ready; two tires per bottle." },
    { from: "tire-700x40c-gravel", to: "tube-700c-presta-48", type: "compatible_with", weight: 0.7, evidence: "700c tube fits 28–45c." },
    { from: "tire-700x32c-commuter", to: "tube-700c-presta-48", type: "accessory_of", weight: 0.95, evidence: "Tube-type tire; needs a 700c tube." },
    { from: "tubeless-sealant-8oz", to: "frame-pump-presta-schrader", type: "accessory_of", weight: 0.5, evidence: "High-volume pump helps seat tubeless beads." },
    { from: "brake-pads-hydraulic-resin", to: "rotor-180mm-6-bolt", type: "bundle_with", weight: 0.5, evidence: "New pads on a worn rotor glaze fast." },
    { from: "chain-lube-wet-4oz", to: "chain-lube-dry-4oz", type: "similar_to", weight: 0.4, evidence: "Dry alternative for clean conditions." },
    { from: "light-set-usb-c", to: "multi-tool-19", type: "bundle_with", weight: 0.4, evidence: "Commuter essentials." },
  ],
};
