/* Generated by scripts/admin/generate-control-bindings.mjs. Do not edit. */
import { anyApi, componentsGeneric } from "convex/server";
export const api = anyApi;
export const internal = anyApi;
export const components = componentsGeneric();
