import { AlertTriangle } from "lucide-react";

/**
 * Banner shown at the top of every page in the legacy in-admin
 * theme/template builder. Communicates that this system is frozen and
 * that templates are now generated by the design:* skill kit in the
 * Website repo.
 *
 * Routes that mount this banner:
 *   /appearance/themes
 *   /appearance/colors
 *   /appearance/header
 *   /appearance/footer
 *   /layouts            (index, new, $layoutId, assign)
 */
export function DeprecatedSystemBanner() {
  return (
    <div className="mb-6 flex gap-3 rounded-sm border border-amber-500/30 bg-amber-500/5 p-4 text-sm">
      <AlertTriangle className="size-5 shrink-0 text-amber-500" aria-hidden />
      <div className="space-y-1">
        <p className="font-medium text-foreground">
          Deprecated &mdash; on hold, not used in production.
        </p>
        <p className="text-muted-foreground">
          The in-admin Theme/Template Builder is frozen. Templates are now
          generated per site by the <code className="rounded-sm bg-muted px-1 py-0.5 text-xs">design:*</code> skill kit in the
          ConvexPress-Website repo (<code className="rounded-sm bg-muted px-1 py-0.5 text-xs">design-kit/README.md</code>).
          This page is kept visible so the deprecation is obvious; the
          underlying code stays until at least one site is fully shipped
          via the skill kit. Do not extend or fix issues here.
        </p>
      </div>
    </div>
  );
}
