import {useEffect,useState} from 'react';
import {useConvex,useMutation,usePaginatedQuery} from 'convex/react';
import {api} from '@backend/convex/_generated/api';
import type {Id} from '@backend/convex/_generated/dataModel';
import type {CanonicalTree} from '@backend/canonical-blocks-foundation/generated/types';
import {Button} from '@/components/ui/button';
import {SchemaBlockForm} from '@/components/blocks/schema-editor/SchemaBlockForm';
import {useUnsavedChangesWarning} from '@/hooks/useUnsavedChangesWarning';
type Review={digest:string;sources:Array<{legacyId:Id<'reusableBlocks'>;title:string;published:boolean;locked:boolean;targetId:Id<'syncedBlocks'>|null;blocks:CanonicalTree}>};
export function LegacySyncedImport({scope,disabled,lock,onImported}:{scope:{websiteKey:string;instanceKey:string};disabled:boolean;lock:(value:boolean)=>void;onImported:(id:Id<'syncedBlocks'>)=>void}){
 const client=useConvex(),apply=useMutation(api.syncedBlocks.legacy.apply),inventory=usePaginatedQuery(api.syncedBlocks.legacy.list,{}, {initialNumItems:20});
 const[id,setId]=useState<Id<'reusableBlocks'>|null>(null),[review,setReview]=useState<Review|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{lock(busy||review!==null);return()=>lock(false);},[busy,review,lock]);
 useUnsavedChangesWarning({isDirty:busy||review!==null,enabled:true});
 const names=new Map(review?.sources.map(s=>[`legacy:${s.legacyId}`,s.title]));
 function fields(blocks:CanonicalTree):React.ReactNode{return blocks.map(block=><div key={block.id} className="space-y-3 rounded-md border border-border p-3">{block.name==='core/synced'?<p className="text-sm">Shared content: {names.get(String(block.attrs.syncedBlock))??'Referenced source'} · follows latest publication</p>:<SchemaBlockForm mode="preview" disabled blockId={block.id} name={block.name} version={block.version} value={block.attrs} revision={review?.digest??''} scope={scope}/>}{block.children?.length?fields(block.children):null}</div>);}
 return <section aria-label="Import legacy reusable content" className="space-y-3 rounded-lg border border-border p-4"><h2 className="font-semibold">Import legacy reusable content</h2><p className="text-sm text-muted-foreground">Review saved sources and their shared dependencies before importing. Originals remain available for recovery. After import, edit the canonical source in this library.</p>
 {inventory.status==='LoadingFirstPage'?<p role="status">Loading legacy sources…</p>:inventory.results.length===0?<p className="text-sm">No legacy reusable sources in this environment.</p>:<><label className="block text-sm">Legacy source<select aria-label="Legacy source" className="mt-1 w-full rounded-md border border-input bg-background p-2" value={id??''} disabled={busy||disabled||review!==null} onChange={event=>{setId(event.target.value as Id<'reusableBlocks'>||null);setError('');}}><option value="">Choose a source</option>{inventory.results.map(s=><option key={s.id} value={s.id}>{s.title} — {s.published?'published':'draft'}{s.locked?' · locked':''}</option>)}</select></label>{inventory.status!=='Exhausted'&&<Button variant="outline" disabled={disabled||busy||review!==null||inventory.status==='LoadingMore'} onClick={()=>inventory.loadMore(20)}>Load more legacy sources</Button>}
 <Button variant="outline" disabled={!id||busy||disabled||review!==null} onClick={async()=>{if(!id)return;setBusy(true);setError('');try{setReview(await client.query(api.syncedBlocks.legacy.review,{legacyId:id}) as Review);}catch(e){setError(e instanceof Error?e.message:'This source could not be reviewed.');}finally{setBusy(false);}}}>Review import</Button></>}
 {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
 {review&&<div className="space-y-4" aria-label="Legacy import review"><p className="text-sm">This review includes {review.sources.length} sources. New imports preserve publication and locks; drafts stay private. Existing imports are reused and keep their current state.</p>{review.sources.map(s=><details key={s.legacyId} open className="space-y-3"><summary className="font-medium">{s.title} · {s.targetId?'Already imported':s.published?'Import as published':'Import as draft'}{s.locked?' · locked':''}</summary>{fields(s.blocks)}</details>)}<div className="flex gap-2"><Button disabled={busy} onClick={async()=>{if(!id)return;setBusy(true);setError('');try{const result=await apply({legacyId:id,expectedDigest:review.digest});setReview(null);onImported(result.id);}catch(e){setReview(null);setError(e instanceof Error?e.message:'Import could not be confirmed. Review again; existing imports will be reused.');}finally{setBusy(false);}}}>{busy?'Importing…':'Confirm import'}</Button><Button variant="outline" disabled={busy} onClick={()=>setReview(null)}>Cancel review</Button></div></div>}
 </section>;
}
