// Generated by sync:blocks:transport-validators. Do not edit.
// Schema leaf: no document DTO imports, which can depend on the generated data model.
import {v} from "convex/values";
export const composedRegistrySnapshotValidator=v.object({"scope":v.object({"websiteKey":v.string(),"instanceKey":v.string(),"deploymentOrigin":v.string()}),"definitions":v.array(v.object({"name":v.string(),"version":v.number(),"digest":v.string(),"definitionJson":v.string()}))});
