import { defineTable } from "convex/server";
import { v } from "convex/values";
export const contentPromotionTables = {
	overseer_contentPromotionMediaRecoveries: defineTable({
		receiptId: v.id("overseer_contentPromotionReviews"),
		reviewFingerprint: v.string(),
		transferKey: v.string(),
		mediaKey: v.string(),
		operatorId: v.id("overseer_users"),
		creatorId: v.id("overseer_users"),
		previousReceiptId: v.id("overseer_contentPromotionReviews"),
		targetCreatorId: v.string(),
		targetIntentId: v.string(),
		storageId: v.string(),
		reason: v.string(),
		evidenceHash: v.string(),
		authorityHash: v.string(),
		expiresAt: v.number(),
		transferId: v.id("overseer_contentPromotionMedia"),
		fingerprint: v.string(),
		recoveryKey: v.string(),
		status: v.union(
			v.literal("prepared"),
			v.literal("granting"),
			v.literal("verified"),
		),
		leaseId: v.string(),
		leaseExpiresAt: v.number(),
		targetGrantId: v.optional(v.string()),
		targetGrantFingerprint: v.optional(v.string()),
		targetBeneficiaryId: v.optional(v.string()),
		createdAt: v.number(),
		updatedAt: v.number(),
	}).index("by_review_transfer", ["receiptId", "transferKey"]),
	overseer_contentPromotionMediaRecoveryAudit: defineTable({
		recoveryId: v.id("overseer_contentPromotionMediaRecoveries"),
		actorId: v.id("overseer_users"),
		event: v.union(
			v.literal("prepared"),
			v.literal("confirmed"),
			v.literal("reconciled"),
		),
		createdAt: v.number(),
	}).index("by_recovery", ["recoveryId"]),
	overseer_contentPromotionMedia: defineTable({
		transferKey: v.string(),
		receiptId: v.id("overseer_contentPromotionReviews"),
		operatorId: v.id("overseer_users"),
		sourceIdentityJson: v.string(),
		targetIdentityJson: v.string(),
		sha256: v.string(),
		fileSize: v.number(),
		mimeType: v.string(),
		phase: v.union(
			v.literal("planned"),
			v.literal("uploading"),
			v.literal("uploaded"),
			v.literal("verified"),
			v.literal("uncertain"),
		),
		leaseId: v.string(),
		leaseExpiresAt: v.number(),
		attempt: v.number(),
		dispatchCount: v.number(),
		targetIntentId: v.optional(v.string()),
		storageId: v.optional(v.string()),
		failureCode: v.optional(v.string()),
		createdAt: v.number(),
		updatedAt: v.number(),
	}).index("by_transfer_key", ["transferKey"]),
	overseer_contentPromotionApplies: defineTable({
		receiptId: v.id("overseer_contentPromotionReviews"),
		operatorId: v.id("overseer_users"),
		reviewFingerprint: v.string(),
		status: v.union(
			v.literal("checking"),
			v.literal("submitting"),
			v.literal("uncertain"),
			v.literal("applied"),
			v.literal("rejected"),
			v.literal("rolled-back"),
		),
		leaseId: v.string(),
		leaseExpiresAt: v.number(),
		attempt: v.number(),
		dispatchCount: v.number(),
		sourceCheckedAt: v.optional(v.number()),
		dispatchedAt: v.optional(v.number()),
		finishedAt: v.optional(v.number()),
		failureCode: v.optional(v.string()),
		mappingsJson: v.optional(v.string()),
		createdAt: v.number(),
		updatedAt: v.number(),
	})
		.index("by_receipt", ["receiptId"])
		.index("by_operator", ["operatorId", "createdAt"]),
	overseer_contentPromotionReviews: defineTable({
		operatorId: v.id("overseer_users"),
		requestKey: v.string(),
		requestHash: v.string(),
		sourceConnectionId: v.id("overseer_connections"),
		targetConnectionId: v.id("overseer_connections"),
		websiteId: v.id("overseer_websites"),
		sourceInstanceId: v.id("overseer_websiteInstances"),
		targetInstanceId: v.id("overseer_websiteInstances"),
		authorityHash: v.string(),
		identitiesJson: v.string(),
		requestJson: v.string(),
		status: v.union(
			v.literal("reviewing"),
			v.literal("reviewed"),
			v.literal("blocked"),
			v.literal("failed"),
		),
		manifestHash: v.optional(v.string()),
		manifestJson: v.optional(v.string()),
		reviewJson: v.optional(v.string()),
		sourceRevisionHash: v.optional(v.string()),
		siteReceiptId: v.optional(v.string()),
		siteDigest: v.optional(v.string()),
		failureCode: v.optional(v.string()),
		createdAt: v.number(),
		updatedAt: v.number(),
		expiresAt: v.number(),
	})
		.index("by_operator_request", ["operatorId", "requestKey"])
		.index("by_operator", ["operatorId", "createdAt"]),
};
