/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as _devCounts from "../_devCounts.js";
import type * as _devEnable from "../_devEnable.js";
import type * as _devPurge from "../_devPurge.js";
import type * as ai_actions from "../ai/actions.js";
import type * as ai_helpers from "../ai/helpers.js";
import type * as ai_internals from "../ai/internals.js";
import type * as ai_prompts from "../ai/prompts.js";
import type * as ai_validators from "../ai/validators.js";
import type * as airtableSync__internal from "../airtableSync/_internal.js";
import type * as airtableSync_actions from "../airtableSync/actions.js";
import type * as airtableSync_syncCapabilities from "../airtableSync/syncCapabilities.js";
import type * as airtableSync_syncEmailNotifications from "../airtableSync/syncEmailNotifications.js";
import type * as airtableSync_syncEvents from "../airtableSync/syncEvents.js";
import type * as airtableSync_syncRoles from "../airtableSync/syncRoles.js";
import type * as airtableSync_syncRoutes from "../airtableSync/syncRoutes.js";
import type * as airtableSync_syncSiteNotifications from "../airtableSync/syncSiteNotifications.js";
import type * as analytics_internals from "../analytics/internals.js";
import type * as analytics_mutations from "../analytics/mutations.js";
import type * as analytics_queries from "../analytics/queries.js";
import type * as analytics_validators from "../analytics/validators.js";
import type * as api_actions from "../api/actions.js";
import type * as api_crypto_helpers from "../api/crypto_helpers.js";
import type * as api_internals from "../api/internals.js";
import type * as api_mutations from "../api/mutations.js";
import type * as api_queries from "../api/queries.js";
import type * as api_validators from "../api/validators.js";
import type * as auditLogs_actions from "../auditLogs/actions.js";
import type * as auditLogs_internals from "../auditLogs/internals.js";
import type * as auditLogs_mutations from "../auditLogs/mutations.js";
import type * as auditLogs_queries from "../auditLogs/queries.js";
import type * as auditLogs_validators from "../auditLogs/validators.js";
import type * as auth_clerkProvisioning from "../auth/clerkProvisioning.js";
import type * as auth_clerkSync from "../auth/clerkSync.js";
import type * as auth_clerkWebhook from "../auth/clerkWebhook.js";
import type * as auth_helpers from "../auth/helpers.js";
import type * as auth_internals from "../auth/internals.js";
import type * as auth_jwks from "../auth/jwks.js";
import type * as auth_login from "../auth/login.js";
import type * as auth_logout from "../auth/logout.js";
import type * as auth_migrations from "../auth/migrations.js";
import type * as auth_queries from "../auth/queries.js";
import type * as auth_refresh from "../auth/refresh.js";
import type * as auth_setup from "../auth/setup.js";
import type * as authTracking_actions from "../authTracking/actions.js";
import type * as authTracking_internals from "../authTracking/internals.js";
import type * as authTracking_mutations from "../authTracking/mutations.js";
import type * as authTracking_queries from "../authTracking/queries.js";
import type * as authTracking_validators from "../authTracking/validators.js";
import type * as blocks_ai from "../blocks/ai.js";
import type * as blocks_aiPromptBuilder from "../blocks/aiPromptBuilder.js";
import type * as blocks_helpers from "../blocks/helpers.js";
import type * as blocks_migrations from "../blocks/migrations.js";
import type * as blocks_mutations from "../blocks/mutations.js";
import type * as blocks_queries from "../blocks/queries.js";
import type * as blocks_validators from "../blocks/validators.js";
import type * as bootstrap_registerListeners from "../bootstrap/registerListeners.js";
import type * as capabilities_queries from "../capabilities/queries.js";
import type * as comments_httpInternals from "../comments/httpInternals.js";
import type * as comments_internals from "../comments/internals.js";
import type * as comments_mutations from "../comments/mutations.js";
import type * as comments_queries from "../comments/queries.js";
import type * as comments_validators from "../comments/validators.js";
import type * as commerce_cart from "../commerce/cart.js";
import type * as commerce_cartHelpers from "../commerce/cartHelpers.js";
import type * as commerce_categories from "../commerce/categories.js";
import type * as commerce_checkout from "../commerce/checkout.js";
import type * as commerce_checkoutBundleHelpers from "../commerce/checkoutBundleHelpers.js";
import type * as commerce_checkoutShippingGuards from "../commerce/checkoutShippingGuards.js";
import type * as commerce_customerGroups from "../commerce/customerGroups.js";
import type * as commerce_customers from "../commerce/customers.js";
import type * as commerce_discountEngine from "../commerce/discountEngine.js";
import type * as commerce_discountInternals from "../commerce/discountInternals.js";
import type * as commerce_discountStripeMirror from "../commerce/discountStripeMirror.js";
import type * as commerce_discounts from "../commerce/discounts.js";
import type * as commerce_draftOrders from "../commerce/draftOrders.js";
import type * as commerce_dynamicPricing from "../commerce/dynamicPricing.js";
import type * as commerce_fulfillment from "../commerce/fulfillment.js";
import type * as commerce_helpers from "../commerce/helpers.js";
import type * as commerce_inventory from "../commerce/inventory.js";
import type * as commerce_migrations from "../commerce/migrations.js";
import type * as commerce_orderBundleHelpers from "../commerce/orderBundleHelpers.js";
import type * as commerce_orderChanges from "../commerce/orderChanges.js";
import type * as commerce_orders from "../commerce/orders.js";
import type * as commerce_paymentActions from "../commerce/paymentActions.js";
import type * as commerce_payments from "../commerce/payments.js";
import type * as commerce_pricing from "../commerce/pricing.js";
import type * as commerce_products from "../commerce/products.js";
import type * as commerce_regions from "../commerce/regions.js";
import type * as commerce_salesChannels from "../commerce/salesChannels.js";
import type * as commerce_tax from "../commerce/tax.js";
import type * as commerce_taxClasses from "../commerce/taxClasses.js";
import type * as commerce_taxStripe from "../commerce/taxStripe.js";
import type * as commerce_validators from "../commerce/validators.js";
import type * as commerce_variantHelpers from "../commerce/variantHelpers.js";
import type * as commerce_variantResolvers from "../commerce/variantResolvers.js";
import type * as commerce_workflows from "../commerce/workflows.js";
import type * as commerceBundles_helpers from "../commerceBundles/helpers.js";
import type * as commerceBundles_internals from "../commerceBundles/internals.js";
import type * as commerceBundles_mutations from "../commerceBundles/mutations.js";
import type * as commerceBundles_queries from "../commerceBundles/queries.js";
import type * as commerceBundles_runtime from "../commerceBundles/runtime.js";
import type * as commerceDigital_actions from "../commerceDigital/actions.js";
import type * as commerceDigital_fulfillment from "../commerceDigital/fulfillment.js";
import type * as commerceDigital_mutations from "../commerceDigital/mutations.js";
import type * as commerceDigital_queries from "../commerceDigital/queries.js";
import type * as commerceReturns_eligibility from "../commerceReturns/eligibility.js";
import type * as commerceReturns_helpers from "../commerceReturns/helpers.js";
import type * as commerceReturns_itemState from "../commerceReturns/itemState.js";
import type * as commerceReturns_migrations from "../commerceReturns/migrations.js";
import type * as commerceReturns_mutations from "../commerceReturns/mutations.js";
import type * as commerceReturns_queries from "../commerceReturns/queries.js";
import type * as commerceReturns_reasons from "../commerceReturns/reasons.js";
import type * as commerceReturns_refundLifecycle from "../commerceReturns/refundLifecycle.js";
import type * as commerceReturns_refundPolicy from "../commerceReturns/refundPolicy.js";
import type * as commerceReturns_storeCredit from "../commerceReturns/storeCredit.js";
import type * as commerceReviews_helpers from "../commerceReviews/helpers.js";
import type * as commerceReviews_mutations from "../commerceReviews/mutations.js";
import type * as commerceReviews_queries from "../commerceReviews/queries.js";
import type * as commerceSubscriptions_actions from "../commerceSubscriptions/actions.js";
import type * as commerceSubscriptions_bridgeDecisions from "../commerceSubscriptions/bridgeDecisions.js";
import type * as commerceSubscriptions_checkout from "../commerceSubscriptions/checkout.js";
import type * as commerceSubscriptions_coupons from "../commerceSubscriptions/coupons.js";
import type * as commerceSubscriptions_dunning from "../commerceSubscriptions/dunning.js";
import type * as commerceSubscriptions_emails from "../commerceSubscriptions/emails.js";
import type * as commerceSubscriptions_helpers from "../commerceSubscriptions/helpers.js";
import type * as commerceSubscriptions_internals from "../commerceSubscriptions/internals.js";
import type * as commerceSubscriptions_mutations from "../commerceSubscriptions/mutations.js";
import type * as commerceSubscriptions_offers from "../commerceSubscriptions/offers.js";
import type * as commerceSubscriptions_portal from "../commerceSubscriptions/portal.js";
import type * as commerceSubscriptions_pricing from "../commerceSubscriptions/pricing.js";
import type * as commerceSubscriptions_pricingCards from "../commerceSubscriptions/pricingCards.js";
import type * as commerceSubscriptions_proration from "../commerceSubscriptions/proration.js";
import type * as commerceSubscriptions_publicCharge from "../commerceSubscriptions/publicCharge.js";
import type * as commerceSubscriptions_queries from "../commerceSubscriptions/queries.js";
import type * as commerceSubscriptions_renewal from "../commerceSubscriptions/renewal.js";
import type * as commerceSubscriptions_stripeCharge from "../commerceSubscriptions/stripeCharge.js";
import type * as commerceSubscriptions_templates from "../commerceSubscriptions/templates.js";
import type * as commerceSubscriptions_validators from "../commerceSubscriptions/validators.js";
import type * as commerceWishlists_availability from "../commerceWishlists/availability.js";
import type * as commerceWishlists_helpers from "../commerceWishlists/helpers.js";
import type * as commerceWishlists_mutations from "../commerceWishlists/mutations.js";
import type * as commerceWishlists_queries from "../commerceWishlists/queries.js";
import type * as crons from "../crons.js";
import type * as customFields_internals from "../customFields/internals.js";
import type * as customFields_mutations from "../customFields/mutations.js";
import type * as customFields_queries from "../customFields/queries.js";
import type * as customFields_validators from "../customFields/validators.js";
import type * as dashboard_helpers from "../dashboard/helpers.js";
import type * as dashboard_mutations from "../dashboard/mutations.js";
import type * as dashboard_queries from "../dashboard/queries.js";
import type * as demoSeed_actions from "../demoSeed/actions.js";
import type * as demoSeed_internals from "../demoSeed/internals.js";
import type * as editor_internals from "../editor/internals.js";
import type * as editor_mutations from "../editor/mutations.js";
import type * as editor_queries from "../editor/queries.js";
import type * as editor_validators from "../editor/validators.js";
import type * as emails_actions from "../emails/actions.js";
import type * as emails_internals from "../emails/internals.js";
import type * as emails_mutations from "../emails/mutations.js";
import type * as emails_queries from "../emails/queries.js";
import type * as emails_registry from "../emails/registry.js";
import type * as emails_templateDefaults from "../emails/templateDefaults.js";
import type * as emails_testData from "../emails/testData.js";
import type * as emails_validators from "../emails/validators.js";
import type * as embeds_actions from "../embeds/actions.js";
import type * as eventDefinitions_queries from "../eventDefinitions/queries.js";
import type * as events_constants from "../events/constants.js";
import type * as events_internals from "../events/internals.js";
import type * as events_mutations from "../events/mutations.js";
import type * as events_queries from "../events/queries.js";
import type * as events_validators from "../events/validators.js";
import type * as extensions_forms___tests___fixtures from "../extensions/forms/__tests__/fixtures.js";
import type * as extensions_forms_actionRegistry from "../extensions/forms/actionRegistry.js";
import type * as extensions_forms_actionTypes from "../extensions/forms/actionTypes.js";
import type * as extensions_forms_actions from "../extensions/forms/actions.js";
import type * as extensions_forms_analytics from "../extensions/forms/analytics.js";
import type * as extensions_forms_builderCore from "../extensions/forms/builderCore.js";
import type * as extensions_forms_calc_evaluate from "../extensions/forms/calc/evaluate.js";
import type * as extensions_forms_calc_format from "../extensions/forms/calc/format.js";
import type * as extensions_forms_calc_grammar from "../extensions/forms/calc/grammar.js";
import type * as extensions_forms_calc_graph from "../extensions/forms/calc/graph.js";
import type * as extensions_forms_calc_index from "../extensions/forms/calc/index.js";
import type * as extensions_forms_calc_parse from "../extensions/forms/calc/parse.js";
import type * as extensions_forms_calc_recompute from "../extensions/forms/calc/recompute.js";
import type * as extensions_forms_commerce from "../extensions/forms/commerce.js";
import type * as extensions_forms_conditionalLogic from "../extensions/forms/conditionalLogic.js";
import type * as extensions_forms_confirmations from "../extensions/forms/confirmations.js";
import type * as extensions_forms_devFixtures from "../extensions/forms/devFixtures.js";
import type * as extensions_forms_draftValidation from "../extensions/forms/draftValidation.js";
import type * as extensions_forms_export from "../extensions/forms/export.js";
import type * as extensions_forms_formLogic from "../extensions/forms/formLogic.js";
import type * as extensions_forms_mergeTags from "../extensions/forms/mergeTags.js";
import type * as extensions_forms_mutations from "../extensions/forms/mutations.js";
import type * as extensions_forms_notifications from "../extensions/forms/notifications.js";
import type * as extensions_forms_queries from "../extensions/forms/queries.js";
import type * as extensions_forms_spam from "../extensions/forms/spam.js";
import type * as extensions_forms_submitGuards from "../extensions/forms/submitGuards.js";
import type * as extensions_forms_tokens from "../extensions/forms/tokens.js";
import type * as feeds_actions from "../feeds/actions.js";
import type * as feeds_internals from "../feeds/internals.js";
import type * as feeds_queries from "../feeds/queries.js";
import type * as feeds_validators from "../feeds/validators.js";
import type * as ga4_actions from "../ga4/actions.js";
import type * as ga4_helpers from "../ga4/helpers.js";
import type * as ga4_internals from "../ga4/internals.js";
import type * as ga4_mutations from "../ga4/mutations.js";
import type * as ga4_queries from "../ga4/queries.js";
import type * as ga4_validators from "../ga4/validators.js";
import type * as gallery_helpers from "../gallery/helpers.js";
import type * as gallery_mutations from "../gallery/mutations.js";
import type * as gallery_queries from "../gallery/queries.js";
import type * as gallery_validators from "../gallery/validators.js";
import type * as healthCheck from "../healthCheck.js";
import type * as helpers_airtable from "../helpers/airtable.js";
import type * as helpers_auditClassification from "../helpers/auditClassification.js";
import type * as helpers_auditDescriptions from "../helpers/auditDescriptions.js";
import type * as helpers_auditObjectExtractors from "../helpers/auditObjectExtractors.js";
import type * as helpers_auth from "../helpers/auth.js";
import type * as helpers_comment from "../helpers/comment.js";
import type * as helpers_coupons from "../helpers/coupons.js";
import type * as helpers_customFieldValidation from "../helpers/customFieldValidation.js";
import type * as helpers_email from "../helpers/email.js";
import type * as helpers_eventFilter from "../helpers/eventFilter.js";
import type * as helpers_eventRetry from "../helpers/eventRetry.js";
import type * as helpers_events from "../helpers/events.js";
import type * as helpers_feedContent from "../helpers/feedContent.js";
import type * as helpers_feedUrls from "../helpers/feedUrls.js";
import type * as helpers_feedXml from "../helpers/feedXml.js";
import type * as helpers_locationRules from "../helpers/locationRules.js";
import type * as helpers_notification from "../helpers/notification.js";
import type * as helpers_password from "../helpers/password.js";
import type * as helpers_permissions from "../helpers/permissions.js";
import type * as helpers_plugins from "../helpers/plugins.js";
import type * as helpers_postAuth from "../helpers/postAuth.js";
import type * as helpers_profile from "../helpers/profile.js";
import type * as helpers_proration from "../helpers/proration.js";
import type * as helpers_registration from "../helpers/registration.js";
import type * as helpers_revisions from "../helpers/revisions.js";
import type * as helpers_routing from "../helpers/routing.js";
import type * as helpers_sanitize from "../helpers/sanitize.js";
import type * as helpers_seo from "../helpers/seo.js";
import type * as helpers_serviceKeys from "../helpers/serviceKeys.js";
import type * as helpers_settingsSecret from "../helpers/settingsSecret.js";
import type * as helpers_sitemap from "../helpers/sitemap.js";
import type * as helpers_slug from "../helpers/slug.js";
import type * as helpers_taxonomy from "../helpers/taxonomy.js";
import type * as helpers_timingSafe from "../helpers/timingSafe.js";
import type * as helpers_types from "../helpers/types.js";
import type * as http from "../http.js";
import type * as http_analytics from "../http/analytics.js";
import type * as http_checkout from "../http/checkout.js";
import type * as http_comments from "../http/comments.js";
import type * as http_discovery from "../http/discovery.js";
import type * as http_helpers from "../http/helpers.js";
import type * as http_inboundEmailWebhook from "../http/inboundEmailWebhook.js";
import type * as http_media from "../http/media.js";
import type * as http_menus from "../http/menus.js";
import type * as http_pages from "../http/pages.js";
import type * as http_posts from "../http/posts.js";
import type * as http_resendWebhook from "../http/resendWebhook.js";
import type * as http_settings from "../http/settings.js";
import type * as http_taxonomies from "../http/taxonomies.js";
import type * as http_users from "../http/users.js";
import type * as kb_analytics from "../kb/analytics.js";
import type * as kb_bookmarks from "../kb/bookmarks.js";
import type * as kb_categories from "../kb/categories.js";
import type * as kb_collections from "../kb/collections.js";
import type * as kb_comments from "../kb/comments.js";
import type * as kb_feedback from "../kb/feedback.js";
import type * as kb_helpers_enrichUser from "../kb/helpers/enrichUser.js";
import type * as kb_helpers_utils from "../kb/helpers/utils.js";
import type * as kb_integration from "../kb/integration.js";
import type * as kb_internals from "../kb/internals.js";
import type * as kb_meilisearch from "../kb/meilisearch.js";
import type * as kb_mutations from "../kb/mutations.js";
import type * as kb_progress from "../kb/progress.js";
import type * as kb_queries from "../kb/queries.js";
import type * as kb_rag from "../kb/rag.js";
import type * as kb_search from "../kb/search.js";
import type * as kb_settings from "../kb/settings.js";
import type * as kb_tags from "../kb/tags.js";
import type * as kb_templates from "../kb/templates.js";
import type * as kb_validators from "../kb/validators.js";
import type * as kb_workflows from "../kb/workflows.js";
import type * as layouts_internals from "../layouts/internals.js";
import type * as layouts_mutations from "../layouts/mutations.js";
import type * as layouts_presets from "../layouts/presets.js";
import type * as layouts_queries from "../layouts/queries.js";
import type * as layouts_validators from "../layouts/validators.js";
import type * as lms_access from "../lms/access.js";
import type * as lms_ai_actions from "../lms/ai/actions.js";
import type * as lms_ai_helpers from "../lms/ai/helpers.js";
import type * as lms_ai_internalActions from "../lms/ai/internalActions.js";
import type * as lms_ai_internals from "../lms/ai/internals.js";
import type * as lms_ai_mutations from "../lms/ai/mutations.js";
import type * as lms_ai_queries from "../lms/ai/queries.js";
import type * as lms_certificates_actions from "../lms/certificates/actions.js";
import type * as lms_certificates_mutations from "../lms/certificates/mutations.js";
import type * as lms_certificates_queries from "../lms/certificates/queries.js";
import type * as lms_certificates_rendering from "../lms/certificates/rendering.js";
import type * as lms_courses_helpers from "../lms/courses/helpers.js";
import type * as lms_courses_mutations from "../lms/courses/mutations.js";
import type * as lms_courses_queries from "../lms/courses/queries.js";
import type * as lms_courses_validators from "../lms/courses/validators.js";
import type * as lms_enrollment_internals from "../lms/enrollment/internals.js";
import type * as lms_enrollment_mutations from "../lms/enrollment/mutations.js";
import type * as lms_enrollment_queries from "../lms/enrollment/queries.js";
import type * as lms_lessons_helpers from "../lms/lessons/helpers.js";
import type * as lms_lessons_mutations from "../lms/lessons/mutations.js";
import type * as lms_lessons_queries from "../lms/lessons/queries.js";
import type * as lms_nodes_mutations from "../lms/nodes/mutations.js";
import type * as lms_nodes_queries from "../lms/nodes/queries.js";
import type * as lms_nodes_validators from "../lms/nodes/validators.js";
import type * as lms_progress_mutations from "../lms/progress/mutations.js";
import type * as lms_progress_queries from "../lms/progress/queries.js";
import type * as lms_seed from "../lms/seed.js";
import type * as lms_topics_mutations from "../lms/topics/mutations.js";
import type * as lms_topics_queries from "../lms/topics/queries.js";
import type * as media_actions from "../media/actions.js";
import type * as media_ai from "../media/ai.js";
import type * as media_helpers from "../media/helpers.js";
import type * as media_imageProcessing from "../media/imageProcessing.js";
import type * as media_internals from "../media/internals.js";
import type * as media_mediaAuth from "../media/mediaAuth.js";
import type * as media_mutations from "../media/mutations.js";
import type * as media_queries from "../media/queries.js";
import type * as media_references from "../media/references.js";
import type * as media_validators from "../media/validators.js";
import type * as membership_access from "../membership/access.js";
import type * as membership_bridgeLogic from "../membership/bridgeLogic.js";
import type * as membership_helpers from "../membership/helpers.js";
import type * as membership_internals from "../membership/internals.js";
import type * as membership_mutations from "../membership/mutations.js";
import type * as membership_queries from "../membership/queries.js";
import type * as membership_validators from "../membership/validators.js";
import type * as menus_internals from "../menus/internals.js";
import type * as menus_mutations from "../menus/mutations.js";
import type * as menus_queries from "../menus/queries.js";
import type * as menus_validators from "../menus/validators.js";
import type * as notificationEngine_registry from "../notificationEngine/registry.js";
import type * as notifications_internals from "../notifications/internals.js";
import type * as notifications_mutations from "../notifications/mutations.js";
import type * as notifications_queries from "../notifications/queries.js";
import type * as notifications_validators from "../notifications/validators.js";
import type * as pages_httpInternals from "../pages/httpInternals.js";
import type * as pages_internals from "../pages/internals.js";
import type * as pages_mutations from "../pages/mutations.js";
import type * as pages_queries from "../pages/queries.js";
import type * as pages_templates from "../pages/templates.js";
import type * as pages_validators from "../pages/validators.js";
import type * as password_actions from "../password/actions.js";
import type * as password_internals from "../password/internals.js";
import type * as password_mutations from "../password/mutations.js";
import type * as password_queries from "../password/queries.js";
import type * as password_validators from "../password/validators.js";
import type * as plugins_registry from "../plugins/registry.js";
import type * as posts_httpInternals from "../posts/httpInternals.js";
import type * as posts_internals from "../posts/internals.js";
import type * as posts_mutations from "../posts/mutations.js";
import type * as posts_queries from "../posts/queries.js";
import type * as posts_validators from "../posts/validators.js";
import type * as productAttributes_mutations from "../productAttributes/mutations.js";
import type * as productAttributes_queries from "../productAttributes/queries.js";
import type * as profiles_internals from "../profiles/internals.js";
import type * as profiles_mutations from "../profiles/mutations.js";
import type * as profiles_queries from "../profiles/queries.js";
import type * as profiles_types from "../profiles/types.js";
import type * as profiles_validators from "../profiles/validators.js";
import type * as recipes_actions from "../recipes/actions.js";
import type * as recipes_mutations from "../recipes/mutations.js";
import type * as recipes_queries from "../recipes/queries.js";
import type * as recipes_validators from "../recipes/validators.js";
import type * as registration_internals from "../registration/internals.js";
import type * as registration_mutations from "../registration/mutations.js";
import type * as registration_queries from "../registration/queries.js";
import type * as registration_validators from "../registration/validators.js";
import type * as revisions_internals from "../revisions/internals.js";
import type * as revisions_mutations from "../revisions/mutations.js";
import type * as revisions_queries from "../revisions/queries.js";
import type * as revisions_validators from "../revisions/validators.js";
import type * as roles_internals from "../roles/internals.js";
import type * as roles_mutations from "../roles/mutations.js";
import type * as roles_queries from "../roles/queries.js";
import type * as roles_validators from "../roles/validators.js";
import type * as routeDefinitions_queries from "../routeDefinitions/queries.js";
import type * as routing_eventHandlers from "../routing/eventHandlers.js";
import type * as routing_internals from "../routing/internals.js";
import type * as routing_mutations from "../routing/mutations.js";
import type * as routing_public from "../routing/public.js";
import type * as routing_queries from "../routing/queries.js";
import type * as routing_validators from "../routing/validators.js";
import type * as schema_analytics from "../schema/analytics.js";
import type * as schema_api from "../schema/api.js";
import type * as schema_auditLogs from "../schema/auditLogs.js";
import type * as schema_auth from "../schema/auth.js";
import type * as schema_authTracking from "../schema/authTracking.js";
import type * as schema_capabilities from "../schema/capabilities.js";
import type * as schema_comments from "../schema/comments.js";
import type * as schema_commerce from "../schema/commerce.js";
import type * as schema_commerceBundles from "../schema/commerceBundles.js";
import type * as schema_commerceDigital from "../schema/commerceDigital.js";
import type * as schema_commerceReturns from "../schema/commerceReturns.js";
import type * as schema_commerceReviews from "../schema/commerceReviews.js";
import type * as schema_commerceSubscriptions from "../schema/commerceSubscriptions.js";
import type * as schema_commerceWishlists from "../schema/commerceWishlists.js";
import type * as schema_customFields from "../schema/customFields.js";
import type * as schema_dashboard from "../schema/dashboard.js";
import type * as schema_editor from "../schema/editor.js";
import type * as schema_emails from "../schema/emails.js";
import type * as schema_eventDefinitions from "../schema/eventDefinitions.js";
import type * as schema_events from "../schema/events.js";
import type * as schema_ga4 from "../schema/ga4.js";
import type * as schema_gallery from "../schema/gallery.js";
import type * as schema_kb from "../schema/kb.js";
import type * as schema_layouts from "../schema/layouts.js";
import type * as schema_lms from "../schema/lms.js";
import type * as schema_media from "../schema/media.js";
import type * as schema_membership from "../schema/membership.js";
import type * as schema_menus from "../schema/menus.js";
import type * as schema_notifications from "../schema/notifications.js";
import type * as schema_posts from "../schema/posts.js";
import type * as schema_productAttributes from "../schema/productAttributes.js";
import type * as schema_recipes from "../schema/recipes.js";
import type * as schema_registration from "../schema/registration.js";
import type * as schema_revisions from "../schema/revisions.js";
import type * as schema_roles from "../schema/roles.js";
import type * as schema_routeDefinitions from "../schema/routeDefinitions.js";
import type * as schema_routing from "../schema/routing.js";
import type * as schema_search from "../schema/search.js";
import type * as schema_seo from "../schema/seo.js";
import type * as schema_settings from "../schema/settings.js";
import type * as schema_shipping from "../schema/shipping.js";
import type * as schema_siteNotificationDefinitions from "../schema/siteNotificationDefinitions.js";
import type * as schema_sitemap from "../schema/sitemap.js";
import type * as schema_support from "../schema/support.js";
import type * as schema_taxonomies from "../schema/taxonomies.js";
import type * as schema_themes from "../schema/themes.js";
import type * as schema_tickets from "../schema/tickets.js";
import type * as schema_users from "../schema/users.js";
import type * as schema_wordpressSync from "../schema/wordpressSync.js";
import type * as search_actions from "../search/actions.js";
import type * as search_eventHandlers from "../search/eventHandlers.js";
import type * as search_helpers from "../search/helpers.js";
import type * as search_internals from "../search/internals.js";
import type * as search_mutations from "../search/mutations.js";
import type * as search_queries from "../search/queries.js";
import type * as search_validators from "../search/validators.js";
import type * as seed_roles from "../seed/roles.js";
import type * as seo_internals from "../seo/internals.js";
import type * as seo_mutations from "../seo/mutations.js";
import type * as seo_queries from "../seo/queries.js";
import type * as seo_validators from "../seo/validators.js";
import type * as settings_defaults from "../settings/defaults.js";
import type * as settings_footerRows from "../settings/footerRows.js";
import type * as settings_helpers from "../settings/helpers.js";
import type * as settings_httpInternals from "../settings/httpInternals.js";
import type * as settings_integrations_testActions from "../settings/integrations/testActions.js";
import type * as settings_internals from "../settings/internals.js";
import type * as settings_mutations from "../settings/mutations.js";
import type * as settings_queries from "../settings/queries.js";
import type * as settings_validation from "../settings/validation.js";
import type * as settings_validators from "../settings/validators.js";
import type * as shipping___tests___fixtures from "../shipping/__tests__/fixtures.js";
import type * as shipping_actions from "../shipping/actions.js";
import type * as shipping_addressValidation_actions from "../shipping/addressValidation/actions.js";
import type * as shipping_addressValidation_mutations from "../shipping/addressValidation/mutations.js";
import type * as shipping_addressValidation_queries from "../shipping/addressValidation/queries.js";
import type * as shipping_addressValidation_validators from "../shipping/addressValidation/validators.js";
import type * as shipping_bootstrap from "../shipping/bootstrap.js";
import type * as shipping_classes_internals from "../shipping/classes/internals.js";
import type * as shipping_classes_mutations from "../shipping/classes/mutations.js";
import type * as shipping_classes_queries from "../shipping/classes/queries.js";
import type * as shipping_classes_validators from "../shipping/classes/validators.js";
import type * as shipping_helpers from "../shipping/helpers.js";
import type * as shipping_helpers_addressFingerprint from "../shipping/helpers/addressFingerprint.js";
import type * as shipping_helpers_binPacking from "../shipping/helpers/binPacking.js";
import type * as shipping_helpers_classResolution from "../shipping/helpers/classResolution.js";
import type * as shipping_helpers_distance from "../shipping/helpers/distance.js";
import type * as shipping_helpers_settings from "../shipping/helpers/settings.js";
import type * as shipping_helpers_zoneMatching from "../shipping/helpers/zoneMatching.js";
import type * as shipping_internals from "../shipping/internals.js";
import type * as shipping_labels_actions from "../shipping/labels/actions.js";
import type * as shipping_labels_internals from "../shipping/labels/internals.js";
import type * as shipping_labels_mutations from "../shipping/labels/mutations.js";
import type * as shipping_labels_queries from "../shipping/labels/queries.js";
import type * as shipping_labels_validators from "../shipping/labels/validators.js";
import type * as shipping_manifests_actions from "../shipping/manifests/actions.js";
import type * as shipping_manifests_internals from "../shipping/manifests/internals.js";
import type * as shipping_manifests_mutations from "../shipping/manifests/mutations.js";
import type * as shipping_manifests_queries from "../shipping/manifests/queries.js";
import type * as shipping_methods_dimensional from "../shipping/methods/dimensional.js";
import type * as shipping_methods_flatRate from "../shipping/methods/flatRate.js";
import type * as shipping_methods_free from "../shipping/methods/free.js";
import type * as shipping_methods_localDelivery from "../shipping/methods/localDelivery.js";
import type * as shipping_methods_localPickup from "../shipping/methods/localPickup.js";
import type * as shipping_methods_mutations from "../shipping/methods/mutations.js";
import type * as shipping_methods_preview from "../shipping/methods/preview.js";
import type * as shipping_methods_priceBased from "../shipping/methods/priceBased.js";
import type * as shipping_methods_quantityBased from "../shipping/methods/quantityBased.js";
import type * as shipping_methods_queries from "../shipping/methods/queries.js";
import type * as shipping_methods_tableRate from "../shipping/methods/tableRate.js";
import type * as shipping_methods_weightBased from "../shipping/methods/weightBased.js";
import type * as shipping_mutations from "../shipping/mutations.js";
import type * as shipping_packages_internals from "../shipping/packages/internals.js";
import type * as shipping_packages_mutations from "../shipping/packages/mutations.js";
import type * as shipping_packages_queries from "../shipping/packages/queries.js";
import type * as shipping_packages_validators from "../shipping/packages/validators.js";
import type * as shipping_providers from "../shipping/providers.js";
import type * as shipping_providers__shared_credentials from "../shipping/providers/_shared/credentials.js";
import type * as shipping_providers__shared_tokenCache from "../shipping/providers/_shared/tokenCache.js";
import type * as shipping_providers_contract from "../shipping/providers/contract.js";
import type * as shipping_providers_dhl_auth from "../shipping/providers/dhl/auth.js";
import type * as shipping_providers_dhl_rates from "../shipping/providers/dhl/rates.js";
import type * as shipping_providers_dhl_serviceCodes from "../shipping/providers/dhl/serviceCodes.js";
import type * as shipping_providers_fedex_auth from "../shipping/providers/fedex/auth.js";
import type * as shipping_providers_fedex_rates from "../shipping/providers/fedex/rates.js";
import type * as shipping_providers_fedex_serviceCodes from "../shipping/providers/fedex/serviceCodes.js";
import type * as shipping_providers_shipstation_rates from "../shipping/providers/shipstation/rates.js";
import type * as shipping_providers_ups_auth from "../shipping/providers/ups/auth.js";
import type * as shipping_providers_ups_rates from "../shipping/providers/ups/rates.js";
import type * as shipping_providers_ups_serviceCodes from "../shipping/providers/ups/serviceCodes.js";
import type * as shipping_providers_usps_auth from "../shipping/providers/usps/auth.js";
import type * as shipping_providers_usps_rates from "../shipping/providers/usps/rates.js";
import type * as shipping_providers_usps_serviceCodes from "../shipping/providers/usps/serviceCodes.js";
import type * as shipping_queries from "../shipping/queries.js";
import type * as shipping_rates_internals from "../shipping/rates/internals.js";
import type * as shipping_rates_pipeline from "../shipping/rates/pipeline.js";
import type * as shipping_rates_ranking from "../shipping/rates/ranking.js";
import type * as shipping_rates_types from "../shipping/rates/types.js";
import type * as shipping_rulesEngine_evaluator from "../shipping/rulesEngine/evaluator.js";
import type * as shipping_rulesEngine_internals from "../shipping/rulesEngine/internals.js";
import type * as shipping_rulesEngine_mutations from "../shipping/rulesEngine/mutations.js";
import type * as shipping_rulesEngine_queries from "../shipping/rulesEngine/queries.js";
import type * as shipping_rulesEngine_types from "../shipping/rulesEngine/types.js";
import type * as shipping_rulesEngine_validator from "../shipping/rulesEngine/validator.js";
import type * as shipping_shipFromLocations_internals from "../shipping/shipFromLocations/internals.js";
import type * as shipping_shipFromLocations_mutations from "../shipping/shipFromLocations/mutations.js";
import type * as shipping_shipFromLocations_queries from "../shipping/shipFromLocations/queries.js";
import type * as shipping_shipFromLocations_validators from "../shipping/shipFromLocations/validators.js";
import type * as shipping_tracking_actions from "../shipping/tracking/actions.js";
import type * as shipping_tracking_internals from "../shipping/tracking/internals.js";
import type * as shipping_tracking_mutations from "../shipping/tracking/mutations.js";
import type * as shipping_tracking_queries from "../shipping/tracking/queries.js";
import type * as shipping_tracking_statusNormalization from "../shipping/tracking/statusNormalization.js";
import type * as shipping_validators from "../shipping/validators.js";
import type * as shipping_webhookDedup from "../shipping/webhookDedup.js";
import type * as shipping_webhooks from "../shipping/webhooks.js";
import type * as shipping_zones_internals from "../shipping/zones/internals.js";
import type * as shipping_zones_mutations from "../shipping/zones/mutations.js";
import type * as shipping_zones_queries from "../shipping/zones/queries.js";
import type * as shipping_zones_validators from "../shipping/zones/validators.js";
import type * as siteNotificationDefinitions_queries from "../siteNotificationDefinitions/queries.js";
import type * as sitemaps_actions from "../sitemaps/actions.js";
import type * as sitemaps_helpers_auth from "../sitemaps/helpers/auth.js";
import type * as sitemaps_helpers_settings from "../sitemaps/helpers/settings.js";
import type * as sitemaps_internals from "../sitemaps/internals.js";
import type * as sitemaps_mutations from "../sitemaps/mutations.js";
import type * as sitemaps_queries from "../sitemaps/queries.js";
import type * as sitemaps_subscribers from "../sitemaps/subscribers.js";
import type * as sitemaps_validators from "../sitemaps/validators.js";
import type * as support_analytics from "../support/analytics.js";
import type * as support_channels from "../support/channels.js";
import type * as support_deflection from "../support/deflection.js";
import type * as support_inboundEmail from "../support/inboundEmail.js";
import type * as support_inboundEmailParser from "../support/inboundEmailParser.js";
import type * as support_inboundSecurity from "../support/inboundSecurity.js";
import type * as support_integration from "../support/integration.js";
import type * as support_internals from "../support/internals.js";
import type * as support_settings from "../support/settings.js";
import type * as support_validators from "../support/validators.js";
import type * as support_widget from "../support/widget.js";
import type * as taxonomies_httpInternals from "../taxonomies/httpInternals.js";
import type * as taxonomies_internals from "../taxonomies/internals.js";
import type * as taxonomies_mutations from "../taxonomies/mutations.js";
import type * as taxonomies_queries from "../taxonomies/queries.js";
import type * as taxonomies_validators from "../taxonomies/validators.js";
import type * as themes_internals from "../themes/internals.js";
import type * as themes_mutations from "../themes/mutations.js";
import type * as themes_presets from "../themes/presets.js";
import type * as themes_queries from "../themes/queries.js";
import type * as tickets_cannedResponses from "../tickets/cannedResponses.js";
import type * as tickets_integration from "../tickets/integration.js";
import type * as tickets_internals from "../tickets/internals.js";
import type * as tickets_messages from "../tickets/messages.js";
import type * as tickets_mutations from "../tickets/mutations.js";
import type * as tickets_queries from "../tickets/queries.js";
import type * as tickets_rateLimit from "../tickets/rateLimit.js";
import type * as tickets_sessions from "../tickets/sessions.js";
import type * as tickets_settings from "../tickets/settings.js";
import type * as tickets_validators from "../tickets/validators.js";
import type * as types_capabilities from "../types/capabilities.js";
import type * as users from "../users.js";
import type * as wordpressSync___tests___fixtures_fullSiteFixture from "../wordpressSync/__tests__/fixtures/fullSiteFixture.js";
import type * as wordpressSync_actions from "../wordpressSync/actions.js";
import type * as wordpressSync_fieldPolicy from "../wordpressSync/fieldPolicy.js";
import type * as wordpressSync_helpers_acfParser from "../wordpressSync/helpers/acfParser.js";
import type * as wordpressSync_helpers_adapters_baseAdapter from "../wordpressSync/helpers/adapters/baseAdapter.js";
import type * as wordpressSync_helpers_adapters_elementorAdapter from "../wordpressSync/helpers/adapters/elementorAdapter.js";
import type * as wordpressSync_helpers_adapters_mediaAdapter from "../wordpressSync/helpers/adapters/mediaAdapter.js";
import type * as wordpressSync_helpers_adapters_menuAdapter from "../wordpressSync/helpers/adapters/menuAdapter.js";
import type * as wordpressSync_helpers_adapters_types from "../wordpressSync/helpers/adapters/types.js";
import type * as wordpressSync_helpers_adapters_wooAdapter from "../wordpressSync/helpers/adapters/wooAdapter.js";
import type * as wordpressSync_helpers_adapters_wpAdapter from "../wordpressSync/helpers/adapters/wpAdapter.js";
import type * as wordpressSync_helpers_elementor from "../wordpressSync/helpers/elementor.js";
import type * as wordpressSync_helpers_idMapping from "../wordpressSync/helpers/idMapping.js";
import type * as wordpressSync_helpers_phpUnserialize from "../wordpressSync/helpers/phpUnserialize.js";
import type * as wordpressSync_helpers_wooClient from "../wordpressSync/helpers/wooClient.js";
import type * as wordpressSync_helpers_wpClient from "../wordpressSync/helpers/wpClient.js";
import type * as wordpressSync_helpers_yoastParser from "../wordpressSync/helpers/yoastParser.js";
import type * as wordpressSync_internals from "../wordpressSync/internals.js";
import type * as wordpressSync_mutations from "../wordpressSync/mutations.js";
import type * as wordpressSync_phases_comments from "../wordpressSync/phases/comments.js";
import type * as wordpressSync_phases_commerceCatalog from "../wordpressSync/phases/commerceCatalog.js";
import type * as wordpressSync_phases_commerceTransactions from "../wordpressSync/phases/commerceTransactions.js";
import type * as wordpressSync_phases_media from "../wordpressSync/phases/media.js";
import type * as wordpressSync_phases_menus from "../wordpressSync/phases/menus.js";
import type * as wordpressSync_phases_pages from "../wordpressSync/phases/pages.js";
import type * as wordpressSync_phases_posts from "../wordpressSync/phases/posts.js";
import type * as wordpressSync_phases_reconciliation from "../wordpressSync/phases/reconciliation.js";
import type * as wordpressSync_phases_taxonomies from "../wordpressSync/phases/taxonomies.js";
import type * as wordpressSync_phases_users from "../wordpressSync/phases/users.js";
import type * as wordpressSync_queries from "../wordpressSync/queries.js";
import type * as wordpressSync_validators from "../wordpressSync/validators.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  _devCounts: typeof _devCounts;
  _devEnable: typeof _devEnable;
  _devPurge: typeof _devPurge;
  "ai/actions": typeof ai_actions;
  "ai/helpers": typeof ai_helpers;
  "ai/internals": typeof ai_internals;
  "ai/prompts": typeof ai_prompts;
  "ai/validators": typeof ai_validators;
  "airtableSync/_internal": typeof airtableSync__internal;
  "airtableSync/actions": typeof airtableSync_actions;
  "airtableSync/syncCapabilities": typeof airtableSync_syncCapabilities;
  "airtableSync/syncEmailNotifications": typeof airtableSync_syncEmailNotifications;
  "airtableSync/syncEvents": typeof airtableSync_syncEvents;
  "airtableSync/syncRoles": typeof airtableSync_syncRoles;
  "airtableSync/syncRoutes": typeof airtableSync_syncRoutes;
  "airtableSync/syncSiteNotifications": typeof airtableSync_syncSiteNotifications;
  "analytics/internals": typeof analytics_internals;
  "analytics/mutations": typeof analytics_mutations;
  "analytics/queries": typeof analytics_queries;
  "analytics/validators": typeof analytics_validators;
  "api/actions": typeof api_actions;
  "api/crypto_helpers": typeof api_crypto_helpers;
  "api/internals": typeof api_internals;
  "api/mutations": typeof api_mutations;
  "api/queries": typeof api_queries;
  "api/validators": typeof api_validators;
  "auditLogs/actions": typeof auditLogs_actions;
  "auditLogs/internals": typeof auditLogs_internals;
  "auditLogs/mutations": typeof auditLogs_mutations;
  "auditLogs/queries": typeof auditLogs_queries;
  "auditLogs/validators": typeof auditLogs_validators;
  "auth/clerkProvisioning": typeof auth_clerkProvisioning;
  "auth/clerkSync": typeof auth_clerkSync;
  "auth/clerkWebhook": typeof auth_clerkWebhook;
  "auth/helpers": typeof auth_helpers;
  "auth/internals": typeof auth_internals;
  "auth/jwks": typeof auth_jwks;
  "auth/login": typeof auth_login;
  "auth/logout": typeof auth_logout;
  "auth/migrations": typeof auth_migrations;
  "auth/queries": typeof auth_queries;
  "auth/refresh": typeof auth_refresh;
  "auth/setup": typeof auth_setup;
  "authTracking/actions": typeof authTracking_actions;
  "authTracking/internals": typeof authTracking_internals;
  "authTracking/mutations": typeof authTracking_mutations;
  "authTracking/queries": typeof authTracking_queries;
  "authTracking/validators": typeof authTracking_validators;
  "blocks/ai": typeof blocks_ai;
  "blocks/aiPromptBuilder": typeof blocks_aiPromptBuilder;
  "blocks/helpers": typeof blocks_helpers;
  "blocks/migrations": typeof blocks_migrations;
  "blocks/mutations": typeof blocks_mutations;
  "blocks/queries": typeof blocks_queries;
  "blocks/validators": typeof blocks_validators;
  "bootstrap/registerListeners": typeof bootstrap_registerListeners;
  "capabilities/queries": typeof capabilities_queries;
  "comments/httpInternals": typeof comments_httpInternals;
  "comments/internals": typeof comments_internals;
  "comments/mutations": typeof comments_mutations;
  "comments/queries": typeof comments_queries;
  "comments/validators": typeof comments_validators;
  "commerce/cart": typeof commerce_cart;
  "commerce/cartHelpers": typeof commerce_cartHelpers;
  "commerce/categories": typeof commerce_categories;
  "commerce/checkout": typeof commerce_checkout;
  "commerce/checkoutBundleHelpers": typeof commerce_checkoutBundleHelpers;
  "commerce/checkoutShippingGuards": typeof commerce_checkoutShippingGuards;
  "commerce/customerGroups": typeof commerce_customerGroups;
  "commerce/customers": typeof commerce_customers;
  "commerce/discountEngine": typeof commerce_discountEngine;
  "commerce/discountInternals": typeof commerce_discountInternals;
  "commerce/discountStripeMirror": typeof commerce_discountStripeMirror;
  "commerce/discounts": typeof commerce_discounts;
  "commerce/draftOrders": typeof commerce_draftOrders;
  "commerce/dynamicPricing": typeof commerce_dynamicPricing;
  "commerce/fulfillment": typeof commerce_fulfillment;
  "commerce/helpers": typeof commerce_helpers;
  "commerce/inventory": typeof commerce_inventory;
  "commerce/migrations": typeof commerce_migrations;
  "commerce/orderBundleHelpers": typeof commerce_orderBundleHelpers;
  "commerce/orderChanges": typeof commerce_orderChanges;
  "commerce/orders": typeof commerce_orders;
  "commerce/paymentActions": typeof commerce_paymentActions;
  "commerce/payments": typeof commerce_payments;
  "commerce/pricing": typeof commerce_pricing;
  "commerce/products": typeof commerce_products;
  "commerce/regions": typeof commerce_regions;
  "commerce/salesChannels": typeof commerce_salesChannels;
  "commerce/tax": typeof commerce_tax;
  "commerce/taxClasses": typeof commerce_taxClasses;
  "commerce/taxStripe": typeof commerce_taxStripe;
  "commerce/validators": typeof commerce_validators;
  "commerce/variantHelpers": typeof commerce_variantHelpers;
  "commerce/variantResolvers": typeof commerce_variantResolvers;
  "commerce/workflows": typeof commerce_workflows;
  "commerceBundles/helpers": typeof commerceBundles_helpers;
  "commerceBundles/internals": typeof commerceBundles_internals;
  "commerceBundles/mutations": typeof commerceBundles_mutations;
  "commerceBundles/queries": typeof commerceBundles_queries;
  "commerceBundles/runtime": typeof commerceBundles_runtime;
  "commerceDigital/actions": typeof commerceDigital_actions;
  "commerceDigital/fulfillment": typeof commerceDigital_fulfillment;
  "commerceDigital/mutations": typeof commerceDigital_mutations;
  "commerceDigital/queries": typeof commerceDigital_queries;
  "commerceReturns/eligibility": typeof commerceReturns_eligibility;
  "commerceReturns/helpers": typeof commerceReturns_helpers;
  "commerceReturns/itemState": typeof commerceReturns_itemState;
  "commerceReturns/migrations": typeof commerceReturns_migrations;
  "commerceReturns/mutations": typeof commerceReturns_mutations;
  "commerceReturns/queries": typeof commerceReturns_queries;
  "commerceReturns/reasons": typeof commerceReturns_reasons;
  "commerceReturns/refundLifecycle": typeof commerceReturns_refundLifecycle;
  "commerceReturns/refundPolicy": typeof commerceReturns_refundPolicy;
  "commerceReturns/storeCredit": typeof commerceReturns_storeCredit;
  "commerceReviews/helpers": typeof commerceReviews_helpers;
  "commerceReviews/mutations": typeof commerceReviews_mutations;
  "commerceReviews/queries": typeof commerceReviews_queries;
  "commerceSubscriptions/actions": typeof commerceSubscriptions_actions;
  "commerceSubscriptions/bridgeDecisions": typeof commerceSubscriptions_bridgeDecisions;
  "commerceSubscriptions/checkout": typeof commerceSubscriptions_checkout;
  "commerceSubscriptions/coupons": typeof commerceSubscriptions_coupons;
  "commerceSubscriptions/dunning": typeof commerceSubscriptions_dunning;
  "commerceSubscriptions/emails": typeof commerceSubscriptions_emails;
  "commerceSubscriptions/helpers": typeof commerceSubscriptions_helpers;
  "commerceSubscriptions/internals": typeof commerceSubscriptions_internals;
  "commerceSubscriptions/mutations": typeof commerceSubscriptions_mutations;
  "commerceSubscriptions/offers": typeof commerceSubscriptions_offers;
  "commerceSubscriptions/portal": typeof commerceSubscriptions_portal;
  "commerceSubscriptions/pricing": typeof commerceSubscriptions_pricing;
  "commerceSubscriptions/pricingCards": typeof commerceSubscriptions_pricingCards;
  "commerceSubscriptions/proration": typeof commerceSubscriptions_proration;
  "commerceSubscriptions/publicCharge": typeof commerceSubscriptions_publicCharge;
  "commerceSubscriptions/queries": typeof commerceSubscriptions_queries;
  "commerceSubscriptions/renewal": typeof commerceSubscriptions_renewal;
  "commerceSubscriptions/stripeCharge": typeof commerceSubscriptions_stripeCharge;
  "commerceSubscriptions/templates": typeof commerceSubscriptions_templates;
  "commerceSubscriptions/validators": typeof commerceSubscriptions_validators;
  "commerceWishlists/availability": typeof commerceWishlists_availability;
  "commerceWishlists/helpers": typeof commerceWishlists_helpers;
  "commerceWishlists/mutations": typeof commerceWishlists_mutations;
  "commerceWishlists/queries": typeof commerceWishlists_queries;
  crons: typeof crons;
  "customFields/internals": typeof customFields_internals;
  "customFields/mutations": typeof customFields_mutations;
  "customFields/queries": typeof customFields_queries;
  "customFields/validators": typeof customFields_validators;
  "dashboard/helpers": typeof dashboard_helpers;
  "dashboard/mutations": typeof dashboard_mutations;
  "dashboard/queries": typeof dashboard_queries;
  "demoSeed/actions": typeof demoSeed_actions;
  "demoSeed/internals": typeof demoSeed_internals;
  "editor/internals": typeof editor_internals;
  "editor/mutations": typeof editor_mutations;
  "editor/queries": typeof editor_queries;
  "editor/validators": typeof editor_validators;
  "emails/actions": typeof emails_actions;
  "emails/internals": typeof emails_internals;
  "emails/mutations": typeof emails_mutations;
  "emails/queries": typeof emails_queries;
  "emails/registry": typeof emails_registry;
  "emails/templateDefaults": typeof emails_templateDefaults;
  "emails/testData": typeof emails_testData;
  "emails/validators": typeof emails_validators;
  "embeds/actions": typeof embeds_actions;
  "eventDefinitions/queries": typeof eventDefinitions_queries;
  "events/constants": typeof events_constants;
  "events/internals": typeof events_internals;
  "events/mutations": typeof events_mutations;
  "events/queries": typeof events_queries;
  "events/validators": typeof events_validators;
  "extensions/forms/__tests__/fixtures": typeof extensions_forms___tests___fixtures;
  "extensions/forms/actionRegistry": typeof extensions_forms_actionRegistry;
  "extensions/forms/actionTypes": typeof extensions_forms_actionTypes;
  "extensions/forms/actions": typeof extensions_forms_actions;
  "extensions/forms/analytics": typeof extensions_forms_analytics;
  "extensions/forms/builderCore": typeof extensions_forms_builderCore;
  "extensions/forms/calc/evaluate": typeof extensions_forms_calc_evaluate;
  "extensions/forms/calc/format": typeof extensions_forms_calc_format;
  "extensions/forms/calc/grammar": typeof extensions_forms_calc_grammar;
  "extensions/forms/calc/graph": typeof extensions_forms_calc_graph;
  "extensions/forms/calc/index": typeof extensions_forms_calc_index;
  "extensions/forms/calc/parse": typeof extensions_forms_calc_parse;
  "extensions/forms/calc/recompute": typeof extensions_forms_calc_recompute;
  "extensions/forms/commerce": typeof extensions_forms_commerce;
  "extensions/forms/conditionalLogic": typeof extensions_forms_conditionalLogic;
  "extensions/forms/confirmations": typeof extensions_forms_confirmations;
  "extensions/forms/devFixtures": typeof extensions_forms_devFixtures;
  "extensions/forms/draftValidation": typeof extensions_forms_draftValidation;
  "extensions/forms/export": typeof extensions_forms_export;
  "extensions/forms/formLogic": typeof extensions_forms_formLogic;
  "extensions/forms/mergeTags": typeof extensions_forms_mergeTags;
  "extensions/forms/mutations": typeof extensions_forms_mutations;
  "extensions/forms/notifications": typeof extensions_forms_notifications;
  "extensions/forms/queries": typeof extensions_forms_queries;
  "extensions/forms/spam": typeof extensions_forms_spam;
  "extensions/forms/submitGuards": typeof extensions_forms_submitGuards;
  "extensions/forms/tokens": typeof extensions_forms_tokens;
  "feeds/actions": typeof feeds_actions;
  "feeds/internals": typeof feeds_internals;
  "feeds/queries": typeof feeds_queries;
  "feeds/validators": typeof feeds_validators;
  "ga4/actions": typeof ga4_actions;
  "ga4/helpers": typeof ga4_helpers;
  "ga4/internals": typeof ga4_internals;
  "ga4/mutations": typeof ga4_mutations;
  "ga4/queries": typeof ga4_queries;
  "ga4/validators": typeof ga4_validators;
  "gallery/helpers": typeof gallery_helpers;
  "gallery/mutations": typeof gallery_mutations;
  "gallery/queries": typeof gallery_queries;
  "gallery/validators": typeof gallery_validators;
  healthCheck: typeof healthCheck;
  "helpers/airtable": typeof helpers_airtable;
  "helpers/auditClassification": typeof helpers_auditClassification;
  "helpers/auditDescriptions": typeof helpers_auditDescriptions;
  "helpers/auditObjectExtractors": typeof helpers_auditObjectExtractors;
  "helpers/auth": typeof helpers_auth;
  "helpers/comment": typeof helpers_comment;
  "helpers/coupons": typeof helpers_coupons;
  "helpers/customFieldValidation": typeof helpers_customFieldValidation;
  "helpers/email": typeof helpers_email;
  "helpers/eventFilter": typeof helpers_eventFilter;
  "helpers/eventRetry": typeof helpers_eventRetry;
  "helpers/events": typeof helpers_events;
  "helpers/feedContent": typeof helpers_feedContent;
  "helpers/feedUrls": typeof helpers_feedUrls;
  "helpers/feedXml": typeof helpers_feedXml;
  "helpers/locationRules": typeof helpers_locationRules;
  "helpers/notification": typeof helpers_notification;
  "helpers/password": typeof helpers_password;
  "helpers/permissions": typeof helpers_permissions;
  "helpers/plugins": typeof helpers_plugins;
  "helpers/postAuth": typeof helpers_postAuth;
  "helpers/profile": typeof helpers_profile;
  "helpers/proration": typeof helpers_proration;
  "helpers/registration": typeof helpers_registration;
  "helpers/revisions": typeof helpers_revisions;
  "helpers/routing": typeof helpers_routing;
  "helpers/sanitize": typeof helpers_sanitize;
  "helpers/seo": typeof helpers_seo;
  "helpers/serviceKeys": typeof helpers_serviceKeys;
  "helpers/settingsSecret": typeof helpers_settingsSecret;
  "helpers/sitemap": typeof helpers_sitemap;
  "helpers/slug": typeof helpers_slug;
  "helpers/taxonomy": typeof helpers_taxonomy;
  "helpers/timingSafe": typeof helpers_timingSafe;
  "helpers/types": typeof helpers_types;
  http: typeof http;
  "http/analytics": typeof http_analytics;
  "http/checkout": typeof http_checkout;
  "http/comments": typeof http_comments;
  "http/discovery": typeof http_discovery;
  "http/helpers": typeof http_helpers;
  "http/inboundEmailWebhook": typeof http_inboundEmailWebhook;
  "http/media": typeof http_media;
  "http/menus": typeof http_menus;
  "http/pages": typeof http_pages;
  "http/posts": typeof http_posts;
  "http/resendWebhook": typeof http_resendWebhook;
  "http/settings": typeof http_settings;
  "http/taxonomies": typeof http_taxonomies;
  "http/users": typeof http_users;
  "kb/analytics": typeof kb_analytics;
  "kb/bookmarks": typeof kb_bookmarks;
  "kb/categories": typeof kb_categories;
  "kb/collections": typeof kb_collections;
  "kb/comments": typeof kb_comments;
  "kb/feedback": typeof kb_feedback;
  "kb/helpers/enrichUser": typeof kb_helpers_enrichUser;
  "kb/helpers/utils": typeof kb_helpers_utils;
  "kb/integration": typeof kb_integration;
  "kb/internals": typeof kb_internals;
  "kb/meilisearch": typeof kb_meilisearch;
  "kb/mutations": typeof kb_mutations;
  "kb/progress": typeof kb_progress;
  "kb/queries": typeof kb_queries;
  "kb/rag": typeof kb_rag;
  "kb/search": typeof kb_search;
  "kb/settings": typeof kb_settings;
  "kb/tags": typeof kb_tags;
  "kb/templates": typeof kb_templates;
  "kb/validators": typeof kb_validators;
  "kb/workflows": typeof kb_workflows;
  "layouts/internals": typeof layouts_internals;
  "layouts/mutations": typeof layouts_mutations;
  "layouts/presets": typeof layouts_presets;
  "layouts/queries": typeof layouts_queries;
  "layouts/validators": typeof layouts_validators;
  "lms/access": typeof lms_access;
  "lms/ai/actions": typeof lms_ai_actions;
  "lms/ai/helpers": typeof lms_ai_helpers;
  "lms/ai/internalActions": typeof lms_ai_internalActions;
  "lms/ai/internals": typeof lms_ai_internals;
  "lms/ai/mutations": typeof lms_ai_mutations;
  "lms/ai/queries": typeof lms_ai_queries;
  "lms/certificates/actions": typeof lms_certificates_actions;
  "lms/certificates/mutations": typeof lms_certificates_mutations;
  "lms/certificates/queries": typeof lms_certificates_queries;
  "lms/certificates/rendering": typeof lms_certificates_rendering;
  "lms/courses/helpers": typeof lms_courses_helpers;
  "lms/courses/mutations": typeof lms_courses_mutations;
  "lms/courses/queries": typeof lms_courses_queries;
  "lms/courses/validators": typeof lms_courses_validators;
  "lms/enrollment/internals": typeof lms_enrollment_internals;
  "lms/enrollment/mutations": typeof lms_enrollment_mutations;
  "lms/enrollment/queries": typeof lms_enrollment_queries;
  "lms/lessons/helpers": typeof lms_lessons_helpers;
  "lms/lessons/mutations": typeof lms_lessons_mutations;
  "lms/lessons/queries": typeof lms_lessons_queries;
  "lms/nodes/mutations": typeof lms_nodes_mutations;
  "lms/nodes/queries": typeof lms_nodes_queries;
  "lms/nodes/validators": typeof lms_nodes_validators;
  "lms/progress/mutations": typeof lms_progress_mutations;
  "lms/progress/queries": typeof lms_progress_queries;
  "lms/seed": typeof lms_seed;
  "lms/topics/mutations": typeof lms_topics_mutations;
  "lms/topics/queries": typeof lms_topics_queries;
  "media/actions": typeof media_actions;
  "media/ai": typeof media_ai;
  "media/helpers": typeof media_helpers;
  "media/imageProcessing": typeof media_imageProcessing;
  "media/internals": typeof media_internals;
  "media/mediaAuth": typeof media_mediaAuth;
  "media/mutations": typeof media_mutations;
  "media/queries": typeof media_queries;
  "media/references": typeof media_references;
  "media/validators": typeof media_validators;
  "membership/access": typeof membership_access;
  "membership/bridgeLogic": typeof membership_bridgeLogic;
  "membership/helpers": typeof membership_helpers;
  "membership/internals": typeof membership_internals;
  "membership/mutations": typeof membership_mutations;
  "membership/queries": typeof membership_queries;
  "membership/validators": typeof membership_validators;
  "menus/internals": typeof menus_internals;
  "menus/mutations": typeof menus_mutations;
  "menus/queries": typeof menus_queries;
  "menus/validators": typeof menus_validators;
  "notificationEngine/registry": typeof notificationEngine_registry;
  "notifications/internals": typeof notifications_internals;
  "notifications/mutations": typeof notifications_mutations;
  "notifications/queries": typeof notifications_queries;
  "notifications/validators": typeof notifications_validators;
  "pages/httpInternals": typeof pages_httpInternals;
  "pages/internals": typeof pages_internals;
  "pages/mutations": typeof pages_mutations;
  "pages/queries": typeof pages_queries;
  "pages/templates": typeof pages_templates;
  "pages/validators": typeof pages_validators;
  "password/actions": typeof password_actions;
  "password/internals": typeof password_internals;
  "password/mutations": typeof password_mutations;
  "password/queries": typeof password_queries;
  "password/validators": typeof password_validators;
  "plugins/registry": typeof plugins_registry;
  "posts/httpInternals": typeof posts_httpInternals;
  "posts/internals": typeof posts_internals;
  "posts/mutations": typeof posts_mutations;
  "posts/queries": typeof posts_queries;
  "posts/validators": typeof posts_validators;
  "productAttributes/mutations": typeof productAttributes_mutations;
  "productAttributes/queries": typeof productAttributes_queries;
  "profiles/internals": typeof profiles_internals;
  "profiles/mutations": typeof profiles_mutations;
  "profiles/queries": typeof profiles_queries;
  "profiles/types": typeof profiles_types;
  "profiles/validators": typeof profiles_validators;
  "recipes/actions": typeof recipes_actions;
  "recipes/mutations": typeof recipes_mutations;
  "recipes/queries": typeof recipes_queries;
  "recipes/validators": typeof recipes_validators;
  "registration/internals": typeof registration_internals;
  "registration/mutations": typeof registration_mutations;
  "registration/queries": typeof registration_queries;
  "registration/validators": typeof registration_validators;
  "revisions/internals": typeof revisions_internals;
  "revisions/mutations": typeof revisions_mutations;
  "revisions/queries": typeof revisions_queries;
  "revisions/validators": typeof revisions_validators;
  "roles/internals": typeof roles_internals;
  "roles/mutations": typeof roles_mutations;
  "roles/queries": typeof roles_queries;
  "roles/validators": typeof roles_validators;
  "routeDefinitions/queries": typeof routeDefinitions_queries;
  "routing/eventHandlers": typeof routing_eventHandlers;
  "routing/internals": typeof routing_internals;
  "routing/mutations": typeof routing_mutations;
  "routing/public": typeof routing_public;
  "routing/queries": typeof routing_queries;
  "routing/validators": typeof routing_validators;
  "schema/analytics": typeof schema_analytics;
  "schema/api": typeof schema_api;
  "schema/auditLogs": typeof schema_auditLogs;
  "schema/auth": typeof schema_auth;
  "schema/authTracking": typeof schema_authTracking;
  "schema/capabilities": typeof schema_capabilities;
  "schema/comments": typeof schema_comments;
  "schema/commerce": typeof schema_commerce;
  "schema/commerceBundles": typeof schema_commerceBundles;
  "schema/commerceDigital": typeof schema_commerceDigital;
  "schema/commerceReturns": typeof schema_commerceReturns;
  "schema/commerceReviews": typeof schema_commerceReviews;
  "schema/commerceSubscriptions": typeof schema_commerceSubscriptions;
  "schema/commerceWishlists": typeof schema_commerceWishlists;
  "schema/customFields": typeof schema_customFields;
  "schema/dashboard": typeof schema_dashboard;
  "schema/editor": typeof schema_editor;
  "schema/emails": typeof schema_emails;
  "schema/eventDefinitions": typeof schema_eventDefinitions;
  "schema/events": typeof schema_events;
  "schema/ga4": typeof schema_ga4;
  "schema/gallery": typeof schema_gallery;
  "schema/kb": typeof schema_kb;
  "schema/layouts": typeof schema_layouts;
  "schema/lms": typeof schema_lms;
  "schema/media": typeof schema_media;
  "schema/membership": typeof schema_membership;
  "schema/menus": typeof schema_menus;
  "schema/notifications": typeof schema_notifications;
  "schema/posts": typeof schema_posts;
  "schema/productAttributes": typeof schema_productAttributes;
  "schema/recipes": typeof schema_recipes;
  "schema/registration": typeof schema_registration;
  "schema/revisions": typeof schema_revisions;
  "schema/roles": typeof schema_roles;
  "schema/routeDefinitions": typeof schema_routeDefinitions;
  "schema/routing": typeof schema_routing;
  "schema/search": typeof schema_search;
  "schema/seo": typeof schema_seo;
  "schema/settings": typeof schema_settings;
  "schema/shipping": typeof schema_shipping;
  "schema/siteNotificationDefinitions": typeof schema_siteNotificationDefinitions;
  "schema/sitemap": typeof schema_sitemap;
  "schema/support": typeof schema_support;
  "schema/taxonomies": typeof schema_taxonomies;
  "schema/themes": typeof schema_themes;
  "schema/tickets": typeof schema_tickets;
  "schema/users": typeof schema_users;
  "schema/wordpressSync": typeof schema_wordpressSync;
  "search/actions": typeof search_actions;
  "search/eventHandlers": typeof search_eventHandlers;
  "search/helpers": typeof search_helpers;
  "search/internals": typeof search_internals;
  "search/mutations": typeof search_mutations;
  "search/queries": typeof search_queries;
  "search/validators": typeof search_validators;
  "seed/roles": typeof seed_roles;
  "seo/internals": typeof seo_internals;
  "seo/mutations": typeof seo_mutations;
  "seo/queries": typeof seo_queries;
  "seo/validators": typeof seo_validators;
  "settings/defaults": typeof settings_defaults;
  "settings/footerRows": typeof settings_footerRows;
  "settings/helpers": typeof settings_helpers;
  "settings/httpInternals": typeof settings_httpInternals;
  "settings/integrations/testActions": typeof settings_integrations_testActions;
  "settings/internals": typeof settings_internals;
  "settings/mutations": typeof settings_mutations;
  "settings/queries": typeof settings_queries;
  "settings/validation": typeof settings_validation;
  "settings/validators": typeof settings_validators;
  "shipping/__tests__/fixtures": typeof shipping___tests___fixtures;
  "shipping/actions": typeof shipping_actions;
  "shipping/addressValidation/actions": typeof shipping_addressValidation_actions;
  "shipping/addressValidation/mutations": typeof shipping_addressValidation_mutations;
  "shipping/addressValidation/queries": typeof shipping_addressValidation_queries;
  "shipping/addressValidation/validators": typeof shipping_addressValidation_validators;
  "shipping/bootstrap": typeof shipping_bootstrap;
  "shipping/classes/internals": typeof shipping_classes_internals;
  "shipping/classes/mutations": typeof shipping_classes_mutations;
  "shipping/classes/queries": typeof shipping_classes_queries;
  "shipping/classes/validators": typeof shipping_classes_validators;
  "shipping/helpers": typeof shipping_helpers;
  "shipping/helpers/addressFingerprint": typeof shipping_helpers_addressFingerprint;
  "shipping/helpers/binPacking": typeof shipping_helpers_binPacking;
  "shipping/helpers/classResolution": typeof shipping_helpers_classResolution;
  "shipping/helpers/distance": typeof shipping_helpers_distance;
  "shipping/helpers/settings": typeof shipping_helpers_settings;
  "shipping/helpers/zoneMatching": typeof shipping_helpers_zoneMatching;
  "shipping/internals": typeof shipping_internals;
  "shipping/labels/actions": typeof shipping_labels_actions;
  "shipping/labels/internals": typeof shipping_labels_internals;
  "shipping/labels/mutations": typeof shipping_labels_mutations;
  "shipping/labels/queries": typeof shipping_labels_queries;
  "shipping/labels/validators": typeof shipping_labels_validators;
  "shipping/manifests/actions": typeof shipping_manifests_actions;
  "shipping/manifests/internals": typeof shipping_manifests_internals;
  "shipping/manifests/mutations": typeof shipping_manifests_mutations;
  "shipping/manifests/queries": typeof shipping_manifests_queries;
  "shipping/methods/dimensional": typeof shipping_methods_dimensional;
  "shipping/methods/flatRate": typeof shipping_methods_flatRate;
  "shipping/methods/free": typeof shipping_methods_free;
  "shipping/methods/localDelivery": typeof shipping_methods_localDelivery;
  "shipping/methods/localPickup": typeof shipping_methods_localPickup;
  "shipping/methods/mutations": typeof shipping_methods_mutations;
  "shipping/methods/preview": typeof shipping_methods_preview;
  "shipping/methods/priceBased": typeof shipping_methods_priceBased;
  "shipping/methods/quantityBased": typeof shipping_methods_quantityBased;
  "shipping/methods/queries": typeof shipping_methods_queries;
  "shipping/methods/tableRate": typeof shipping_methods_tableRate;
  "shipping/methods/weightBased": typeof shipping_methods_weightBased;
  "shipping/mutations": typeof shipping_mutations;
  "shipping/packages/internals": typeof shipping_packages_internals;
  "shipping/packages/mutations": typeof shipping_packages_mutations;
  "shipping/packages/queries": typeof shipping_packages_queries;
  "shipping/packages/validators": typeof shipping_packages_validators;
  "shipping/providers": typeof shipping_providers;
  "shipping/providers/_shared/credentials": typeof shipping_providers__shared_credentials;
  "shipping/providers/_shared/tokenCache": typeof shipping_providers__shared_tokenCache;
  "shipping/providers/contract": typeof shipping_providers_contract;
  "shipping/providers/dhl/auth": typeof shipping_providers_dhl_auth;
  "shipping/providers/dhl/rates": typeof shipping_providers_dhl_rates;
  "shipping/providers/dhl/serviceCodes": typeof shipping_providers_dhl_serviceCodes;
  "shipping/providers/fedex/auth": typeof shipping_providers_fedex_auth;
  "shipping/providers/fedex/rates": typeof shipping_providers_fedex_rates;
  "shipping/providers/fedex/serviceCodes": typeof shipping_providers_fedex_serviceCodes;
  "shipping/providers/shipstation/rates": typeof shipping_providers_shipstation_rates;
  "shipping/providers/ups/auth": typeof shipping_providers_ups_auth;
  "shipping/providers/ups/rates": typeof shipping_providers_ups_rates;
  "shipping/providers/ups/serviceCodes": typeof shipping_providers_ups_serviceCodes;
  "shipping/providers/usps/auth": typeof shipping_providers_usps_auth;
  "shipping/providers/usps/rates": typeof shipping_providers_usps_rates;
  "shipping/providers/usps/serviceCodes": typeof shipping_providers_usps_serviceCodes;
  "shipping/queries": typeof shipping_queries;
  "shipping/rates/internals": typeof shipping_rates_internals;
  "shipping/rates/pipeline": typeof shipping_rates_pipeline;
  "shipping/rates/ranking": typeof shipping_rates_ranking;
  "shipping/rates/types": typeof shipping_rates_types;
  "shipping/rulesEngine/evaluator": typeof shipping_rulesEngine_evaluator;
  "shipping/rulesEngine/internals": typeof shipping_rulesEngine_internals;
  "shipping/rulesEngine/mutations": typeof shipping_rulesEngine_mutations;
  "shipping/rulesEngine/queries": typeof shipping_rulesEngine_queries;
  "shipping/rulesEngine/types": typeof shipping_rulesEngine_types;
  "shipping/rulesEngine/validator": typeof shipping_rulesEngine_validator;
  "shipping/shipFromLocations/internals": typeof shipping_shipFromLocations_internals;
  "shipping/shipFromLocations/mutations": typeof shipping_shipFromLocations_mutations;
  "shipping/shipFromLocations/queries": typeof shipping_shipFromLocations_queries;
  "shipping/shipFromLocations/validators": typeof shipping_shipFromLocations_validators;
  "shipping/tracking/actions": typeof shipping_tracking_actions;
  "shipping/tracking/internals": typeof shipping_tracking_internals;
  "shipping/tracking/mutations": typeof shipping_tracking_mutations;
  "shipping/tracking/queries": typeof shipping_tracking_queries;
  "shipping/tracking/statusNormalization": typeof shipping_tracking_statusNormalization;
  "shipping/validators": typeof shipping_validators;
  "shipping/webhookDedup": typeof shipping_webhookDedup;
  "shipping/webhooks": typeof shipping_webhooks;
  "shipping/zones/internals": typeof shipping_zones_internals;
  "shipping/zones/mutations": typeof shipping_zones_mutations;
  "shipping/zones/queries": typeof shipping_zones_queries;
  "shipping/zones/validators": typeof shipping_zones_validators;
  "siteNotificationDefinitions/queries": typeof siteNotificationDefinitions_queries;
  "sitemaps/actions": typeof sitemaps_actions;
  "sitemaps/helpers/auth": typeof sitemaps_helpers_auth;
  "sitemaps/helpers/settings": typeof sitemaps_helpers_settings;
  "sitemaps/internals": typeof sitemaps_internals;
  "sitemaps/mutations": typeof sitemaps_mutations;
  "sitemaps/queries": typeof sitemaps_queries;
  "sitemaps/subscribers": typeof sitemaps_subscribers;
  "sitemaps/validators": typeof sitemaps_validators;
  "support/analytics": typeof support_analytics;
  "support/channels": typeof support_channels;
  "support/deflection": typeof support_deflection;
  "support/inboundEmail": typeof support_inboundEmail;
  "support/inboundEmailParser": typeof support_inboundEmailParser;
  "support/inboundSecurity": typeof support_inboundSecurity;
  "support/integration": typeof support_integration;
  "support/internals": typeof support_internals;
  "support/settings": typeof support_settings;
  "support/validators": typeof support_validators;
  "support/widget": typeof support_widget;
  "taxonomies/httpInternals": typeof taxonomies_httpInternals;
  "taxonomies/internals": typeof taxonomies_internals;
  "taxonomies/mutations": typeof taxonomies_mutations;
  "taxonomies/queries": typeof taxonomies_queries;
  "taxonomies/validators": typeof taxonomies_validators;
  "themes/internals": typeof themes_internals;
  "themes/mutations": typeof themes_mutations;
  "themes/presets": typeof themes_presets;
  "themes/queries": typeof themes_queries;
  "tickets/cannedResponses": typeof tickets_cannedResponses;
  "tickets/integration": typeof tickets_integration;
  "tickets/internals": typeof tickets_internals;
  "tickets/messages": typeof tickets_messages;
  "tickets/mutations": typeof tickets_mutations;
  "tickets/queries": typeof tickets_queries;
  "tickets/rateLimit": typeof tickets_rateLimit;
  "tickets/sessions": typeof tickets_sessions;
  "tickets/settings": typeof tickets_settings;
  "tickets/validators": typeof tickets_validators;
  "types/capabilities": typeof types_capabilities;
  users: typeof users;
  "wordpressSync/__tests__/fixtures/fullSiteFixture": typeof wordpressSync___tests___fixtures_fullSiteFixture;
  "wordpressSync/actions": typeof wordpressSync_actions;
  "wordpressSync/fieldPolicy": typeof wordpressSync_fieldPolicy;
  "wordpressSync/helpers/acfParser": typeof wordpressSync_helpers_acfParser;
  "wordpressSync/helpers/adapters/baseAdapter": typeof wordpressSync_helpers_adapters_baseAdapter;
  "wordpressSync/helpers/adapters/elementorAdapter": typeof wordpressSync_helpers_adapters_elementorAdapter;
  "wordpressSync/helpers/adapters/mediaAdapter": typeof wordpressSync_helpers_adapters_mediaAdapter;
  "wordpressSync/helpers/adapters/menuAdapter": typeof wordpressSync_helpers_adapters_menuAdapter;
  "wordpressSync/helpers/adapters/types": typeof wordpressSync_helpers_adapters_types;
  "wordpressSync/helpers/adapters/wooAdapter": typeof wordpressSync_helpers_adapters_wooAdapter;
  "wordpressSync/helpers/adapters/wpAdapter": typeof wordpressSync_helpers_adapters_wpAdapter;
  "wordpressSync/helpers/elementor": typeof wordpressSync_helpers_elementor;
  "wordpressSync/helpers/idMapping": typeof wordpressSync_helpers_idMapping;
  "wordpressSync/helpers/phpUnserialize": typeof wordpressSync_helpers_phpUnserialize;
  "wordpressSync/helpers/wooClient": typeof wordpressSync_helpers_wooClient;
  "wordpressSync/helpers/wpClient": typeof wordpressSync_helpers_wpClient;
  "wordpressSync/helpers/yoastParser": typeof wordpressSync_helpers_yoastParser;
  "wordpressSync/internals": typeof wordpressSync_internals;
  "wordpressSync/mutations": typeof wordpressSync_mutations;
  "wordpressSync/phases/comments": typeof wordpressSync_phases_comments;
  "wordpressSync/phases/commerceCatalog": typeof wordpressSync_phases_commerceCatalog;
  "wordpressSync/phases/commerceTransactions": typeof wordpressSync_phases_commerceTransactions;
  "wordpressSync/phases/media": typeof wordpressSync_phases_media;
  "wordpressSync/phases/menus": typeof wordpressSync_phases_menus;
  "wordpressSync/phases/pages": typeof wordpressSync_phases_pages;
  "wordpressSync/phases/posts": typeof wordpressSync_phases_posts;
  "wordpressSync/phases/reconciliation": typeof wordpressSync_phases_reconciliation;
  "wordpressSync/phases/taxonomies": typeof wordpressSync_phases_taxonomies;
  "wordpressSync/phases/users": typeof wordpressSync_phases_users;
  "wordpressSync/queries": typeof wordpressSync_queries;
  "wordpressSync/validators": typeof wordpressSync_validators;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
