// Generated by scripts/generate-media-reference-inventory.ts. Do not edit.
export const typedMediaReferences = {
  "commerce_product_brands": [
    {
      "path": [
        "logoMediaId"
      ],
      "optional": true
    }
  ],
  "commerce_product_categories": [
    {
      "path": [
        "thumbnailMediaId"
      ],
      "optional": true
    }
  ],
  "commerce_product_variants": [
    {
      "path": [
        "featuredMediaId"
      ],
      "optional": true
    },
    {
      "path": [
        "galleryMediaIds",
        "*"
      ],
      "optional": true
    }
  ],
  "commerce_products": [
    {
      "path": [
        "featuredMediaId"
      ],
      "optional": true
    },
    {
      "path": [
        "galleryMediaIds",
        "*"
      ],
      "optional": true
    }
  ],
  "gallery_albumItems": [
    {
      "path": [
        "mediaId"
      ],
      "optional": false
    }
  ],
  "gallery_albums": [
    {
      "path": [
        "coverMediaId"
      ],
      "optional": true
    }
  ],
  "kb_articles": [
    {
      "path": [
        "featuredImageId"
      ],
      "optional": true
    }
  ],
  "kb_collections": [
    {
      "path": [
        "coverImageId"
      ],
      "optional": true
    }
  ],
  "lms_certificate_issues": [
    {
      "path": [
        "pdfMediaId"
      ],
      "optional": true
    }
  ],
  "lms_certificates": [
    {
      "path": [
        "backgroundMediaId"
      ],
      "optional": true
    }
  ],
  "lms_courses": [
    {
      "path": [
        "featuredImageId"
      ],
      "optional": true
    }
  ],
  "lms_nodes": [
    {
      "path": [
        "videoMediaId"
      ],
      "optional": true
    },
    {
      "path": [
        "audioMediaId"
      ],
      "optional": true
    },
    {
      "path": [
        "captionsMediaId"
      ],
      "optional": true
    },
    {
      "path": [
        "aiVideoMediaId"
      ],
      "optional": true
    }
  ],
  "mediaMeta": [
    {
      "path": [
        "mediaId"
      ],
      "optional": false
    }
  ],
  "mediaSizes": [
    {
      "path": [
        "mediaId"
      ],
      "optional": false
    }
  ],
  "posts": [
    {
      "path": [
        "featuredImageId"
      ],
      "optional": true
    },
    {
      "path": [
        "hero",
        "imageId"
      ],
      "optional": true
    },
    {
      "path": [
        "topics",
        "*",
        "imageId"
      ],
      "optional": true
    }
  ],
  "recipes": [
    {
      "path": [
        "featuredImageId"
      ],
      "optional": true
    },
    {
      "path": [
        "scanMediaId"
      ],
      "optional": true
    }
  ],
  "revisions": [
    {
      "path": [
        "hero",
        "imageId"
      ],
      "optional": true
    },
    {
      "path": [
        "topics",
        "*",
        "imageId"
      ],
      "optional": true
    },
    {
      "path": [
        "featuredImageId"
      ],
      "optional": true
    }
  ],
  "users": [
    {
      "path": [
        "avatarMediaId"
      ],
      "optional": true
    }
  ]
} as const;
export const opaqueMediaReferences = {
  "appearance_drafts": [
    "packId",
    "sourceRevision",
    "values",
    "variants"
  ],
  "blockDefinitionVersions": [
    "definitionJson",
    "digest"
  ],
  "canonicalDocumentDrafts": [
    "draft"
  ],
  "commerce_product_categories": [
    "description",
    "icon",
    "metaDescription",
    "metaTitle",
    "name",
    "slug"
  ],
  "commerce_product_variants": [
    "description",
    "globalUniqueId",
    "optionSummary",
    "price",
    "salePrice",
    "selectionKey",
    "selections",
    "shippingHeightIn",
    "shippingLengthIn",
    "shippingWidthIn",
    "sku",
    "taxClass",
    "title",
    "weight"
  ],
  "commerce_products": [
    "assistantSummary",
    "basePrice",
    "conversationalAttributes",
    "defaultAttributes",
    "description",
    "excerpt",
    "optionTypes",
    "productAttributes",
    "rawSourceMeta",
    "salePrice",
    "searchText",
    "sku",
    "slug",
    "taxClass",
    "title"
  ],
  "fieldDefinitions": [
    "conditionalLogic",
    "defaultValue",
    "instructions",
    "key",
    "label",
    "name",
    "settings",
    "type",
    "wrapperClass",
    "wrapperId",
    "wrapperWidth"
  ],
  "fieldValues": [
    "entityId",
    "entityType",
    "fieldKey",
    "fieldName",
    "formFieldSnapshot",
    "updatedBy",
    "value"
  ],
  "kb_articleVersions": [
    "changeSummary",
    "content",
    "title"
  ],
  "kb_articles": [
    "content",
    "contentPlainText",
    "excerpt",
    "keywords",
    "metaDescription",
    "metaTitle",
    "slug",
    "title"
  ],
  "kb_templates": [
    "content",
    "description",
    "name",
    "slug"
  ],
  "layouts": [
    "config",
    "description",
    "name",
    "slug"
  ],
  "lms_certificates": [
    "templateDoc",
    "title"
  ],
  "lms_courses": [
    "categoryIds",
    "completionRedirectUrl",
    "descriptionDoc",
    "excerpt",
    "externalButtonUrl",
    "materialsDoc",
    "promoVideoUrl",
    "slug",
    "tagIds",
    "title"
  ],
  "lms_lessonVersions": [
    "bodyDoc",
    "snapshotJson"
  ],
  "lms_nodes": [
    "bodyDoc",
    "description",
    "materialsDoc",
    "title",
    "transcriptText",
    "videoProvider",
    "videoUrl"
  ],
  "postMeta": [
    "key",
    "value"
  ],
  "posts": [
    "autosaveContent",
    "autosaveTitle",
    "blocks",
    "composedDefinitions",
    "content",
    "excerpt",
    "hero",
    "layoutId",
    "pagePrompt",
    "pageSections",
    "pageTemplate",
    "password",
    "path",
    "previousStatus",
    "slug",
    "sources",
    "summary",
    "tableOfContents",
    "title",
    "topics",
    "wpGuid"
  ],
  "recipes": [
    "description",
    "excerpt",
    "ingredients",
    "instructions",
    "notes",
    "nutrition",
    "scannedText",
    "servings",
    "slug",
    "title",
    "yieldText"
  ],
  "reusableBlocks": [
    "blockType",
    "category",
    "content",
    "description",
    "slug",
    "title"
  ],
  "revisions": [
    "authorId",
    "autosaveContent",
    "autosaveTitle",
    "blocks",
    "changedFields",
    "composedDefinitions",
    "content",
    "excerpt",
    "hero",
    "layoutId",
    "pagePrompt",
    "pageSections",
    "pageTemplate",
    "sources",
    "summary",
    "tableOfContents",
    "title",
    "topics"
  ],
  "settings": [
    "values"
  ],
  "syncedBlockRevisions": [
    "blocks",
    "digest",
    "legacySourceJson",
    "title"
  ],
  "themes": [
    "colorPalette",
    "description",
    "footerConfig",
    "headerConfig",
    "layoutAssignments",
    "name",
    "slug",
    "thumbnail"
  ]
} as const;
export const mediaReferenceIndexes = {
  "commerce_product_brands": {
    "logoMediaId": "by_media_ref_logoMediaId"
  },
  "commerce_product_categories": {
    "thumbnailMediaId": "by_media_ref_thumbnailMediaId"
  },
  "commerce_product_variants": {
    "featuredMediaId": "by_media_ref_featuredMediaId"
  },
  "commerce_products": {
    "featuredMediaId": "by_media_ref_featuredMediaId"
  },
  "gallery_albumItems": {
    "mediaId": "by_media"
  },
  "gallery_albums": {
    "coverMediaId": "by_media_ref_coverMediaId"
  },
  "kb_articles": {
    "featuredImageId": "by_media_ref_featuredImageId"
  },
  "kb_collections": {
    "coverImageId": "by_media_ref_coverImageId"
  },
  "lms_certificate_issues": {
    "pdfMediaId": "by_media_ref_pdfMediaId"
  },
  "lms_certificates": {
    "backgroundMediaId": "by_media_ref_backgroundMediaId"
  },
  "lms_courses": {
    "featuredImageId": "by_media_ref_featuredImageId"
  },
  "lms_nodes": {
    "videoMediaId": "by_media_ref_videoMediaId",
    "audioMediaId": "by_media_ref_audioMediaId",
    "captionsMediaId": "by_media_ref_captionsMediaId",
    "aiVideoMediaId": "by_media_ref_aiVideoMediaId"
  },
  "mediaMeta": {
    "mediaId": "by_media"
  },
  "mediaSizes": {
    "mediaId": "by_media"
  },
  "posts": {
    "featuredImageId": "by_media_ref_featuredImageId",
    "hero.imageId": "by_media_ref_hero_imageId"
  },
  "recipes": {
    "featuredImageId": "by_media_ref_featuredImageId",
    "scanMediaId": "by_media_ref_scanMediaId"
  },
  "revisions": {
    "hero.imageId": "by_media_ref_hero_imageId",
    "featuredImageId": "by_media_ref_featuredImageId"
  },
  "users": {
    "avatarMediaId": "by_media_ref_avatarMediaId"
  }
} as const;
