// Generated by scripts/generate-media-writer-coverage.mjs. Do not edit.
export const MEDIA_WRITER_COVERAGE_VERSION = "media-edges-c61cf9e5c4d683cc41d82e4b";
export const MEDIA_WRITER_OWNER_COUNT = 31;
