// Generated by scripts/generate-media-writer-coverage.mjs. Do not edit.
export const MEDIA_WRITER_COVERAGE_VERSION = "media-edges-632e70bcab5dd2f99365dd34";
export const MEDIA_WRITER_OWNER_COUNT = 29;
