// Generated by scripts/generate-media-writer-coverage.mjs. Do not edit.
export const MEDIA_WRITER_COVERAGE_VERSION = "media-edges-cf6bac555f3790c19c770b4e";
export const MEDIA_WRITER_OWNER_COUNT = 30;
