import type { LucideIcon } from "lucide-react";
import {
  Bell,
  BookOpen,
  Brain,
  CreditCard,
  Database,
  FileSearch,
  Files,
  GalleryVerticalEnd,
  Globe,
  LayoutTemplate,
  Mail,
  MessageSquare,
  Palette,
  Receipt,
  Repeat,
  Search,
  Settings2,
  Shield,
  ShoppingCart,
  Truck,
  UserRound,
  WandSparkles,
} from "lucide-react";

import type { AdminPluginId } from "@/lib/plugins/registry";
import type { SettingsSection } from "@/types/settings";

export type SettingsSurfaceGroup =
  | "core"
  | "messaging"
  | "intelligence"
  | "commerce"
  | "integrations"
  | "appearance"
  | "support";

export type SettingsSaveMode = "autosave" | "manual" | "mixed";
export type SettingsSurfaceLocation = "central" | "external";
export type SettingsImplementationStatus = "live" | "missing";

export interface SettingsSurfaceDefinition {
  id: string;
  title: string;
  description: string;
  group: SettingsSurfaceGroup;
  icon: LucideIcon;
  route?: string;
  sections: SettingsSection[];
  capability: string;
  saveMode: SettingsSaveMode;
  location: SettingsSurfaceLocation;
  status: SettingsImplementationStatus;
  pluginId?: AdminPluginId;
  notes?: string;
}

export const SETTINGS_GROUPS: Record<
  SettingsSurfaceGroup,
  { title: string; description: string }
> = {
  core: {
    title: "Core Site",
    description: "Foundational website settings and editorial defaults.",
  },
  messaging: {
    title: "Notifications & Messaging",
    description: "Email delivery, alerts, and notification preferences.",
  },
  intelligence: {
    title: "Search, AI & SEO",
    description: "Search indexing, analytics, AI providers, and discoverability.",
  },
  commerce: {
    title: "Commerce",
    description: "Storefront, checkout, tax, returns, subscriptions, and addon controls.",
  },
  integrations: {
    title: "Integrations",
    description: "Third-party services, processors, and carrier connections.",
  },
  appearance: {
    title: "Appearance",
    description: "Layout assignments and global presentation surfaces.",
  },
  support: {
    title: "Support & Access",
    description: "Membership, help systems, ticketing, and extension-level settings.",
  },
};

export const SETTINGS_GROUP_ORDER: SettingsSurfaceGroup[] = [
  "core",
  "messaging",
  "intelligence",
  "commerce",
  "integrations",
  "appearance",
  "support",
];

export const SETTINGS_REGISTRY: SettingsSurfaceDefinition[] = [
  {
    id: "general",
    title: "General",
    description: "Site identity, locale, registration, and base account defaults.",
    group: "core",
    icon: Globe,
    route: "/settings/general",
    sections: ["general"],
    capability: "settings.update_general",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "reading",
    title: "Reading",
    description: "Homepage behavior, post listing, feed output, and indexing visibility.",
    group: "core",
    icon: Files,
    route: "/settings/reading",
    sections: ["reading"],
    capability: "settings.update_reading",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "writing",
    title: "Writing",
    description: "Default post category and editorial format defaults.",
    group: "core",
    icon: WandSparkles,
    route: "/settings/writing",
    sections: ["writing"],
    capability: "settings.update_writing",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "discussion",
    title: "Discussion",
    description: "Comment policy, moderation, paging, and avatar preferences.",
    group: "core",
    icon: MessageSquare,
    route: "/settings/discussion",
    sections: ["discussion"],
    capability: "settings.update_discussion",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "permalinks",
    title: "Permalinks",
    description: "URL structure rules for posts, categories, and tags.",
    group: "core",
    icon: Globe,
    route: "/settings/permalinks",
    sections: ["permalinks"],
    capability: "settings.update_permalinks",
    saveMode: "manual",
    location: "central",
    status: "live",
    notes: "Manual confirmation remains intentional because structure changes can break live URLs.",
  },
  {
    id: "privacy",
    title: "Privacy",
    description: "Privacy policy page selection and public disclosure links.",
    group: "core",
    icon: Shield,
    route: "/settings/privacy",
    sections: ["privacy"],
    capability: "settings.update_privacy",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "media",
    title: "Media",
    description: "Upload limits and generated image size defaults.",
    group: "core",
    icon: GalleryVerticalEnd,
    route: "/settings/media",
    sections: ["media"],
    capability: "manage_options",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "notifications",
    title: "Notifications",
    description: "Per-type in-app and desktop delivery preferences.",
    group: "messaging",
    icon: Bell,
    route: "/settings/notifications",
    sections: [],
    capability: "notification.update_preferences",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "email",
    title: "Email Delivery",
    description: "Resend transport, queue behavior, templates, and test sends.",
    group: "messaging",
    icon: Mail,
    route: "/settings/email",
    sections: ["email"],
    capability: "settings.update_email",
    saveMode: "manual",
    location: "central",
    status: "live",
  },
  {
    id: "search",
    title: "Search",
    description: "Meilisearch configuration for content indexing and query delivery.",
    group: "intelligence",
    icon: Search,
    route: "/settings/search",
    sections: ["search"],
    capability: "search.query",
    saveMode: "manual",
    location: "central",
    status: "live",
  },
  {
    id: "analytics",
    title: "Analytics",
    description: "Built-in analytics tracking and GA4 data collection behavior.",
    group: "intelligence",
    icon: Database,
    route: "/settings/analytics",
    sections: ["analytics"],
    capability: "manage_options",
    saveMode: "mixed",
    location: "central",
    status: "live",
  },
  {
    id: "analytics-ga4",
    title: "Google Analytics 4",
    description: "Service account credentials and property connection for GA4.",
    group: "integrations",
    icon: Database,
    route: "/settings/analytics/ga4",
    sections: ["analytics.ga4"],
    capability: "manage_options",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "ai",
    title: "AI Providers",
    description: "Provider credentials, default models, and research integrations.",
    group: "intelligence",
    icon: Brain,
    route: "/settings/ai",
    sections: ["ai"],
    capability: "manage_options",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "seo",
    title: "SEO",
    description: "Global search, social, schema, robots, and verification settings.",
    group: "intelligence",
    icon: FileSearch,
    route: "/seo/settings",
    sections: [],
    capability: "seo.update_global",
    saveMode: "mixed",
    location: "external",
    status: "live",
  },
  {
    id: "plugins",
    title: "Extensions",
    description: "Plugin enablement and parent-child addon availability.",
    group: "support",
    icon: Settings2,
    route: "/plugins",
    sections: ["plugins"],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "live",
  },
  {
    id: "tools",
    title: "Import / Export",
    description: "Settings import, export, and repair utilities.",
    group: "support",
    icon: Settings2,
    route: "/settings/tools",
    sections: [],
    capability: "manage_options",
    saveMode: "manual",
    location: "central",
    status: "live",
  },
  {
    id: "commerce-store",
    title: "Commerce Store",
    description: "Store identity, checkout policy, fallback methods, and return policy.",
    group: "commerce",
    icon: ShoppingCart,
    route: "/commerce/settings",
    sections: ["commerce.general"],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "live",
    pluginId: "commerce",
  },
  {
    id: "commerce-shipping",
    title: "Shipping Runtime",
    description: "Carrier preference, badge copy, quote behavior, and origin address.",
    group: "commerce",
    icon: Truck,
    route: "/commerce/settings/shipping",
    sections: ["integrations.shipping"],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "live",
    pluginId: "commerce",
  },
  {
    id: "commerce-tax",
    title: "Tax Rules",
    description: "Tax classes, rules, preview calculations, and seeded defaults.",
    group: "commerce",
    icon: Receipt,
    route: "/commerce/settings/tax",
    sections: [],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "live",
    pluginId: "commerce",
  },
  {
    id: "commerce-returns",
    title: "Returns",
    description: "Return eligibility policy and returns-specific maintenance tasks.",
    group: "commerce",
    icon: Receipt,
    route: "/commerce/returns/settings",
    sections: ["commerce.general"],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "live",
    pluginId: "commerceReturns",
  },
  {
    id: "commerce-subscriptions",
    title: "Subscriptions",
    description: "Recurring billing operations, offers, templates, invoices, and dunning.",
    group: "commerce",
    icon: Repeat,
    route: "/commerce/subscriptions",
    sections: [],
    capability: "manage_options",
    saveMode: "mixed",
    location: "external",
    status: "live",
    pluginId: "commerceSubscriptions",
  },
  {
    id: "commerce-subscription-counters",
    title: "Subscription Counters",
    description: "Invoice counter and prefix configuration for subscription invoicing.",
    group: "commerce",
    icon: Repeat,
    sections: ["commerce.subscriptions.counters"],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "missing",
    pluginId: "commerceSubscriptions",
    notes: "Runtime section exists, but there is no discoverable admin page yet.",
  },
  {
    id: "commerce-digital",
    title: "Digital Products",
    description: "Download-token policy, license-key policy, and fulfillment defaults.",
    group: "commerce",
    icon: ShoppingCart,
    sections: [],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "missing",
    pluginId: "commerceDigital",
    notes: "Only plugin enablement exists today; runtime defaults are still hardcoded in code.",
  },
  {
    id: "commerce-reviews",
    title: "Product Reviews",
    description: "Review policy, moderation defaults, and verified-purchase behavior.",
    group: "commerce",
    icon: MessageSquare,
    sections: [],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "missing",
    pluginId: "commerceReviews",
    notes: "Review runtime exists, but there is no dedicated settings surface beyond plugin enablement.",
  },
  {
    id: "commerce-wishlists",
    title: "Wishlists",
    description: "Wishlist sharing, privacy, limits, and guest merge behavior.",
    group: "commerce",
    icon: UserRound,
    sections: [],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "missing",
    pluginId: "commerceWishlists",
    notes: "Analytics/admin pages exist, but no dedicated settings page exists yet.",
  },
  {
    id: "commerce-bundles",
    title: "Bundles",
    description: "Bundle cleanup, inventory, and bundle-runtime policy settings.",
    group: "commerce",
    icon: ShoppingCart,
    sections: [],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "missing",
    pluginId: "commerceBundles",
    notes: "Bundle runtime is implemented, but settings are still implicit and code-driven.",
  },
  {
    id: "integrations-overview",
    title: "Integrations Overview",
    description: "High-level status dashboard for connected third-party services.",
    group: "integrations",
    icon: Settings2,
    route: "/settings/integrations",
    sections: [],
    capability: "manage_options",
    saveMode: "manual",
    location: "central",
    status: "live",
  },
  {
    id: "stripe",
    title: "Stripe",
    description: "Publishable key, secret key, mode, and webhook signing secret.",
    group: "integrations",
    icon: CreditCard,
    route: "/settings/integrations/stripe",
    sections: ["commerce.payments"],
    capability: "manage_options",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "paypal",
    title: "PayPal",
    description: "Client credentials, mode, and webhook verification settings.",
    group: "integrations",
    icon: CreditCard,
    route: "/settings/integrations/paypal",
    sections: ["commerce.payments"],
    capability: "manage_options",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "clerk",
    title: "Clerk",
    description: "Authentication secret keys and webhook verification settings.",
    group: "integrations",
    icon: Shield,
    route: "/settings/integrations/clerk",
    sections: ["integrations.clerk"],
    capability: "manage_options",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "google-places",
    title: "Google Places",
    description: "Address autocomplete and geocoding integration keys.",
    group: "integrations",
    icon: Globe,
    route: "/settings/integrations/google",
    sections: ["integrations.google"],
    capability: "manage_options",
    saveMode: "autosave",
    location: "central",
    status: "live",
  },
  {
    id: "shipping-overview",
    title: "Shipping Carriers",
    description: "Overview of carrier connectivity and direct carrier coverage.",
    group: "integrations",
    icon: Truck,
    route: "/settings/integrations/shipping",
    sections: ["integrations.shipping"],
    capability: "manage_options",
    saveMode: "manual",
    location: "central",
    status: "live",
  },
  {
    id: "shipstation",
    title: "ShipStation",
    description: "Aggregator credentials, metadata, rate shopping, and verification.",
    group: "integrations",
    icon: Truck,
    route: "/settings/integrations/shipping/shipstation",
    sections: ["integrations.shipping.shipstation"],
    capability: "manage_options",
    saveMode: "manual",
    location: "central",
    status: "live",
  },
  {
    id: "ups",
    title: "UPS",
    description: "Direct carrier credentials, metadata, and readiness checks.",
    group: "integrations",
    icon: Truck,
    route: "/settings/integrations/shipping/ups",
    sections: ["integrations.shipping.ups"],
    capability: "manage_options",
    saveMode: "manual",
    location: "central",
    status: "live",
  },
  {
    id: "usps",
    title: "USPS",
    description: "Direct carrier credentials plus address validation checks.",
    group: "integrations",
    icon: Truck,
    route: "/settings/integrations/shipping/usps",
    sections: ["integrations.shipping.usps"],
    capability: "manage_options",
    saveMode: "manual",
    location: "central",
    status: "live",
  },
  {
    id: "fedex",
    title: "FedEx",
    description: "Direct carrier credentials, metadata, and readiness checks.",
    group: "integrations",
    icon: Truck,
    route: "/settings/integrations/shipping/fedex",
    sections: ["integrations.shipping.fedex"],
    capability: "manage_options",
    saveMode: "manual",
    location: "central",
    status: "live",
  },
  {
    id: "dhl",
    title: "DHL",
    description: "Direct carrier credentials and readiness checks.",
    group: "integrations",
    icon: Truck,
    route: "/settings/integrations/shipping/dhl",
    sections: ["integrations.shipping.dhl"],
    capability: "manage_options",
    saveMode: "manual",
    location: "central",
    status: "live",
  },
  {
    id: "layout",
    title: "Default Layouts",
    description: "Global layout assignments for content and archive surfaces.",
    group: "appearance",
    icon: LayoutTemplate,
    route: "/layouts/assign",
    sections: ["layout"],
    capability: "manage_options",
    saveMode: "autosave",
    location: "external",
    status: "live",
  },
  {
    id: "header",
    title: "Header",
    description: "Global site header composition, slots, and responsive behavior.",
    group: "appearance",
    icon: Palette,
    route: "/appearance/header",
    sections: ["header"],
    capability: "edit_theme_options",
    saveMode: "manual",
    location: "external",
    status: "live",
  },
  {
    id: "footer",
    title: "Footer",
    description: "Global footer composition, column layout, and bottom-bar behavior.",
    group: "appearance",
    icon: GalleryVerticalEnd,
    route: "/appearance/footer",
    sections: ["footer"],
    capability: "edit_theme_options",
    saveMode: "manual",
    location: "external",
    status: "live",
  },
  {
    id: "membership",
    title: "Membership",
    description: "Membership availability, diagnostics, and links to plans, grants, and restrictions.",
    group: "support",
    icon: Shield,
    route: "/membership/settings",
    sections: ["plugins"],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "live",
    pluginId: "membership",
  },
  {
    id: "knowledge-base",
    title: "Knowledge Base",
    description: "KB general behavior, feature toggles, and AI/RAG search settings.",
    group: "support",
    icon: BookOpen,
    route: "/kb/settings",
    sections: ["kb.general", "kb.features", "kb.search"],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "live",
    pluginId: "knowledgeBase",
  },
  {
    id: "tickets",
    title: "Support Tickets",
    description: "Ticket categories, default priority, auto-close, and SLA targets.",
    group: "support",
    icon: MessageSquare,
    route: "/tickets/settings",
    sections: ["ticket.general", "ticket.sla"],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "live",
    pluginId: "tickets",
  },
  {
    id: "support",
    title: "Support Widget",
    description: "Support widget appearance, AI answers, and deflection search settings.",
    group: "support",
    icon: MessageSquare,
    route: "/support/settings",
    sections: ["support.widget", "support.ai"],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "live",
    pluginId: "tickets",
  },
  {
    id: "gallery",
    title: "Gallery",
    description: "Gallery route availability and extension-level public behavior.",
    group: "support",
    icon: GalleryVerticalEnd,
    route: "/gallery/settings",
    sections: ["plugins"],
    capability: "manage_options",
    saveMode: "manual",
    location: "external",
    status: "live",
    pluginId: "gallery",
  },
];

export function groupSettingsRegistry() {
  const grouped = new Map<SettingsSurfaceGroup, SettingsSurfaceDefinition[]>();

  for (const group of SETTINGS_GROUP_ORDER) {
    grouped.set(group, []);
  }

  for (const entry of SETTINGS_REGISTRY) {
    grouped.get(entry.group)?.push(entry);
  }

  return grouped;
}
